export const kpiDict={
 en:{
  kpi:'KPI & SLA',
  kpiDashboard:'Maintenance KPI & SLA Dashboard',
  kpiPeriod:'Period',
  kpiFrom:'From',
  kpiTo:'To',
  kpiApply:'Apply',
  kpiRefresh:'Refresh',
  kpiWorkOrders:'Work orders',
  kpiOpen:'Open',
  kpiClosed:'Closed',
  kpiSlaBreached:'SLA breached',
  kpiSlaMet:'SLA met',
  kpiP1Open:'Open P1',
  kpiAvgClose:'Avg. close hours',
  kpiPpm:'PPM',
  kpiCompleted:'Completed',
  kpiOverdue:'Overdue',
  kpiCompliance:'Compliance %',
  kpiAssets:'Assets',
  kpiCritical:'Critical assets',
  kpiPoorFailed:'Poor / failed',
  kpiOutOfService:'Out of service',
  kpiSlaList:'SLA breach action list',
  kpiPpmList:'Overdue PPM action list',
  kpiNoData:'No records for the selected period'
 },
 ar:{
  kpi:'مؤشرات الأداء و SLA',
  kpiDashboard:'لوحة مؤشرات أداء الصيانة و SLA',
  kpiPeriod:'الفترة',
  kpiFrom:'من',
  kpiTo:'إلى',
  kpiApply:'تطبيق',
  kpiRefresh:'تحديث',
  kpiWorkOrders:'أوامر العمل',
  kpiOpen:'مفتوحة',
  kpiClosed:'مغلقة',
  kpiSlaBreached:'تجاوز SLA',
  kpiSlaMet:'ضمن SLA',
  kpiP1Open:'P1 مفتوحة',
  kpiAvgClose:'متوسط ساعات الإغلاق',
  kpiPpm:'الصيانة الوقائية PPM',
  kpiCompleted:'مكتملة',
  kpiOverdue:'متأخرة',
  kpiCompliance:'نسبة الالتزام %',
  kpiAssets:'الأصول',
  kpiCritical:'أصول حرجة',
  kpiPoorFailed:'حالة ضعيفة / متعطلة',
  kpiOutOfService:'خارج الخدمة',
  kpiSlaList:'قائمة معالجة تجاوزات SLA',
  kpiPpmList:'قائمة PPM المتأخرة',
  kpiNoData:'لا توجد بيانات للفترة المحددة'
 }
}
