export const reportDict={
en:{
 reportDefOverview:"Work orders are counted by creation date, PPM by due date, and labor by interval start. Statuses are current, not historical.",
 reportDefWorkOrders:"Work orders created in the selected period. Current statuses and recorded response/completion durations are shown; SLA compliance is not inferred.",
 reportDefPPM:"Generated, non-cancelled PPM jobs due in the period. Closed / due is not a full contractual compliance measure because missing schedules are not inferred.",
 reportDefTechnicians:"Actual recorded labor intervals starting in the period. Visits and work orders are distinct counts; these are not verified GPS attendance.",
 reportDefMaterials:"Gross consumption events in the period multiplied by allocation cost snapshots. Returns and financial reversals are not netted; legacy stock is excluded.",
 reportDefMonthly:"Monthly work-order creation cohorts. Current closed and breached counts are not month-end historical snapshots.",
 reportDefQuality:"QA rejection, approval and reopening events in the period. Counts are events, not unique work orders.",

 work_order_number:"Work order no.",
 title:"Title",
 priority:"Priority",
 status:"Status",
 approval_status:"Approval status",
 sla_status:"SLA status",
 created_at:"Created",
 started_at:"Started",
 completed_at:"Completed",
 closed_at:"Closed",
 completion_due_at:"Completion due",
 response_minutes:"Response minutes",
 completion_minutes:"Completion minutes",
 diagnosis:"Diagnosis",
 root_cause:"Root cause",
 work_performed:"Work performed",
 client_id:"Client ID",
 site_id:"Site ID",
 asset_id:"Asset ID",
 job_number:"PPM job no.",
 due_date:"Due date",
 assigned_to:"Assigned technician",
 approved_at:"Approved at",
 failed_steps:"Failed steps",
 corrective_followups:"Corrective follow-ups",
 full_name:"Technician",
 ended_at:"Ended",
 minutes:"Minutes",
 activity:"Activity",
 technician_id:"Technician ID",
 visit_id:"Visit ID",
 sku:"SKU",
 name_ar:"Arabic name",
 name_en:"English name",
 unit:"Unit",
 owner_client_id:"Stock owner ID",
 lot_code:"Lot / batch",
 serial_number:"Serial number",
 consumed_qty:"Consumed quantity",
 currency:"Currency",
 unit_cost:"Unit cost",
 actual_cost:"Actual cost",
 work_order_id:"Work order ID",
 month:"Month",
 created:"Created",
 currently_closed:"Currently closed",
 currently_breached:"Currently breached",
 action:"Action",
 from_status:"From status",
 to_status:"To status",
 metric:"Metric",
 value:"Value",
 work_orders:"Work orders",
 open_work_orders:"Currently open",
 closed_work_orders:"Currently closed",
 cancelled_work_orders:"Currently cancelled",
 sla_breached:"Marked breached",
 ppm_due:"PPM due",
 ppm_closed:"PPM closed",
 ppm_overdue:"PPM overdue",
 labor_minutes:"Labor minutes",

 reports:'Management reports',reportOverview:'Executive overview',reportWorkOrders:'Work orders',reportPPM:'Preventive maintenance',
 reportTechnicians:'Technician performance',reportMaterials:'Material consumption',reportMonthly:'Monthly trends',reportQuality:'Quality & rework',
 reportMetric:'Metric',reportWorkOrderNo:'Work order no.',reportCurrentStatus:'Current status',
 reportCompany:'Company',reportClient:'Client',reportSite:'Site',reportStart:'From',reportEnd:'To',
 reportApply:'Apply filters',reportExportExcel:'Export Excel',reportExportPDF:'Print / Save PDF',
 reportExporting:'Preparing export...',reportRows:'Rows',reportNoData:'No data for the selected filters',
 reportDefinition:'Metric definition',reportCurrent:'Current status',reportGenerated:'Generated',reportPeriod:'Reporting period',
 reportPage:'Page',reportPrevious:'Previous',reportNext:'Next',reportAll:'All',reportSelect:'Select...',
 reportCreated:'Created work orders',reportOpen:'Currently open',reportClosed:'Currently closed',reportSla:'Marked breached',
 reportDue:'PPM due',reportCompliance:'PPM closed / due',reportLabor:'Recorded labor',reportHours:'hours',
 reportFailed:'Failed PPM jobs',reportRework:'QA rejections',reportCost:'Internal material cost',
 reportNotAvailable:'Not available',reportSnapshot:'Live report. Status values may change after export.',
 reportCostNotice:'Cost data is restricted to authorized finance/management roles. No selling prices, tax invoices or currency conversion are included.',
 reportLimits:'Date range is limited to 367 calendar days. Export is limited to 50,000 rows. Split larger reports into smaller ranges.',
 reportPartial:'The export contains all returned rows for this filter; it is not an immutable accounting snapshot.',
 reportNoPermission:'You do not have access to these reports.',reportExcelError:'Excel export failed',
 reportExportName:'Basmat Facilities Report',reportStatus:'Status',reportTotal:'Total',reportCount:'Count',
 reportMinutes:'Minutes',reportDate:'Date',reportAction:'Action',reportValue:'Value',reportFilter:'Filter',
 reportUnknown:'Unknown',reportOpenDetails:'Open work order'
},
ar:{
 reportDefOverview:"تُحسب أوامر العمل حسب تاريخ الإنشاء، والصيانة الوقائية حسب الاستحقاق، وساعات العمل حسب بداية الفترة. الحالات حالية وليست تاريخية.",
 reportDefWorkOrders:"أوامر العمل المنشأة خلال الفترة. تظهر الحالات الحالية وأزمنة الاستجابة والإكمال المسجلة، دون افتراض الالتزام باتفاقيات SLA.",
 reportDefPPM:"مهام الصيانة الوقائية المجدولة وغير الملغاة والمستحقة خلال الفترة. نسبة المغلقة إلى المستحقة ليست مؤشر التزام تعاقدي كاملًا لعدم احتساب الجداول غير المنشأة.",
 reportDefTechnicians:"فترات العمل الفعلية المسجلة التي تبدأ خلال الفترة. أعداد الزيارات وأوامر العمل فريدة، ولا تمثل حضورًا موثقًا عبر GPS.",
 reportDefMaterials:"الاستهلاك الإجمالي المسجل خلال الفترة مضروبًا في تكلفة التخصيص الثابتة. لا تُخصم المرتجعات أو التسويات المالية، ولا يشمل المخزون القديم.",
 reportDefMonthly:"مجموعات شهرية حسب تاريخ إنشاء أمر العمل. أعداد الإغلاق والتجاوز هي حالات حالية وليست لقطات تاريخية لنهاية الشهر.",
 reportDefQuality:"أحداث رفض واعتماد الجودة وإعادة الفتح خلال الفترة. الأعداد تمثل أحداثًا وليست أوامر عمل فريدة.",

 work_order_number:"رقم أمر العمل",
 title:"العنوان",
 priority:"الأولوية",
 status:"الحالة",
 approval_status:"حالة الاعتماد",
 sla_status:"حالة SLA",
 created_at:"تاريخ الإنشاء",
 started_at:"البداية",
 completed_at:"الإكمال",
 closed_at:"الإغلاق",
 completion_due_at:"موعد الإكمال",
 response_minutes:"دقائق الاستجابة",
 completion_minutes:"دقائق التنفيذ",
 diagnosis:"التشخيص",
 root_cause:"السبب الجذري",
 work_performed:"الأعمال المنفذة",
 client_id:"معرف العميل",
 site_id:"معرف الموقع",
 asset_id:"معرف الأصل",
 job_number:"رقم مهمة PPM",
 due_date:"تاريخ الاستحقاق",
 assigned_to:"الفني المسند",
 approved_at:"تاريخ الاعتماد",
 failed_steps:"الخطوات الفاشلة",
 corrective_followups:"المتابعات التصحيحية",
 full_name:"الفني",
 ended_at:"النهاية",
 minutes:"الدقائق",
 activity:"النشاط",
 technician_id:"معرف الفني",
 visit_id:"معرف الزيارة",
 sku:"كود الصنف",
 name_ar:"الاسم العربي",
 name_en:"الاسم الإنجليزي",
 unit:"الوحدة",
 owner_client_id:"معرف مالك المخزون",
 lot_code:"الدفعة",
 serial_number:"الرقم التسلسلي",
 consumed_qty:"الكمية المستهلكة",
 currency:"العملة",
 unit_cost:"تكلفة الوحدة",
 actual_cost:"التكلفة الفعلية",
 work_order_id:"معرف أمر العمل",
 month:"الشهر",
 created:"المنشأة",
 currently_closed:"المغلقة حاليًا",
 currently_breached:"المتجاوزة حاليًا",
 action:"الإجراء",
 from_status:"الحالة السابقة",
 to_status:"الحالة التالية",
 metric:"المؤشر",
 value:"القيمة",
 work_orders:"أوامر العمل",
 open_work_orders:"المفتوحة حاليًا",
 closed_work_orders:"المغلقة حاليًا",
 cancelled_work_orders:"الملغاة حاليًا",
 sla_breached:"المسجلة متجاوزة",
 ppm_due:"PPM المستحقة",
 ppm_closed:"PPM المغلقة",
 ppm_overdue:"PPM المتأخرة",
 labor_minutes:"دقائق العمل",

 reports:'التقارير الإدارية',reportOverview:'الملخص التنفيذي',reportWorkOrders:'أوامر العمل',reportPPM:'الصيانة الوقائية',
 reportTechnicians:'أداء الفنيين',reportMaterials:'استهلاك المواد',reportMonthly:'الاتجاهات الشهرية',reportQuality:'الجودة وإعادة العمل',
 reportMetric:'المؤشر',reportWorkOrderNo:'رقم أمر العمل',reportCurrentStatus:'الحالة الحالية',
 reportCompany:'الشركة',reportClient:'العميل',reportSite:'الموقع',reportStart:'من تاريخ',reportEnd:'إلى تاريخ',
 reportApply:'تطبيق الفلاتر',reportExportExcel:'تصدير Excel',reportExportPDF:'طباعة / حفظ PDF',
 reportExporting:'جارٍ تجهيز التصدير...',reportRows:'صف',reportNoData:'لا توجد بيانات للفلاتر المختارة',
 reportDefinition:'تعريف المؤشر',reportCurrent:'الحالة الحالية',reportGenerated:'تاريخ التقرير',reportPeriod:'فترة التقرير',
 reportPage:'الصفحة',reportPrevious:'السابق',reportNext:'التالي',reportAll:'الكل',reportSelect:'اختر...',
 reportCreated:'أوامر العمل المنشأة',reportOpen:'المفتوحة حاليًا',reportClosed:'المغلقة حاليًا',reportSla:'المسجلة متجاوزة SLA',
 reportDue:'الصيانة الوقائية المستحقة',reportCompliance:'المغلقة / المستحقة',reportLabor:'ساعات العمل المسجلة',reportHours:'ساعة',
 reportFailed:'أعمال PPM التي بها فشل',reportRework:'حالات رفض الجودة',reportCost:'التكلفة الداخلية للمواد',
 reportNotAvailable:'غير متاح',reportSnapshot:'تقرير حي؛ قد تتغير الحالات بعد التصدير.',
 reportCostNotice:'بيانات التكلفة مقصورة على الإدارة المخولة. لا تشمل أسعار البيع أو الفواتير الضريبية أو تحويل العملات.',
 reportLimits:'الفترة القصوى 367 يومًا تقويميًا، والتصدير حتى 50,000 صف. قسم التقارير الكبيرة إلى فترات أصغر.',
 reportPartial:'يشمل التصدير جميع الصفوف المسترجعة للفلاتر المحددة، وليس لقطة محاسبية ثابتة.',
 reportNoPermission:'ليست لديك صلاحية الوصول إلى التقارير.',reportExcelError:'تعذر تصدير Excel',
 reportExportName:'تقرير بصمة النوابغ للمرافق',reportStatus:'الحالة',reportTotal:'الإجمالي',reportCount:'العدد',
 reportMinutes:'دقيقة',reportDate:'التاريخ',reportAction:'الإجراء',reportValue:'القيمة',reportFilter:'الفلتر',
 reportUnknown:'غير معروف',reportOpenDetails:'فتح أمر العمل'
}}
