export const supplierPerformanceDict={
 en:{
  supplierPerformance:'Supplier performance',
  supplierPerformanceCenter:'Supplier performance & evaluation',
  supplierPerformanceSupplier:'Supplier',
  supplierPerformancePOs:'Purchase orders',
  supplierPerformanceFulfilled:'Fulfilled POs',
  supplierPerformanceOrderedValue:'Ordered value',
  supplierPerformanceReceivedValue:'Received value',
  supplierPerformanceReceiptCount:'Receipts',
  supplierPerformanceReceiptDays:'Avg. receipt days',
  supplierPerformanceEvalCount:'Evaluations',
  supplierPerformanceAvgScore:'Avg. score',
  supplierPerformanceQuality:'Quality',
  supplierPerformanceDelivery:'Delivery',
  supplierPerformanceService:'Service',
  supplierPerformanceCommercial:'Commercial',
  supplierPerformanceEvaluate:'Add evaluation',
  supplierPerformanceDate:'Evaluation date',
  supplierPerformanceNotes:'Notes',
  supplierPerformanceSave:'Save evaluation',
  supplierPerformanceFrom:'From',
  supplierPerformanceTo:'To',
  supplierPerformanceApply:'Apply',
  supplierPerformanceRefresh:'Refresh',
  supplierPerformanceNoData:'No supplier performance data',
  supplierPerformanceRecent:'Recent evaluations'
 },
 ar:{
  supplierPerformance:'أداء الموردين',
  supplierPerformanceCenter:'أداء وتقييم الموردين',
  supplierPerformanceSupplier:'المورد',
  supplierPerformancePOs:'أوامر الشراء',
  supplierPerformanceFulfilled:'أوامر منفذة',
  supplierPerformanceOrderedValue:'قيمة الطلبات',
  supplierPerformanceReceivedValue:'قيمة المستلم',
  supplierPerformanceReceiptCount:'الاستلامات',
  supplierPerformanceReceiptDays:'متوسط أيام الاستلام',
  supplierPerformanceEvalCount:'عدد التقييمات',
  supplierPerformanceAvgScore:'متوسط التقييم',
  supplierPerformanceQuality:'الجودة',
  supplierPerformanceDelivery:'التسليم',
  supplierPerformanceService:'الخدمة',
  supplierPerformanceCommercial:'التجاري',
  supplierPerformanceEvaluate:'إضافة تقييم',
  supplierPerformanceDate:'تاريخ التقييم',
  supplierPerformanceNotes:'ملاحظات',
  supplierPerformanceSave:'حفظ التقييم',
  supplierPerformanceFrom:'من',
  supplierPerformanceTo:'إلى',
  supplierPerformanceApply:'تطبيق',
  supplierPerformanceRefresh:'تحديث',
  supplierPerformanceNoData:'لا توجد بيانات أداء للموردين',
  supplierPerformanceRecent:'آخر التقييمات'
 }
}
