export const advancedStockDict={
en:{
 advancedStock:'Advanced stock operations',advancedRequests:'Material requests',advancedCosts:'Actual material costs',
 retryOperation:'Retry the same operation',newAdvancedRequest:'New material request',requestNumber:'Request number',workOrder:'Work order',reason:'Reason',
 part:'Part',stockOwner:'Stock owner',companyStock:'Company-owned',ownerStock:'Client-owned',
 organization:'Company',client:'Client',quantity:'Quantity',reserved:'Reserved',issued:'Issued',received:'Received',
 consumed:'Consumed',returned:'Returned',available:'Available',remaining:'Remaining',unit:'Unit',
 warehouse:'Warehouse',bin:'Bin',lotCode:'Lot / batch',serialNumber:'Serial number',expiresOn:'Expiry date',
 create:'Create',addLine:'Add line',submit:'Submit',approve:'Approve',reject:'Reject',reserve:'Reserve',
 release:'Release reservation',issue:'Issue',receive:'Confirm receipt',consume:'Record consumption',
 return:'Return to stock',cancelRequest:'Cancel request',closeRequest:'Close request',
 allocation:'Allocation',allocations:'Stock allocations',custody:'Return custody',receivedCustody:'Received by technician',
 unreceivedCustody:'Not yet received',reference:'Reference',status:'Status',actions:'Actions',
 details:'Details',history:'Activity history',createdAt:'Created',actualCost:'Actual cost',currency:'Currency',
 submitted:'Submitted',approved:'Approved',rejected:'Rejected',cancelled:'Cancelled',closed:'Closed',
 refresh:'Refresh',save:'Save',cancel:'Cancel',select:'Select...',all:'All',search:'Search',
 loading:'Loading...',noData:'No records found',saved:'Saved successfully',confirmAction:'Confirm this action?',
 requestNotice:'Create a request linked to a corrective work order. Material owner must match the work order client, or be company-owned.',
 stockNotice:'Stock is reserved and issued from the traceable ledger only. Legacy Sprint 6 balances remain separate and are not included.',
 executionNotice:'Reservations, issues, receipts, consumption and returns are separate, auditable transactions. The same operation cannot be applied twice using its request key.',
 costNotice:'Actual material costs are internal and grouped by currency. They are not selling prices, tax invoices or contract claims.',
 closureNotice:'Release all reservations and reconcile every issued quantity before closing.',
 serialNotice:'Serialized items are indivisible. Expired stock cannot be reserved or returned to active stock.',
 independentApproval:'The request creator cannot approve their own request.',
 noStock:'No matching available stock',noLines:'Add at least one material line.',noAllocation:'No allocation is available.',noPermission:'Access denied',
}
,ar:{
 advancedStock:'عمليات المخزون المتقدمة',advancedRequests:'طلبات المواد',advancedCosts:'التكلفة الفعلية للمواد',
 retryOperation:'إعادة محاولة نفس العملية',newAdvancedRequest:'طلب مواد جديد',requestNumber:'رقم الطلب',workOrder:'أمر العمل',reason:'السبب',
 part:'الصنف',stockOwner:'مالك المخزون',companyStock:'مملوك للشركة',ownerStock:'مملوك للعميل',
 organization:'الشركة',client:'العميل',quantity:'الكمية',reserved:'محجوز',issued:'مصروف',received:'مستلم',
 consumed:'مستهلك',returned:'مرتجع',available:'متاح',remaining:'المتبقي',unit:'الوحدة',
 warehouse:'المستودع',bin:'موقع التخزين',lotCode:'الدفعة',serialNumber:'الرقم التسلسلي',expiresOn:'تاريخ الانتهاء',
 create:'إنشاء',addLine:'إضافة بند',submit:'تقديم',approve:'اعتماد',reject:'رفض',reserve:'حجز',
 release:'فك الحجز',issue:'صرف',receive:'تأكيد الاستلام',consume:'تسجيل الاستهلاك',
 return:'إرجاع للمخزون',cancelRequest:'إلغاء الطلب',closeRequest:'إغلاق الطلب',
 allocation:'تخصيص',allocations:'تخصيصات المخزون',custody:'حالة عهدة الإرجاع',receivedCustody:'مستلم بواسطة الفني',
 unreceivedCustody:'لم يستلمه الفني',reference:'المرجع',status:'الحالة',actions:'الإجراءات',
 details:'التفاصيل',history:'سجل النشاط',createdAt:'تاريخ الإنشاء',actualCost:'التكلفة الفعلية',currency:'العملة',
 submitted:'مقدم',approved:'معتمد',rejected:'مرفوض',cancelled:'ملغي',closed:'مغلق',
 refresh:'تحديث',save:'حفظ',cancel:'إلغاء',select:'اختر...',all:'الكل',search:'بحث',
 loading:'جارٍ التحميل...',noData:'لا توجد بيانات',saved:'تم الحفظ بنجاح',confirmAction:'هل تؤكد تنفيذ هذا الإجراء؟',
 requestNotice:'أنشئ طلبًا مرتبطًا بأمر صيانة تصحيحية. يجب أن يكون المخزون مملوكًا للشركة أو لنفس عميل أمر العمل.',
 stockNotice:'يتم الحجز والصرف من المخزون المتتبع فقط. أرصدة Sprint 6 القديمة منفصلة ولا تدخل في الحساب.',
 executionNotice:'الحجز والصرف والاستلام والاستهلاك والإرجاع معاملات مستقلة وموثقة. مفتاح العملية يمنع تكرار تنفيذها.',
 costNotice:'تكاليف المواد الفعلية داخلية ومجمعة حسب العملة، وليست أسعار بيع أو فواتير ضريبية أو مستخلصات عقود.',
 closureNotice:'يجب فك جميع الحجوزات وتسوية كل الكميات المصروفة قبل إغلاق الطلب.',
 serialNotice:'الأصناف المتسلسلة لا تقبل التجزئة. لا يمكن حجز المخزون المنتهي أو إرجاعه إلى المخزون النشط.',
 independentApproval:'لا يمكن لمنشئ الطلب اعتماد طلبه بنفسه.',
 noStock:'لا يوجد مخزون مطابق ومتاح',noLines:'أضف بند مواد واحدًا على الأقل.',noAllocation:'لا يوجد تخصيص متاح.',noPermission:'غير مصرح',
}}
