export const fieldDict={
en:{
 fieldOperations:'Field operations',fieldMaterials:'Actual materials consumed',fieldVisits:'Technician visits',fieldLabor:'Labor records',fieldEvidence:'Photos & attachments',
 startVisit:'Start visit',finishVisit:'Finish visit',cancelVisit:'Cancel visit',recordLabor:'Record labor',
 enableField:'Enable field completion controls',fieldControls:'Field quality controls',requireEvidence:'Require evidence for completion',
 visitNumber:'Visit number',technician:'Technician',startedAt:'Started at',endedAt:'Ended at',finishedAt:'Finished at',
 duration:'Duration',minutes:'minutes',activity:'Activity',diagnosis:'Diagnosis',workPerformed:'Work performed',
 testsPerformed:'Tests performed',notes:'Notes',reason:'Reason',file:'File',caption:'Caption',uploadEvidence:'Upload evidence',
 openEvidence:'Open attachment',pending:'Pending',ready:'Ready',failed:'Failed',finished:'Finished',
 open:'Open',cancelled:'Cancelled',workOrder:'Work order',status:'Status',actions:'Actions',details:'Details',
 createdAt:'Created',refresh:'Refresh',save:'Save',cancel:'Cancel',select:'Select...',loading:'Loading...',noData:'No records found',
 saved:'Saved successfully',confirmAction:'Confirm this action?',noPermission:'Access denied',
 fieldNotice:'Visits and labor use server-recorded timestamps and entered work intervals. GPS, QR attendance and digital signatures are not yet implemented.',
 evidenceNotice:'Private evidence accepts JPG, PNG, WebP and PDF up to 10 MB. Uploads remain linked to their original work order and are not publicly accessible.',
 laborNotice:'Enter the actual work interval. Overlapping labor and intervals outside the visit are rejected. One technician may have only one open visit.',
 fieldGateNotice:'Enabling field controls requires a finished visit, recorded labor and verified evidence before the existing work order can be completed. Existing work orders are not automatically changed.',
 materialsNotice:'Materials consumed are recorded in Advanced Stock. This page links to the existing stock workflow rather than duplicating balances.',
}
,ar:{
 fieldOperations:'العمليات الميدانية',fieldMaterials:'المواد المستهلكة فعليًا',fieldVisits:'زيارات الفنيين',fieldLabor:'سجلات ساعات العمل',fieldEvidence:'الصور والمرفقات',
 startVisit:'بدء الزيارة',finishVisit:'إنهاء الزيارة',cancelVisit:'إلغاء الزيارة',recordLabor:'تسجيل وقت العمل',
 enableField:'تفعيل ضوابط الإكمال الميداني',fieldControls:'ضوابط الجودة الميدانية',requireEvidence:'اشتراط المرفقات للإكمال',
 visitNumber:'رقم الزيارة',technician:'الفني',startedAt:'وقت البداية',endedAt:'وقت النهاية',finishedAt:'وقت الانتهاء',
 duration:'المدة',minutes:'دقيقة',activity:'النشاط',diagnosis:'التشخيص',workPerformed:'الأعمال المنفذة',
 testsPerformed:'الاختبارات المنفذة',notes:'ملاحظات',reason:'السبب',file:'الملف',caption:'الوصف',uploadEvidence:'رفع مرفق',
 openEvidence:'فتح المرفق',pending:'قيد الرفع',ready:'جاهز',failed:'فشل',finished:'منتهية',
 open:'مفتوحة',cancelled:'ملغاة',workOrder:'أمر العمل',status:'الحالة',actions:'الإجراءات',details:'التفاصيل',
 createdAt:'تاريخ الإنشاء',refresh:'تحديث',save:'حفظ',cancel:'إلغاء',select:'اختر...',loading:'جارٍ التحميل...',noData:'لا توجد بيانات',
 saved:'تم الحفظ بنجاح',confirmAction:'هل تؤكد تنفيذ الإجراء؟',noPermission:'غير مصرح',
 fieldNotice:'تستخدم الزيارات وقت الخادم وفترات العمل المدخلة. التحقق من GPS والحضور عبر QR والتوقيعات الرقمية لم تُنفذ بعد.',
 evidenceNotice:'المرفقات خاصة وتقبل JPG وPNG وWebP وPDF حتى 10 ميجابايت. تبقى مرتبطة بأمر العمل الأصلي ولا تُتاح للعامة.',
 laborNotice:'أدخل فترة العمل الفعلية. يمنع النظام تداخل الساعات أو تسجيل وقت خارج الزيارة، ويسمح بزيارة مفتوحة واحدة لكل فني.',
 fieldGateNotice:'يتطلب تفعيل الضوابط زيارة منتهية وساعات عمل مسجلة ومرفقًا موثقًا قبل إكمال أمر العمل الحالي. لا تتغير أوامر العمل السابقة تلقائيًا.',
 materialsNotice:'تُسجل المواد المستهلكة في المخزون المتقدم. هذه الصفحة ترتبط بالمسار الموجود دون تكرار الأرصدة.',
}}
