export const ppmDict={
en:{
 year:'Year',month:'Month',ppm:'Preventive maintenance',ppmProcedures:'Procedure library',ppmPlans:'Asset plans',ppmSchedule:'Annual schedule',ppmJobs:'PPM work orders',
 newProcedure:'New procedure',newPlan:'New asset plan',procedure:'Procedure',plan:'Plan',job:'Work order',procedureCode:'Procedure code',planCode:'Plan code',jobNumber:'PPM job number',workOrder:'Unified work order',
 frequency:'Frequency',daily:'Daily',weekly:'Weekly',monthly:'Monthly',quarterly:'Quarterly',semiannual:'Semiannual',annual:'Annual',intervalCount:'Every N intervals',startDate:'Start date',nextDue:'Next due',dueDate:'Due date',
 estimatedMinutes:'Estimated minutes',manufacturer:'Manufacturer',model:'Model',category:'Category',asset:'Asset',organization:'Company',client:'Client',site:'Site',contractNumber:'Contract',
 nameAr:'Arabic name',nameEn:'English name',description:'Description',reference:'OEM / contract reference',version:'Version',revision:'Revision',revise:'Create new revision',addStep:'Add procedure step',editStep:'Edit step',deleteStep:'Delete step',
 instructionsAr:'Arabic instructions',instructionsEn:'English instructions',taskType:'Task type',responseType:'Response type',required:'Mandatory',unit:'Unit',minValue:'Minimum',maxValue:'Maximum',
 safetyNotes:'Safety / LOTO / permit',tools:'Tools and instruments',materials:'Materials / spares',inspection:'Inspection',cleaning:'Cleaning',lubrication:'Lubrication',adjustment:'Adjustment',test:'Test',replacement:'Replacement',safety:'Safety',other:'Other',
 pass_fail:'Pass / Fail / N/A',reading:'Numeric reading',text:'Text',pass:'Pass',fail:'Fail',na:'Not applicable',comment:'Comment',result:'Result',checklist:'Execution checklist',results:'Results',
 create:'Create',activate:'Activate',pause:'Pause',archive:'Archive',approve:'Approve',assign:'Assign',start:'Start',complete:'Submit completion',close:'Close',reject:'Return for rework',
 generate:'Generate schedule',throughDate:'Generate through',assignedTo:'Assigned technician',scheduled:'Scheduled',assigned:'Assigned',in_progress:'In progress',completed:'Completed',approved:'Approved',closed:'Closed',cancelled:'Cancelled',draft:'Draft',active:'Active',paused:'Paused',archived:'Archived',
 scope:'Company / client / site',title:'Title',status:'Status',actions:'Actions',details:'Details',history:'Activity history',createdAt:'Created',loading:'Loading...',noData:'No records found',noPermission:'Access denied',saved:'Saved successfully',refresh:'Refresh',save:'Save',cancel:'Cancel',select:'Select...',all:'All',search:'Search',reason:'Reason',
 procedureNotice:'Use approved OEM, contract or applicable standard procedures. Illustrative examples are not certified maintenance instructions.',
 scheduleNotice:'Schedules are generated from each asset plan. Generation is idempotent; it does not generate weekly or monthly work from an annual procedure.',
 followup:'Create corrective request',followupCreated:'Corrective request',executionNotice:'Complete every step. Mandatory steps cannot be skipped. A failed step blocks QA approval until resolved.',
 planNotice:'The procedure is selected for this asset. Every frequency requires its own plan and approved procedure.',
 qaNotice:'An independent approver is required. PDF reports, stock transactions, GPS and PDF reporting, stock transactions and GPS are planned for later releases.',
 confirmAction:'Confirm this action?',noAssignee:'Assign an authorized technician first.',noProcedure:'Create and approve a procedure first.',noPlan:'Create an active plan first.',automaticCode:'Generated when saved'
},
ar:{
 year:'السنة',month:'الشهر',ppm:'الصيانة الوقائية',ppmProcedures:'مكتبة الإجراءات',ppmPlans:'خطط المعدات',ppmSchedule:'الجدول السنوي',ppmJobs:'أوامر الصيانة الوقائية',
 newProcedure:'إجراء جديد',newPlan:'خطة معدة جديدة',procedure:'الإجراء',plan:'الخطة',job:'أمر العمل',procedureCode:'كود الإجراء',planCode:'كود الخطة',jobNumber:'رقم مهمة PPM',workOrder:'أمر العمل الموحد',
 frequency:'التكرار',daily:'يومي',weekly:'أسبوعي',monthly:'شهري',quarterly:'ربع سنوي',semiannual:'نصف سنوي',annual:'سنوي',intervalCount:'كل عدد من الفترات',startDate:'تاريخ البداية',nextDue:'الموعد التالي',dueDate:'تاريخ الاستحقاق',
 estimatedMinutes:'الدقائق التقديرية',manufacturer:'الشركة المصنعة',model:'الموديل',category:'التصنيف',asset:'المعدة',organization:'الشركة',client:'العميل',site:'الموقع',contractNumber:'العقد',
 nameAr:'الاسم بالعربية',nameEn:'الاسم بالإنجليزية',description:'الوصف',reference:'مرجع المصنع / العقد',version:'الإصدار',revision:'المراجعة',revise:'إنشاء مراجعة جديدة',addStep:'إضافة خطوة',editStep:'تعديل الخطوة',deleteStep:'حذف الخطوة',
 instructionsAr:'التعليمات بالعربية',instructionsEn:'التعليمات بالإنجليزية',taskType:'نوع المهمة',responseType:'نوع الاستجابة',required:'إلزامية',unit:'الوحدة',minValue:'الحد الأدنى',maxValue:'الحد الأعلى',
 safetyNotes:'السلامة / العزل / التصريح',tools:'الأدوات وأجهزة القياس',materials:'المواد وقطع الغيار',inspection:'فحص',cleaning:'تنظيف',lubrication:'تشحيم',adjustment:'ضبط',test:'اختبار',replacement:'استبدال',safety:'سلامة',other:'أخرى',
 pass_fail:'نجاح / فشل / لا ينطبق',reading:'قراءة رقمية',text:'نص',pass:'ناجح',fail:'فشل',na:'لا ينطبق',comment:'ملاحظة',result:'النتيجة',checklist:'قائمة التنفيذ',results:'النتائج',
 create:'إنشاء',activate:'تفعيل',pause:'إيقاف مؤقت',archive:'أرشفة',approve:'اعتماد',assign:'إسناد',start:'بدء',complete:'تقديم الإنجاز',close:'إغلاق',reject:'إعادة للعمل',
 generate:'توليد الجدول',throughDate:'التوليد حتى',assignedTo:'الفني المكلف',scheduled:'مجدول',assigned:'مسند',in_progress:'قيد التنفيذ',completed:'مكتمل',approved:'معتمد',closed:'مغلق',cancelled:'ملغي',draft:'مسودة',active:'نشط',paused:'متوقف',archived:'مؤرشف',
 scope:'الشركة / العميل / الموقع',title:'العنوان',status:'الحالة',actions:'الإجراءات',details:'التفاصيل',history:'سجل النشاط',createdAt:'تاريخ الإنشاء',loading:'جارٍ التحميل...',noData:'لا توجد بيانات',noPermission:'غير مصرح',saved:'تم الحفظ بنجاح',refresh:'تحديث',save:'حفظ',cancel:'إلغاء',select:'اختر...',all:'الكل',search:'بحث',reason:'السبب',
 procedureNotice:'استخدم إجراءات المصنع المعتمدة أو العقد أو المعايير المنطبقة. الأمثلة التوضيحية ليست تعليمات صيانة معتمدة.',
 scheduleNotice:'يتم توليد الجدول من خطة كل معدة. التوليد لا يكرر الأوامر، والإجراء السنوي لا ينشئ التكرارات الأقل تلقائيًا.',
 followup:'إنشاء طلب صيانة تصحيحية',followupCreated:'الطلب التصحيحي',executionNotice:'أكمل جميع الخطوات. الخطوات الإلزامية لا يمكن تخطيها، والفشل يمنع اعتماد الجودة حتى معالجته.',
 planNotice:'يتم اختيار الإجراء المناسب لهذه المعدة. كل تكرار له خطة وإجراء معتمد مستقل.',
 qaNotice:'يلزم اعتماد مستقل. تقارير PDF وحركات المخزون وGPS ليست مفعلة في هذا الإصدار التأسيسي.',
 confirmAction:'هل تؤكد تنفيذ الإجراء؟',noAssignee:'قم بإسناد فني مخول أولًا.',noProcedure:'أنشئ إجراءً واعتمده أولًا.',noPlan:'أنشئ خطة نشطة أولًا.',automaticCode:'ينشأ عند الحفظ'
}}
