export const productExperienceDict={
 en:{
  workspace:'Workspace',
  workspaceOperations:'Operations Workspace',
  workspaceField:'Field Operations Workspace',
  workspaceSoftFm:'Soft FM Workspace',
  workspaceManagement:'Management Workspace',
  workspaceAdministration:'Administration Workspace',
  navCore:'Core Operations',
  navAssets:'Assets & Facilities',
  navSupply:'Supply & Commercial',
  navSafety:'Safety & Compliance',
  navPerformance:'Performance & Analytics',
  navAdministration:'Administration',
  quickActions:'Quick actions',
  quickActionsHelp:'Your most relevant tools are shown based on your permissions.',
  commandCenter:'Operations command center',
  commandCenterHelp:'Open only the modules required for your role. Other capabilities remain available to authorized users.',
  openModule:'Open module',
  accessReviewWorkflow:'Request → Independent approval → Scoped access → Periodic review',
  focusWorkOrders:'Work orders',
  focusPreventive:'Preventive maintenance',
  focusField:'My field work',
  focusSoftFm:'Soft FM tasks',
  focusAssets:'Asset register',
  focusPlanning:'Planning calendar',
  focusWorkforce:'Workforce dispatch',
  focusInventory:'Inventory',
  focusProcurement:'Procurement',
  focusReports:'Reports',
  focusKpi:'KPI & SLA',
  focusExecutive:'Executive dashboard',
  focusUsers:'Users & access',
  usersAccess:'Users & Access',
  focusGovernance:'Governance',
  focusAccessReview:'Access approvals'
 },
 ar:{
  workspace:'مساحة العمل',
  workspaceOperations:'مساحة العمليات',
  workspaceField:'مساحة العمليات الميدانية',
  workspaceSoftFm:'مساحة الخدمات المساندة',
  workspaceManagement:'مساحة الإدارة',
  workspaceAdministration:'مساحة إدارة النظام',
  navCore:'العمليات الأساسية',
  navAssets:'الأصول والمرافق',
  navSupply:'الإمداد والتجاري',
  navSafety:'السلامة والامتثال',
  navPerformance:'الأداء والتحليلات',
  navAdministration:'إدارة النظام',
  quickActions:'الوصول السريع',
  quickActionsHelp:'تظهر الأدوات الأكثر ارتباطًا بعملك حسب صلاحياتك.',
  commandCenter:'مركز العمليات',
  commandCenterHelp:'تظهر لك الوحدات المناسبة لصلاحياتك فقط، وتبقى بقية الوظائف متاحة للمخولين.',
  openModule:'فتح الوحدة',
  accessReviewWorkflow:'طلب صلاحية ← اعتماد مستقل ← تطبيق الصلاحية ضمن النطاق ← مراجعة دورية',
  focusWorkOrders:'أوامر العمل',
  focusPreventive:'الصيانة الوقائية',
  focusField:'أعمالي الميدانية',
  focusSoftFm:'مهام الخدمات المساندة',
  focusAssets:'سجل الأصول',
  focusPlanning:'تقويم الصيانة',
  focusWorkforce:'توزيع القوى العاملة',
  focusInventory:'المخزون',
  focusProcurement:'المشتريات',
  focusReports:'التقارير',
  focusKpi:'مؤشرات الأداء و SLA',
  focusExecutive:'لوحة الإدارة التنفيذية',
  focusUsers:'المستخدمون والصلاحيات',
  usersAccess:'المستخدمون والصلاحيات',
  focusGovernance:'حوكمة الصلاحيات',
  focusAccessReview:'اعتماد الصلاحيات'
 }
}
