export const approvalDict={
en:{
 approvals:'Owner & consultant approvals',approvalPortal:'Approval portal',approvalRequests:'Approval requests',
 approvalCreate:'Request approval',approvalReviewer:'Reviewer',approvalOwner:'Owner / client',approvalConsultant:'Consultant',
 approvalEntity:'Entity',approvalWorkOrder:'Work order',approvalPPM:'PPM job',approvalSubject:'Subject',
 approvalRequestComment:'Request comment',approvalDecisionComment:'Decision comment',approvalDue:'Due date',
 approvalApprove:'Approve',approvalReject:'Reject',approvalCancel:'Cancel request',approvalPending:'Pending',
 approvalApproved:'Approved',approvalRejected:'Rejected',approvalCancelled:'Cancelled',approvalRound:'Round',
 approvalRequestedAt:'Requested',approvalDecidedAt:'Decided',approvalNoData:'No approval requests found',
 approvalIndependent:'The requester cannot decide their own approval. Rejections require a reason.',
 approvalCloseGate:'Once an external approval is requested, the entity cannot close while its latest requested approval is pending or rejected.',
 approvalExternalOnly:'Owner and consultant decisions are external to the internal QA approval.',
 approvalConsultantAccess:'Consultant access',approvalConsultantEmail:'Consultant email',
 approvalFindUser:'Find user',approvalGrantAccess:'Grant consultant access',approvalRevokeAccess:'Revoke access',
 approvalUserFound:'Active user found',approvalUserNotFound:'No active profile found for this email.',
 approvalClient:'Client',approvalStatus:'Status',approvalAll:'All',approvalRefresh:'Refresh',
 approvalFilter:'Apply filter',approvalSave:'Save',approvalSelect:'Select...',approvalReasonRequired:'A reason of at least 5 characters is required.',
 approvalRequestCreated:'Approval request created.',approvalDecisionSaved:'Decision saved.',
 approvalAccessSaved:'Consultant access updated.',approvalEntityState:'Only internally approved work orders and PPM jobs are eligible.',
 approvalNoAccess:'No owner/consultant approval access is available for this account.',
 approvalRoleStaff:'Internal staff',approvalRoleOwner:'Owner / client',approvalRoleConsultant:'Consultant',
 approvalDetails:'Details',approvalEntityNumber:'Reference',approvalEntityTitle:'Title'
},
ar:{
 approvals:'اعتمادات المالك والاستشاري',approvalPortal:'بوابة الاعتمادات',approvalRequests:'طلبات الاعتماد',
 approvalCreate:'طلب اعتماد',approvalReviewer:'جهة الاعتماد',approvalOwner:'المالك / العميل',approvalConsultant:'الاستشاري',
 approvalEntity:'المعاملة',approvalWorkOrder:'أمر عمل',approvalPPM:'مهمة صيانة وقائية',approvalSubject:'الموضوع',
 approvalRequestComment:'ملاحظات الطلب',approvalDecisionComment:'ملاحظات القرار',approvalDue:'موعد الاستحقاق',
 approvalApprove:'اعتماد',approvalReject:'رفض',approvalCancel:'إلغاء الطلب',approvalPending:'قيد الاعتماد',
 approvalApproved:'معتمد',approvalRejected:'مرفوض',approvalCancelled:'ملغى',approvalRound:'الجولة',
 approvalRequestedAt:'تاريخ الطلب',approvalDecidedAt:'تاريخ القرار',approvalNoData:'لا توجد طلبات اعتماد',
 approvalIndependent:'لا يمكن لطالب الاعتماد اتخاذ القرار على طلبه. الرفض يتطلب سببًا.',
 approvalCloseGate:'بعد إنشاء طلب اعتماد خارجي، لا يمكن إغلاق المعاملة ما دام أحدث اعتماد مطلوب قيد الانتظار أو مرفوضًا.',
 approvalExternalOnly:'اعتماد المالك أو الاستشاري مستقل عن اعتماد الجودة الداخلي.',
 approvalConsultantAccess:'صلاحيات الاستشاري',approvalConsultantEmail:'بريد الاستشاري',
 approvalFindUser:'بحث عن المستخدم',approvalGrantAccess:'منح صلاحية الاستشاري',approvalRevokeAccess:'إلغاء الصلاحية',
 approvalUserFound:'تم العثور على مستخدم نشط',approvalUserNotFound:'لا يوجد ملف مستخدم نشط بهذا البريد.',
 approvalClient:'العميل',approvalStatus:'الحالة',approvalAll:'الكل',approvalRefresh:'تحديث',
 approvalFilter:'تطبيق الفلتر',approvalSave:'حفظ',approvalSelect:'اختر...',approvalReasonRequired:'السبب مطلوب وبحد أدنى 5 أحرف.',
 approvalRequestCreated:'تم إنشاء طلب الاعتماد.',approvalDecisionSaved:'تم حفظ القرار.',
 approvalAccessSaved:'تم تحديث صلاحية الاستشاري.',approvalEntityState:'المتاح فقط أوامر العمل ومهام PPM المعتمدة داخليًا.',
 approvalNoAccess:'لا توجد صلاحية لاعتمادات المالك أو الاستشاري لهذا الحساب.',
 approvalRoleStaff:'موظف داخلي',approvalRoleOwner:'المالك / العميل',approvalRoleConsultant:'الاستشاري',
 approvalDetails:'التفاصيل',approvalEntityNumber:'المرجع',approvalEntityTitle:'العنوان'
}}
