export const mobileFieldDict={
en:{
 mobileField:'Field Mobile',
 mobileFieldTitle:'Mobile Field Workspace',
 mfRefresh:'Refresh',
 mfAssigned:'Assigned',
 mfP1:'Critical',
 mfBreached:'SLA breached',
 mfDueToday:'Due today',
 mfActiveVisit:'Active visit',
 mfAssetLookup:'Scan QR or find asset',
 mfAssetCode:'Scan the asset QR or enter its system-generated asset number',
 mfLookup:'Find asset',
 mfWorkOrders:'My work orders',
 mfStart:'Start visit',
 mfFinish:'Finish visit',
 mfWorkPerformed:'Work performed',
 mfDiagnosis:'Diagnosis',
 mfTests:'Tests performed',
 mfNotes:'Notes',
 mfLabor:'Add labor',
 mfActivity:'Activity',
 mfMinutes:'Minutes',
 mfEvidence:'Photo / Evidence',
 mfCaption:'Caption',
 mfUpload:'Upload',
 mfClient:'Client',
 mfSite:'Site',
 mfAsset:'Asset',
 mfPriority:'Priority',
 mfStatus:'Status',
 mfSla:'SLA',
 mfNoData:'No assigned work orders'
},
ar:{
 mobileField:'ميدان الفني',
 mobileFieldTitle:'واجهة الفني الميدانية للجوال',
 mfRefresh:'تحديث',
 mfAssigned:'المسندة',
 mfP1:'حرجة',
 mfBreached:'متجاوزة SLA',
 mfDueToday:'مستحق اليوم',
 mfActiveVisit:'زيارة نشطة',
 mfAssetLookup:'مسح QR أو البحث عن الأصل',
 mfAssetCode:'امسح QR للأصل أو أدخل رقم الأصل الذي أنشأه النظام تلقائيًا',
 mfLookup:'بحث عن الأصل',
 mfWorkOrders:'أوامر العمل المسندة لي',
 mfStart:'بدء الزيارة',
 mfFinish:'إنهاء الزيارة',
 mfWorkPerformed:'العمل المنفذ',
 mfDiagnosis:'التشخيص',
 mfTests:'الاختبارات',
 mfNotes:'ملاحظات',
 mfLabor:'إضافة وقت عمل',
 mfActivity:'النشاط',
 mfMinutes:'الدقائق',
 mfEvidence:'صورة / إثبات',
 mfCaption:'وصف',
 mfUpload:'رفع',
 mfClient:'العميل',
 mfSite:'الموقع',
 mfAsset:'الأصل',
 mfPriority:'الأولوية',
 mfStatus:'الحالة',
 mfSla:'SLA',
 mfNoData:'لا توجد أوامر عمل مسندة'
}}
