import {useEffect,useState} from 'react'
import {useLanguage} from '../i18n/LanguageContext'
import {supabase} from '../lib/supabaseClient'
import {loadHseDashboard,createHseIncident,loadHseDetail,addHseAction,completeHseAction,updateHseInvestigation,closeHseIncident} from '../lib/hse'
const localNow=()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16)
export default function HseIncidents(){
 const {t}=useLanguage(),[data,setData]=useState({incidents:[],sites:[],assets:[],work_orders:[],summary:{}}),[detail,setDetail]=useState(null),[selected,setSelected]=useState(''),[staff,setStaff]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const [form,setForm]=useState({site_id:'',asset_id:'',work_order_id:'',incident_type:'near_miss',severity:'medium',title:'',description:'',occurred_at:localNow(),immediate_action:''})
 const [action,setAction]=useState({action_text:'',owner_id:'',due_date:'',priority:'medium'}),[investigation,setInvestigation]=useState({root_cause:'',notes:'',immediate_action:''})
 const load=async()=>{setBusy(true);setError('');try{const [x,s]=await Promise.all([loadHseDashboard(),supabase.rpc('bf4_staff_directory')]);if(s.error)throw s.error;setData(x);setStaff(s.data||[]);if(!form.site_id&&x.sites?.[0])setForm(v=>({...v,site_id:x.sites[0].id}));if(selected)setDetail(await loadHseDetail(selected))}catch(e){setError(e.message)}finally{setBusy(false)}}
 useEffect(()=>{load()},[])
 const openDetail=async id=>{setSelected(id);setBusy(true);try{const x=await loadHseDetail(id);setDetail(x);setInvestigation({root_cause:x.incident?.root_cause||'',notes:x.incident?.investigation_notes||'',immediate_action:x.incident?.immediate_action||''})}catch(e){setError(e.message)}finally{setBusy(false)}}
 const saveIncident=async e=>{e.preventDefault();try{setBusy(true);const id=await createHseIncident(form);setForm(v=>({...v,title:'',description:'',asset_id:'',work_order_id:'',immediate_action:'',occurred_at:localNow()}));await load();await openDetail(id)}catch(e){setError(e.message)}finally{setBusy(false)}}
 const saveAction=async e=>{e.preventDefault();try{setBusy(true);await addHseAction({...action,incident_id:selected});setAction({action_text:'',owner_id:'',due_date:'',priority:'medium'});await openDetail(selected);await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 const saveInvestigation=async e=>{e.preventDefault();try{setBusy(true);await updateHseInvestigation(selected,investigation.root_cause,investigation.notes,investigation.immediate_action);await openDetail(selected);await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 const filteredAssets=(data.assets||[]).filter(a=>a.site_id===form.site_id),filteredWO=(data.work_orders||[]).filter(w=>w.site_id===form.site_id),s=data.summary||{},i=detail?.incident
 const typeLabel=x=>({injury:t('hseInjuryType'),near_miss:t('hseNearMissType'),property_damage:t('hseProperty'),environmental:t('hseEnvironmental'),unsafe_condition:t('hseUnsafe'),other:t('hseOther')}[x]||x)
 return <section className="facility-module">
  <div className="page-head"><h1>{t('hseCenter')}</h1><button className="btn secondary" onClick={load}>{t('hseRefresh')}</button></div>{error&&<div className="facility-panel" role="alert">{error}</div>}
  <div className="stats-grid facility-stats">{[['hseTotal',s.total],['hseOpen',s.open],['hseCritical',s.critical],['hseNearMiss',s.near_miss],['hseInjury',s.injury],['hseReady',s.ready_for_close]].map(([k,v])=><div className="stat-card" key={k}><span>{t(k)}</span><strong>{v||0}</strong></div>)}</div>
  <form className="facility-panel" onSubmit={saveIncident}><h2>{t('hseAdd')}</h2><div className="form-grid">
   <label>{t('hseSite')}<select required value={form.site_id} onChange={e=>setForm(v=>({...v,site_id:e.target.value,asset_id:'',work_order_id:''}))}><option value="">—</option>{data.sites?.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
   <label>{t('hseAsset')}<select value={form.asset_id} onChange={e=>setForm(v=>({...v,asset_id:e.target.value}))}><option value="">—</option>{filteredAssets.map(x=><option key={x.id} value={x.id}>{x.asset_tag} — {x.name}</option>)}</select></label>
   <label>{t('hseWorkOrder')}<select value={form.work_order_id} onChange={e=>setForm(v=>({...v,work_order_id:e.target.value}))}><option value="">—</option>{filteredWO.map(x=><option key={x.id} value={x.id}>{x.work_order_number} — {x.title}</option>)}</select></label>
   <label>{t('hseType')}<select value={form.incident_type} onChange={e=>setForm(v=>({...v,incident_type:e.target.value}))}>{['near_miss','injury','property_damage','environmental','unsafe_condition','other'].map(x=><option key={x} value={x}>{typeLabel(x)}</option>)}</select></label>
   <label>{t('hseSeverity')}<select value={form.severity} onChange={e=>setForm(v=>({...v,severity:e.target.value}))}>{['low','medium','high','critical'].map(x=><option key={x}>{x}</option>)}</select></label>
   <label>{t('hseOccurred')}<input required type="datetime-local" value={form.occurred_at} onChange={e=>setForm(v=>({...v,occurred_at:e.target.value}))}/></label>
   <label>{t('hseTitle')}<input required minLength={3} value={form.title} onChange={e=>setForm(v=>({...v,title:e.target.value}))}/></label>
   <label>{t('hseDescription')}<textarea required minLength={5} value={form.description} onChange={e=>setForm(v=>({...v,description:e.target.value}))}/></label>
   <label>{t('hseImmediate')}<textarea value={form.immediate_action} onChange={e=>setForm(v=>({...v,immediate_action:e.target.value}))}/></label>
  </div><button className="btn primary" disabled={busy}>{t('hseSave')}</button></form>
  <div className="facility-panel">{!data.incidents?.length?<p>{t('hseNoData')}</p>:<div className="table-wrap"><table><thead><tr><th>#</th><th>{t('hseType')}</th><th>{t('hseSite')}</th><th>{t('hseSeverity')}</th><th>{t('status')}</th><th></th></tr></thead><tbody>{data.incidents.map(x=><tr key={x.id}><td>{x.incident_number}</td><td>{typeLabel(x.incident_type)}</td><td>{x.site_name}</td><td>{x.severity}</td><td>{x.status}</td><td><button className="btn xs secondary" onClick={()=>openDetail(x.id)}>{t('hseDetail')}</button></td></tr>)}</tbody></table></div>}</div>
  {i&&<div className="facility-panel"><h2>{i.incident_number} — {i.title}</h2>
   {i.status!=='closed'&&i.status!=='cancelled'&&<form onSubmit={saveInvestigation}><div className="form-grid"><label>{t('hseRootCause')}<textarea required minLength={5} value={investigation.root_cause} onChange={e=>setInvestigation(v=>({...v,root_cause:e.target.value}))}/></label><label>{t('hseInvestigation')}<textarea value={investigation.notes} onChange={e=>setInvestigation(v=>({...v,notes:e.target.value}))}/></label></div><button className="btn secondary">{t('hseUpdateInvestigation')}</button></form>}
   {i.status!=='closed'&&i.status!=='cancelled'&&<form onSubmit={saveAction}><div className="form-grid"><label>{t('hseAction')}<input required minLength={5} value={action.action_text} onChange={e=>setAction(v=>({...v,action_text:e.target.value}))}/></label><label>{t('hseOwner')}<select value={action.owner_id} onChange={e=>setAction(v=>({...v,owner_id:e.target.value}))}><option value="">—</option>{staff.filter(x=>x.organization_id===i.organization_id).map(x=><option key={x.id} value={x.id}>{x.full_name||x.email}</option>)}</select></label><label>{t('hseDue')}<input type="date" value={action.due_date} onChange={e=>setAction(v=>({...v,due_date:e.target.value}))}/></label></div><button className="btn secondary">{t('hseAddAction')}</button></form>}
   <div className="event-list">{detail.actions?.map(a=><div className="event-item" key={a.id}><strong>{a.action_text}</strong><span>{a.status} · {a.full_name||a.email||''}</span>{['open','in_progress'].includes(a.status)&&<button className="btn xs primary" onClick={async()=>{const n=prompt(t('hseComplete'));if(n){await completeHseAction(a.id,n);await openDetail(selected);await load()}}}>{t('hseComplete')}</button>}</div>)}</div>
   {i.status!=='closed'&&i.status!=='cancelled'&&<button className="btn primary" onClick={async()=>{const n=prompt(t('hseClose'));if(n){try{await closeHseIncident(selected,n);await openDetail(selected);await load()}catch(e){setError(e.message)}}}}>{t('hseClose')}</button>}
  </div>}
 </section>
}
