import {useEffect,useState} from 'react'
import {useLanguage} from '../i18n/LanguageContext'
import {supabase} from '../lib/supabaseClient'
import {loadCosting,saveRate,addCost,voidCost} from '../lib/costing'
export default function MaintenanceCosting(){
 const {t}=useLanguage(),[data,setData]=useState({rows:[],totals:{},rates:[],extra_costs:[]}),[orgs,setOrgs]=useState([]),[staff,setStaff]=useState([]),[org,setOrg]=useState(''),[error,setError]=useState('')
 const [rate,setRate]=useState({technician_id:'',hourly_rate:'',currency:'SAR',effective_from:new Date().toISOString().slice(0,10),effective_to:''})
 const [cost,setCost]=useState({work_order_id:'',cost_type:'other',description:'',amount:'',currency:'SAR',cost_date:new Date().toISOString().slice(0,10)})
 const load=async()=>{try{setError('');const [d,o,s]=await Promise.all([loadCosting(org||null),supabase.from('bf_organizations').select('id,name_ar,name_en'),supabase.from('bf_profiles').select('id,full_name,email').eq('status','active')]);if(o.error)throw o.error;if(s.error)throw s.error;setData(d);setOrgs(o.data||[]);setStaff(s.data||[])}catch(e){setError(e.message)}}
 useEffect(()=>{load()},[org])
 return <section className="facility-module"><div className="page-head"><h1>{t('costingCenter')}</h1><button className="btn secondary" onClick={load}>{t('costingRefresh')}</button></div>{error&&<div className="facility-panel">{error}</div>}
 <div className="facility-panel"><select value={org} onChange={e=>setOrg(e.target.value)}><option value="">{t('all')}</option>{orgs.map(o=><option key={o.id} value={o.id}>{o.name_ar||o.name_en}</option>)}</select></div>
 <div className="stats-grid facility-stats">{[['costingLabor',data.totals?.labor],['costingMaterial',data.totals?.material],['costingExtra',data.totals?.extra],['costingTotal',data.totals?.grand]].map(([k,v])=><div className="stat-card" key={k}><span>{t(k)}</span><strong>{v||0}</strong></div>)}</div>
 <form className="facility-panel" onSubmit={async e=>{e.preventDefault();await saveRate({...rate,organization_id:org});await load()}}><h2>{t('costingSaveRate')}</h2><div className="form-grid"><select required value={rate.technician_id} onChange={e=>setRate(v=>({...v,technician_id:e.target.value}))}><option value="">{t('select')}</option>{staff.map(s=><option key={s.id} value={s.id}>{s.full_name||s.email}</option>)}</select><input required type="number" min="0" step="0.01" placeholder={t('costingRate')} value={rate.hourly_rate} onChange={e=>setRate(v=>({...v,hourly_rate:e.target.value}))}/><input required type="date" value={rate.effective_from} onChange={e=>setRate(v=>({...v,effective_from:e.target.value}))}/><input type="date" value={rate.effective_to} onChange={e=>setRate(v=>({...v,effective_to:e.target.value}))}/></div><button className="btn primary" disabled={!org}>{t('costingSaveRate')}</button></form>
 <form className="facility-panel" onSubmit={async e=>{e.preventDefault();await addCost(cost);setCost(v=>({...v,description:'',amount:''}));await load()}}><h2>{t('costingAdd')}</h2><div className="form-grid"><select required value={cost.work_order_id} onChange={e=>setCost(v=>({...v,work_order_id:e.target.value}))}><option value="">{t('select')}</option>{data.rows?.map(w=><option key={w.id} value={w.id}>{w.work_order_number} — {w.title}</option>)}</select><select value={cost.cost_type} onChange={e=>setCost(v=>({...v,cost_type:e.target.value}))}>{['contractor','transport','rental','other'].map(x=><option key={x}>{x}</option>)}</select><input required minLength={3} placeholder={t('costingDescription')} value={cost.description} onChange={e=>setCost(v=>({...v,description:e.target.value}))}/><input required type="number" min="0" step="0.01" placeholder={t('costingAmount')} value={cost.amount} onChange={e=>setCost(v=>({...v,amount:e.target.value}))}/></div><button className="btn primary">{t('costingAdd')}</button></form>
 <div className="facility-panel"><h2>{t('costing')}</h2>{!data.rows?.length?<p>{t('costingNoData')}</p>:<div className="table-wrap"><table><thead><tr><th>{t('costingWorkOrder')}</th><th>{t('costingLabor')}</th><th>{t('costingMaterial')}</th><th>{t('costingExtra')}</th><th>{t('costingTotal')}</th></tr></thead><tbody>{data.rows.map(w=><tr key={w.id}><td>{w.work_order_number}<br/><small>{w.title}</small></td><td>{w.labor_cost}</td><td>{w.material_cost}</td><td>{w.extra_cost}</td><td><strong>{w.total_cost}</strong></td></tr>)}</tbody></table></div>}</div>
 <div className="facility-panel"><h2>{t('costingExtra')}</h2>{data.extra_costs?.map(c=><div className="event-item" key={c.id}><strong>{c.description} — {c.amount} {c.currency}</strong><button className="btn xs danger-soft" onClick={async()=>{const r=prompt(t('costingVoid'));if(r){await voidCost(c.id,r);await load()}}}>{t('costingVoid')}</button></div>)}</div></section>}
