-- Basmat Facilities CMMS — Professional Reference Library + Team User Membership Fix
-- Safe additive migration. Does not delete production data.
-- 2026-09-24

create table if not exists public.bf_ref_facility_owners (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name_ar text not null,
  name_en text,
  category text not null default 'government_entity',
  sector text,
  country_code text not null default 'SA',
  status text not null default 'active',
  source_url text,
  source_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.bf_ref_maintenance_companies (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name_ar text not null,
  name_en text,
  capabilities text[] not null default '{}'::text[],
  website text,
  status text not null default 'active',
  source_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.bf_ref_facility_types (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name_ar text not null,
  name_en text,
  status text not null default 'active',
  created_at timestamptz not null default now()
);

insert into public.bf_ref_facility_owners
(code,name_ar,name_en,category,sector,country_code,status,source_url,source_note)
values
('MOI','وزارة الداخلية','Ministry of Interior','government_ministry','security','SA','active','https://my.gov.sa/en/agencies','Official Saudi government directory / مرجع حكومي رسمي'),
('MOD','وزارة الدفاع','Ministry of Defense','government_ministry','defense','SA','active','https://my.gov.sa/en/agencies','Official Saudi government directory / مرجع حكومي رسمي'),
('MNG','وزارة الحرس الوطني','Ministry of National Guard','government_ministry','defense','SA','active','https://my.gov.sa/en/agencies','Official Saudi government directory / مرجع حكومي رسمي'),
('MOFA','وزارة الخارجية','Ministry of Foreign Affairs','government_ministry','foreign_affairs','SA','active','https://my.gov.sa/en/agencies','Official Saudi government directory / مرجع حكومي رسمي'),
('MOJ','وزارة العدل','Ministry of Justice','government_ministry','justice','SA','active','https://my.gov.sa/en/agencies','Official Saudi government directory / مرجع حكومي رسمي'),
('MOIA','وزارة الشؤون الإسلامية والدعوة والإرشاد','Ministry of Islamic Affairs, Dawah and Guidance','government_ministry','religious_affairs','SA','active','https://my.gov.sa/en/agencies','Official Saudi government directory / مرجع حكومي رسمي'),
('MOHU','وزارة الحج والعمرة','Ministry of Hajj and Umrah','government_ministry','hajj_umrah','SA','active','https://my.gov.sa/en/agencies','Official Saudi government directory / مرجع حكومي رسمي'),
('MOH','وزارة الصحة','Ministry of Health','government_ministry','health','SA','active','https://my.gov.sa/en/agencies','Official Saudi government directory / مرجع حكومي رسمي'),
('MOE','وزارة التعليم','Ministry of Education','government_ministry','education','SA','active','https://my.gov.sa/en/agencies','Official Saudi government directory / مرجع حكومي رسمي'),
('MOF','وزارة المالية','Ministry of Finance','government_ministry','finance','SA','active','https://my.gov.sa/en/agencies','Official Saudi government directory / مرجع حكومي رسمي'),
('MEP','وزارة الاقتصاد والتخطيط','Ministry of Economy and Planning','government_ministry','economy','SA','active','https://my.gov.sa/en/agencies','Official Saudi government directory / مرجع حكومي رسمي'),
('MOC','وزارة التجارة','Ministry of Commerce','government_ministry','commerce','SA','active','https://my.gov.sa/en/agencies','Official Saudi government directory / مرجع حكومي رسمي'),
('MISA','وزارة الاستثمار','Ministry of Investment','government_ministry','investment','SA','active','https://my.gov.sa/en/agencies','Official Saudi government directory / مرجع حكومي رسمي'),
('MOEN','وزارة الطاقة','Ministry of Energy','government_ministry','energy','SA','active','https://my.gov.sa/en/agencies','Official Saudi government directory / مرجع حكومي رسمي'),
('MIM','وزارة الصناعة والثروة المعدنية','Ministry of Industry and Mineral Resources','government_ministry','industry','SA','active','https://my.gov.sa/en/agencies','Official Saudi government directory / مرجع حكومي رسمي'),
('MEWA','وزارة البيئة والمياه والزراعة','Ministry of Environment, Water and Agriculture','government_ministry','environment','SA','active','https://my.gov.sa/en/agencies','Official Saudi government directory / مرجع حكومي رسمي'),
('MHRSD','وزارة الموارد البشرية والتنمية الاجتماعية','Ministry of Human Resources and Social Development','government_ministry','human_resources','SA','active','https://my.gov.sa/en/agencies','Official Saudi government directory / مرجع حكومي رسمي'),
('MOHOU','وزارة البلديات والإسكان','Ministry of Municipalities and Housing','government_ministry','municipal_housing','SA','active','https://my.gov.sa/en/agencies','Official Saudi government directory / مرجع حكومي رسمي'),
('MOTLS','وزارة النقل والخدمات اللوجستية','Ministry of Transport and Logistics Services','government_ministry','transport','SA','active','https://my.gov.sa/en/agencies','Official Saudi government directory / مرجع حكومي رسمي'),
('MCIT','وزارة الاتصالات وتقنية المعلومات','Ministry of Communications and Information Technology','government_ministry','ict','SA','active','https://my.gov.sa/en/agencies','Official Saudi government directory / مرجع حكومي رسمي'),
('MOM','وزارة الإعلام','Ministry of Media','government_ministry','media','SA','active','https://my.gov.sa/en/agencies','Official Saudi government directory / مرجع حكومي رسمي'),
('MOCUL','وزارة الثقافة','Ministry of Culture','government_ministry','culture','SA','active','https://my.gov.sa/en/agencies','Official Saudi government directory / مرجع حكومي رسمي'),
('MOS','وزارة الرياضة','Ministry of Sport','government_ministry','sport','SA','active','https://my.gov.sa/en/agencies','Official Saudi government directory / مرجع حكومي رسمي'),
('MOT','وزارة السياحة','Ministry of Tourism','government_ministry','tourism','SA','active','https://my.gov.sa/en/agencies','Official Saudi government directory / مرجع حكومي رسمي')
on conflict (code) do update set
 name_ar=excluded.name_ar,
 name_en=excluded.name_en,
 category=excluded.category,
 sector=excluded.sector,
 country_code=excluded.country_code,
 status='active',
 source_url=excluded.source_url,
 source_note=excluded.source_note,
 updated_at=now();

insert into public.bf_ref_maintenance_companies
(code,name_ar,name_en,capabilities,website,status,source_note)
values
('SHALFA','مجموعة شلفا / شلفا لإدارة المرافق','Shalfa Group / Shalfa Facility Management',ARRAY['facility_management','operations_maintenance','cleaning','security_safety','fire_safety','environmental']::text[],'https://shalfa.sa/Ar/','active','Reference catalog only; not a ranking or contract claim'),
('NASBAN','مجموعة النصبان','Nasban Group',ARRAY['facility_management','operations_maintenance','hard_services','soft_services']::text[],'https://nasban.com.sa/','active','Reference catalog only; not a ranking or contract claim'),
('MAG','مجموعة المجال العربي','Al Majal Al Arabi Group',ARRAY['integrated_facility_management','operations_maintenance','environmental','catering']::text[],'https://mag-sa.com/ar/','active','Reference catalog only; not a ranking or contract claim'),
('FMCO','شركة إدارة المرافق المتكاملة FMCO','FMCO',ARRAY['total_facility_management','hard_services','soft_services','catering','infrastructure_maintenance']::text[],'https://www.fmco.sa/','active','Reference catalog only; not a ranking or contract claim'),
('SRACO','سراكو لإدارة المرافق','SRACO Facility Management',ARRAY['facility_management','operations_maintenance','asset_management','energy_management','landscape']::text[],'https://sraco.com.sa/en','active','Reference catalog only; not a ranking or contract claim'),
('ALBAWANI_DFM','البواني - إدارة المرافق والتطوير','Al Bawani - Development & Facilities Management',ARRAY['facility_management','development','operations_maintenance']::text[],'https://www.albawani.net/','active','Reference catalog only; not a ranking or contract claim')
on conflict (code) do update set
 name_ar=excluded.name_ar,
 name_en=excluded.name_en,
 capabilities=excluded.capabilities,
 website=excluded.website,
 status='active',
 source_note=excluded.source_note,
 updated_at=now();

insert into public.bf_ref_facility_types(code,name_ar,name_en,status)
values
('HQ','مقر رئيسي','Headquarters','active'),
('REGIONAL','فرع / إدارة إقليمية','Regional Office','active'),
('ADMIN','مجمع إداري','Administrative Complex','active'),
('OPS','مركز عمليات','Operations Center','active'),
('COMMAND','مركز قيادة وتحكم','Command & Control Center','active'),
('DATA_CENTER','مركز بيانات','Data Center','active'),
('WAREHOUSE','مستودع مركزي','Central Warehouse','active'),
('WORKSHOP','ورشة صيانة','Maintenance Workshop','active'),
('TRAINING','مركز تدريب','Training Center','active'),
('RESIDENTIAL','مجمع سكني','Residential Compound','active'),
('SECURITY','منشأة أمنية','Security Facility','active'),
('PRISON','إصلاحية / سجن','Correctional Facility','active'),
('BORDER','منشأة حدودية','Border Facility','active'),
('CIVIL_DEFENSE','مركز دفاع مدني','Civil Defense Center','active'),
('POLICE','مركز شرطة','Police Station','active'),
('SCHOOL','مدرسة / منشأة تعليمية','School / Education Facility','active'),
('UNIVERSITY','حرم جامعي','University Campus','active'),
('HOSPITAL','مستشفى / مجمع صحي','Hospital / Healthcare Complex','active'),
('SPORT','مدينة / منشأة رياضية','Sports Facility','active'),
('MUNICIPAL','مرفق بلدي','Municipal Facility','active'),
('CULTURE','مرفق ثقافي','Cultural Facility','active'),
('TOURISM','مرفق سياحي','Tourism Facility','active')
on conflict (code) do update set
 name_ar=excluded.name_ar,
 name_en=excluded.name_en,
 status='active';

alter table public.bf_ref_facility_owners enable row level security;
alter table public.bf_ref_maintenance_companies enable row level security;
alter table public.bf_ref_facility_types enable row level security;

drop policy if exists "bf_ref_facility_owners_read" on public.bf_ref_facility_owners;
create policy "bf_ref_facility_owners_read" on public.bf_ref_facility_owners
for select to authenticated using (true);

drop policy if exists "bf_ref_maintenance_companies_read" on public.bf_ref_maintenance_companies;
create policy "bf_ref_maintenance_companies_read" on public.bf_ref_maintenance_companies
for select to authenticated using (true);

drop policy if exists "bf_ref_facility_types_read" on public.bf_ref_facility_types;
create policy "bf_ref_facility_types_read" on public.bf_ref_facility_types
for select to authenticated using (true);

-- Explicit bridge between an authenticated user and every organization in which
-- that user may work. This solves the old assumption that a person has only one organization_id.
create table if not exists public.bf_user_org_memberships (
  user_id uuid not null,
  organization_id uuid not null references public.bf_organizations(id) on delete cascade,
  source text not null default 'manual',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, organization_id, source)
);

create index if not exists bf_user_org_memberships_org_idx
  on public.bf_user_org_memberships(organization_id, active);

-- Mirror current/future permission assignments into the membership bridge.
-- We only touch tables whose names clearly indicate access/permission/role assignments
-- and that actually contain BOTH user_id and organization_id.
create or replace function public.bf_sync_user_org_membership_trigger()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_source text := 'access:' || tg_table_name;
begin
  if tg_op = 'DELETE' then
    delete from public.bf_user_org_memberships
     where user_id = old.user_id
       and organization_id = old.organization_id
       and source = v_source;
    return old;
  end if;

  if tg_op = 'UPDATE'
     and (old.user_id is distinct from new.user_id
       or old.organization_id is distinct from new.organization_id) then
    delete from public.bf_user_org_memberships
     where user_id = old.user_id
       and organization_id = old.organization_id
       and source = v_source;
  end if;

  if new.user_id is not null and new.organization_id is not null then
    insert into public.bf_user_org_memberships(user_id,organization_id,source,active,updated_at)
    values(new.user_id,new.organization_id,v_source,true,now())
    on conflict (user_id,organization_id,source)
    do update set active=true,updated_at=now();
  end if;
  return new;
end;
$$;

do $$
declare r record;
begin
  for r in
    select t.table_schema,t.table_name
    from information_schema.tables t
    where t.table_schema='public'
      and t.table_type='BASE TABLE'
      and (
        t.table_name ilike '%permission%'
        or t.table_name ilike '%access%'
        or t.table_name ilike '%user_role%'
        or t.table_name ilike '%role_assign%'
      )
      and exists (
        select 1 from information_schema.columns c
        where c.table_schema=t.table_schema and c.table_name=t.table_name and c.column_name='user_id'
      )
      and exists (
        select 1 from information_schema.columns c
        where c.table_schema=t.table_schema and c.table_name=t.table_name and c.column_name='organization_id'
      )
  loop
    begin
      execute format(
        'insert into public.bf_user_org_memberships(user_id,organization_id,source,active)
         select user_id::uuid,organization_id::uuid,%L,true
         from %I.%I
         where user_id is not null and organization_id is not null
         on conflict (user_id,organization_id,source)
         do update set active=true,updated_at=now()',
        'access:'||r.table_name,r.table_schema,r.table_name
      );

      execute format('drop trigger if exists bf_sync_user_org_membership on %I.%I',r.table_schema,r.table_name);
      execute format(
        'create trigger bf_sync_user_org_membership
         after insert or update or delete on %I.%I
         for each row execute function public.bf_sync_user_org_membership_trigger()',
        r.table_schema,r.table_name
      );
    exception when others then
      raise notice 'Skipped access table %.%: %',r.table_schema,r.table_name,sqlerrm;
    end;
  end loop;
end $$;

-- Also preserve the organization relationship already returned by bf4_staff_directory().
do $$
begin
  begin
    insert into public.bf_user_org_memberships(user_id,organization_id,source,active)
    select
      coalesce((to_jsonb(s)->>'id')::uuid,(to_jsonb(s)->>'user_id')::uuid),
      (to_jsonb(s)->>'organization_id')::uuid,
      'staff_directory',
      true
    from public.bf4_staff_directory() s
    where coalesce(to_jsonb(s)->>'id',to_jsonb(s)->>'user_id') is not null
      and nullif(to_jsonb(s)->>'organization_id','') is not null
    on conflict (user_id,organization_id,source)
    do update set active=true,updated_at=now();
  exception when others then
    raise notice 'Staff directory membership backfill skipped: %',sqlerrm;
  end;
end $$;

-- Team directory = original staff directory + any user who has organization membership/access.
create or replace function public.bf_team_user_directory(p_org uuid default null)
returns setof jsonb
language sql
security definer
set search_path = public, auth
as $$
with base as (
  select to_jsonb(s) as j
  from public.bf4_staff_directory() s
),
base_normalized as (
  select
    j ||
    jsonb_build_object(
      'id', coalesce(j->>'id',j->>'user_id'),
      'user_id', coalesce(j->>'user_id',j->>'id')
    ) as j
  from base
  where p_org is null
     or nullif(j->>'organization_id','') = p_org::text
),
membership_users as (
  select jsonb_build_object(
    'id',u.id,
    'user_id',u.id,
    'organization_id',m.organization_id,
    'full_name',coalesce(
      nullif(u.raw_user_meta_data->>'full_name',''),
      nullif(u.raw_user_meta_data->>'name',''),
      split_part(coalesce(u.email,''),'@',1)
    ),
    'email',u.email,
    'membership_source',m.source
  ) as j
  from public.bf_user_org_memberships m
  join auth.users u on u.id=m.user_id
  where m.active=true
    and (p_org is null or m.organization_id=p_org)
),
all_rows as (
  select j from base_normalized
  union all
  select j from membership_users
),
dedup as (
  select distinct on (
    coalesce(j->>'id',j->>'user_id'),
    coalesce(j->>'organization_id','')
  ) j
  from all_rows
  where coalesce(j->>'id',j->>'user_id') is not null
  order by
    coalesce(j->>'id',j->>'user_id'),
    coalesce(j->>'organization_id',''),
    case when coalesce(j->>'full_name','')<>'' then 0 else 1 end
)
select j from dedup;
$$;

revoke all on function public.bf_team_user_directory(uuid) from public;
grant execute on function public.bf_team_user_directory(uuid) to authenticated;

-- Optional project/contractor relationship for professional portfolio examples.
create table if not exists public.bf_project_contractors (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null,
  contractor_ref_id bigint references public.bf_ref_maintenance_companies(id),
  relationship_role text not null default 'primary_fm_contractor',
  contract_reference text,
  start_date date,
  end_date date,
  notes text,
  created_at timestamptz not null default now(),
  unique(project_id,contractor_ref_id,relationship_role)
);
create index if not exists bf_project_contractors_project_idx on public.bf_project_contractors(project_id);
