begin;

-- Basmat Facilities CMMS V8
-- Medical Master Library Expansion
-- 237 device classes across 30 medical specialties.
-- All seeded procedures remain generic baseline unless a verified OEM/vendor source is added.

with x(code,name) as (values
('GEHC','GE HealthCare'),
('SIEMENS-H','Siemens Healthineers'),
('PHILIPS-H','Philips Healthcare'),
('CANON-MED','Canon Medical Systems'),
('FUJIFILM-MED','Fujifilm Healthcare'),
('DRAGER','Dräger'),
('MINDRAY','Mindray'),
('NIHON-KOHDEN','Nihon Kohden'),
('MASIMO','Masimo'),
('SCHILLER','Schiller'),
('ZOLL','ZOLL Medical'),
('BAXTER','Baxter'),
('BBRAUN','B. Braun'),
('FRESENIUS','Fresenius Medical Care'),
('GETINGE','Getinge'),
('STERIS','STERIS'),
('STRYKER','Stryker'),
('HILLROM','Hillrom / Baxter'),
('MEDTRONIC','Medtronic'),
('OLYMPUS','Olympus'),
('KARL-STORZ','KARL STORZ'),
('PENTAX-MED','PENTAX Medical'),
('ROCHE-DIAG','Roche Diagnostics'),
('ABBOTT-DIAG','Abbott Diagnostics'),
('BECKMAN','Beckman Coulter'),
('SYSMEX','Sysmex'),
('BIORAD','Bio-Rad'),
('THERMO','Thermo Fisher Scientific'),
('BD','BD'),
('HOLOGIC','Hologic'),
('ZEISS-MED','ZEISS Medical Technology'),
('NIDEK','NIDEK'),
('ALCON','Alcon'),
('PLANMECA','Planmeca'),
('DENTSPLY','Dentsply Sirona'),
('KAVO','KaVo Dental'),
('CARESTREAM','Carestream'),
('TUTTNAUER','Tuttnauer'),
('HAMILTON','Hamilton Medical'),
('RESMED','ResMed'),
('MAQUET','Maquet / Getinge'),
('EDWARDS','Edwards Lifesciences'),
('TERUMO','Terumo'),
('SMITHS-MED','Smiths Medical'),
('ARJO','Arjo'),
('INVACARE','Invacare'),
('ELEKTA','Elekta'),
('VARIAN','Varian'),
('IBA','IBA'),
('SHIMADZU','Shimadzu'),
('AGFA','Agfa HealthCare'),
('CARESTREAM-H','Carestream Health'),
('SAMSUNG-MED','Samsung Medison'),
('SONOSCAPE','SonoScape'),
('ESAOTE','Esaote'),
('HORIBA','HORIBA Medical'),
('BIO-RAD','Bio-Rad'),
('QIAGEN','QIAGEN'),
('ILLUMINA','Illumina'),
('CEPHEID','Cepheid'),
('BIOMERIEUX','bioMérieux'),
('EPPENDORF','Eppendorf'),
('SARTORIUS','Sartorius'),
('ESCO','Esco Lifesciences'),
('PANASONIC-H','PHCbi'),
('HELMER','Helmer Scientific'),
('HAEMONETICS','Haemonetics'),
('TERUMO-BCT','Terumo Blood and Cell Technologies'),
('BELIMED','Belimed'),
('STEELCO','Steelco'),
('MELAG','MELAG'),
('NATUS','Natus Medical'),
('NICOLET','Nicolet'),
('INTERACOUSTICS','Interacoustics'),
('GN-OTOMETRICS','Natus Otometrics'),
('RICHARD-WOLF','Richard Wolf'),
('COOK-MED','Cook Medical'),
('KARL-KAPS','KARL KAPS'),
('BTL','BTL'),
('CHATTANOOGA','Chattanooga'),
('HOCOMA','Hocoma'),
('RIESTER','Riester'),
('SECA','seca'),
('WELCHALLYN','Welch Allyn'),
('FLUKE-BIOMED','Fluke Biomedical'),
('RIGEL','Rigel Medical'),
('BC-GROUP','BC Group'),
('METRON','Metron'),
('PRONK','Pronk Technologies')
)
insert into public.bf_med_manufacturers(code,name,status)
select x.code,x.name,'active'
from x
where not exists(
 select 1 from public.bf_med_manufacturers m
 where m.code=x.code or lower(m.name)=lower(x.name)
);

with x(code,name) as (values
('GEHC','GE HealthCare'),
('SIEMENS-H','Siemens Healthineers'),
('PHILIPS-H','Philips Healthcare'),
('CANON-MED','Canon Medical Systems'),
('FUJIFILM-MED','Fujifilm Healthcare'),
('DRAGER','Dräger'),
('MINDRAY','Mindray'),
('NIHON-KOHDEN','Nihon Kohden'),
('MASIMO','Masimo'),
('SCHILLER','Schiller'),
('ZOLL','ZOLL Medical'),
('BAXTER','Baxter'),
('BBRAUN','B. Braun'),
('FRESENIUS','Fresenius Medical Care'),
('GETINGE','Getinge'),
('STERIS','STERIS'),
('STRYKER','Stryker'),
('HILLROM','Hillrom / Baxter'),
('MEDTRONIC','Medtronic'),
('OLYMPUS','Olympus'),
('KARL-STORZ','KARL STORZ'),
('PENTAX-MED','PENTAX Medical'),
('ROCHE-DIAG','Roche Diagnostics'),
('ABBOTT-DIAG','Abbott Diagnostics'),
('BECKMAN','Beckman Coulter'),
('SYSMEX','Sysmex'),
('BIORAD','Bio-Rad'),
('THERMO','Thermo Fisher Scientific'),
('BD','BD'),
('HOLOGIC','Hologic'),
('ZEISS-MED','ZEISS Medical Technology'),
('NIDEK','NIDEK'),
('ALCON','Alcon'),
('PLANMECA','Planmeca'),
('DENTSPLY','Dentsply Sirona'),
('KAVO','KaVo Dental'),
('CARESTREAM','Carestream'),
('TUTTNAUER','Tuttnauer'),
('HAMILTON','Hamilton Medical'),
('RESMED','ResMed'),
('MAQUET','Maquet / Getinge'),
('EDWARDS','Edwards Lifesciences'),
('TERUMO','Terumo'),
('SMITHS-MED','Smiths Medical'),
('ARJO','Arjo'),
('INVACARE','Invacare'),
('ELEKTA','Elekta'),
('VARIAN','Varian'),
('IBA','IBA'),
('SHIMADZU','Shimadzu'),
('AGFA','Agfa HealthCare'),
('CARESTREAM-H','Carestream Health'),
('SAMSUNG-MED','Samsung Medison'),
('SONOSCAPE','SonoScape'),
('ESAOTE','Esaote'),
('HORIBA','HORIBA Medical'),
('BIO-RAD','Bio-Rad'),
('QIAGEN','QIAGEN'),
('ILLUMINA','Illumina'),
('CEPHEID','Cepheid'),
('BIOMERIEUX','bioMérieux'),
('EPPENDORF','Eppendorf'),
('SARTORIUS','Sartorius'),
('ESCO','Esco Lifesciences'),
('PANASONIC-H','PHCbi'),
('HELMER','Helmer Scientific'),
('HAEMONETICS','Haemonetics'),
('TERUMO-BCT','Terumo Blood and Cell Technologies'),
('BELIMED','Belimed'),
('STEELCO','Steelco'),
('MELAG','MELAG'),
('NATUS','Natus Medical'),
('NICOLET','Nicolet'),
('INTERACOUSTICS','Interacoustics'),
('GN-OTOMETRICS','Natus Otometrics'),
('RICHARD-WOLF','Richard Wolf'),
('COOK-MED','Cook Medical'),
('KARL-KAPS','KARL KAPS'),
('BTL','BTL'),
('CHATTANOOGA','Chattanooga'),
('HOCOMA','Hocoma'),
('RIESTER','Riester'),
('SECA','seca'),
('WELCHALLYN','Welch Allyn'),
('FLUKE-BIOMED','Fluke Biomedical'),
('RIGEL','Rigel Medical'),
('BC-GROUP','BC Group'),
('METRON','Metron'),
('PRONK','Pronk Technologies')
)
update public.bf_med_manufacturers m
set status='active'
from x
where m.code=x.code or lower(m.name)=lower(x.name);

insert into public.bf_med_master_types(
 system_code,code,name_ar,name_en,default_criticality,icon_text,
 default_pm_months,default_calibration_months,procurement_class,default_lead_time_days
)
values
('PATIENT_MONITORING','MED-BEDSIDE-MONITOR','جهاز مراقبة سريري بجانب السرير','Bedside Patient Monitor','critical','🫀',6,6,'standard',45),
('PATIENT_MONITORING','MED-TRANSPORT-MONITOR','جهاز مراقبة نقل المريض','Transport Patient Monitor','critical','🫀',6,6,'standard',45),
('PATIENT_MONITORING','MED-CENTRAL-MONITORING','محطة مراقبة مركزية','Central Monitoring Station','critical','🖥️',6,12,'long_lead',90),
('PATIENT_MONITORING','MED-TELEMETRY','نظام مراقبة تيليمتري','Telemetry Monitoring System','critical','📡',6,12,'long_lead',90),
('PATIENT_MONITORING','MED-ECG-12LEAD','جهاز تخطيط قلب 12 قناة','12-Lead ECG Machine','high','❤️',12,12,'standard',45),
('PATIENT_MONITORING','MED-HOLTER-ECG','جهاز هولتر للقلب','Holter ECG Recorder','high','❤️',12,12,'standard',45),
('PATIENT_MONITORING','MED-HOLTER-BP','جهاز هولتر ضغط','Ambulatory Blood Pressure Monitor','high','🩺',12,12,'standard',45),
('PATIENT_MONITORING','MED-PULSE-OXIMETER','جهاز قياس تشبع الأكسجين','Pulse Oximeter','high','🫁',12,12,'standard',30),
('PATIENT_MONITORING','MED-CAPNOGRAPH','جهاز قياس ثاني أكسيد الكربون','Capnograph','high','🫁',12,12,'standard',45),
('PATIENT_MONITORING','MED-TEMP-MONITOR','جهاز مراقبة الحرارة','Temperature Monitor','medium','🌡️',12,12,'standard',30),
('PATIENT_MONITORING','MED-ICP-MONITOR','جهاز مراقبة الضغط داخل الجمجمة','Intracranial Pressure Monitor','critical','🧠',6,6,'long_lead',90),
('PATIENT_MONITORING','MED-CARDIAC-OUTPUT','جهاز قياس النتاج القلبي','Cardiac Output Monitor','critical','🫀',6,6,'standard',60),
('CRITICAL_CARE','MED-ICU-VENTILATOR','جهاز تنفس صناعي للعناية المركزة','ICU Ventilator','critical','🫁',6,6,'long_lead',120),
('CRITICAL_CARE','MED-TRANSPORT-VENT','جهاز تنفس نقل','Transport Ventilator','critical','🫁',6,6,'standard',60),
('CRITICAL_CARE','MED-NIV','جهاز تنفس غير جراحي','Non-Invasive Ventilator','critical','🫁',6,6,'standard',60),
('CRITICAL_CARE','MED-HFNC','جهاز أوكسجين عالي التدفق','High Flow Nasal Cannula System','critical','🫁',6,6,'standard',60),
('CRITICAL_CARE','MED-ECMO','جهاز الأكسجة الغشائية ECMO','ECMO System','critical','🫀',3,6,'long_lead',180),
('CRITICAL_CARE','MED-IABP','مضخة بالون داخل الأبهر','Intra-Aortic Balloon Pump','critical','🫀',3,6,'long_lead',150),
('CRITICAL_CARE','MED-INFUSION-PUMP','مضخة محاليل','Infusion Pump','critical','💉',12,12,'standard',45),
('CRITICAL_CARE','MED-SYRINGE-PUMP','مضخة حقن','Syringe Pump','critical','💉',12,12,'standard',45),
('CRITICAL_CARE','MED-PCA-PUMP','مضخة تسكين PCA','PCA Pump','critical','💉',12,12,'standard',45),
('CRITICAL_CARE','MED-ENTERAL-PUMP','مضخة تغذية معوية','Enteral Feeding Pump','high','🥣',12,12,'standard',45),
('CRITICAL_CARE','MED-DEFIBRILLATOR','جهاز صدمات ومراقبة','Defibrillator Monitor','critical','⚡',6,6,'standard',60),
('CRITICAL_CARE','MED-MEDICAL-SUCTION','جهاز شفط طبي','Medical Suction Unit','high','🫁',12,12,'standard',30),
('ANESTHESIA_OR','MED-ANESTHESIA-WORKSTATION','محطة تخدير','Anesthesia Workstation','critical','😷',6,6,'long_lead',120),
('ANESTHESIA_OR','MED-ANESTHESIA-VENT','جهاز تنفس للتخدير','Anesthesia Ventilator','critical','🫁',6,6,'long_lead',90),
('ANESTHESIA_OR','MED-OR-TABLE','طاولة عمليات','Operating Table','critical','🛏️',12,12,'long_lead',120),
('ANESTHESIA_OR','MED-SURGICAL-LIGHT','إضاءة عمليات','Surgical Light','high','💡',12,12,'long_lead',90),
('ANESTHESIA_OR','MED-ESU','جهاز كي جراحي','Electrosurgical Unit','critical','⚡',12,12,'standard',60),
('ANESTHESIA_OR','MED-SURGICAL-SMOKE','جهاز شفط دخان جراحي','Surgical Smoke Evacuator','high','💨',12,12,'standard',45),
('ANESTHESIA_OR','MED-TOURNIQUET','جهاز تورنيكيه جراحي','Surgical Tourniquet','high','🩸',12,12,'standard',45),
('ANESTHESIA_OR','MED-PATIENT-WARMER','جهاز تدفئة مريض','Patient Warming System','high','🌡️',12,12,'standard',45),
('ANESTHESIA_OR','MED-FLUID-WARMER','جهاز تدفئة سوائل','Fluid and Blood Warmer','high','🌡️',12,12,'standard',45),
('ANESTHESIA_OR','MED-OR-MICROSCOPE','مجهر جراحي','Surgical Microscope','critical','🔬',6,12,'long_lead',120),
('ANESTHESIA_OR','MED-SURGICAL-NAV','نظام ملاحة جراحية','Surgical Navigation System','critical','🧭',6,12,'long_lead',150),
('ANESTHESIA_OR','MED-LAPAROSCOPY-TOWER','برج مناظير جراحية','Laparoscopy Tower','critical','🎥',6,12,'long_lead',120),
('IMAGING','MED-XRAY-FIXED','جهاز أشعة سينية ثابت','Fixed X-Ray System','critical','☢️',6,12,'long_lead',180),
('IMAGING','MED-XRAY-MOBILE','جهاز أشعة متنقل','Mobile X-Ray System','critical','☢️',6,12,'long_lead',150),
('IMAGING','MED-DR-PANEL','كاشف أشعة رقمي DR','Digital Radiography Detector','critical','☢️',6,12,'long_lead',120),
('IMAGING','MED-CR-READER','قارئ أشعة CR','Computed Radiography Reader','high','☢️',12,12,'long_lead',90),
('IMAGING','MED-FLUOROSCOPY','جهاز فلوروسكوبي','Fluoroscopy System','critical','☢️',6,12,'long_lead',180),
('IMAGING','MED-CARM','جهاز C-Arm','C-Arm Imaging System','critical','☢️',6,12,'long_lead',150),
('IMAGING','MED-CT','جهاز أشعة مقطعية CT','CT Scanner','critical','🌀',3,6,'long_lead',240),
('IMAGING','MED-MRI','جهاز رنين مغناطيسي MRI','MRI System','critical','🧲',3,6,'long_lead',300),
('IMAGING','MED-ULTRASOUND-GEN','جهاز موجات فوق صوتية','General Ultrasound System','high','📡',6,12,'long_lead',120),
('IMAGING','MED-ULTRASOUND-POC','جهاز موجات فوق صوتية محمول','Point-of-Care Ultrasound','high','📡',6,12,'standard',60),
('IMAGING','MED-MAMMOGRAPHY','جهاز ماموغرام','Mammography System','critical','☢️',6,12,'long_lead',180),
('IMAGING','MED-BONE-DENSITY','جهاز قياس كثافة العظام','Bone Densitometer','high','🦴',12,12,'long_lead',150),
('IMAGING','MED-CONTRAST-INJECTOR','حاقن صبغة','Contrast Media Injector','high','💉',6,12,'standard',60),
('IMAGING','MED-PACS-DIAGNOSTIC','محطة PACS تشخيصية','Diagnostic PACS Workstation','high','🖥️',12,12,'long_lead',90),
('NUCLEAR_MEDICINE','MED-GAMMA-CAMERA','كاميرا جاما','Gamma Camera','critical','☢️',6,12,'long_lead',180),
('NUCLEAR_MEDICINE','MED-SPECT','جهاز SPECT','SPECT System','critical','☢️',6,12,'long_lead',210),
('NUCLEAR_MEDICINE','MED-PETCT','جهاز PET/CT','PET/CT System','critical','☢️',3,6,'long_lead',300),
('NUCLEAR_MEDICINE','MED-DOSE-CALIBRATOR','معاير جرعات نووية','Dose Calibrator','critical','☢️',6,6,'standard',60),
('NUCLEAR_MEDICINE','MED-GAMMA-COUNTER','عداد جاما','Gamma Counter','high','☢️',12,12,'standard',60),
('NUCLEAR_MEDICINE','MED-RADIATION-SURVEY','جهاز قياس الإشعاع','Radiation Survey Meter','critical','☢️',6,6,'standard',45),
('RADIOTHERAPY','MED-LINAC','المعجل الخطي','Linear Accelerator','critical','☢️',1,3,'long_lead',365),
('RADIOTHERAPY','MED-BRACHY','جهاز علاج إشعاعي داخلي','Brachytherapy Afterloader','critical','☢️',3,6,'long_lead',240),
('RADIOTHERAPY','MED-RT-TPS','نظام تخطيط العلاج الإشعاعي','Radiotherapy Treatment Planning System','critical','🖥️',6,12,'long_lead',120),
('RADIOTHERAPY','MED-RT-IMAGING','نظام تصوير للعلاج الإشعاعي','Radiotherapy Imaging System','critical','☢️',3,6,'long_lead',180),
('RADIOTHERAPY','MED-DOSIMETER','جهاز قياس جرعات','Radiotherapy Dosimeter','critical','☢️',6,6,'standard',60),
('LAB','MED-CHEM-ANALYZER','محلل كيمياء حيوية','Clinical Chemistry Analyzer','critical','🧪',6,6,'long_lead',120),
('LAB','MED-HEMATOLOGY','محلل دم','Hematology Analyzer','critical','🩸',6,6,'long_lead',120),
('LAB','MED-IMMUNOASSAY','محلل مناعة','Immunoassay Analyzer','critical','🧪',6,6,'long_lead',120),
('LAB','MED-COAGULATION','محلل تخثر','Coagulation Analyzer','high','🩸',6,6,'standard',60),
('LAB','MED-BLOOD-GAS','محلل غازات الدم','Blood Gas Analyzer','critical','🩸',6,6,'standard',60),
('LAB','MED-ELECTROLYTE','محلل إلكتروليت','Electrolyte Analyzer','high','🧪',6,6,'standard',60),
('LAB','MED-URINALYSIS','محلل بول','Urinalysis Analyzer','high','🧪',12,12,'standard',45),
('LAB','MED-HBA1C','محلل HbA1c','HbA1c Analyzer','high','🧪',12,12,'standard',45),
('LAB','MED-ESR','محلل سرعة ترسيب','ESR Analyzer','medium','🧪',12,12,'standard',45),
('LAB','MED-PCR','جهاز PCR','PCR System','critical','🧬',6,6,'long_lead',120),
('LAB','MED-RT-PCR','جهاز Real-Time PCR','Real-Time PCR System','critical','🧬',6,6,'long_lead',120),
('LAB','MED-GENE-SEQUENCER','جهاز تسلسل جيني','Genetic Sequencer','critical','🧬',6,12,'long_lead',180),
('LAB','MED-MICROBIOLOGY','نظام ميكروبيولوجي','Microbiology Identification System','critical','🧫',6,12,'long_lead',120),
('LAB','MED-BLOOD-CULTURE','جهاز زراعة دم','Blood Culture System','critical','🧫',6,12,'long_lead',120),
('LAB','MED-CENTRIFUGE','جهاز طرد مركزي','Laboratory Centrifuge','high','🧪',12,12,'standard',45),
('LAB','MED-MICROCENTRIFUGE','جهاز طرد مركزي صغير','Microcentrifuge','medium','🧪',12,12,'standard',30),
('LAB','MED-MICROSCOPE','مجهر مختبر','Laboratory Microscope','medium','🔬',12,12,'standard',45),
('LAB','MED-LAB-INCUBATOR','حاضنة مختبر','Laboratory Incubator','high','🌡️',12,12,'standard',45),
('LAB','MED-BIOSAFETY-CAB','كابينة أمان حيوي','Biosafety Cabinet','critical','🧫',6,12,'long_lead',90),
('LAB','MED-LAMINAR-FLOW','كابينة تدفق صفحي','Laminar Flow Cabinet','high','🧫',6,12,'long_lead',90),
('LAB','MED-LAB-REFRIGERATOR','ثلاجة مختبر','Laboratory Refrigerator','critical','🧊',6,12,'standard',60),
('LAB','MED-LAB-FREEZER','فريزر مختبر','Laboratory Freezer','critical','🧊',6,12,'standard',60),
('LAB','MED-ULTRALOW-FREEZER','فريزر حرارة منخفضة جدًا','Ultra-Low Temperature Freezer','critical','🧊',6,12,'long_lead',90),
('LAB','MED-WATER-BATH','حمام مائي مختبري','Laboratory Water Bath','medium','🌡️',12,12,'standard',30),
('LAB','MED-LAB-BALANCE','ميزان تحليلي','Analytical Balance','high','⚖️',12,12,'standard',45),
('LAB','MED-SPECTROPHOTOMETER','جهاز سبكتروفوتوميتر','Spectrophotometer','high','🔬',12,12,'standard',60),
('BLOOD_BANK','MED-BLOOD-FRIDGE','ثلاجة بنك دم','Blood Bank Refrigerator','critical','🩸',3,6,'long_lead',90),
('BLOOD_BANK','MED-PLASMA-FREEZER','فريزر بلازما','Plasma Freezer','critical','🧊',3,6,'long_lead',90),
('BLOOD_BANK','MED-PLATELET-INCUBATOR','حاضنة صفائح دموية','Platelet Incubator','critical','🩸',3,6,'long_lead',90),
('BLOOD_BANK','MED-PLATELET-AGITATOR','هزاز صفائح دموية','Platelet Agitator','critical','🩸',6,6,'standard',60),
('BLOOD_BANK','MED-BLOOD-MIXER','خلاط أكياس دم','Blood Bag Mixer','high','🩸',12,12,'standard',45),
('BLOOD_BANK','MED-BLOOD-COLLECTION-MONITOR','جهاز مراقبة سحب الدم','Blood Collection Monitor','high','🩸',12,12,'standard',45),
('BLOOD_BANK','MED-CELL-WASHER','غاسل خلايا','Cell Washer','high','🩸',12,12,'standard',45),
('BLOOD_BANK','MED-PLASMA-THAWER','جهاز إذابة بلازما','Plasma Thawer','high','🌡️',12,12,'standard',45),
('STERILIZATION','MED-STEAM-STERILIZER','أوتوكلاف بخاري','Steam Sterilizer / Autoclave','critical','♨️',6,6,'long_lead',150),
('STERILIZATION','MED-LOWTEMP-STER','جهاز تعقيم منخفض الحرارة','Low Temperature Sterilizer','critical','♨️',6,6,'long_lead',150),
('STERILIZATION','MED-H2O2-STER','جهاز تعقيم بيروكسيد الهيدروجين','Hydrogen Peroxide Plasma Sterilizer','critical','♨️',6,6,'long_lead',150),
('STERILIZATION','MED-WASHER-DISINFECTOR','غسالة ومطهر أدوات','Washer Disinfector','critical','🧼',6,6,'long_lead',120),
('STERILIZATION','MED-ULTRASONIC-CLEANER','منظف بالموجات فوق الصوتية','Ultrasonic Cleaner','high','🫧',12,12,'standard',45),
('STERILIZATION','MED-INSTRUMENT-DRYER','خزانة تجفيف أدوات','Instrument Drying Cabinet','high','🌬️',12,12,'standard',60),
('STERILIZATION','MED-PACKAGE-SEALER','جهاز لحام أكياس التعقيم','Sterile Packaging Sealer','high','📦',12,12,'standard',45),
('STERILIZATION','MED-STERILE-STORAGE','خزانة تخزين معقم','Sterile Storage Cabinet','medium','📦',12,12,'standard',45),
('DIALYSIS','MED-HEMODIALYSIS','جهاز غسيل كلوي','Hemodialysis Machine','critical','🩸',6,6,'long_lead',120),
('DIALYSIS','MED-CRRT','جهاز CRRT','Continuous Renal Replacement Therapy System','critical','🩸',6,6,'long_lead',120),
('DIALYSIS','MED-DIALYSIS-RO','وحدة RO لغسيل الكلى','Dialysis RO Unit','critical','💧',3,6,'long_lead',150),
('DIALYSIS','MED-DIALYSIS-WATER-LOOP','نظام توزيع مياه غسيل الكلى','Dialysis Water Distribution Loop','critical','💧',3,6,'long_lead',150),
('DIALYSIS','MED-DIALYSIS-CHAIR','كرسي غسيل كلوي','Dialysis Chair','high','🪑',12,12,'standard',60),
('CARDIOLOGY','MED-ECHO','جهاز إيكو قلب','Echocardiography System','critical','❤️',6,12,'long_lead',120),
('CARDIOLOGY','MED-STRESS-TEST','نظام اختبار جهد القلب','Cardiac Stress Test System','high','🏃',6,12,'long_lead',90),
('CARDIOLOGY','MED-CATHLAB','نظام قسطرة قلب','Cardiac Catheterization Lab System','critical','❤️',3,6,'long_lead',240),
('CARDIOLOGY','MED-EP-SYSTEM','نظام فيزيولوجيا كهربائية','Electrophysiology System','critical','⚡',6,12,'long_lead',180),
('CARDIOLOGY','MED-TEMP-PACEMAKER','منظم ضربات مؤقت','Temporary Pacemaker','critical','❤️',6,6,'standard',60),
('CARDIOLOGY','MED-HOLTER-ANALYZER','نظام تحليل هولتر','Holter Analysis System','high','❤️',12,12,'standard',60),
('RESPIRATORY','MED-SPIROMETER','جهاز قياس التنفس','Spirometer','high','🫁',12,12,'standard',45),
('RESPIRATORY','MED-PFT','جهاز وظائف الرئة','Pulmonary Function Test System','high','🫁',6,12,'long_lead',90),
('RESPIRATORY','MED-NEBULIZER','جهاز نيبولايزر','Nebulizer','medium','🫁',12,12,'standard',30),
('RESPIRATORY','MED-OXYGEN-CONCENTRATOR','جهاز تركيز الأكسجين','Oxygen Concentrator','high','🫁',12,12,'standard',45),
('RESPIRATORY','MED-CPAP','جهاز CPAP','CPAP System','high','🫁',12,12,'standard',45),
('RESPIRATORY','MED-BIPAP','جهاز BiPAP','BiPAP System','high','🫁',12,12,'standard',45),
('RESPIRATORY','MED-POLYSOMNOGRAPHY','نظام دراسة النوم','Polysomnography System','high','😴',12,12,'long_lead',90),
('NEONATAL_MATERNITY','MED-INFANT-INCUBATOR','حاضنة أطفال','Infant Incubator','critical','👶',6,6,'long_lead',90),
('NEONATAL_MATERNITY','MED-RADIANT-WARMER','جهاز تدفئة أطفال','Infant Radiant Warmer','critical','👶',6,6,'long_lead',90),
('NEONATAL_MATERNITY','MED-PHOTOTHERAPY','جهاز علاج ضوئي','Phototherapy Unit','high','💡',12,12,'standard',45),
('NEONATAL_MATERNITY','MED-NEONATAL-VENT','جهاز تنفس حديثي الولادة','Neonatal Ventilator','critical','🫁',6,6,'long_lead',120),
('NEONATAL_MATERNITY','MED-NEONATAL-CPAP','جهاز CPAP لحديثي الولادة','Neonatal CPAP System','critical','🫁',6,6,'standard',60),
('NEONATAL_MATERNITY','MED-FETAL-MONITOR','جهاز مراقبة الجنين CTG','Fetal Monitor / CTG','critical','👶',6,12,'standard',60),
('NEONATAL_MATERNITY','MED-FETAL-DOPPLER','دوبلر جنين','Fetal Doppler','high','👶',12,12,'standard',45),
('NEONATAL_MATERNITY','MED-DELIVERY-BED','سرير ولادة','Delivery Bed','high','🛏️',12,12,'standard',60),
('NEONATAL_MATERNITY','MED-INFANT-SCALE','ميزان أطفال','Infant Scale','medium','⚖️',12,12,'standard',30),
('NEONATAL_MATERNITY','MED-BREAST-PUMP','مضخة حليب طبية','Clinical Breast Pump','medium','🍼',12,12,'standard',30),
('ENDOSCOPY','MED-ENDOSCOPY-TOWER','برج مناظير','Endoscopy Tower','critical','🎥',6,12,'long_lead',120),
('ENDOSCOPY','MED-GASTROSCOPE','منظار معدة','Gastroscope','critical','🔬',6,12,'long_lead',90),
('ENDOSCOPY','MED-COLONOSCOPE','منظار قولون','Colonoscope','critical','🔬',6,12,'long_lead',90),
('ENDOSCOPY','MED-BRONCHOSCOPE','منظار شعب هوائية','Bronchoscope','critical','🔬',6,12,'long_lead',90),
('ENDOSCOPY','MED-EUS','جهاز موجات فوق صوتية بالمنظار','Endoscopic Ultrasound System','critical','📡',6,12,'long_lead',150),
('ENDOSCOPY','MED-ENDO-INSUFFLATOR','جهاز نفخ للمناظير','Endoscopy Insufflator','high','💨',12,12,'standard',60),
('ENDOSCOPY','MED-ENDO-PROCESSOR','معالج فيديو مناظير','Endoscopy Video Processor','critical','🎥',6,12,'long_lead',90),
('ENDOSCOPY','MED-ENDO-LIGHT','مصدر ضوء للمناظير','Endoscopy Light Source','high','💡',12,12,'standard',60),
('ENDOSCOPY','MED-ENDO-REPROCESSOR','غسالة مناظير','Endoscope Reprocessor','critical','🧼',6,6,'long_lead',120),
('ENDOSCOPY','MED-ENDO-DRYING','خزانة تجفيف مناظير','Endoscope Drying Cabinet','high','🌬️',12,12,'standard',60),
('EMERGENCY','MED-AED','جهاز AED','Automated External Defibrillator','critical','⚡',6,12,'standard',45),
('EMERGENCY','MED-EMERGENCY-STRETCHER','نقالة طوارئ','Emergency Stretcher','high','🛏️',12,12,'standard',45),
('EMERGENCY','MED-EMERGENCY-VENT','جهاز تنفس للطوارئ','Emergency Ventilator','critical','🫁',6,6,'standard',60),
('EMERGENCY','MED-EMERGENCY-MONITOR','جهاز مراقبة للطوارئ','Emergency Monitor','critical','🫀',6,6,'standard',60),
('EMERGENCY','MED-EMERGENCY-SUCTION','جهاز شفط للطوارئ','Emergency Suction Unit','high','🫁',12,12,'standard',30),
('DENTAL','MED-DENTAL-UNIT','كرسي ووحدة أسنان','Dental Unit / Chair','high','🦷',12,12,'long_lead',90),
('DENTAL','MED-DENTAL-XRAY','جهاز أشعة أسنان','Dental Intraoral X-Ray','high','☢️',6,12,'long_lead',90),
('DENTAL','MED-DENTAL-PANO','جهاز أشعة بانوراما','Dental Panoramic X-Ray','critical','☢️',6,12,'long_lead',120),
('DENTAL','MED-DENTAL-CBCT','جهاز CBCT أسنان','Dental CBCT','critical','☢️',6,12,'long_lead',150),
('DENTAL','MED-DENTAL-AUTOCLAVE','أوتوكلاف أسنان','Dental Autoclave','critical','♨️',6,6,'standard',60),
('DENTAL','MED-DENTAL-COMPRESSOR','كمبروسر أسنان','Dental Air Compressor','high','💨',12,12,'standard',60),
('DENTAL','MED-DENTAL-SUCTION','شفط مركزي للأسنان','Dental Suction System','high','🫁',12,12,'standard',60),
('DENTAL','MED-ULTRASONIC-SCALER','جهاز تنظيف أسنان بالموجات','Ultrasonic Dental Scaler','high','🦷',12,12,'standard',45),
('DENTAL','MED-CURING-LIGHT','جهاز ضوء معالجة الأسنان','Dental Curing Light','medium','💡',12,12,'standard',30),
('DENTAL','MED-ENDO-MOTOR','جهاز علاج جذور','Endodontic Motor','high','🦷',12,12,'standard',45),
('OPHTHALMOLOGY','MED-SLIT-LAMP','مصباح شقي','Slit Lamp','high','👁️',12,12,'standard',45),
('OPHTHALMOLOGY','MED-AUTOREFRACTOR','جهاز فحص انكسار','Auto Refractometer','high','👁️',12,12,'standard',45),
('OPHTHALMOLOGY','MED-TONOMETER','جهاز قياس ضغط العين','Tonometer','high','👁️',12,12,'standard',45),
('OPHTHALMOLOGY','MED-VISUAL-FIELD','جهاز مجال بصري','Visual Field Analyzer','high','👁️',12,12,'long_lead',90),
('OPHTHALMOLOGY','MED-FUNDUS-CAMERA','كاميرا قاع العين','Fundus Camera','high','👁️',12,12,'long_lead',90),
('OPHTHALMOLOGY','MED-OCT','جهاز OCT','Optical Coherence Tomography','critical','👁️',6,12,'long_lead',120),
('OPHTHALMOLOGY','MED-OPTICAL-BIOMETER','جهاز قياس بصري للعين','Optical Biometer','high','👁️',12,12,'long_lead',90),
('OPHTHALMOLOGY','MED-PHACO','جهاز فاكو','Phacoemulsification System','critical','👁️',6,6,'long_lead',150),
('OPHTHALMOLOGY','MED-EXCIMER-LASER','ليزر إكسيمر','Excimer Laser','critical','✨',3,6,'long_lead',180),
('ENT_AUDIOLOGY','MED-ENT-UNIT','وحدة أنف وأذن وحنجرة','ENT Treatment Unit','high','👂',12,12,'long_lead',90),
('ENT_AUDIOLOGY','MED-AUDIOMETER','جهاز قياس السمع','Audiometer','high','👂',12,12,'standard',60),
('ENT_AUDIOLOGY','MED-TYMPANOMETER','جهاز قياس طبلة الأذن','Tympanometer','high','👂',12,12,'standard',60),
('ENT_AUDIOLOGY','MED-OAE','جهاز OAE','Otoacoustic Emissions System','high','👂',12,12,'standard',60),
('ENT_AUDIOLOGY','MED-ABR','جهاز فحص جذع الدماغ السمعي','Auditory Brainstem Response System','high','👂',12,12,'long_lead',90),
('ENT_AUDIOLOGY','MED-HEARING-AID-ANALYZER','جهاز تحليل سماعات الأذن','Hearing Aid Analyzer','medium','👂',12,12,'standard',45),
('ENT_AUDIOLOGY','MED-ENT-ENDOSCOPE','منظار ENT','ENT Endoscopy System','high','🎥',12,12,'long_lead',90),
('NEUROLOGY','MED-EEG','جهاز تخطيط الدماغ','EEG System','high','🧠',12,12,'long_lead',90),
('NEUROLOGY','MED-EMG','جهاز تخطيط الأعصاب والعضلات','EMG/NCS System','high','🧠',12,12,'long_lead',90),
('NEUROLOGY','MED-EVOKED-POTENTIAL','جهاز الجهد المستثار','Evoked Potential System','high','🧠',12,12,'long_lead',90),
('NEUROLOGY','MED-TCD','جهاز دوبلر عبر الجمجمة','Transcranial Doppler','high','🧠',12,12,'long_lead',90),
('NEUROLOGY','MED-INTRAOP-NEUROMON','نظام مراقبة عصبية أثناء الجراحة','Intraoperative Neuro Monitoring System','critical','🧠',6,12,'long_lead',120),
('UROLOGY','MED-LITHOTRIPTER','جهاز تفتيت حصوات','Lithotripter','critical','🪨',6,12,'long_lead',180),
('UROLOGY','MED-URODYNAMIC','جهاز ديناميكية البول','Urodynamic System','high','💧',12,12,'long_lead',90),
('UROLOGY','MED-CYSTOSCOPY','نظام منظار مثانة','Cystoscopy System','high','🎥',12,12,'long_lead',90),
('UROLOGY','MED-BLADDER-SCANNER','جهاز فحص المثانة','Bladder Scanner','high','📡',12,12,'standard',60),
('UROLOGY','MED-URO-LASER','ليزر المسالك البولية','Urology Laser System','critical','✨',6,12,'long_lead',150),
('DERMATOLOGY','MED-DERM-LASER','ليزر جلدي','Dermatology Laser System','critical','✨',6,12,'long_lead',150),
('DERMATOLOGY','MED-PHOTOTHERAPY-CABIN','كابينة علاج ضوئي','Dermatology Phototherapy Cabin','high','💡',12,12,'long_lead',90),
('DERMATOLOGY','MED-DERMATOSCOPE','منظار جلدي','Dermatoscope','medium','🔬',12,12,'standard',45),
('DERMATOLOGY','MED-CRYOSURGERY','جهاز كرايو جراحة جلدية','Cryosurgery Unit','high','❄️',12,12,'standard',60),
('PHARMACY','MED-PHARM-FRIDGE','ثلاجة أدوية','Pharmacy Refrigerator','critical','💊',6,12,'standard',60),
('PHARMACY','MED-VACCINE-FRIDGE','ثلاجة لقاحات','Vaccine Refrigerator','critical','💉',3,6,'standard',60),
('PHARMACY','MED-AUTOMATED-DISPENSING','خزانة صرف أدوية آلي','Automated Medication Dispensing Cabinet','critical','💊',6,12,'long_lead',120),
('PHARMACY','MED-PHARMACY-ROBOT','روبوت صيدلية','Pharmacy Dispensing Robot','critical','🤖',6,12,'long_lead',180),
('PHARMACY','MED-COMPOUNDING-HOOD','كابينة تحضير أدوية','Pharmacy Compounding Hood','critical','🧪',6,12,'long_lead',90),
('REHAB','MED-PHYSIO-ULTRASOUND','جهاز علاج بالموجات فوق الصوتية','Therapeutic Ultrasound','medium','🦿',12,12,'standard',45),
('REHAB','MED-TENS','جهاز TENS','TENS Unit','medium','⚡',12,12,'standard',30),
('REHAB','MED-ELECTROTHERAPY','جهاز علاج كهربائي','Electrotherapy Unit','medium','⚡',12,12,'standard',45),
('REHAB','MED-SHOCKWAVE','جهاز موجات صادمة','Shockwave Therapy Unit','high','💥',12,12,'standard',60),
('REHAB','MED-CPM','جهاز حركة سلبية مستمرة','Continuous Passive Motion Device','medium','🦿',12,12,'standard',45),
('REHAB','MED-REHAB-TREADMILL','جهاز مشي طبي','Medical Treadmill','medium','🏃',12,12,'standard',60),
('REHAB','MED-GAIT-ANALYSIS','نظام تحليل المشي','Gait Analysis System','high','🦿',12,12,'long_lead',120),
('REHAB','MED-REHAB-ROBOT','روبوت تأهيل','Rehabilitation Robot','high','🤖',6,12,'long_lead',180),
('GENERAL_MEDICAL','MED-HOSPITAL-BED','سرير مستشفى كهربائي','Electric Hospital Bed','high','🛏️',12,12,'standard',60),
('GENERAL_MEDICAL','MED-ICU-BED','سرير عناية مركزة','ICU Bed','critical','🛏️',12,12,'standard',60),
('GENERAL_MEDICAL','MED-EXAM-TABLE','طاولة فحص','Examination Table','medium','🛏️',12,12,'standard',45),
('GENERAL_MEDICAL','MED-PATIENT-LIFT','رافعة مريض','Patient Lift','high','♿',12,12,'standard',60),
('GENERAL_MEDICAL','MED-WHEELCHAIR-POWER','كرسي متحرك كهربائي','Powered Wheelchair','medium','♿',12,12,'standard',60),
('GENERAL_MEDICAL','MED-MEDICAL-SCALE','ميزان طبي','Medical Scale','medium','⚖️',12,12,'standard',30),
('GENERAL_MEDICAL','MED-HEIGHT-WEIGHT','جهاز قياس طول ووزن','Height and Weight Station','medium','⚖️',12,12,'standard',30),
('GENERAL_MEDICAL','MED-EXAM-LIGHT','إضاءة فحص','Examination Light','medium','💡',12,12,'standard',30),
('MEDICAL_GAS_DEVICES','MED-O2-FLOWMETER','مقياس تدفق أوكسجين','Oxygen Flowmeter','high','🫁',12,12,'standard',30),
('MEDICAL_GAS_DEVICES','MED-GAS-REGULATOR','منظم غاز طبي','Medical Gas Regulator','high','🫁',12,12,'standard',30),
('MEDICAL_GAS_DEVICES','MED-VACUUM-REGULATOR','منظم شفط طبي','Medical Vacuum Regulator','high','🫁',12,12,'standard',30),
('MEDICAL_GAS_DEVICES','MED-GAS-ALARM-PANEL','لوحة إنذار غازات طبية','Medical Gas Alarm Panel','critical','🚨',6,12,'standard',60),
('MEDICAL_GAS_DEVICES','MED-GAS-MANIFOLD-CONTROLLER','وحدة تحكم ماني فولد غازات','Medical Gas Manifold Controller','critical','🫁',6,12,'long_lead',90),
('POCT','MED-POCT-GLUCOSE','جهاز قياس سكر سريري','POCT Glucose Meter','high','🩸',12,12,'standard',30),
('POCT','MED-POCT-BLOODGAS','جهاز غازات دم محمول','POCT Blood Gas Analyzer','critical','🩸',6,6,'standard',60),
('POCT','MED-POCT-TROPONIN','محلل تروبونين محمول','POCT Troponin Analyzer','high','❤️',12,12,'standard',45),
('POCT','MED-POCT-COAG','محلل تخثر محمول','POCT Coagulation Analyzer','high','🩸',12,12,'standard',45),
('POCT','MED-POCT-HBA1C','محلل HbA1c محمول','POCT HbA1c Analyzer','high','🧪',12,12,'standard',45),
('BIOMED_TEST','MED-TEST-ELEC-SAFETY','محلل سلامة كهربائية طبية','Electrical Safety Analyzer','critical','⚡',12,12,'standard',60),
('BIOMED_TEST','MED-TEST-PATIENT-SIM','محاكي مريض','Patient Simulator','high','🫀',12,12,'standard',60),
('BIOMED_TEST','MED-TEST-DEFIB','محلل جهاز صدمات','Defibrillator Analyzer','high','⚡',12,12,'standard',60),
('BIOMED_TEST','MED-TEST-INFUSION','محلل مضخات محاليل','Infusion Device Analyzer','high','💉',12,12,'standard',60),
('BIOMED_TEST','MED-TEST-VENT','محلل أجهزة تنفس','Ventilator Analyzer','high','🫁',12,12,'standard',60),
('BIOMED_TEST','MED-TEST-ESU','محلل جهاز كي جراحي','Electrosurgical Analyzer','high','⚡',12,12,'standard',60),
('BIOMED_TEST','MED-TEST-SPO2','محاكي SpO2','SpO2 Simulator','high','🫁',12,12,'standard',45),
('BIOMED_TEST','MED-TEST-NIBP','محاكي ضغط NIBP','NIBP Simulator','high','🩺',12,12,'standard',45),
('BIOMED_TEST','MED-TEST-TEMP','معاير حرارة','Temperature Calibrator','high','🌡️',12,12,'standard',45),
('BIOMED_TEST','MED-TEST-PRESSURE','معاير ضغط','Pressure Calibrator','high','🩺',12,12,'standard',45),
('MEDICAL_IT','MED-PACS-SERVER','خادم PACS','PACS Server','critical','🖥️',12,12,'long_lead',90),
('MEDICAL_IT','MED-RIS-SERVER','خادم RIS','RIS Server','critical','🖥️',12,12,'long_lead',90),
('MEDICAL_IT','MED-DEVICE-GATEWAY','بوابة تكامل أجهزة طبية','Medical Device Integration Gateway','critical','🔗',12,12,'long_lead',90),
('MEDICAL_IT','MED-CENTRAL-MON-SERVER','خادم مراقبة مركزية','Central Monitoring Server','critical','🖥️',12,12,'long_lead',90),
('MEDICAL_IT','MED-CLINICAL-WORKSTATION','محطة عمل سريرية','Clinical Workstation','high','🖥️',12,12,'standard',60),
('AMBULANCE','MED-AMB-MONITOR','جهاز مراقبة إسعاف','Ambulance Patient Monitor','critical','🚑',6,6,'standard',60),
('AMBULANCE','MED-AMB-VENT','جهاز تنفس إسعاف','Ambulance Transport Ventilator','critical','🚑',6,6,'standard',60),
('AMBULANCE','MED-AMB-SUCTION','جهاز شفط إسعاف','Ambulance Suction Unit','high','🚑',12,12,'standard',30),
('AMBULANCE','MED-AMB-STRETCHER','نقالة إسعاف','Ambulance Stretcher','high','🚑',12,12,'standard',45),
('AMBULANCE','MED-AMB-DEFIB','جهاز صدمات إسعاف','Ambulance Defibrillator','critical','🚑',6,6,'standard',60)
on conflict(code) do update set
 system_code=excluded.system_code,
 name_ar=excluded.name_ar,
 name_en=excluded.name_en,
 default_criticality=excluded.default_criticality,
 icon_text=excluded.icon_text,
 default_pm_months=excluded.default_pm_months,
 default_calibration_months=excluded.default_calibration_months,
 procurement_class=excluded.procurement_class,
 default_lead_time_days=excluded.default_lead_time_days,
 status='active';

with x(asset_code,manufacturer_code) as (values
('MED-BEDSIDE-MONITOR','PHILIPS-H'),
('MED-BEDSIDE-MONITOR','GEHC'),
('MED-BEDSIDE-MONITOR','MINDRAY'),
('MED-BEDSIDE-MONITOR','NIHON-KOHDEN'),
('MED-BEDSIDE-MONITOR','MASIMO'),
('MED-BEDSIDE-MONITOR','SCHILLER'),
('MED-TRANSPORT-MONITOR','PHILIPS-H'),
('MED-TRANSPORT-MONITOR','GEHC'),
('MED-TRANSPORT-MONITOR','MINDRAY'),
('MED-TRANSPORT-MONITOR','NIHON-KOHDEN'),
('MED-TRANSPORT-MONITOR','MASIMO'),
('MED-TRANSPORT-MONITOR','SCHILLER'),
('MED-CENTRAL-MONITORING','PHILIPS-H'),
('MED-CENTRAL-MONITORING','GEHC'),
('MED-CENTRAL-MONITORING','MINDRAY'),
('MED-CENTRAL-MONITORING','NIHON-KOHDEN'),
('MED-CENTRAL-MONITORING','MASIMO'),
('MED-CENTRAL-MONITORING','SCHILLER'),
('MED-TELEMETRY','PHILIPS-H'),
('MED-TELEMETRY','GEHC'),
('MED-TELEMETRY','MINDRAY'),
('MED-TELEMETRY','NIHON-KOHDEN'),
('MED-TELEMETRY','MASIMO'),
('MED-TELEMETRY','SCHILLER'),
('MED-ECG-12LEAD','PHILIPS-H'),
('MED-ECG-12LEAD','GEHC'),
('MED-ECG-12LEAD','MINDRAY'),
('MED-ECG-12LEAD','NIHON-KOHDEN'),
('MED-ECG-12LEAD','MASIMO'),
('MED-ECG-12LEAD','SCHILLER'),
('MED-HOLTER-ECG','PHILIPS-H'),
('MED-HOLTER-ECG','GEHC'),
('MED-HOLTER-ECG','MINDRAY'),
('MED-HOLTER-ECG','NIHON-KOHDEN'),
('MED-HOLTER-ECG','MASIMO'),
('MED-HOLTER-ECG','SCHILLER'),
('MED-HOLTER-BP','PHILIPS-H'),
('MED-HOLTER-BP','GEHC'),
('MED-HOLTER-BP','MINDRAY'),
('MED-HOLTER-BP','NIHON-KOHDEN'),
('MED-HOLTER-BP','MASIMO'),
('MED-HOLTER-BP','SCHILLER'),
('MED-PULSE-OXIMETER','PHILIPS-H'),
('MED-PULSE-OXIMETER','GEHC'),
('MED-PULSE-OXIMETER','MINDRAY'),
('MED-PULSE-OXIMETER','NIHON-KOHDEN'),
('MED-PULSE-OXIMETER','MASIMO'),
('MED-PULSE-OXIMETER','SCHILLER'),
('MED-CAPNOGRAPH','PHILIPS-H'),
('MED-CAPNOGRAPH','GEHC'),
('MED-CAPNOGRAPH','MINDRAY'),
('MED-CAPNOGRAPH','NIHON-KOHDEN'),
('MED-CAPNOGRAPH','MASIMO'),
('MED-CAPNOGRAPH','SCHILLER'),
('MED-TEMP-MONITOR','PHILIPS-H'),
('MED-TEMP-MONITOR','GEHC'),
('MED-TEMP-MONITOR','MINDRAY'),
('MED-TEMP-MONITOR','NIHON-KOHDEN'),
('MED-TEMP-MONITOR','MASIMO'),
('MED-TEMP-MONITOR','SCHILLER'),
('MED-ICP-MONITOR','PHILIPS-H'),
('MED-ICP-MONITOR','GEHC'),
('MED-ICP-MONITOR','MINDRAY'),
('MED-ICP-MONITOR','NIHON-KOHDEN'),
('MED-ICP-MONITOR','MASIMO'),
('MED-ICP-MONITOR','SCHILLER'),
('MED-CARDIAC-OUTPUT','PHILIPS-H'),
('MED-CARDIAC-OUTPUT','GEHC'),
('MED-CARDIAC-OUTPUT','MINDRAY'),
('MED-CARDIAC-OUTPUT','NIHON-KOHDEN'),
('MED-CARDIAC-OUTPUT','MASIMO'),
('MED-CARDIAC-OUTPUT','SCHILLER'),
('MED-ICU-VENTILATOR','DRAGER'),
('MED-ICU-VENTILATOR','HAMILTON'),
('MED-ICU-VENTILATOR','PHILIPS-H'),
('MED-ICU-VENTILATOR','GEHC'),
('MED-ICU-VENTILATOR','MINDRAY'),
('MED-ICU-VENTILATOR','BAXTER'),
('MED-ICU-VENTILATOR','BBRAUN'),
('MED-ICU-VENTILATOR','MEDTRONIC'),
('MED-ICU-VENTILATOR','ZOLL'),
('MED-TRANSPORT-VENT','DRAGER'),
('MED-TRANSPORT-VENT','HAMILTON'),
('MED-TRANSPORT-VENT','PHILIPS-H'),
('MED-TRANSPORT-VENT','GEHC'),
('MED-TRANSPORT-VENT','MINDRAY'),
('MED-TRANSPORT-VENT','BAXTER'),
('MED-TRANSPORT-VENT','BBRAUN'),
('MED-TRANSPORT-VENT','MEDTRONIC'),
('MED-TRANSPORT-VENT','ZOLL'),
('MED-NIV','DRAGER'),
('MED-NIV','HAMILTON'),
('MED-NIV','PHILIPS-H'),
('MED-NIV','GEHC'),
('MED-NIV','MINDRAY'),
('MED-NIV','BAXTER'),
('MED-NIV','BBRAUN'),
('MED-NIV','MEDTRONIC'),
('MED-NIV','ZOLL'),
('MED-HFNC','DRAGER'),
('MED-HFNC','HAMILTON'),
('MED-HFNC','PHILIPS-H'),
('MED-HFNC','GEHC'),
('MED-HFNC','MINDRAY'),
('MED-HFNC','BAXTER'),
('MED-HFNC','BBRAUN'),
('MED-HFNC','MEDTRONIC'),
('MED-HFNC','ZOLL'),
('MED-ECMO','DRAGER'),
('MED-ECMO','HAMILTON'),
('MED-ECMO','PHILIPS-H'),
('MED-ECMO','GEHC'),
('MED-ECMO','MINDRAY'),
('MED-ECMO','BAXTER'),
('MED-ECMO','BBRAUN'),
('MED-ECMO','MEDTRONIC'),
('MED-ECMO','ZOLL'),
('MED-IABP','DRAGER'),
('MED-IABP','HAMILTON'),
('MED-IABP','PHILIPS-H'),
('MED-IABP','GEHC'),
('MED-IABP','MINDRAY'),
('MED-IABP','BAXTER'),
('MED-IABP','BBRAUN'),
('MED-IABP','MEDTRONIC'),
('MED-IABP','ZOLL'),
('MED-INFUSION-PUMP','DRAGER'),
('MED-INFUSION-PUMP','HAMILTON'),
('MED-INFUSION-PUMP','PHILIPS-H'),
('MED-INFUSION-PUMP','GEHC'),
('MED-INFUSION-PUMP','MINDRAY'),
('MED-INFUSION-PUMP','BAXTER'),
('MED-INFUSION-PUMP','BBRAUN'),
('MED-INFUSION-PUMP','MEDTRONIC'),
('MED-INFUSION-PUMP','ZOLL'),
('MED-SYRINGE-PUMP','DRAGER'),
('MED-SYRINGE-PUMP','HAMILTON'),
('MED-SYRINGE-PUMP','PHILIPS-H'),
('MED-SYRINGE-PUMP','GEHC'),
('MED-SYRINGE-PUMP','MINDRAY'),
('MED-SYRINGE-PUMP','BAXTER'),
('MED-SYRINGE-PUMP','BBRAUN'),
('MED-SYRINGE-PUMP','MEDTRONIC'),
('MED-SYRINGE-PUMP','ZOLL'),
('MED-PCA-PUMP','DRAGER'),
('MED-PCA-PUMP','HAMILTON'),
('MED-PCA-PUMP','PHILIPS-H'),
('MED-PCA-PUMP','GEHC'),
('MED-PCA-PUMP','MINDRAY'),
('MED-PCA-PUMP','BAXTER'),
('MED-PCA-PUMP','BBRAUN'),
('MED-PCA-PUMP','MEDTRONIC'),
('MED-PCA-PUMP','ZOLL'),
('MED-ENTERAL-PUMP','DRAGER'),
('MED-ENTERAL-PUMP','HAMILTON'),
('MED-ENTERAL-PUMP','PHILIPS-H'),
('MED-ENTERAL-PUMP','GEHC'),
('MED-ENTERAL-PUMP','MINDRAY'),
('MED-ENTERAL-PUMP','BAXTER'),
('MED-ENTERAL-PUMP','BBRAUN'),
('MED-ENTERAL-PUMP','MEDTRONIC'),
('MED-ENTERAL-PUMP','ZOLL'),
('MED-DEFIBRILLATOR','DRAGER'),
('MED-DEFIBRILLATOR','HAMILTON'),
('MED-DEFIBRILLATOR','PHILIPS-H'),
('MED-DEFIBRILLATOR','GEHC'),
('MED-DEFIBRILLATOR','MINDRAY'),
('MED-DEFIBRILLATOR','BAXTER'),
('MED-DEFIBRILLATOR','BBRAUN'),
('MED-DEFIBRILLATOR','MEDTRONIC'),
('MED-DEFIBRILLATOR','ZOLL'),
('MED-MEDICAL-SUCTION','DRAGER'),
('MED-MEDICAL-SUCTION','HAMILTON'),
('MED-MEDICAL-SUCTION','PHILIPS-H'),
('MED-MEDICAL-SUCTION','GEHC'),
('MED-MEDICAL-SUCTION','MINDRAY'),
('MED-MEDICAL-SUCTION','BAXTER'),
('MED-MEDICAL-SUCTION','BBRAUN'),
('MED-MEDICAL-SUCTION','MEDTRONIC'),
('MED-MEDICAL-SUCTION','ZOLL'),
('MED-ANESTHESIA-WORKSTATION','DRAGER'),
('MED-ANESTHESIA-WORKSTATION','GEHC'),
('MED-ANESTHESIA-WORKSTATION','GETINGE'),
('MED-ANESTHESIA-WORKSTATION','MAQUET'),
('MED-ANESTHESIA-WORKSTATION','STRYKER'),
('MED-ANESTHESIA-WORKSTATION','MEDTRONIC'),
('MED-ANESTHESIA-WORKSTATION','KARL-STORZ'),
('MED-ANESTHESIA-VENT','DRAGER'),
('MED-ANESTHESIA-VENT','GEHC'),
('MED-ANESTHESIA-VENT','GETINGE'),
('MED-ANESTHESIA-VENT','MAQUET'),
('MED-ANESTHESIA-VENT','STRYKER'),
('MED-ANESTHESIA-VENT','MEDTRONIC'),
('MED-ANESTHESIA-VENT','KARL-STORZ'),
('MED-OR-TABLE','DRAGER'),
('MED-OR-TABLE','GEHC'),
('MED-OR-TABLE','GETINGE'),
('MED-OR-TABLE','MAQUET'),
('MED-OR-TABLE','STRYKER'),
('MED-OR-TABLE','MEDTRONIC'),
('MED-OR-TABLE','KARL-STORZ'),
('MED-SURGICAL-LIGHT','DRAGER'),
('MED-SURGICAL-LIGHT','GEHC'),
('MED-SURGICAL-LIGHT','GETINGE'),
('MED-SURGICAL-LIGHT','MAQUET'),
('MED-SURGICAL-LIGHT','STRYKER'),
('MED-SURGICAL-LIGHT','MEDTRONIC'),
('MED-SURGICAL-LIGHT','KARL-STORZ'),
('MED-ESU','DRAGER'),
('MED-ESU','GEHC'),
('MED-ESU','GETINGE'),
('MED-ESU','MAQUET'),
('MED-ESU','STRYKER'),
('MED-ESU','MEDTRONIC'),
('MED-ESU','KARL-STORZ'),
('MED-SURGICAL-SMOKE','DRAGER'),
('MED-SURGICAL-SMOKE','GEHC'),
('MED-SURGICAL-SMOKE','GETINGE'),
('MED-SURGICAL-SMOKE','MAQUET'),
('MED-SURGICAL-SMOKE','STRYKER'),
('MED-SURGICAL-SMOKE','MEDTRONIC'),
('MED-SURGICAL-SMOKE','KARL-STORZ'),
('MED-TOURNIQUET','DRAGER'),
('MED-TOURNIQUET','GEHC'),
('MED-TOURNIQUET','GETINGE'),
('MED-TOURNIQUET','MAQUET'),
('MED-TOURNIQUET','STRYKER'),
('MED-TOURNIQUET','MEDTRONIC'),
('MED-TOURNIQUET','KARL-STORZ'),
('MED-PATIENT-WARMER','DRAGER'),
('MED-PATIENT-WARMER','GEHC'),
('MED-PATIENT-WARMER','GETINGE'),
('MED-PATIENT-WARMER','MAQUET'),
('MED-PATIENT-WARMER','STRYKER'),
('MED-PATIENT-WARMER','MEDTRONIC'),
('MED-PATIENT-WARMER','KARL-STORZ'),
('MED-FLUID-WARMER','DRAGER'),
('MED-FLUID-WARMER','GEHC'),
('MED-FLUID-WARMER','GETINGE'),
('MED-FLUID-WARMER','MAQUET'),
('MED-FLUID-WARMER','STRYKER'),
('MED-FLUID-WARMER','MEDTRONIC'),
('MED-FLUID-WARMER','KARL-STORZ'),
('MED-OR-MICROSCOPE','DRAGER'),
('MED-OR-MICROSCOPE','GEHC'),
('MED-OR-MICROSCOPE','GETINGE'),
('MED-OR-MICROSCOPE','MAQUET'),
('MED-OR-MICROSCOPE','STRYKER'),
('MED-OR-MICROSCOPE','MEDTRONIC'),
('MED-OR-MICROSCOPE','KARL-STORZ'),
('MED-SURGICAL-NAV','DRAGER'),
('MED-SURGICAL-NAV','GEHC'),
('MED-SURGICAL-NAV','GETINGE'),
('MED-SURGICAL-NAV','MAQUET'),
('MED-SURGICAL-NAV','STRYKER'),
('MED-SURGICAL-NAV','MEDTRONIC'),
('MED-SURGICAL-NAV','KARL-STORZ'),
('MED-LAPAROSCOPY-TOWER','DRAGER'),
('MED-LAPAROSCOPY-TOWER','GEHC'),
('MED-LAPAROSCOPY-TOWER','GETINGE'),
('MED-LAPAROSCOPY-TOWER','MAQUET'),
('MED-LAPAROSCOPY-TOWER','STRYKER'),
('MED-LAPAROSCOPY-TOWER','MEDTRONIC'),
('MED-LAPAROSCOPY-TOWER','KARL-STORZ'),
('MED-XRAY-FIXED','SIEMENS-H'),
('MED-XRAY-FIXED','GEHC'),
('MED-XRAY-FIXED','PHILIPS-H'),
('MED-XRAY-FIXED','CANON-MED'),
('MED-XRAY-FIXED','FUJIFILM-MED'),
('MED-XRAY-FIXED','SHIMADZU'),
('MED-XRAY-FIXED','HOLOGIC'),
('MED-XRAY-FIXED','SAMSUNG-MED'),
('MED-XRAY-MOBILE','SIEMENS-H'),
('MED-XRAY-MOBILE','GEHC'),
('MED-XRAY-MOBILE','PHILIPS-H'),
('MED-XRAY-MOBILE','CANON-MED'),
('MED-XRAY-MOBILE','FUJIFILM-MED'),
('MED-XRAY-MOBILE','SHIMADZU'),
('MED-XRAY-MOBILE','HOLOGIC'),
('MED-XRAY-MOBILE','SAMSUNG-MED'),
('MED-DR-PANEL','SIEMENS-H'),
('MED-DR-PANEL','GEHC'),
('MED-DR-PANEL','PHILIPS-H'),
('MED-DR-PANEL','CANON-MED'),
('MED-DR-PANEL','FUJIFILM-MED'),
('MED-DR-PANEL','SHIMADZU'),
('MED-DR-PANEL','HOLOGIC'),
('MED-DR-PANEL','SAMSUNG-MED'),
('MED-CR-READER','SIEMENS-H'),
('MED-CR-READER','GEHC'),
('MED-CR-READER','PHILIPS-H'),
('MED-CR-READER','CANON-MED'),
('MED-CR-READER','FUJIFILM-MED'),
('MED-CR-READER','SHIMADZU'),
('MED-CR-READER','HOLOGIC'),
('MED-CR-READER','SAMSUNG-MED'),
('MED-FLUOROSCOPY','SIEMENS-H'),
('MED-FLUOROSCOPY','GEHC'),
('MED-FLUOROSCOPY','PHILIPS-H'),
('MED-FLUOROSCOPY','CANON-MED'),
('MED-FLUOROSCOPY','FUJIFILM-MED'),
('MED-FLUOROSCOPY','SHIMADZU'),
('MED-FLUOROSCOPY','HOLOGIC'),
('MED-FLUOROSCOPY','SAMSUNG-MED'),
('MED-CARM','SIEMENS-H'),
('MED-CARM','GEHC'),
('MED-CARM','PHILIPS-H'),
('MED-CARM','CANON-MED'),
('MED-CARM','FUJIFILM-MED'),
('MED-CARM','SHIMADZU'),
('MED-CARM','HOLOGIC'),
('MED-CARM','SAMSUNG-MED'),
('MED-CT','SIEMENS-H'),
('MED-CT','GEHC'),
('MED-CT','PHILIPS-H'),
('MED-CT','CANON-MED'),
('MED-CT','FUJIFILM-MED'),
('MED-CT','SHIMADZU'),
('MED-CT','HOLOGIC'),
('MED-CT','SAMSUNG-MED'),
('MED-MRI','SIEMENS-H'),
('MED-MRI','GEHC'),
('MED-MRI','PHILIPS-H'),
('MED-MRI','CANON-MED'),
('MED-MRI','FUJIFILM-MED'),
('MED-MRI','SHIMADZU'),
('MED-MRI','HOLOGIC'),
('MED-MRI','SAMSUNG-MED'),
('MED-ULTRASOUND-GEN','SIEMENS-H'),
('MED-ULTRASOUND-GEN','GEHC'),
('MED-ULTRASOUND-GEN','PHILIPS-H'),
('MED-ULTRASOUND-GEN','CANON-MED'),
('MED-ULTRASOUND-GEN','FUJIFILM-MED'),
('MED-ULTRASOUND-GEN','SHIMADZU'),
('MED-ULTRASOUND-GEN','HOLOGIC'),
('MED-ULTRASOUND-GEN','SAMSUNG-MED'),
('MED-ULTRASOUND-POC','SIEMENS-H'),
('MED-ULTRASOUND-POC','GEHC'),
('MED-ULTRASOUND-POC','PHILIPS-H'),
('MED-ULTRASOUND-POC','CANON-MED'),
('MED-ULTRASOUND-POC','FUJIFILM-MED'),
('MED-ULTRASOUND-POC','SHIMADZU'),
('MED-ULTRASOUND-POC','HOLOGIC'),
('MED-ULTRASOUND-POC','SAMSUNG-MED'),
('MED-MAMMOGRAPHY','SIEMENS-H'),
('MED-MAMMOGRAPHY','GEHC'),
('MED-MAMMOGRAPHY','PHILIPS-H'),
('MED-MAMMOGRAPHY','CANON-MED'),
('MED-MAMMOGRAPHY','FUJIFILM-MED'),
('MED-MAMMOGRAPHY','SHIMADZU'),
('MED-MAMMOGRAPHY','HOLOGIC'),
('MED-MAMMOGRAPHY','SAMSUNG-MED'),
('MED-BONE-DENSITY','SIEMENS-H'),
('MED-BONE-DENSITY','GEHC'),
('MED-BONE-DENSITY','PHILIPS-H'),
('MED-BONE-DENSITY','CANON-MED'),
('MED-BONE-DENSITY','FUJIFILM-MED'),
('MED-BONE-DENSITY','SHIMADZU'),
('MED-BONE-DENSITY','HOLOGIC'),
('MED-BONE-DENSITY','SAMSUNG-MED'),
('MED-CONTRAST-INJECTOR','SIEMENS-H'),
('MED-CONTRAST-INJECTOR','GEHC'),
('MED-CONTRAST-INJECTOR','PHILIPS-H'),
('MED-CONTRAST-INJECTOR','CANON-MED'),
('MED-CONTRAST-INJECTOR','FUJIFILM-MED'),
('MED-CONTRAST-INJECTOR','SHIMADZU'),
('MED-CONTRAST-INJECTOR','HOLOGIC'),
('MED-CONTRAST-INJECTOR','SAMSUNG-MED'),
('MED-PACS-DIAGNOSTIC','SIEMENS-H'),
('MED-PACS-DIAGNOSTIC','GEHC'),
('MED-PACS-DIAGNOSTIC','PHILIPS-H'),
('MED-PACS-DIAGNOSTIC','CANON-MED'),
('MED-PACS-DIAGNOSTIC','FUJIFILM-MED'),
('MED-PACS-DIAGNOSTIC','SHIMADZU'),
('MED-PACS-DIAGNOSTIC','HOLOGIC'),
('MED-PACS-DIAGNOSTIC','SAMSUNG-MED'),
('MED-GAMMA-CAMERA','SIEMENS-H'),
('MED-GAMMA-CAMERA','GEHC'),
('MED-GAMMA-CAMERA','PHILIPS-H'),
('MED-SPECT','SIEMENS-H'),
('MED-SPECT','GEHC'),
('MED-SPECT','PHILIPS-H'),
('MED-PETCT','SIEMENS-H'),
('MED-PETCT','GEHC'),
('MED-PETCT','PHILIPS-H'),
('MED-DOSE-CALIBRATOR','SIEMENS-H'),
('MED-DOSE-CALIBRATOR','GEHC'),
('MED-DOSE-CALIBRATOR','PHILIPS-H'),
('MED-GAMMA-COUNTER','SIEMENS-H'),
('MED-GAMMA-COUNTER','GEHC'),
('MED-GAMMA-COUNTER','PHILIPS-H'),
('MED-RADIATION-SURVEY','SIEMENS-H'),
('MED-RADIATION-SURVEY','GEHC'),
('MED-RADIATION-SURVEY','PHILIPS-H'),
('MED-LINAC','VARIAN'),
('MED-LINAC','ELEKTA'),
('MED-LINAC','IBA'),
('MED-BRACHY','VARIAN'),
('MED-BRACHY','ELEKTA'),
('MED-BRACHY','IBA'),
('MED-RT-TPS','VARIAN'),
('MED-RT-TPS','ELEKTA'),
('MED-RT-TPS','IBA'),
('MED-RT-IMAGING','VARIAN'),
('MED-RT-IMAGING','ELEKTA'),
('MED-RT-IMAGING','IBA'),
('MED-DOSIMETER','VARIAN'),
('MED-DOSIMETER','ELEKTA'),
('MED-DOSIMETER','IBA'),
('MED-CHEM-ANALYZER','ROCHE-DIAG'),
('MED-CHEM-ANALYZER','ABBOTT-DIAG'),
('MED-CHEM-ANALYZER','BECKMAN'),
('MED-CHEM-ANALYZER','SYSMEX'),
('MED-CHEM-ANALYZER','HORIBA'),
('MED-CHEM-ANALYZER','BIORAD'),
('MED-CHEM-ANALYZER','QIAGEN'),
('MED-CHEM-ANALYZER','THERMO'),
('MED-CHEM-ANALYZER','BD'),
('MED-CHEM-ANALYZER','BIOMERIEUX'),
('MED-HEMATOLOGY','ROCHE-DIAG'),
('MED-HEMATOLOGY','ABBOTT-DIAG'),
('MED-HEMATOLOGY','BECKMAN'),
('MED-HEMATOLOGY','SYSMEX'),
('MED-HEMATOLOGY','HORIBA'),
('MED-HEMATOLOGY','BIORAD'),
('MED-HEMATOLOGY','QIAGEN'),
('MED-HEMATOLOGY','THERMO'),
('MED-HEMATOLOGY','BD'),
('MED-HEMATOLOGY','BIOMERIEUX'),
('MED-IMMUNOASSAY','ROCHE-DIAG'),
('MED-IMMUNOASSAY','ABBOTT-DIAG'),
('MED-IMMUNOASSAY','BECKMAN'),
('MED-IMMUNOASSAY','SYSMEX'),
('MED-IMMUNOASSAY','HORIBA'),
('MED-IMMUNOASSAY','BIORAD'),
('MED-IMMUNOASSAY','QIAGEN'),
('MED-IMMUNOASSAY','THERMO'),
('MED-IMMUNOASSAY','BD'),
('MED-IMMUNOASSAY','BIOMERIEUX'),
('MED-COAGULATION','ROCHE-DIAG'),
('MED-COAGULATION','ABBOTT-DIAG'),
('MED-COAGULATION','BECKMAN'),
('MED-COAGULATION','SYSMEX'),
('MED-COAGULATION','HORIBA'),
('MED-COAGULATION','BIORAD'),
('MED-COAGULATION','QIAGEN'),
('MED-COAGULATION','THERMO'),
('MED-COAGULATION','BD'),
('MED-COAGULATION','BIOMERIEUX'),
('MED-BLOOD-GAS','ROCHE-DIAG'),
('MED-BLOOD-GAS','ABBOTT-DIAG'),
('MED-BLOOD-GAS','BECKMAN'),
('MED-BLOOD-GAS','SYSMEX'),
('MED-BLOOD-GAS','HORIBA'),
('MED-BLOOD-GAS','BIORAD'),
('MED-BLOOD-GAS','QIAGEN'),
('MED-BLOOD-GAS','THERMO'),
('MED-BLOOD-GAS','BD'),
('MED-BLOOD-GAS','BIOMERIEUX'),
('MED-ELECTROLYTE','ROCHE-DIAG'),
('MED-ELECTROLYTE','ABBOTT-DIAG'),
('MED-ELECTROLYTE','BECKMAN'),
('MED-ELECTROLYTE','SYSMEX'),
('MED-ELECTROLYTE','HORIBA'),
('MED-ELECTROLYTE','BIORAD'),
('MED-ELECTROLYTE','QIAGEN'),
('MED-ELECTROLYTE','THERMO'),
('MED-ELECTROLYTE','BD'),
('MED-ELECTROLYTE','BIOMERIEUX'),
('MED-URINALYSIS','ROCHE-DIAG'),
('MED-URINALYSIS','ABBOTT-DIAG'),
('MED-URINALYSIS','BECKMAN'),
('MED-URINALYSIS','SYSMEX'),
('MED-URINALYSIS','HORIBA'),
('MED-URINALYSIS','BIORAD'),
('MED-URINALYSIS','QIAGEN'),
('MED-URINALYSIS','THERMO'),
('MED-URINALYSIS','BD'),
('MED-URINALYSIS','BIOMERIEUX'),
('MED-HBA1C','ROCHE-DIAG'),
('MED-HBA1C','ABBOTT-DIAG'),
('MED-HBA1C','BECKMAN'),
('MED-HBA1C','SYSMEX'),
('MED-HBA1C','HORIBA'),
('MED-HBA1C','BIORAD'),
('MED-HBA1C','QIAGEN'),
('MED-HBA1C','THERMO'),
('MED-HBA1C','BD'),
('MED-HBA1C','BIOMERIEUX'),
('MED-ESR','ROCHE-DIAG'),
('MED-ESR','ABBOTT-DIAG'),
('MED-ESR','BECKMAN'),
('MED-ESR','SYSMEX'),
('MED-ESR','HORIBA'),
('MED-ESR','BIORAD'),
('MED-ESR','QIAGEN'),
('MED-ESR','THERMO'),
('MED-ESR','BD'),
('MED-ESR','BIOMERIEUX'),
('MED-PCR','ROCHE-DIAG'),
('MED-PCR','ABBOTT-DIAG'),
('MED-PCR','BECKMAN'),
('MED-PCR','SYSMEX'),
('MED-PCR','HORIBA'),
('MED-PCR','BIORAD'),
('MED-PCR','QIAGEN'),
('MED-PCR','THERMO'),
('MED-PCR','BD'),
('MED-PCR','BIOMERIEUX'),
('MED-RT-PCR','ROCHE-DIAG'),
('MED-RT-PCR','ABBOTT-DIAG'),
('MED-RT-PCR','BECKMAN'),
('MED-RT-PCR','SYSMEX'),
('MED-RT-PCR','HORIBA'),
('MED-RT-PCR','BIORAD'),
('MED-RT-PCR','QIAGEN'),
('MED-RT-PCR','THERMO'),
('MED-RT-PCR','BD'),
('MED-RT-PCR','BIOMERIEUX'),
('MED-GENE-SEQUENCER','ROCHE-DIAG'),
('MED-GENE-SEQUENCER','ABBOTT-DIAG'),
('MED-GENE-SEQUENCER','BECKMAN'),
('MED-GENE-SEQUENCER','SYSMEX'),
('MED-GENE-SEQUENCER','HORIBA'),
('MED-GENE-SEQUENCER','BIORAD'),
('MED-GENE-SEQUENCER','QIAGEN'),
('MED-GENE-SEQUENCER','THERMO'),
('MED-GENE-SEQUENCER','BD'),
('MED-GENE-SEQUENCER','BIOMERIEUX'),
('MED-MICROBIOLOGY','ROCHE-DIAG'),
('MED-MICROBIOLOGY','ABBOTT-DIAG'),
('MED-MICROBIOLOGY','BECKMAN'),
('MED-MICROBIOLOGY','SYSMEX'),
('MED-MICROBIOLOGY','HORIBA'),
('MED-MICROBIOLOGY','BIORAD'),
('MED-MICROBIOLOGY','QIAGEN'),
('MED-MICROBIOLOGY','THERMO'),
('MED-MICROBIOLOGY','BD'),
('MED-MICROBIOLOGY','BIOMERIEUX'),
('MED-BLOOD-CULTURE','ROCHE-DIAG'),
('MED-BLOOD-CULTURE','ABBOTT-DIAG'),
('MED-BLOOD-CULTURE','BECKMAN'),
('MED-BLOOD-CULTURE','SYSMEX'),
('MED-BLOOD-CULTURE','HORIBA'),
('MED-BLOOD-CULTURE','BIORAD'),
('MED-BLOOD-CULTURE','QIAGEN'),
('MED-BLOOD-CULTURE','THERMO'),
('MED-BLOOD-CULTURE','BD'),
('MED-BLOOD-CULTURE','BIOMERIEUX'),
('MED-CENTRIFUGE','ROCHE-DIAG'),
('MED-CENTRIFUGE','ABBOTT-DIAG'),
('MED-CENTRIFUGE','BECKMAN'),
('MED-CENTRIFUGE','SYSMEX'),
('MED-CENTRIFUGE','HORIBA'),
('MED-CENTRIFUGE','BIORAD'),
('MED-CENTRIFUGE','QIAGEN'),
('MED-CENTRIFUGE','THERMO'),
('MED-CENTRIFUGE','BD'),
('MED-CENTRIFUGE','BIOMERIEUX'),
('MED-MICROCENTRIFUGE','ROCHE-DIAG'),
('MED-MICROCENTRIFUGE','ABBOTT-DIAG'),
('MED-MICROCENTRIFUGE','BECKMAN'),
('MED-MICROCENTRIFUGE','SYSMEX'),
('MED-MICROCENTRIFUGE','HORIBA'),
('MED-MICROCENTRIFUGE','BIORAD'),
('MED-MICROCENTRIFUGE','QIAGEN'),
('MED-MICROCENTRIFUGE','THERMO'),
('MED-MICROCENTRIFUGE','BD'),
('MED-MICROCENTRIFUGE','BIOMERIEUX'),
('MED-MICROSCOPE','ROCHE-DIAG'),
('MED-MICROSCOPE','ABBOTT-DIAG'),
('MED-MICROSCOPE','BECKMAN'),
('MED-MICROSCOPE','SYSMEX'),
('MED-MICROSCOPE','HORIBA'),
('MED-MICROSCOPE','BIORAD'),
('MED-MICROSCOPE','QIAGEN'),
('MED-MICROSCOPE','THERMO'),
('MED-MICROSCOPE','BD'),
('MED-MICROSCOPE','BIOMERIEUX'),
('MED-LAB-INCUBATOR','ROCHE-DIAG'),
('MED-LAB-INCUBATOR','ABBOTT-DIAG'),
('MED-LAB-INCUBATOR','BECKMAN'),
('MED-LAB-INCUBATOR','SYSMEX'),
('MED-LAB-INCUBATOR','HORIBA'),
('MED-LAB-INCUBATOR','BIORAD'),
('MED-LAB-INCUBATOR','QIAGEN'),
('MED-LAB-INCUBATOR','THERMO'),
('MED-LAB-INCUBATOR','BD'),
('MED-LAB-INCUBATOR','BIOMERIEUX'),
('MED-BIOSAFETY-CAB','ROCHE-DIAG'),
('MED-BIOSAFETY-CAB','ABBOTT-DIAG'),
('MED-BIOSAFETY-CAB','BECKMAN'),
('MED-BIOSAFETY-CAB','SYSMEX'),
('MED-BIOSAFETY-CAB','HORIBA'),
('MED-BIOSAFETY-CAB','BIORAD'),
('MED-BIOSAFETY-CAB','QIAGEN'),
('MED-BIOSAFETY-CAB','THERMO'),
('MED-BIOSAFETY-CAB','BD'),
('MED-BIOSAFETY-CAB','BIOMERIEUX'),
('MED-LAMINAR-FLOW','ROCHE-DIAG'),
('MED-LAMINAR-FLOW','ABBOTT-DIAG'),
('MED-LAMINAR-FLOW','BECKMAN'),
('MED-LAMINAR-FLOW','SYSMEX'),
('MED-LAMINAR-FLOW','HORIBA'),
('MED-LAMINAR-FLOW','BIORAD'),
('MED-LAMINAR-FLOW','QIAGEN'),
('MED-LAMINAR-FLOW','THERMO'),
('MED-LAMINAR-FLOW','BD'),
('MED-LAMINAR-FLOW','BIOMERIEUX'),
('MED-LAB-REFRIGERATOR','ROCHE-DIAG'),
('MED-LAB-REFRIGERATOR','ABBOTT-DIAG'),
('MED-LAB-REFRIGERATOR','BECKMAN'),
('MED-LAB-REFRIGERATOR','SYSMEX'),
('MED-LAB-REFRIGERATOR','HORIBA'),
('MED-LAB-REFRIGERATOR','BIORAD'),
('MED-LAB-REFRIGERATOR','QIAGEN'),
('MED-LAB-REFRIGERATOR','THERMO'),
('MED-LAB-REFRIGERATOR','BD'),
('MED-LAB-REFRIGERATOR','BIOMERIEUX'),
('MED-LAB-FREEZER','ROCHE-DIAG'),
('MED-LAB-FREEZER','ABBOTT-DIAG'),
('MED-LAB-FREEZER','BECKMAN'),
('MED-LAB-FREEZER','SYSMEX'),
('MED-LAB-FREEZER','HORIBA'),
('MED-LAB-FREEZER','BIORAD'),
('MED-LAB-FREEZER','QIAGEN'),
('MED-LAB-FREEZER','THERMO'),
('MED-LAB-FREEZER','BD'),
('MED-LAB-FREEZER','BIOMERIEUX'),
('MED-ULTRALOW-FREEZER','ROCHE-DIAG'),
('MED-ULTRALOW-FREEZER','ABBOTT-DIAG'),
('MED-ULTRALOW-FREEZER','BECKMAN'),
('MED-ULTRALOW-FREEZER','SYSMEX'),
('MED-ULTRALOW-FREEZER','HORIBA'),
('MED-ULTRALOW-FREEZER','BIORAD'),
('MED-ULTRALOW-FREEZER','QIAGEN'),
('MED-ULTRALOW-FREEZER','THERMO'),
('MED-ULTRALOW-FREEZER','BD'),
('MED-ULTRALOW-FREEZER','BIOMERIEUX'),
('MED-WATER-BATH','ROCHE-DIAG'),
('MED-WATER-BATH','ABBOTT-DIAG'),
('MED-WATER-BATH','BECKMAN'),
('MED-WATER-BATH','SYSMEX'),
('MED-WATER-BATH','HORIBA'),
('MED-WATER-BATH','BIORAD'),
('MED-WATER-BATH','QIAGEN'),
('MED-WATER-BATH','THERMO'),
('MED-WATER-BATH','BD'),
('MED-WATER-BATH','BIOMERIEUX'),
('MED-LAB-BALANCE','ROCHE-DIAG'),
('MED-LAB-BALANCE','ABBOTT-DIAG'),
('MED-LAB-BALANCE','BECKMAN'),
('MED-LAB-BALANCE','SYSMEX'),
('MED-LAB-BALANCE','HORIBA'),
('MED-LAB-BALANCE','BIORAD'),
('MED-LAB-BALANCE','QIAGEN'),
('MED-LAB-BALANCE','THERMO'),
('MED-LAB-BALANCE','BD'),
('MED-LAB-BALANCE','BIOMERIEUX'),
('MED-SPECTROPHOTOMETER','ROCHE-DIAG'),
('MED-SPECTROPHOTOMETER','ABBOTT-DIAG'),
('MED-SPECTROPHOTOMETER','BECKMAN'),
('MED-SPECTROPHOTOMETER','SYSMEX'),
('MED-SPECTROPHOTOMETER','HORIBA'),
('MED-SPECTROPHOTOMETER','BIORAD'),
('MED-SPECTROPHOTOMETER','QIAGEN'),
('MED-SPECTROPHOTOMETER','THERMO'),
('MED-SPECTROPHOTOMETER','BD'),
('MED-SPECTROPHOTOMETER','BIOMERIEUX'),
('MED-BLOOD-FRIDGE','HELMER'),
('MED-BLOOD-FRIDGE','HAEMONETICS'),
('MED-BLOOD-FRIDGE','TERUMO-BCT'),
('MED-BLOOD-FRIDGE','THERMO'),
('MED-PLASMA-FREEZER','HELMER'),
('MED-PLASMA-FREEZER','HAEMONETICS'),
('MED-PLASMA-FREEZER','TERUMO-BCT'),
('MED-PLASMA-FREEZER','THERMO'),
('MED-PLATELET-INCUBATOR','HELMER'),
('MED-PLATELET-INCUBATOR','HAEMONETICS'),
('MED-PLATELET-INCUBATOR','TERUMO-BCT'),
('MED-PLATELET-INCUBATOR','THERMO'),
('MED-PLATELET-AGITATOR','HELMER'),
('MED-PLATELET-AGITATOR','HAEMONETICS'),
('MED-PLATELET-AGITATOR','TERUMO-BCT'),
('MED-PLATELET-AGITATOR','THERMO'),
('MED-BLOOD-MIXER','HELMER'),
('MED-BLOOD-MIXER','HAEMONETICS'),
('MED-BLOOD-MIXER','TERUMO-BCT'),
('MED-BLOOD-MIXER','THERMO'),
('MED-BLOOD-COLLECTION-MONITOR','HELMER'),
('MED-BLOOD-COLLECTION-MONITOR','HAEMONETICS'),
('MED-BLOOD-COLLECTION-MONITOR','TERUMO-BCT'),
('MED-BLOOD-COLLECTION-MONITOR','THERMO'),
('MED-CELL-WASHER','HELMER'),
('MED-CELL-WASHER','HAEMONETICS'),
('MED-CELL-WASHER','TERUMO-BCT'),
('MED-CELL-WASHER','THERMO'),
('MED-PLASMA-THAWER','HELMER'),
('MED-PLASMA-THAWER','HAEMONETICS'),
('MED-PLASMA-THAWER','TERUMO-BCT'),
('MED-PLASMA-THAWER','THERMO'),
('MED-STEAM-STERILIZER','GETINGE'),
('MED-STEAM-STERILIZER','STERIS'),
('MED-STEAM-STERILIZER','TUTTNAUER'),
('MED-STEAM-STERILIZER','BELIMED'),
('MED-STEAM-STERILIZER','STEELCO'),
('MED-STEAM-STERILIZER','MELAG'),
('MED-LOWTEMP-STER','GETINGE'),
('MED-LOWTEMP-STER','STERIS'),
('MED-LOWTEMP-STER','TUTTNAUER'),
('MED-LOWTEMP-STER','BELIMED'),
('MED-LOWTEMP-STER','STEELCO'),
('MED-LOWTEMP-STER','MELAG'),
('MED-H2O2-STER','GETINGE'),
('MED-H2O2-STER','STERIS'),
('MED-H2O2-STER','TUTTNAUER'),
('MED-H2O2-STER','BELIMED'),
('MED-H2O2-STER','STEELCO'),
('MED-H2O2-STER','MELAG'),
('MED-WASHER-DISINFECTOR','GETINGE'),
('MED-WASHER-DISINFECTOR','STERIS'),
('MED-WASHER-DISINFECTOR','TUTTNAUER'),
('MED-WASHER-DISINFECTOR','BELIMED'),
('MED-WASHER-DISINFECTOR','STEELCO'),
('MED-WASHER-DISINFECTOR','MELAG'),
('MED-ULTRASONIC-CLEANER','GETINGE'),
('MED-ULTRASONIC-CLEANER','STERIS'),
('MED-ULTRASONIC-CLEANER','TUTTNAUER'),
('MED-ULTRASONIC-CLEANER','BELIMED'),
('MED-ULTRASONIC-CLEANER','STEELCO'),
('MED-ULTRASONIC-CLEANER','MELAG'),
('MED-INSTRUMENT-DRYER','GETINGE'),
('MED-INSTRUMENT-DRYER','STERIS'),
('MED-INSTRUMENT-DRYER','TUTTNAUER'),
('MED-INSTRUMENT-DRYER','BELIMED'),
('MED-INSTRUMENT-DRYER','STEELCO'),
('MED-INSTRUMENT-DRYER','MELAG'),
('MED-PACKAGE-SEALER','GETINGE'),
('MED-PACKAGE-SEALER','STERIS'),
('MED-PACKAGE-SEALER','TUTTNAUER'),
('MED-PACKAGE-SEALER','BELIMED'),
('MED-PACKAGE-SEALER','STEELCO'),
('MED-PACKAGE-SEALER','MELAG'),
('MED-STERILE-STORAGE','GETINGE'),
('MED-STERILE-STORAGE','STERIS'),
('MED-STERILE-STORAGE','TUTTNAUER'),
('MED-STERILE-STORAGE','BELIMED'),
('MED-STERILE-STORAGE','STEELCO'),
('MED-STERILE-STORAGE','MELAG'),
('MED-HEMODIALYSIS','FRESENIUS'),
('MED-HEMODIALYSIS','BBRAUN'),
('MED-HEMODIALYSIS','BAXTER'),
('MED-CRRT','FRESENIUS'),
('MED-CRRT','BBRAUN'),
('MED-CRRT','BAXTER'),
('MED-DIALYSIS-RO','FRESENIUS'),
('MED-DIALYSIS-RO','BBRAUN'),
('MED-DIALYSIS-RO','BAXTER'),
('MED-DIALYSIS-WATER-LOOP','FRESENIUS'),
('MED-DIALYSIS-WATER-LOOP','BBRAUN'),
('MED-DIALYSIS-WATER-LOOP','BAXTER'),
('MED-DIALYSIS-CHAIR','FRESENIUS'),
('MED-DIALYSIS-CHAIR','BBRAUN'),
('MED-DIALYSIS-CHAIR','BAXTER'),
('MED-ECHO','PHILIPS-H'),
('MED-ECHO','GEHC'),
('MED-ECHO','SIEMENS-H'),
('MED-ECHO','SCHILLER'),
('MED-ECHO','EDWARDS'),
('MED-ECHO','TERUMO'),
('MED-STRESS-TEST','PHILIPS-H'),
('MED-STRESS-TEST','GEHC'),
('MED-STRESS-TEST','SIEMENS-H'),
('MED-STRESS-TEST','SCHILLER'),
('MED-STRESS-TEST','EDWARDS'),
('MED-STRESS-TEST','TERUMO'),
('MED-CATHLAB','PHILIPS-H'),
('MED-CATHLAB','GEHC'),
('MED-CATHLAB','SIEMENS-H'),
('MED-CATHLAB','SCHILLER'),
('MED-CATHLAB','EDWARDS'),
('MED-CATHLAB','TERUMO'),
('MED-EP-SYSTEM','PHILIPS-H'),
('MED-EP-SYSTEM','GEHC'),
('MED-EP-SYSTEM','SIEMENS-H'),
('MED-EP-SYSTEM','SCHILLER'),
('MED-EP-SYSTEM','EDWARDS'),
('MED-EP-SYSTEM','TERUMO'),
('MED-TEMP-PACEMAKER','PHILIPS-H'),
('MED-TEMP-PACEMAKER','GEHC'),
('MED-TEMP-PACEMAKER','SIEMENS-H'),
('MED-TEMP-PACEMAKER','SCHILLER'),
('MED-TEMP-PACEMAKER','EDWARDS'),
('MED-TEMP-PACEMAKER','TERUMO'),
('MED-HOLTER-ANALYZER','PHILIPS-H'),
('MED-HOLTER-ANALYZER','GEHC'),
('MED-HOLTER-ANALYZER','SIEMENS-H'),
('MED-HOLTER-ANALYZER','SCHILLER'),
('MED-HOLTER-ANALYZER','EDWARDS'),
('MED-HOLTER-ANALYZER','TERUMO'),
('MED-SPIROMETER','DRAGER'),
('MED-SPIROMETER','HAMILTON'),
('MED-SPIROMETER','PHILIPS-H'),
('MED-SPIROMETER','RESMED'),
('MED-PFT','DRAGER'),
('MED-PFT','HAMILTON'),
('MED-PFT','PHILIPS-H'),
('MED-PFT','RESMED'),
('MED-NEBULIZER','DRAGER'),
('MED-NEBULIZER','HAMILTON'),
('MED-NEBULIZER','PHILIPS-H'),
('MED-NEBULIZER','RESMED'),
('MED-OXYGEN-CONCENTRATOR','DRAGER'),
('MED-OXYGEN-CONCENTRATOR','HAMILTON'),
('MED-OXYGEN-CONCENTRATOR','PHILIPS-H'),
('MED-OXYGEN-CONCENTRATOR','RESMED'),
('MED-CPAP','DRAGER'),
('MED-CPAP','HAMILTON'),
('MED-CPAP','PHILIPS-H'),
('MED-CPAP','RESMED'),
('MED-BIPAP','DRAGER'),
('MED-BIPAP','HAMILTON'),
('MED-BIPAP','PHILIPS-H'),
('MED-BIPAP','RESMED'),
('MED-POLYSOMNOGRAPHY','DRAGER'),
('MED-POLYSOMNOGRAPHY','HAMILTON'),
('MED-POLYSOMNOGRAPHY','PHILIPS-H'),
('MED-POLYSOMNOGRAPHY','RESMED'),
('MED-INFANT-INCUBATOR','DRAGER'),
('MED-INFANT-INCUBATOR','GEHC'),
('MED-INFANT-INCUBATOR','PHILIPS-H'),
('MED-INFANT-INCUBATOR','MINDRAY'),
('MED-RADIANT-WARMER','DRAGER'),
('MED-RADIANT-WARMER','GEHC'),
('MED-RADIANT-WARMER','PHILIPS-H'),
('MED-RADIANT-WARMER','MINDRAY'),
('MED-PHOTOTHERAPY','DRAGER'),
('MED-PHOTOTHERAPY','GEHC'),
('MED-PHOTOTHERAPY','PHILIPS-H'),
('MED-PHOTOTHERAPY','MINDRAY'),
('MED-NEONATAL-VENT','DRAGER'),
('MED-NEONATAL-VENT','GEHC'),
('MED-NEONATAL-VENT','PHILIPS-H'),
('MED-NEONATAL-VENT','MINDRAY'),
('MED-NEONATAL-CPAP','DRAGER'),
('MED-NEONATAL-CPAP','GEHC'),
('MED-NEONATAL-CPAP','PHILIPS-H'),
('MED-NEONATAL-CPAP','MINDRAY'),
('MED-FETAL-MONITOR','DRAGER'),
('MED-FETAL-MONITOR','GEHC'),
('MED-FETAL-MONITOR','PHILIPS-H'),
('MED-FETAL-MONITOR','MINDRAY'),
('MED-FETAL-DOPPLER','DRAGER'),
('MED-FETAL-DOPPLER','GEHC'),
('MED-FETAL-DOPPLER','PHILIPS-H'),
('MED-FETAL-DOPPLER','MINDRAY'),
('MED-DELIVERY-BED','DRAGER'),
('MED-DELIVERY-BED','GEHC'),
('MED-DELIVERY-BED','PHILIPS-H'),
('MED-DELIVERY-BED','MINDRAY'),
('MED-INFANT-SCALE','DRAGER'),
('MED-INFANT-SCALE','GEHC'),
('MED-INFANT-SCALE','PHILIPS-H'),
('MED-INFANT-SCALE','MINDRAY'),
('MED-BREAST-PUMP','DRAGER'),
('MED-BREAST-PUMP','GEHC'),
('MED-BREAST-PUMP','PHILIPS-H'),
('MED-BREAST-PUMP','MINDRAY'),
('MED-ENDOSCOPY-TOWER','OLYMPUS'),
('MED-ENDOSCOPY-TOWER','KARL-STORZ'),
('MED-ENDOSCOPY-TOWER','PENTAX-MED'),
('MED-ENDOSCOPY-TOWER','FUJIFILM-MED'),
('MED-ENDOSCOPY-TOWER','RICHARD-WOLF'),
('MED-GASTROSCOPE','OLYMPUS'),
('MED-GASTROSCOPE','KARL-STORZ'),
('MED-GASTROSCOPE','PENTAX-MED'),
('MED-GASTROSCOPE','FUJIFILM-MED'),
('MED-GASTROSCOPE','RICHARD-WOLF'),
('MED-COLONOSCOPE','OLYMPUS'),
('MED-COLONOSCOPE','KARL-STORZ'),
('MED-COLONOSCOPE','PENTAX-MED'),
('MED-COLONOSCOPE','FUJIFILM-MED'),
('MED-COLONOSCOPE','RICHARD-WOLF'),
('MED-BRONCHOSCOPE','OLYMPUS'),
('MED-BRONCHOSCOPE','KARL-STORZ'),
('MED-BRONCHOSCOPE','PENTAX-MED'),
('MED-BRONCHOSCOPE','FUJIFILM-MED'),
('MED-BRONCHOSCOPE','RICHARD-WOLF'),
('MED-EUS','OLYMPUS'),
('MED-EUS','KARL-STORZ'),
('MED-EUS','PENTAX-MED'),
('MED-EUS','FUJIFILM-MED'),
('MED-EUS','RICHARD-WOLF'),
('MED-ENDO-INSUFFLATOR','OLYMPUS'),
('MED-ENDO-INSUFFLATOR','KARL-STORZ'),
('MED-ENDO-INSUFFLATOR','PENTAX-MED'),
('MED-ENDO-INSUFFLATOR','FUJIFILM-MED'),
('MED-ENDO-INSUFFLATOR','RICHARD-WOLF'),
('MED-ENDO-PROCESSOR','OLYMPUS'),
('MED-ENDO-PROCESSOR','KARL-STORZ'),
('MED-ENDO-PROCESSOR','PENTAX-MED'),
('MED-ENDO-PROCESSOR','FUJIFILM-MED'),
('MED-ENDO-PROCESSOR','RICHARD-WOLF'),
('MED-ENDO-LIGHT','OLYMPUS'),
('MED-ENDO-LIGHT','KARL-STORZ'),
('MED-ENDO-LIGHT','PENTAX-MED'),
('MED-ENDO-LIGHT','FUJIFILM-MED'),
('MED-ENDO-LIGHT','RICHARD-WOLF'),
('MED-ENDO-REPROCESSOR','OLYMPUS'),
('MED-ENDO-REPROCESSOR','KARL-STORZ'),
('MED-ENDO-REPROCESSOR','PENTAX-MED'),
('MED-ENDO-REPROCESSOR','FUJIFILM-MED'),
('MED-ENDO-REPROCESSOR','RICHARD-WOLF'),
('MED-ENDO-DRYING','OLYMPUS'),
('MED-ENDO-DRYING','KARL-STORZ'),
('MED-ENDO-DRYING','PENTAX-MED'),
('MED-ENDO-DRYING','FUJIFILM-MED'),
('MED-ENDO-DRYING','RICHARD-WOLF'),
('MED-AED','ZOLL'),
('MED-AED','PHILIPS-H'),
('MED-AED','STRYKER'),
('MED-AED','SCHILLER'),
('MED-EMERGENCY-STRETCHER','ZOLL'),
('MED-EMERGENCY-STRETCHER','PHILIPS-H'),
('MED-EMERGENCY-STRETCHER','STRYKER'),
('MED-EMERGENCY-STRETCHER','SCHILLER'),
('MED-EMERGENCY-VENT','ZOLL'),
('MED-EMERGENCY-VENT','PHILIPS-H'),
('MED-EMERGENCY-VENT','STRYKER'),
('MED-EMERGENCY-VENT','SCHILLER'),
('MED-EMERGENCY-MONITOR','ZOLL'),
('MED-EMERGENCY-MONITOR','PHILIPS-H'),
('MED-EMERGENCY-MONITOR','STRYKER'),
('MED-EMERGENCY-MONITOR','SCHILLER'),
('MED-EMERGENCY-SUCTION','ZOLL'),
('MED-EMERGENCY-SUCTION','PHILIPS-H'),
('MED-EMERGENCY-SUCTION','STRYKER'),
('MED-EMERGENCY-SUCTION','SCHILLER'),
('MED-DENTAL-UNIT','PLANMECA'),
('MED-DENTAL-UNIT','DENTSPLY'),
('MED-DENTAL-UNIT','KAVO'),
('MED-DENTAL-UNIT','CARESTREAM'),
('MED-DENTAL-XRAY','PLANMECA'),
('MED-DENTAL-XRAY','DENTSPLY'),
('MED-DENTAL-XRAY','KAVO'),
('MED-DENTAL-XRAY','CARESTREAM'),
('MED-DENTAL-PANO','PLANMECA'),
('MED-DENTAL-PANO','DENTSPLY'),
('MED-DENTAL-PANO','KAVO'),
('MED-DENTAL-PANO','CARESTREAM'),
('MED-DENTAL-CBCT','PLANMECA'),
('MED-DENTAL-CBCT','DENTSPLY'),
('MED-DENTAL-CBCT','KAVO'),
('MED-DENTAL-CBCT','CARESTREAM'),
('MED-DENTAL-AUTOCLAVE','PLANMECA'),
('MED-DENTAL-AUTOCLAVE','DENTSPLY'),
('MED-DENTAL-AUTOCLAVE','KAVO'),
('MED-DENTAL-AUTOCLAVE','CARESTREAM'),
('MED-DENTAL-COMPRESSOR','PLANMECA'),
('MED-DENTAL-COMPRESSOR','DENTSPLY'),
('MED-DENTAL-COMPRESSOR','KAVO'),
('MED-DENTAL-COMPRESSOR','CARESTREAM'),
('MED-DENTAL-SUCTION','PLANMECA'),
('MED-DENTAL-SUCTION','DENTSPLY'),
('MED-DENTAL-SUCTION','KAVO'),
('MED-DENTAL-SUCTION','CARESTREAM'),
('MED-ULTRASONIC-SCALER','PLANMECA'),
('MED-ULTRASONIC-SCALER','DENTSPLY'),
('MED-ULTRASONIC-SCALER','KAVO'),
('MED-ULTRASONIC-SCALER','CARESTREAM'),
('MED-CURING-LIGHT','PLANMECA'),
('MED-CURING-LIGHT','DENTSPLY'),
('MED-CURING-LIGHT','KAVO'),
('MED-CURING-LIGHT','CARESTREAM'),
('MED-ENDO-MOTOR','PLANMECA'),
('MED-ENDO-MOTOR','DENTSPLY'),
('MED-ENDO-MOTOR','KAVO'),
('MED-ENDO-MOTOR','CARESTREAM'),
('MED-SLIT-LAMP','ZEISS-MED'),
('MED-SLIT-LAMP','NIDEK'),
('MED-SLIT-LAMP','ALCON'),
('MED-AUTOREFRACTOR','ZEISS-MED'),
('MED-AUTOREFRACTOR','NIDEK'),
('MED-AUTOREFRACTOR','ALCON'),
('MED-TONOMETER','ZEISS-MED'),
('MED-TONOMETER','NIDEK'),
('MED-TONOMETER','ALCON'),
('MED-VISUAL-FIELD','ZEISS-MED'),
('MED-VISUAL-FIELD','NIDEK'),
('MED-VISUAL-FIELD','ALCON'),
('MED-FUNDUS-CAMERA','ZEISS-MED'),
('MED-FUNDUS-CAMERA','NIDEK'),
('MED-FUNDUS-CAMERA','ALCON'),
('MED-OCT','ZEISS-MED'),
('MED-OCT','NIDEK'),
('MED-OCT','ALCON'),
('MED-OPTICAL-BIOMETER','ZEISS-MED'),
('MED-OPTICAL-BIOMETER','NIDEK'),
('MED-OPTICAL-BIOMETER','ALCON'),
('MED-PHACO','ZEISS-MED'),
('MED-PHACO','NIDEK'),
('MED-PHACO','ALCON'),
('MED-EXCIMER-LASER','ZEISS-MED'),
('MED-EXCIMER-LASER','NIDEK'),
('MED-EXCIMER-LASER','ALCON'),
('MED-ENT-UNIT','NATUS'),
('MED-ENT-UNIT','INTERACOUSTICS'),
('MED-ENT-UNIT','GN-OTOMETRICS'),
('MED-ENT-UNIT','KARL-STORZ'),
('MED-AUDIOMETER','NATUS'),
('MED-AUDIOMETER','INTERACOUSTICS'),
('MED-AUDIOMETER','GN-OTOMETRICS'),
('MED-AUDIOMETER','KARL-STORZ'),
('MED-TYMPANOMETER','NATUS'),
('MED-TYMPANOMETER','INTERACOUSTICS'),
('MED-TYMPANOMETER','GN-OTOMETRICS'),
('MED-TYMPANOMETER','KARL-STORZ'),
('MED-OAE','NATUS'),
('MED-OAE','INTERACOUSTICS'),
('MED-OAE','GN-OTOMETRICS'),
('MED-OAE','KARL-STORZ'),
('MED-ABR','NATUS'),
('MED-ABR','INTERACOUSTICS'),
('MED-ABR','GN-OTOMETRICS'),
('MED-ABR','KARL-STORZ'),
('MED-HEARING-AID-ANALYZER','NATUS'),
('MED-HEARING-AID-ANALYZER','INTERACOUSTICS'),
('MED-HEARING-AID-ANALYZER','GN-OTOMETRICS'),
('MED-HEARING-AID-ANALYZER','KARL-STORZ'),
('MED-ENT-ENDOSCOPE','NATUS'),
('MED-ENT-ENDOSCOPE','INTERACOUSTICS'),
('MED-ENT-ENDOSCOPE','GN-OTOMETRICS'),
('MED-ENT-ENDOSCOPE','KARL-STORZ'),
('MED-EEG','NATUS'),
('MED-EEG','NIHON-KOHDEN'),
('MED-EEG','NICOLET'),
('MED-EMG','NATUS'),
('MED-EMG','NIHON-KOHDEN'),
('MED-EMG','NICOLET'),
('MED-EVOKED-POTENTIAL','NATUS'),
('MED-EVOKED-POTENTIAL','NIHON-KOHDEN'),
('MED-EVOKED-POTENTIAL','NICOLET'),
('MED-TCD','NATUS'),
('MED-TCD','NIHON-KOHDEN'),
('MED-TCD','NICOLET'),
('MED-INTRAOP-NEUROMON','NATUS'),
('MED-INTRAOP-NEUROMON','NIHON-KOHDEN'),
('MED-INTRAOP-NEUROMON','NICOLET'),
('MED-LITHOTRIPTER','KARL-STORZ'),
('MED-LITHOTRIPTER','OLYMPUS'),
('MED-LITHOTRIPTER','RICHARD-WOLF'),
('MED-LITHOTRIPTER','COOK-MED'),
('MED-URODYNAMIC','KARL-STORZ'),
('MED-URODYNAMIC','OLYMPUS'),
('MED-URODYNAMIC','RICHARD-WOLF'),
('MED-URODYNAMIC','COOK-MED'),
('MED-CYSTOSCOPY','KARL-STORZ'),
('MED-CYSTOSCOPY','OLYMPUS'),
('MED-CYSTOSCOPY','RICHARD-WOLF'),
('MED-CYSTOSCOPY','COOK-MED'),
('MED-BLADDER-SCANNER','KARL-STORZ'),
('MED-BLADDER-SCANNER','OLYMPUS'),
('MED-BLADDER-SCANNER','RICHARD-WOLF'),
('MED-BLADDER-SCANNER','COOK-MED'),
('MED-URO-LASER','KARL-STORZ'),
('MED-URO-LASER','OLYMPUS'),
('MED-URO-LASER','RICHARD-WOLF'),
('MED-URO-LASER','COOK-MED'),
('MED-DERM-LASER','BTL'),
('MED-DERM-LASER','ZEISS-MED'),
('MED-PHOTOTHERAPY-CABIN','BTL'),
('MED-PHOTOTHERAPY-CABIN','ZEISS-MED'),
('MED-DERMATOSCOPE','BTL'),
('MED-DERMATOSCOPE','ZEISS-MED'),
('MED-CRYOSURGERY','BTL'),
('MED-CRYOSURGERY','ZEISS-MED'),
('MED-PHARM-FRIDGE','BAXTER'),
('MED-PHARM-FRIDGE','BD'),
('MED-VACCINE-FRIDGE','BAXTER'),
('MED-VACCINE-FRIDGE','BD'),
('MED-AUTOMATED-DISPENSING','BAXTER'),
('MED-AUTOMATED-DISPENSING','BD'),
('MED-PHARMACY-ROBOT','BAXTER'),
('MED-PHARMACY-ROBOT','BD'),
('MED-COMPOUNDING-HOOD','BAXTER'),
('MED-COMPOUNDING-HOOD','BD'),
('MED-PHYSIO-ULTRASOUND','BTL'),
('MED-PHYSIO-ULTRASOUND','CHATTANOOGA'),
('MED-PHYSIO-ULTRASOUND','HOCOMA'),
('MED-TENS','BTL'),
('MED-TENS','CHATTANOOGA'),
('MED-TENS','HOCOMA'),
('MED-ELECTROTHERAPY','BTL'),
('MED-ELECTROTHERAPY','CHATTANOOGA'),
('MED-ELECTROTHERAPY','HOCOMA'),
('MED-SHOCKWAVE','BTL'),
('MED-SHOCKWAVE','CHATTANOOGA'),
('MED-SHOCKWAVE','HOCOMA'),
('MED-CPM','BTL'),
('MED-CPM','CHATTANOOGA'),
('MED-CPM','HOCOMA'),
('MED-REHAB-TREADMILL','BTL'),
('MED-REHAB-TREADMILL','CHATTANOOGA'),
('MED-REHAB-TREADMILL','HOCOMA'),
('MED-GAIT-ANALYSIS','BTL'),
('MED-GAIT-ANALYSIS','CHATTANOOGA'),
('MED-GAIT-ANALYSIS','HOCOMA'),
('MED-REHAB-ROBOT','BTL'),
('MED-REHAB-ROBOT','CHATTANOOGA'),
('MED-REHAB-ROBOT','HOCOMA'),
('MED-HOSPITAL-BED','STRYKER'),
('MED-HOSPITAL-BED','HILLROM'),
('MED-HOSPITAL-BED','ARJO'),
('MED-HOSPITAL-BED','INVACARE'),
('MED-HOSPITAL-BED','SECA'),
('MED-HOSPITAL-BED','WELCHALLYN'),
('MED-ICU-BED','STRYKER'),
('MED-ICU-BED','HILLROM'),
('MED-ICU-BED','ARJO'),
('MED-ICU-BED','INVACARE'),
('MED-ICU-BED','SECA'),
('MED-ICU-BED','WELCHALLYN'),
('MED-EXAM-TABLE','STRYKER'),
('MED-EXAM-TABLE','HILLROM'),
('MED-EXAM-TABLE','ARJO'),
('MED-EXAM-TABLE','INVACARE'),
('MED-EXAM-TABLE','SECA'),
('MED-EXAM-TABLE','WELCHALLYN'),
('MED-PATIENT-LIFT','STRYKER'),
('MED-PATIENT-LIFT','HILLROM'),
('MED-PATIENT-LIFT','ARJO'),
('MED-PATIENT-LIFT','INVACARE'),
('MED-PATIENT-LIFT','SECA'),
('MED-PATIENT-LIFT','WELCHALLYN'),
('MED-WHEELCHAIR-POWER','STRYKER'),
('MED-WHEELCHAIR-POWER','HILLROM'),
('MED-WHEELCHAIR-POWER','ARJO'),
('MED-WHEELCHAIR-POWER','INVACARE'),
('MED-WHEELCHAIR-POWER','SECA'),
('MED-WHEELCHAIR-POWER','WELCHALLYN'),
('MED-MEDICAL-SCALE','STRYKER'),
('MED-MEDICAL-SCALE','HILLROM'),
('MED-MEDICAL-SCALE','ARJO'),
('MED-MEDICAL-SCALE','INVACARE'),
('MED-MEDICAL-SCALE','SECA'),
('MED-MEDICAL-SCALE','WELCHALLYN'),
('MED-HEIGHT-WEIGHT','STRYKER'),
('MED-HEIGHT-WEIGHT','HILLROM'),
('MED-HEIGHT-WEIGHT','ARJO'),
('MED-HEIGHT-WEIGHT','INVACARE'),
('MED-HEIGHT-WEIGHT','SECA'),
('MED-HEIGHT-WEIGHT','WELCHALLYN'),
('MED-EXAM-LIGHT','STRYKER'),
('MED-EXAM-LIGHT','HILLROM'),
('MED-EXAM-LIGHT','ARJO'),
('MED-EXAM-LIGHT','INVACARE'),
('MED-EXAM-LIGHT','SECA'),
('MED-EXAM-LIGHT','WELCHALLYN'),
('MED-O2-FLOWMETER','DRAGER'),
('MED-O2-FLOWMETER','GETINGE'),
('MED-GAS-REGULATOR','DRAGER'),
('MED-GAS-REGULATOR','GETINGE'),
('MED-VACUUM-REGULATOR','DRAGER'),
('MED-VACUUM-REGULATOR','GETINGE'),
('MED-GAS-ALARM-PANEL','DRAGER'),
('MED-GAS-ALARM-PANEL','GETINGE'),
('MED-GAS-MANIFOLD-CONTROLLER','DRAGER'),
('MED-GAS-MANIFOLD-CONTROLLER','GETINGE'),
('MED-POCT-GLUCOSE','ABBOTT-DIAG'),
('MED-POCT-GLUCOSE','ROCHE-DIAG'),
('MED-POCT-GLUCOSE','SIEMENS-H'),
('MED-POCT-BLOODGAS','ABBOTT-DIAG'),
('MED-POCT-BLOODGAS','ROCHE-DIAG'),
('MED-POCT-BLOODGAS','SIEMENS-H'),
('MED-POCT-TROPONIN','ABBOTT-DIAG'),
('MED-POCT-TROPONIN','ROCHE-DIAG'),
('MED-POCT-TROPONIN','SIEMENS-H'),
('MED-POCT-COAG','ABBOTT-DIAG'),
('MED-POCT-COAG','ROCHE-DIAG'),
('MED-POCT-COAG','SIEMENS-H'),
('MED-POCT-HBA1C','ABBOTT-DIAG'),
('MED-POCT-HBA1C','ROCHE-DIAG'),
('MED-POCT-HBA1C','SIEMENS-H'),
('MED-TEST-ELEC-SAFETY','FLUKE-BIOMED'),
('MED-TEST-ELEC-SAFETY','RIGEL'),
('MED-TEST-ELEC-SAFETY','BC-GROUP'),
('MED-TEST-ELEC-SAFETY','METRON'),
('MED-TEST-ELEC-SAFETY','PRONK'),
('MED-TEST-PATIENT-SIM','FLUKE-BIOMED'),
('MED-TEST-PATIENT-SIM','RIGEL'),
('MED-TEST-PATIENT-SIM','BC-GROUP'),
('MED-TEST-PATIENT-SIM','METRON'),
('MED-TEST-PATIENT-SIM','PRONK'),
('MED-TEST-DEFIB','FLUKE-BIOMED'),
('MED-TEST-DEFIB','RIGEL'),
('MED-TEST-DEFIB','BC-GROUP'),
('MED-TEST-DEFIB','METRON'),
('MED-TEST-DEFIB','PRONK'),
('MED-TEST-INFUSION','FLUKE-BIOMED'),
('MED-TEST-INFUSION','RIGEL'),
('MED-TEST-INFUSION','BC-GROUP'),
('MED-TEST-INFUSION','METRON'),
('MED-TEST-INFUSION','PRONK'),
('MED-TEST-VENT','FLUKE-BIOMED'),
('MED-TEST-VENT','RIGEL'),
('MED-TEST-VENT','BC-GROUP'),
('MED-TEST-VENT','METRON'),
('MED-TEST-VENT','PRONK'),
('MED-TEST-ESU','FLUKE-BIOMED'),
('MED-TEST-ESU','RIGEL'),
('MED-TEST-ESU','BC-GROUP'),
('MED-TEST-ESU','METRON'),
('MED-TEST-ESU','PRONK'),
('MED-TEST-SPO2','FLUKE-BIOMED'),
('MED-TEST-SPO2','RIGEL'),
('MED-TEST-SPO2','BC-GROUP'),
('MED-TEST-SPO2','METRON'),
('MED-TEST-SPO2','PRONK'),
('MED-TEST-NIBP','FLUKE-BIOMED'),
('MED-TEST-NIBP','RIGEL'),
('MED-TEST-NIBP','BC-GROUP'),
('MED-TEST-NIBP','METRON'),
('MED-TEST-NIBP','PRONK'),
('MED-TEST-TEMP','FLUKE-BIOMED'),
('MED-TEST-TEMP','RIGEL'),
('MED-TEST-TEMP','BC-GROUP'),
('MED-TEST-TEMP','METRON'),
('MED-TEST-TEMP','PRONK'),
('MED-TEST-PRESSURE','FLUKE-BIOMED'),
('MED-TEST-PRESSURE','RIGEL'),
('MED-TEST-PRESSURE','BC-GROUP'),
('MED-TEST-PRESSURE','METRON'),
('MED-TEST-PRESSURE','PRONK'),
('MED-PACS-SERVER','PHILIPS-H'),
('MED-PACS-SERVER','GEHC'),
('MED-PACS-SERVER','SIEMENS-H'),
('MED-PACS-SERVER','AGFA'),
('MED-PACS-SERVER','CARESTREAM-H'),
('MED-RIS-SERVER','PHILIPS-H'),
('MED-RIS-SERVER','GEHC'),
('MED-RIS-SERVER','SIEMENS-H'),
('MED-RIS-SERVER','AGFA'),
('MED-RIS-SERVER','CARESTREAM-H'),
('MED-DEVICE-GATEWAY','PHILIPS-H'),
('MED-DEVICE-GATEWAY','GEHC'),
('MED-DEVICE-GATEWAY','SIEMENS-H'),
('MED-DEVICE-GATEWAY','AGFA'),
('MED-DEVICE-GATEWAY','CARESTREAM-H'),
('MED-CENTRAL-MON-SERVER','PHILIPS-H'),
('MED-CENTRAL-MON-SERVER','GEHC'),
('MED-CENTRAL-MON-SERVER','SIEMENS-H'),
('MED-CENTRAL-MON-SERVER','AGFA'),
('MED-CENTRAL-MON-SERVER','CARESTREAM-H'),
('MED-CLINICAL-WORKSTATION','PHILIPS-H'),
('MED-CLINICAL-WORKSTATION','GEHC'),
('MED-CLINICAL-WORKSTATION','SIEMENS-H'),
('MED-CLINICAL-WORKSTATION','AGFA'),
('MED-CLINICAL-WORKSTATION','CARESTREAM-H'),
('MED-AMB-MONITOR','ZOLL'),
('MED-AMB-MONITOR','PHILIPS-H'),
('MED-AMB-MONITOR','STRYKER'),
('MED-AMB-MONITOR','SCHILLER'),
('MED-AMB-MONITOR','HAMILTON'),
('MED-AMB-VENT','ZOLL'),
('MED-AMB-VENT','PHILIPS-H'),
('MED-AMB-VENT','STRYKER'),
('MED-AMB-VENT','SCHILLER'),
('MED-AMB-VENT','HAMILTON'),
('MED-AMB-SUCTION','ZOLL'),
('MED-AMB-SUCTION','PHILIPS-H'),
('MED-AMB-SUCTION','STRYKER'),
('MED-AMB-SUCTION','SCHILLER'),
('MED-AMB-SUCTION','HAMILTON'),
('MED-AMB-STRETCHER','ZOLL'),
('MED-AMB-STRETCHER','PHILIPS-H'),
('MED-AMB-STRETCHER','STRYKER'),
('MED-AMB-STRETCHER','SCHILLER'),
('MED-AMB-STRETCHER','HAMILTON'),
('MED-AMB-DEFIB','ZOLL'),
('MED-AMB-DEFIB','PHILIPS-H'),
('MED-AMB-DEFIB','STRYKER'),
('MED-AMB-DEFIB','SCHILLER'),
('MED-AMB-DEFIB','HAMILTON')
)
insert into public.bf_med_master_options(asset_type_id,manufacturer_id,model_family,status)
select t.id,m.id,null,'active'
from x
join public.bf_med_master_types t on t.code=x.asset_code
join public.bf_med_manufacturers m on m.code=x.manufacturer_code
where not exists(
 select 1 from public.bf_med_master_options o
 where o.asset_type_id=t.id
   and o.manufacturer_id=m.id
   and o.model_family is null
);

-- Ensure every active medical device class has a baseline PM template.
insert into public.bf_med_master_pm_templates(
 asset_type_id,title_ar,title_en,interval_months,calibration_required,
 reference,status,source_type,source_name,required_skill,required_personnel,
 required_tools,required_test_equipment,required_ppe,required_consumables,
 prerequisites,shutdown_required,frequency_basis,interval_value,interval_unit,
 procedure_priority
)
select
 t.id,
 'الصيانة الوقائية - '||t.name_ar,
 'Preventive Maintenance - '||t.name_en,
 coalesce(t.default_pm_months,12),
 case when t.default_calibration_months is not null then true else false end,
 'Generic biomedical baseline. Supersede with verified OEM/vendor procedure before clinical service where required.',
 'active','generic','Basmat Medical Generic Baseline',
 'Biomedical Engineer / Biomedical Technician',1,
 'Approved biomedical service tools appropriate to the device',
 'Approved biomedical test equipment appropriate to the device and service scope',
 'Hospital PPE and infection-control PPE as applicable',
 'OEM-approved consumables/parts where applicable',
 'Remove device from clinical use. Review device history, OEM service manual, hospital biomedical procedure, infection-control requirements and calibration status before maintenance.',
 true,'calendar',coalesce(t.default_pm_months,12),'month',10
from public.bf_med_master_types t
where t.status='active'
and not exists(
 select 1 from public.bf_med_master_pm_templates p
 where p.asset_type_id=t.id and p.status='active'
);

-- Add a six-step executable baseline to any medical template without steps.
insert into public.bf_med_master_pm_steps(
 template_id,seq,title_ar,title_en,instructions_ar,instructions_en,
 response_type,safety_notes,task_type,required,acceptance_text,photo_required,
 tools,materials,failure_action,escalation_role,hold_point,reference
)
select p.id,s.seq,s.ar,s.en,s.iar,s.ien,s.resp,s.safety,s.task,true,s.acceptance,s.photo,
 s.tools,s.materials,s.failure,s.escalation,s.hold,'Generic biomedical baseline'
from public.bf_med_master_pm_templates p
cross join lateral (values
 (1,'التحقق من الهوية والسلامة','Identification and safety verification',
  'تحقق من رقم الأصل والموديل والرقم التسلسلي وحالة الخدمة والملصقات والتنبيهات قبل البدء.',
  'Verify asset tag, model, serial number, service status, labels and alerts before starting.',
  'pass_fail',
  'Qualified biomedical personnel only. Remove the device from patient use before service unless the approved procedure explicitly permits otherwise.',
  'safety',
  'Correct device identity confirmed and no uncontrolled safety condition exists.',
  true,
  'PPE and lockout/isolation tools where applicable',
  null,
  'Stop work and quarantine/escalate if device identity or safety status is uncertain.',
  'Biomedical Supervisor',
  true),
 (2,'الفحص البصري والميكانيكي','Visual and mechanical inspection',
  'افحص الهيكل والكابلات والموصلات والأجزاء المتحركة والملحقات والبطاريات بحثاً عن تلف أو تآكل أو تلوث.',
  'Inspect enclosure, cables, connectors, moving parts, accessories and batteries for damage, wear or contamination.',
  'pass_fail',
  'Follow infection-control and electrical/mechanical safety precautions.',
  'inspection',
  'No unaddressed physical defect that can affect safe operation.',
  true,
  'Inspection tools',
  'Approved cleaning consumables as applicable',
  'Document defect, keep out of service if unsafe, and raise corrective action.',
  'Biomedical Supervisor',
  false),
 (3,'فحص الطاقة والسلامة الكهربائية','Power and electrical safety check',
  'تحقق من مصدر الطاقة والبطارية والتأريض والحماية الكهربائية واختبار السلامة الكهربائية عند انطباقه.',
  'Verify power source, battery, grounding and electrical protection; perform electrical safety testing when applicable.',
  'pass_fail',
  'Use approved electrical safety analyzer and OEM/hospital procedure when testing is required.',
  'test',
  'Electrical safety requirements meet the approved OEM/hospital standard.',
  false,
  'Electrical safety analyzer where applicable',
  null,
  'Fail the step and remove from service when electrical safety is outside approved limits.',
  'Biomedical Supervisor',
  true),
 (4,'اختبار الأداء الوظيفي','Functional performance verification',
  'نفذ اختبار الأداء المعتمد واختبر الإنذارات والحساسات والوظائف الرئيسية بدون استخدام سريري على مريض.',
  'Perform approved functional verification including alarms, sensors and key functions without patient use.',
  'text',
  'Do not bypass safety interlocks or simulate clinical use outside the approved service method.',
  'test',
  'All required functions and alarms meet the approved service criteria.',
  false,
  'Device-specific simulator/test equipment',
  null,
  'Record failed function, quarantine when clinically unsafe, and escalate for repair/OEM support.',
  'Biomedical Supervisor',
  true),
 (5,'المعايرة والقياسات','Calibration and measurement verification',
  'تحقق من حالة المعايرة وسجل القراءات المطلوبة وحدد ما إذا كانت المعايرة مستحقة أو تحتاج جهة مخولة.',
  'Verify calibration status, record required measurements and determine whether calibration or authorized service is due.',
  'text',
  'Calibration must follow approved traceable procedure and qualified scope.',
  'test',
  'Measurements are within the approved OEM/calibration tolerance or are formally escalated.',
  false,
  'Traceable calibration/test equipment appropriate to the device',
  null,
  'Do not release to clinical service when calibration is expired or outside tolerance.',
  'Biomedical Supervisor',
  true),
 (6,'التوثيق وإعادة الجهاز للخدمة','Documentation and return-to-service decision',
  'سجل النتائج والصور والقطع المستبدلة والقراءات والشهادة وملاحظات السلامة وحدد حالة الجهاز بعد الصيانة.',
  'Record results, evidence, replaced parts, readings, certificate and safety findings, then document the return-to-service decision.',
  'text',
  'Only authorized biomedical personnel may release the device to clinical service according to hospital policy.',
  'inspection',
  'All mandatory evidence is recorded and return-to-service status is explicitly documented.',
  true,
  'Documentation tools',
  null,
  'Keep device out of service until all mandatory failures are resolved and approved.',
  'Biomedical Supervisor',
  true)
) as s(seq,ar,en,iar,ien,resp,safety,task,acceptance,photo,tools,materials,failure,escalation,hold)
where p.status='active'
and not exists(
 select 1 from public.bf_med_master_pm_steps z where z.template_id=p.id
)
on conflict(template_id,seq) do nothing;

-- Coverage summary for medical master library.
drop view if exists public.bf_medical_library_summary;
create view public.bf_medical_library_summary
with (security_invoker=true)
as
select
 t.system_code,
 count(*) as device_types,
 count(*) filter(where t.procurement_class='long_lead') as long_lead_types,
 count(*) filter(where t.default_criticality='critical') as critical_types,
 count(distinct p.id) filter(where p.status='active') as active_templates,
 count(distinct p.id) filter(where p.status='active' and p.source_type in('oem','vendor','contract','regulatory')) as verified_source_templates,
 count(distinct s.id) as maintenance_steps
from public.bf_med_master_types t
left join public.bf_med_master_pm_templates p on p.asset_type_id=t.id and p.status='active'
left join public.bf_med_master_pm_steps s on s.template_id=p.id
where t.status='active'
group by t.system_code
order by t.system_code;

grant select on public.bf_medical_library_summary to authenticated;

notify pgrst,'reload schema';
commit;
