begin;

alter table public.bf_master_asset_types add column if not exists procurement_class text not null default 'standard';
alter table public.bf_master_asset_types add column if not exists default_lead_time_days integer;
alter table public.bf_master_asset_types add column if not exists critical_spare boolean not null default false;
alter table public.bf_master_asset_types add column if not exists stock_strategy text;

do $$ begin
 if not exists(
  select 1 from pg_constraint where conname='bf_master_asset_procurement_class_chk'
 ) then
  alter table public.bf_master_asset_types
   add constraint bf_master_asset_procurement_class_chk
   check(procurement_class in('standard','long_lead','special_order'));
 end if;
end $$;


insert into public.bf_master_asset_types(
 system_code,code,name_ar,name_en,default_criticality,expected_life_years,icon_text,
 procurement_class,default_lead_time_days,critical_spare
)
values
('TELEPHONY','TEL-IP-PBX','سنترال IP / IP PBX','IP PBX / Unified Communications Core','critical',10,'☎️','long_lead',90,true),
('TELEPHONY','TEL-CALL-MANAGER','خادم إدارة المكالمات','Call Manager / Communications Manager','critical',8,'🖥️','long_lead',75,true),
('TELEPHONY','TEL-VOICE-GW','بوابة صوت','Voice Gateway','high',10,'🔌','standard',45,true),
('TELEPHONY','TEL-SBC','متحكم حدود الجلسات SBC','Session Border Controller','critical',8,'🛡️','long_lead',75,true),
('TELEPHONY','TEL-IP-PHONE','هاتف IP','IP Desk Phone','medium',7,'☎️','standard',30,false),
('TELEPHONY','TEL-CONF-PHONE','هاتف مؤتمرات','Conference Phone','medium',7,'🎙️','standard',30,false),
('TELEPHONY','TEL-ANALOG-GW','بوابة هواتف تناظرية','Analog Voice Gateway','high',10,'🔌','standard',45,true),
('TELEPHONY','TEL-VOICEMAIL','خادم بريد صوتي','Voicemail / Messaging Server','high',8,'📨','long_lead',60,true),
('TELEPHONY','TEL-RECORDER','مسجل مكالمات','Call Recording System','high',8,'🎙️','long_lead',60,true),
('TELEPHONY','TEL-ATTENDANT','كونسول مشغل السنترال','Attendant Console','medium',7,'🎧','standard',30,false),
('TELEPHONY','TEL-DECT','نظام DECT','DECT Cordless Telephony System','high',10,'📞','standard',45,true),
('TELEPHONY','TEL-FAX-GW','بوابة فاكس','Fax Gateway','medium',8,'📠','standard',30,false),
('UC_AV','UC-VIDEO-CODEC','نظام مؤتمرات مرئية','Video Conference Codec / Room System','high',7,'🎥','standard',45,true),
('UC_AV','UC-DSP','معالج صوت DSP','Audio DSP','high',10,'🎚️','standard',45,true),
('UC_AV','UC-CONTROL','معالج تحكم قاعات','AV Control Processor','high',10,'🎛️','standard',45,true),
('UC_AV','UC-WIRELESS-PRESENT','نظام عرض لاسلكي','Wireless Presentation System','medium',7,'📺','standard',30,false),
('UC_AV','UC-DISPLAY','شاشة عرض احترافية','Professional Display','medium',7,'🖥️','standard',30,false),
('UC_AV','UC-PROJECTOR','بروجكتور','Projector','medium',7,'📽️','standard',30,false),
('UC_AV','UC-MIC-SYSTEM','نظام ميكروفونات مؤتمرات','Conference Microphone System','medium',8,'🎤','standard',30,false),
('RADIO','RADIO-HANDHELD','جهاز لاسلكي محمول','Handheld Two-Way Radio','high',7,'📻','standard',45,true),
('RADIO','RADIO-MOBILE','جهاز لاسلكي مركبة','Mobile Two-Way Radio','high',8,'🚙','standard',45,true),
('RADIO','RADIO-BASE','محطة لاسلكي ثابتة','Radio Base Station','critical',12,'📡','long_lead',90,true),
('RADIO','RADIO-REPEATER','مكرر لاسلكي','Radio Repeater','critical',12,'📡','long_lead',90,true),
('RADIO','RADIO-DISPATCH','كونسول تحكم لاسلكي','Radio Dispatch Console','critical',10,'🎧','long_lead',75,true),
('RADIO','RADIO-ANTENNA','هوائي اتصالات لاسلكية','Radio Antenna','high',15,'📡','standard',45,true),
('RADIO','RADIO-COMBINE','مجمّع/مقسم RF','RF Combiner / Multicoupler','high',12,'🔀','long_lead',75,true),
('RADIO','RADIO-TETRA','نظام TETRA','TETRA Radio System','critical',15,'📡','long_lead',120,true),
('RADIO','RADIO-DMR','نظام DMR','DMR Radio System','critical',12,'📡','long_lead',90,true),
('RADIO','RADIO-PTT','منصة Push-to-Talk','Push-to-Talk Platform','high',8,'🎙️','long_lead',60,true),
('WIRELESS','WLS-P2P','وصلة لاسلكية Point-to-Point','Point-to-Point Wireless Link','critical',10,'📡','long_lead',60,true),
('WIRELESS','WLS-P2MP','وصلة Point-to-Multipoint','Point-to-Multipoint Wireless System','high',10,'📡','long_lead',60,true),
('WIRELESS','WLS-MICROWAVE','وصلة مايكروويف','Microwave Radio Link','critical',15,'📡','long_lead',120,true),
('WIRELESS','WLS-OUTDOOR-AP','نقطة وصول خارجية','Outdoor Wireless Access Point','high',8,'📶','standard',45,true),
('WIRELESS','WLS-MESH','شبكة Mesh لاسلكية','Wireless Mesh Node','high',8,'📶','standard',45,true),
('WIRELESS','WLS-PRIVATE-LTE','شبكة LTE خاصة','Private LTE System','critical',10,'📶','long_lead',120,true),
('WIRELESS','WLS-PRIVATE-5G','شبكة 5G خاصة','Private 5G System','critical',10,'📶','long_lead',150,true),
('WIRELESS','WLS-SMALL-CELL','خلية صغيرة','Small Cell','critical',10,'📡','long_lead',120,true),
('WIRELESS','WLS-SAT-TERM','طرفية اتصالات ساتلية','Satellite Communications Terminal','critical',12,'🛰️','long_lead',120,true),
('DAS','DAS-HEADEND','هيد إند DAS','DAS Headend','critical',12,'📡','long_lead',120,true),
('DAS','DAS-MASTER','وحدة رئيسية DAS','DAS Master Unit','critical',12,'📡','long_lead',120,true),
('DAS','DAS-REMOTE','وحدة بعيدة DAS','DAS Remote Unit','high',10,'📡','long_lead',90,true),
('DAS','DAS-BDA','مضخم ثنائي الاتجاه BDA','Bi-Directional Amplifier','critical',10,'📶','long_lead',90,true),
('DAS','DAS-ANTENNA','هوائي DAS داخلي','Indoor DAS Antenna','high',15,'📡','standard',45,false),
('DAS','DAS-SPLITTER','مقسم/تاب RF','RF Splitter / Tapper','medium',15,'🔀','standard',45,false),
('PAGA','PAGA-CONTROLLER','كنترولر PAGA','PAGA Controller','critical',12,'📢','long_lead',90,true),
('PAGA','PAGA-AMPLIFIER','مضخم PAGA','PAGA Power Amplifier','critical',10,'🔊','long_lead',75,true),
('PAGA','PAGA-CALL-STATION','محطة نداء PAGA','PAGA Call Station','high',10,'🎙️','standard',45,true),
('PAGA','PAGA-HORN','سماعة هورن','Horn Loudspeaker','high',15,'📣','standard',45,true),
('STRUCTURED_CABLING','CAB-FIBER-ODF','لوحة توزيع ألياف ODF','Fiber ODF / Patch Panel','high',20,'🧵','standard',45,true),
('STRUCTURED_CABLING','CAB-COPPER-PANEL','باتش بانل نحاس','Copper Patch Panel','medium',20,'🔗','standard',30,false),
('STRUCTURED_CABLING','CAB-FIBER-BACKBONE','مسار ألياف رئيسي','Fiber Backbone Link','critical',20,'🧵','long_lead',60,true),
('STRUCTURED_CABLING','CAB-COPPER-HORIZONTAL','تمديدات نحاس أفقية','Horizontal Copper Cabling','medium',20,'🔗','standard',30,false),
('STRUCTURED_CABLING','CAB-FIBERGUIDE','مسار FiberGuide','Fiber Raceway / FiberGuide','high',20,'🟨','standard',60,true),
('STRUCTURED_CABLING','CAB-LADDER','سلم كابلات','Cable Ladder / Tray','medium',25,'🪜','standard',45,false),
('CLOCK_PAGING','CLOCK-MASTER','ساعة مركزية رئيسية','Master Clock Controller','high',12,'🕒','long_lead',60,true),
('CLOCK_PAGING','CLOCK-SLAVE','ساعة فرعية','Slave Clock','medium',12,'🕒','standard',30,false),
('LONG_LEAD_COMPONENT','LLI-CHILLER-COMP','كمبروسر شيلر رئيسي','Chiller Compressor','critical',15,'🧊','long_lead',180,true),
('LONG_LEAD_COMPONENT','LLI-CHILLER-CONTROL','لوحة تحكم شيلر','Chiller Control Board / Panel','critical',10,'🎛️','long_lead',120,true),
('LONG_LEAD_COMPONENT','LLI-TRANSFORMER','محول قدرة احتياطي/استبدال','Replacement Power Transformer','critical',30,'🔋','long_lead',240,true),
('LONG_LEAD_COMPONENT','LLI-MV-BREAKER','قاطع جهد متوسط','MV Circuit Breaker','critical',20,'⚡','long_lead',180,true),
('LONG_LEAD_COMPONENT','LLI-ACB','قاطع ACB رئيسي','Main ACB','critical',20,'⚡','long_lead',120,true),
('LONG_LEAD_COMPONENT','LLI-GEN-ALTERNATOR','ألترنيتر مولد','Generator Alternator','critical',15,'⚙️','long_lead',150,true),
('LONG_LEAD_COMPONENT','LLI-GEN-CONTROLLER','كنترولر مولد','Generator Controller','critical',10,'🎛️','long_lead',90,true),
('LONG_LEAD_COMPONENT','LLI-UPS-POWER-MOD','موديول قدرة UPS','UPS Power Module','critical',10,'🔋','long_lead',120,true),
('LONG_LEAD_COMPONENT','LLI-ELEV-DRIVE','درايف مصعد','Elevator Drive / VVVF','critical',12,'🛗','long_lead',120,true),
('LONG_LEAD_COMPONENT','LLI-ELEV-CONTROLLER','كنترولر مصعد','Elevator Controller','critical',15,'🛗','long_lead',150,true),
('LONG_LEAD_COMPONENT','LLI-FIRE-PANEL','لوحة إنذار حريق رئيسية','Main Fire Alarm Control Panel','critical',15,'🚨','long_lead',120,true),
('LONG_LEAD_COMPONENT','LLI-BMS-CONTROLLER','كنترولر BMS رئيسي','Critical BMS Controller','critical',12,'🎛️','long_lead',90,true),
('LONG_LEAD_COMPONENT','LLI-CRAC-COMP','كمبروسر CRAC','CRAC Compressor','critical',12,'❄️','long_lead',120,true)
on conflict(code) do update set
 system_code=excluded.system_code,
 name_ar=excluded.name_ar,
 name_en=excluded.name_en,
 default_criticality=excluded.default_criticality,
 expected_life_years=excluded.expected_life_years,
 icon_text=excluded.icon_text,
 procurement_class=excluded.procurement_class,
 default_lead_time_days=excluded.default_lead_time_days,
 critical_spare=excluded.critical_spare,
 status='active';


insert into public.bf_master_manufacturers(code,name,short_name)
values
('AVAYA','Avaya','Avaya'),
('CISCO-UC','Cisco Collaboration','Cisco'),
('MITEL','Mitel','Mitel'),
('ALE','Alcatel-Lucent Enterprise','Alcatel-Luce'),
('YEALINK','Yealink','Yealink'),
('POLY','HP Poly','HP'),
('GRANDSTREAM','Grandstream','Grandstream'),
('NEC-UC','NEC Unified Communications','NEC'),
('MOTOROLA','Motorola Solutions','Motorola'),
('HYTERA','Hytera','Hytera'),
('KENWOOD','JVCKENWOOD','JVCKENWOOD'),
('ICOM','Icom','Icom'),
('SEPURA','Sepura','Sepura'),
('TAIT','Tait Communications','Tait'),
('ERICSSON','Ericsson','Ericsson'),
('NOKIA','Nokia','Nokia'),
('CAMBIUM','Cambium Networks','Cambium'),
('UBIQUITI','Ubiquiti','Ubiquiti'),
('AVIAT','Aviat Networks','Aviat'),
('CERAGON','Ceragon Networks','Ceragon'),
('COMMSCOPE-ANDREW','CommScope / Andrew','CommScope'),
('JMA','JMA Wireless','JMA'),
('SOLID','SOLiD','SOLiD'),
('CORNING','Corning','Corning'),
('ROSENBERGER','Rosenberger','Rosenberger'),
('RFS','Radio Frequency Systems','Radio'),
('CRESTRON','Crestron','Crestron'),
('QSC','Q-SYS / QSC','Q-SYS'),
('BIAMP','Biamp','Biamp'),
('SHURE','Shure','Shure'),
('SENNHEISER','Sennheiser','Sennheiser'),
('EXTRON','Extron','Extron'),
('BARCO','Barco','Barco'),
('BOSCH-PA','Bosch Public Address','Bosch'),
('TOA','TOA','TOA'),
('COMMEND','Commend','Commend'),
('ZENITEL','Zenitel','Zenitel')
on conflict(code) do update set name=excluded.name,short_name=excluded.short_name,status='active';


with x(asset_code,manufacturer_code,model_family) as (values
('TEL-IP-PBX','AVAYA',null),
('TEL-IP-PBX','CISCO-UC',null),
('TEL-IP-PBX','MITEL',null),
('TEL-IP-PBX','ALE',null),
('TEL-IP-PBX','NEC-UC',null),
('TEL-CALL-MANAGER','AVAYA',null),
('TEL-CALL-MANAGER','CISCO-UC',null),
('TEL-CALL-MANAGER','MITEL',null),
('TEL-CALL-MANAGER','ALE',null),
('TEL-VOICE-GW','AVAYA',null),
('TEL-VOICE-GW','CISCO-UC',null),
('TEL-VOICE-GW','MITEL',null),
('TEL-VOICE-GW','ALE',null),
('TEL-VOICE-GW','YEALINK',null),
('TEL-VOICE-GW','POLY',null),
('TEL-VOICE-GW','GRANDSTREAM',null),
('TEL-VOICE-GW','NEC-UC',null),
('TEL-SBC','AVAYA',null),
('TEL-SBC','CISCO-UC',null),
('TEL-SBC','MITEL',null),
('TEL-IP-PHONE','AVAYA',null),
('TEL-IP-PHONE','CISCO-UC',null),
('TEL-IP-PHONE','YEALINK',null),
('TEL-IP-PHONE','POLY',null),
('TEL-IP-PHONE','GRANDSTREAM',null),
('TEL-IP-PHONE','MITEL',null),
('TEL-IP-PHONE','ALE',null),
('TEL-CONF-PHONE','AVAYA',null),
('TEL-CONF-PHONE','CISCO-UC',null),
('TEL-CONF-PHONE','MITEL',null),
('TEL-CONF-PHONE','ALE',null),
('TEL-CONF-PHONE','YEALINK',null),
('TEL-CONF-PHONE','POLY',null),
('TEL-CONF-PHONE','GRANDSTREAM',null),
('TEL-CONF-PHONE','NEC-UC',null),
('TEL-ANALOG-GW','AVAYA',null),
('TEL-ANALOG-GW','CISCO-UC',null),
('TEL-ANALOG-GW','MITEL',null),
('TEL-ANALOG-GW','ALE',null),
('TEL-ANALOG-GW','YEALINK',null),
('TEL-ANALOG-GW','POLY',null),
('TEL-ANALOG-GW','GRANDSTREAM',null),
('TEL-ANALOG-GW','NEC-UC',null),
('TEL-VOICEMAIL','AVAYA',null),
('TEL-VOICEMAIL','CISCO-UC',null),
('TEL-VOICEMAIL','MITEL',null),
('TEL-VOICEMAIL','ALE',null),
('TEL-VOICEMAIL','YEALINK',null),
('TEL-VOICEMAIL','POLY',null),
('TEL-VOICEMAIL','GRANDSTREAM',null),
('TEL-VOICEMAIL','NEC-UC',null),
('TEL-RECORDER','AVAYA',null),
('TEL-RECORDER','CISCO-UC',null),
('TEL-RECORDER','MITEL',null),
('TEL-RECORDER','ALE',null),
('TEL-RECORDER','YEALINK',null),
('TEL-RECORDER','POLY',null),
('TEL-RECORDER','GRANDSTREAM',null),
('TEL-RECORDER','NEC-UC',null),
('TEL-ATTENDANT','AVAYA',null),
('TEL-ATTENDANT','CISCO-UC',null),
('TEL-ATTENDANT','MITEL',null),
('TEL-ATTENDANT','ALE',null),
('TEL-ATTENDANT','YEALINK',null),
('TEL-ATTENDANT','POLY',null),
('TEL-ATTENDANT','GRANDSTREAM',null),
('TEL-ATTENDANT','NEC-UC',null),
('TEL-DECT','AVAYA',null),
('TEL-DECT','CISCO-UC',null),
('TEL-DECT','MITEL',null),
('TEL-DECT','ALE',null),
('TEL-DECT','YEALINK',null),
('TEL-DECT','POLY',null),
('TEL-DECT','GRANDSTREAM',null),
('TEL-DECT','NEC-UC',null),
('TEL-FAX-GW','AVAYA',null),
('TEL-FAX-GW','CISCO-UC',null),
('TEL-FAX-GW','MITEL',null),
('TEL-FAX-GW','ALE',null),
('TEL-FAX-GW','YEALINK',null),
('TEL-FAX-GW','POLY',null),
('TEL-FAX-GW','GRANDSTREAM',null),
('TEL-FAX-GW','NEC-UC',null),
('UC-VIDEO-CODEC','CISCO-UC',null),
('UC-VIDEO-CODEC','POLY',null),
('UC-VIDEO-CODEC','CRESTRON',null),
('UC-DSP','CISCO-UC',null),
('UC-DSP','CRESTRON',null),
('UC-DSP','QSC',null),
('UC-DSP','BIAMP',null),
('UC-DSP','SHURE',null),
('UC-DSP','SENNHEISER',null),
('UC-DSP','EXTRON',null),
('UC-DSP','BARCO',null),
('UC-DSP','POLY',null),
('UC-CONTROL','CISCO-UC',null),
('UC-CONTROL','CRESTRON',null),
('UC-CONTROL','QSC',null),
('UC-CONTROL','BIAMP',null),
('UC-CONTROL','SHURE',null),
('UC-CONTROL','SENNHEISER',null),
('UC-CONTROL','EXTRON',null),
('UC-CONTROL','BARCO',null),
('UC-CONTROL','POLY',null),
('UC-WIRELESS-PRESENT','CISCO-UC',null),
('UC-WIRELESS-PRESENT','CRESTRON',null),
('UC-WIRELESS-PRESENT','QSC',null),
('UC-WIRELESS-PRESENT','BIAMP',null),
('UC-WIRELESS-PRESENT','SHURE',null),
('UC-WIRELESS-PRESENT','SENNHEISER',null),
('UC-WIRELESS-PRESENT','EXTRON',null),
('UC-WIRELESS-PRESENT','BARCO',null),
('UC-WIRELESS-PRESENT','POLY',null),
('UC-DISPLAY','CISCO-UC',null),
('UC-DISPLAY','CRESTRON',null),
('UC-DISPLAY','QSC',null),
('UC-DISPLAY','BIAMP',null),
('UC-DISPLAY','SHURE',null),
('UC-DISPLAY','SENNHEISER',null),
('UC-DISPLAY','EXTRON',null),
('UC-DISPLAY','BARCO',null),
('UC-DISPLAY','POLY',null),
('UC-PROJECTOR','CISCO-UC',null),
('UC-PROJECTOR','CRESTRON',null),
('UC-PROJECTOR','QSC',null),
('UC-PROJECTOR','BIAMP',null),
('UC-PROJECTOR','SHURE',null),
('UC-PROJECTOR','SENNHEISER',null),
('UC-PROJECTOR','EXTRON',null),
('UC-PROJECTOR','BARCO',null),
('UC-PROJECTOR','POLY',null),
('UC-MIC-SYSTEM','CISCO-UC',null),
('UC-MIC-SYSTEM','CRESTRON',null),
('UC-MIC-SYSTEM','QSC',null),
('UC-MIC-SYSTEM','BIAMP',null),
('UC-MIC-SYSTEM','SHURE',null),
('UC-MIC-SYSTEM','SENNHEISER',null),
('UC-MIC-SYSTEM','EXTRON',null),
('UC-MIC-SYSTEM','BARCO',null),
('UC-MIC-SYSTEM','POLY',null),
('RADIO-HANDHELD','MOTOROLA',null),
('RADIO-HANDHELD','HYTERA',null),
('RADIO-HANDHELD','KENWOOD',null),
('RADIO-HANDHELD','ICOM',null),
('RADIO-HANDHELD','SEPURA',null),
('RADIO-HANDHELD','TAIT',null),
('RADIO-MOBILE','MOTOROLA',null),
('RADIO-MOBILE','HYTERA',null),
('RADIO-MOBILE','KENWOOD',null),
('RADIO-MOBILE','ICOM',null),
('RADIO-MOBILE','SEPURA',null),
('RADIO-MOBILE','TAIT',null),
('RADIO-BASE','MOTOROLA',null),
('RADIO-BASE','HYTERA',null),
('RADIO-BASE','KENWOOD',null),
('RADIO-BASE','ICOM',null),
('RADIO-BASE','SEPURA',null),
('RADIO-BASE','TAIT',null),
('RADIO-REPEATER','MOTOROLA',null),
('RADIO-REPEATER','HYTERA',null),
('RADIO-REPEATER','KENWOOD',null),
('RADIO-REPEATER','ICOM',null),
('RADIO-REPEATER','SEPURA',null),
('RADIO-REPEATER','TAIT',null),
('RADIO-DISPATCH','MOTOROLA',null),
('RADIO-DISPATCH','HYTERA',null),
('RADIO-DISPATCH','KENWOOD',null),
('RADIO-DISPATCH','ICOM',null),
('RADIO-DISPATCH','SEPURA',null),
('RADIO-DISPATCH','TAIT',null),
('RADIO-ANTENNA','MOTOROLA',null),
('RADIO-ANTENNA','HYTERA',null),
('RADIO-ANTENNA','KENWOOD',null),
('RADIO-ANTENNA','ICOM',null),
('RADIO-ANTENNA','SEPURA',null),
('RADIO-ANTENNA','TAIT',null),
('RADIO-COMBINE','MOTOROLA',null),
('RADIO-COMBINE','HYTERA',null),
('RADIO-COMBINE','KENWOOD',null),
('RADIO-COMBINE','ICOM',null),
('RADIO-COMBINE','SEPURA',null),
('RADIO-COMBINE','TAIT',null),
('RADIO-TETRA','MOTOROLA',null),
('RADIO-TETRA','SEPURA',null),
('RADIO-TETRA','HYTERA',null),
('RADIO-DMR','MOTOROLA',null),
('RADIO-DMR','HYTERA',null),
('RADIO-DMR','KENWOOD',null),
('RADIO-DMR','TAIT',null),
('RADIO-PTT','MOTOROLA',null),
('RADIO-PTT','HYTERA',null),
('RADIO-PTT','KENWOOD',null),
('RADIO-PTT','ICOM',null),
('RADIO-PTT','SEPURA',null),
('RADIO-PTT','TAIT',null),
('WLS-P2P','CISCO',null),
('WLS-P2P','ARUBA',null),
('WLS-P2P','CAMBIUM',null),
('WLS-P2P','UBIQUITI',null),
('WLS-P2P','AVIAT',null),
('WLS-P2P','CERAGON',null),
('WLS-P2P','ERICSSON',null),
('WLS-P2P','NOKIA',null),
('WLS-P2P','HUAWEI',null),
('WLS-P2MP','CISCO',null),
('WLS-P2MP','ARUBA',null),
('WLS-P2MP','CAMBIUM',null),
('WLS-P2MP','UBIQUITI',null),
('WLS-P2MP','AVIAT',null),
('WLS-P2MP','CERAGON',null),
('WLS-P2MP','ERICSSON',null),
('WLS-P2MP','NOKIA',null),
('WLS-P2MP','HUAWEI',null),
('WLS-MICROWAVE','AVIAT',null),
('WLS-MICROWAVE','CERAGON',null),
('WLS-MICROWAVE','ERICSSON',null),
('WLS-MICROWAVE','NOKIA',null),
('WLS-MICROWAVE','HUAWEI',null),
('WLS-OUTDOOR-AP','CISCO',null),
('WLS-OUTDOOR-AP','ARUBA',null),
('WLS-OUTDOOR-AP','CAMBIUM',null),
('WLS-OUTDOOR-AP','UBIQUITI',null),
('WLS-OUTDOOR-AP','AVIAT',null),
('WLS-OUTDOOR-AP','CERAGON',null),
('WLS-OUTDOOR-AP','ERICSSON',null),
('WLS-OUTDOOR-AP','NOKIA',null),
('WLS-OUTDOOR-AP','HUAWEI',null),
('WLS-MESH','CISCO',null),
('WLS-MESH','ARUBA',null),
('WLS-MESH','CAMBIUM',null),
('WLS-MESH','UBIQUITI',null),
('WLS-MESH','AVIAT',null),
('WLS-MESH','CERAGON',null),
('WLS-MESH','ERICSSON',null),
('WLS-MESH','NOKIA',null),
('WLS-MESH','HUAWEI',null),
('WLS-PRIVATE-LTE','ERICSSON',null),
('WLS-PRIVATE-LTE','NOKIA',null),
('WLS-PRIVATE-LTE','HUAWEI',null),
('WLS-PRIVATE-5G','ERICSSON',null),
('WLS-PRIVATE-5G','NOKIA',null),
('WLS-PRIVATE-5G','HUAWEI',null),
('WLS-SMALL-CELL','CISCO',null),
('WLS-SMALL-CELL','ARUBA',null),
('WLS-SMALL-CELL','CAMBIUM',null),
('WLS-SMALL-CELL','UBIQUITI',null),
('WLS-SMALL-CELL','AVIAT',null),
('WLS-SMALL-CELL','CERAGON',null),
('WLS-SMALL-CELL','ERICSSON',null),
('WLS-SMALL-CELL','NOKIA',null),
('WLS-SMALL-CELL','HUAWEI',null),
('WLS-SAT-TERM','CISCO',null),
('WLS-SAT-TERM','ARUBA',null),
('WLS-SAT-TERM','CAMBIUM',null),
('WLS-SAT-TERM','UBIQUITI',null),
('WLS-SAT-TERM','AVIAT',null),
('WLS-SAT-TERM','CERAGON',null),
('WLS-SAT-TERM','ERICSSON',null),
('WLS-SAT-TERM','NOKIA',null),
('WLS-SAT-TERM','HUAWEI',null),
('DAS-HEADEND','COMMSCOPE-ANDREW',null),
('DAS-HEADEND','JMA',null),
('DAS-HEADEND','SOLID',null),
('DAS-HEADEND','CORNING',null),
('DAS-MASTER','COMMSCOPE-ANDREW',null),
('DAS-MASTER','JMA',null),
('DAS-MASTER','SOLID',null),
('DAS-MASTER','CORNING',null),
('DAS-MASTER','ROSENBERGER',null),
('DAS-MASTER','RFS',null),
('DAS-REMOTE','COMMSCOPE-ANDREW',null),
('DAS-REMOTE','JMA',null),
('DAS-REMOTE','SOLID',null),
('DAS-REMOTE','CORNING',null),
('DAS-REMOTE','ROSENBERGER',null),
('DAS-REMOTE','RFS',null),
('DAS-BDA','COMMSCOPE-ANDREW',null),
('DAS-BDA','JMA',null),
('DAS-BDA','SOLID',null),
('DAS-ANTENNA','COMMSCOPE-ANDREW',null),
('DAS-ANTENNA','JMA',null),
('DAS-ANTENNA','SOLID',null),
('DAS-ANTENNA','CORNING',null),
('DAS-ANTENNA','ROSENBERGER',null),
('DAS-ANTENNA','RFS',null),
('DAS-SPLITTER','COMMSCOPE-ANDREW',null),
('DAS-SPLITTER','JMA',null),
('DAS-SPLITTER','SOLID',null),
('DAS-SPLITTER','CORNING',null),
('DAS-SPLITTER','ROSENBERGER',null),
('DAS-SPLITTER','RFS',null),
('PAGA-CONTROLLER','BOSCH-PA',null),
('PAGA-CONTROLLER','TOA',null),
('PAGA-CONTROLLER','COMMEND',null),
('PAGA-CONTROLLER','ZENITEL',null),
('PAGA-AMPLIFIER','BOSCH-PA',null),
('PAGA-AMPLIFIER','TOA',null),
('PAGA-AMPLIFIER','COMMEND',null),
('PAGA-AMPLIFIER','ZENITEL',null),
('PAGA-AMPLIFIER','HONEYWELL',null),
('PAGA-CALL-STATION','BOSCH-PA',null),
('PAGA-CALL-STATION','TOA',null),
('PAGA-CALL-STATION','COMMEND',null),
('PAGA-CALL-STATION','ZENITEL',null),
('PAGA-CALL-STATION','HONEYWELL',null),
('PAGA-HORN','BOSCH-PA',null),
('PAGA-HORN','TOA',null),
('PAGA-HORN','COMMEND',null),
('PAGA-HORN','ZENITEL',null),
('PAGA-HORN','HONEYWELL',null),
('CAB-FIBER-ODF','COMMSCOPE',null),
('CAB-FIBER-ODF','PANDUIT',null),
('CAB-FIBER-ODF','CORNING',null),
('CAB-FIBER-ODF','LEGRAND',null),
('CAB-FIBER-ODF','ROSENBERGER',null),
('CAB-COPPER-PANEL','COMMSCOPE',null),
('CAB-COPPER-PANEL','PANDUIT',null),
('CAB-COPPER-PANEL','CORNING',null),
('CAB-COPPER-PANEL','LEGRAND',null),
('CAB-COPPER-PANEL','ROSENBERGER',null),
('CAB-FIBER-BACKBONE','COMMSCOPE',null),
('CAB-FIBER-BACKBONE','CORNING',null),
('CAB-FIBER-BACKBONE','PANDUIT',null),
('CAB-FIBER-BACKBONE','ROSENBERGER',null),
('CAB-COPPER-HORIZONTAL','COMMSCOPE',null),
('CAB-COPPER-HORIZONTAL','PANDUIT',null),
('CAB-COPPER-HORIZONTAL','CORNING',null),
('CAB-COPPER-HORIZONTAL','LEGRAND',null),
('CAB-COPPER-HORIZONTAL','ROSENBERGER',null),
('CAB-FIBERGUIDE','COMMSCOPE',null),
('CAB-FIBERGUIDE','PANDUIT',null),
('CAB-LADDER','COMMSCOPE',null),
('CAB-LADDER','PANDUIT',null),
('CAB-LADDER','CORNING',null),
('CAB-LADDER','LEGRAND',null),
('CAB-LADDER','ROSENBERGER',null),
('CLOCK-MASTER','BOSCH-PA',null),
('CLOCK-MASTER','TOA',null),
('CLOCK-MASTER','SIEMENS',null),
('CLOCK-MASTER','HONEYWELL',null),
('CLOCK-SLAVE','BOSCH-PA',null),
('CLOCK-SLAVE','TOA',null),
('CLOCK-SLAVE','SIEMENS',null),
('CLOCK-SLAVE','HONEYWELL',null),
('LLI-CHILLER-COMP','CARRIER',null),
('LLI-CHILLER-COMP','TRANE',null),
('LLI-CHILLER-COMP','YORK',null),
('LLI-CHILLER-COMP','DAIKIN',null),
('LLI-CHILLER-COMP','SCHNEIDER',null),
('LLI-CHILLER-COMP','ABB',null),
('LLI-CHILLER-COMP','SIEMENS',null),
('LLI-CHILLER-COMP','CUMMINS',null),
('LLI-CHILLER-COMP','CATERPILLAR',null),
('LLI-CHILLER-COMP','VERTIV',null),
('LLI-CHILLER-CONTROL','CARRIER',null),
('LLI-CHILLER-CONTROL','TRANE',null),
('LLI-CHILLER-CONTROL','YORK',null),
('LLI-CHILLER-CONTROL','DAIKIN',null),
('LLI-CHILLER-CONTROL','SCHNEIDER',null),
('LLI-CHILLER-CONTROL','ABB',null),
('LLI-CHILLER-CONTROL','SIEMENS',null),
('LLI-CHILLER-CONTROL','CUMMINS',null),
('LLI-CHILLER-CONTROL','CATERPILLAR',null),
('LLI-CHILLER-CONTROL','VERTIV',null),
('LLI-TRANSFORMER','CARRIER',null),
('LLI-TRANSFORMER','TRANE',null),
('LLI-TRANSFORMER','YORK',null),
('LLI-TRANSFORMER','DAIKIN',null),
('LLI-TRANSFORMER','SCHNEIDER',null),
('LLI-TRANSFORMER','ABB',null),
('LLI-TRANSFORMER','SIEMENS',null),
('LLI-TRANSFORMER','CUMMINS',null),
('LLI-TRANSFORMER','CATERPILLAR',null),
('LLI-TRANSFORMER','VERTIV',null),
('LLI-MV-BREAKER','CARRIER',null),
('LLI-MV-BREAKER','TRANE',null),
('LLI-MV-BREAKER','YORK',null),
('LLI-MV-BREAKER','DAIKIN',null),
('LLI-MV-BREAKER','SCHNEIDER',null),
('LLI-MV-BREAKER','ABB',null),
('LLI-MV-BREAKER','SIEMENS',null),
('LLI-MV-BREAKER','CUMMINS',null),
('LLI-MV-BREAKER','CATERPILLAR',null),
('LLI-MV-BREAKER','VERTIV',null),
('LLI-ACB','CARRIER',null),
('LLI-ACB','TRANE',null),
('LLI-ACB','YORK',null),
('LLI-ACB','DAIKIN',null),
('LLI-ACB','SCHNEIDER',null),
('LLI-ACB','ABB',null),
('LLI-ACB','SIEMENS',null),
('LLI-ACB','CUMMINS',null),
('LLI-ACB','CATERPILLAR',null),
('LLI-ACB','VERTIV',null),
('LLI-GEN-ALTERNATOR','CARRIER',null),
('LLI-GEN-ALTERNATOR','TRANE',null),
('LLI-GEN-ALTERNATOR','YORK',null),
('LLI-GEN-ALTERNATOR','DAIKIN',null),
('LLI-GEN-ALTERNATOR','SCHNEIDER',null),
('LLI-GEN-ALTERNATOR','ABB',null),
('LLI-GEN-ALTERNATOR','SIEMENS',null),
('LLI-GEN-ALTERNATOR','CUMMINS',null),
('LLI-GEN-ALTERNATOR','CATERPILLAR',null),
('LLI-GEN-ALTERNATOR','VERTIV',null),
('LLI-GEN-CONTROLLER','CARRIER',null),
('LLI-GEN-CONTROLLER','TRANE',null),
('LLI-GEN-CONTROLLER','YORK',null),
('LLI-GEN-CONTROLLER','DAIKIN',null),
('LLI-GEN-CONTROLLER','SCHNEIDER',null),
('LLI-GEN-CONTROLLER','ABB',null),
('LLI-GEN-CONTROLLER','SIEMENS',null),
('LLI-GEN-CONTROLLER','CUMMINS',null),
('LLI-GEN-CONTROLLER','CATERPILLAR',null),
('LLI-GEN-CONTROLLER','VERTIV',null),
('LLI-UPS-POWER-MOD','CARRIER',null),
('LLI-UPS-POWER-MOD','TRANE',null),
('LLI-UPS-POWER-MOD','YORK',null),
('LLI-UPS-POWER-MOD','DAIKIN',null),
('LLI-UPS-POWER-MOD','SCHNEIDER',null),
('LLI-UPS-POWER-MOD','ABB',null),
('LLI-UPS-POWER-MOD','SIEMENS',null),
('LLI-UPS-POWER-MOD','CUMMINS',null),
('LLI-UPS-POWER-MOD','CATERPILLAR',null),
('LLI-UPS-POWER-MOD','VERTIV',null),
('LLI-ELEV-DRIVE','CARRIER',null),
('LLI-ELEV-DRIVE','TRANE',null),
('LLI-ELEV-DRIVE','YORK',null),
('LLI-ELEV-DRIVE','DAIKIN',null),
('LLI-ELEV-DRIVE','SCHNEIDER',null),
('LLI-ELEV-DRIVE','ABB',null),
('LLI-ELEV-DRIVE','SIEMENS',null),
('LLI-ELEV-DRIVE','CUMMINS',null),
('LLI-ELEV-DRIVE','CATERPILLAR',null),
('LLI-ELEV-DRIVE','VERTIV',null),
('LLI-ELEV-CONTROLLER','CARRIER',null),
('LLI-ELEV-CONTROLLER','TRANE',null),
('LLI-ELEV-CONTROLLER','YORK',null),
('LLI-ELEV-CONTROLLER','DAIKIN',null),
('LLI-ELEV-CONTROLLER','SCHNEIDER',null),
('LLI-ELEV-CONTROLLER','ABB',null),
('LLI-ELEV-CONTROLLER','SIEMENS',null),
('LLI-ELEV-CONTROLLER','CUMMINS',null),
('LLI-ELEV-CONTROLLER','CATERPILLAR',null),
('LLI-ELEV-CONTROLLER','VERTIV',null),
('LLI-FIRE-PANEL','CARRIER',null),
('LLI-FIRE-PANEL','TRANE',null),
('LLI-FIRE-PANEL','YORK',null),
('LLI-FIRE-PANEL','DAIKIN',null),
('LLI-FIRE-PANEL','SCHNEIDER',null),
('LLI-FIRE-PANEL','ABB',null),
('LLI-FIRE-PANEL','SIEMENS',null),
('LLI-FIRE-PANEL','CUMMINS',null),
('LLI-FIRE-PANEL','CATERPILLAR',null),
('LLI-FIRE-PANEL','VERTIV',null),
('LLI-BMS-CONTROLLER','CARRIER',null),
('LLI-BMS-CONTROLLER','TRANE',null),
('LLI-BMS-CONTROLLER','YORK',null),
('LLI-BMS-CONTROLLER','DAIKIN',null),
('LLI-BMS-CONTROLLER','SCHNEIDER',null),
('LLI-BMS-CONTROLLER','ABB',null),
('LLI-BMS-CONTROLLER','SIEMENS',null),
('LLI-BMS-CONTROLLER','CUMMINS',null),
('LLI-BMS-CONTROLLER','CATERPILLAR',null),
('LLI-BMS-CONTROLLER','VERTIV',null),
('LLI-CRAC-COMP','CARRIER',null),
('LLI-CRAC-COMP','TRANE',null),
('LLI-CRAC-COMP','YORK',null),
('LLI-CRAC-COMP','DAIKIN',null),
('LLI-CRAC-COMP','SCHNEIDER',null),
('LLI-CRAC-COMP','ABB',null),
('LLI-CRAC-COMP','SIEMENS',null),
('LLI-CRAC-COMP','CUMMINS',null),
('LLI-CRAC-COMP','CATERPILLAR',null),
('LLI-CRAC-COMP','VERTIV',null),
('TEL-IP-PBX','AVAYA','Aura Communication Manager'),
('TEL-CALL-MANAGER','CISCO-UC','Unified Communications Manager (CUCM)'),
('TEL-IP-PHONE','CISCO-UC','Cisco IP Phone / Webex Desk'),
('TEL-IP-PHONE','AVAYA','J100 Series / IP Deskphones'),
('TEL-IP-PHONE','YEALINK','T Series / SIP Phones'),
('UC-VIDEO-CODEC','CISCO-UC','Webex Room Series'),
('UC-VIDEO-CODEC','POLY','Studio / RealPresence'),
('RADIO-TETRA','MOTOROLA','DIMETRA / TETRA'),
('RADIO-DMR','MOTOROLA','MOTOTRBO'),
('RADIO-DMR','HYTERA','DMR Systems'),
('WLS-P2P','CAMBIUM','PTP Series'),
('WLS-P2P','UBIQUITI','airFiber / airMAX'),
('WLS-MICROWAVE','AVIAT','Microwave Radio'),
('WLS-MICROWAVE','CERAGON','IP-50 / Microwave'),
('DAS-HEADEND','COMMSCOPE-ANDREW','ERA / ION / DAS'),
('DAS-HEADEND','SOLID','ALLIANCE DAS'),
('PAGA-CONTROLLER','BOSCH-PA','PRAESENSA / Public Address'),
('PAGA-CONTROLLER','TOA','Voice Evacuation / PA'),
('CAB-FIBER-BACKBONE','COMMSCOPE','SYSTIMAX / TeraSPEED')
)
insert into public.bf_master_asset_options(asset_type_id,manufacturer_id,model_family)
select t.id,m.id,x.model_family
from x
join public.bf_master_asset_types t on t.code=x.asset_code
join public.bf_master_manufacturers m on m.code=x.manufacturer_code
where not exists(
 select 1 from public.bf_master_asset_options o
 where o.asset_type_id=t.id and o.manufacturer_id=m.id
 and coalesce(o.model_family,'')=coalesce(x.model_family,'')
);


update public.bf_master_asset_types
set group_ar=case system_code when 'TELEPHONY' then 'السنترالات والهواتف' when 'UC_AV' then 'المؤتمرات المرئية والصوتية' when 'RADIO' then 'الاتصالات اللاسلكية' when 'WIRELESS' then 'روابط وشبكات لاسلكية' when 'DAS' then 'التغطية الخلوية الداخلية DAS' when 'PAGA' then 'النداء العام والاتصال الحرج' when 'STRUCTURED_CABLING' then 'البنية التحتية للاتصالات' when 'CLOCK_PAGING' then 'الساعات المركزية والنداء' when 'LONG_LEAD_COMPONENT' then 'مكونات حرجة طويلة التوريد' else group_ar end,
    group_en=case system_code when 'TELEPHONY' then 'Telephony & Unified Communications' when 'UC_AV' then 'Unified Communications & AV' when 'RADIO' then 'Two-Way Radio Communications' when 'WIRELESS' then 'Wireless Communications' when 'DAS' then 'In-Building Cellular / DAS' when 'PAGA' then 'PAGA / Critical Communications' when 'STRUCTURED_CABLING' then 'Structured Cabling' when 'CLOCK_PAGING' then 'Master Clock & Paging' when 'LONG_LEAD_COMPONENT' then 'Critical Long Lead Components' else group_en end
where system_code in('TELEPHONY','UC_AV','RADIO','WIRELESS','DAS','PAGA','STRUCTURED_CABLING','CLOCK_PAGING','LONG_LEAD_COMPONENT');

update public.bf_master_asset_types set procurement_class='long_lead',default_lead_time_days=150,critical_spare=true where code='HVAC-CHILLER-AIR';
update public.bf_master_asset_types set procurement_class='long_lead',default_lead_time_days=180,critical_spare=true where code='HVAC-CHILLER-WATER';
update public.bf_master_asset_types set procurement_class='long_lead',default_lead_time_days=90,critical_spare=true where code='HVAC-AHU';
update public.bf_master_asset_types set procurement_class='long_lead',default_lead_time_days=90,critical_spare=true where code='HVAC-FAHU';
update public.bf_master_asset_types set procurement_class='long_lead',default_lead_time_days=180,critical_spare=true where code='ELEC-RMU';
update public.bf_master_asset_types set procurement_class='long_lead',default_lead_time_days=210,critical_spare=true where code='ELEC-MV-SWGR';
update public.bf_master_asset_types set procurement_class='long_lead',default_lead_time_days=240,critical_spare=true where code='ELEC-TRANSFORMER';
update public.bf_master_asset_types set procurement_class='long_lead',default_lead_time_days=180,critical_spare=true where code='ELEC-GENERATOR';
update public.bf_master_asset_types set procurement_class='long_lead',default_lead_time_days=120,critical_spare=true where code='ELEC-UPS';
update public.bf_master_asset_types set procurement_class='long_lead',default_lead_time_days=120,critical_spare=true where code='DC-UPS';
update public.bf_master_asset_types set procurement_class='long_lead',default_lead_time_days=120,critical_spare=true where code='DC-CRAC';
update public.bf_master_asset_types set procurement_class='long_lead',default_lead_time_days=120,critical_spare=true where code='DC-CRAH';
update public.bf_master_asset_types set procurement_class='long_lead',default_lead_time_days=180,critical_spare=true where code='LIFT-PASSENGER';
update public.bf_master_asset_types set procurement_class='long_lead',default_lead_time_days=180,critical_spare=true where code='LIFT-SERVICE';
update public.bf_master_asset_types set procurement_class='long_lead',default_lead_time_days=210,critical_spare=true where code='LIFT-FREIGHT';
update public.bf_master_asset_types set procurement_class='long_lead',default_lead_time_days=210,critical_spare=true where code='ESCALATOR';
update public.bf_master_asset_types set procurement_class='long_lead',default_lead_time_days=120,critical_spare=true where code='FIRE-ALARM-PANEL';
update public.bf_master_asset_types set procurement_class='long_lead',default_lead_time_days=120,critical_spare=true where code='FIRE-PUMP-ELECTRIC';
update public.bf_master_asset_types set procurement_class='long_lead',default_lead_time_days=150,critical_spare=true where code='FIRE-PUMP-DIESEL';
update public.bf_master_asset_types set procurement_class='long_lead',default_lead_time_days=75,critical_spare=true where code='BMS-SERVER';
update public.bf_master_asset_types set procurement_class='long_lead',default_lead_time_days=75,critical_spare=true where code='BMS-CONTROLLER';
update public.bf_master_asset_types set procurement_class='long_lead',default_lead_time_days=75,critical_spare=true where code='SEC-VMS';
update public.bf_master_asset_types set procurement_class='long_lead',default_lead_time_days=90,critical_spare=true where code='ICT-CORE-SWITCH';

update public.bf_master_asset_types
set stock_strategy=case
 when critical_spare and procurement_class='long_lead' then 'Maintain approved critical spare / contingency plan or framework agreement.'
 when critical_spare then 'Maintain minimum critical spare or approved rapid-supply source.'
 else 'Order against approved maintenance need and OEM specification.'
end
where stock_strategy is null;

insert into public.bf_master_ppm_templates(asset_type_id,title_ar,title_en,frequency,estimated_minutes,reference,status)
select t.id,'الصيانة الدورية - '||t.name_ar,'Periodic Maintenance - '||t.name_en,
       case when t.system_code in('TELEPHONY','RADIO','WIRELESS','DAS','PAGA') then 'monthly' else 'quarterly' end,
       case when t.default_criticality='critical' then 75 else 45 end,
       'Baseline telecom/ICT maintenance template. Follow OEM documentation and approved site procedures.',
       'active'
from public.bf_master_asset_types t
where t.status='active'
and t.system_code in('TELEPHONY','UC_AV','RADIO','WIRELESS','DAS','PAGA','STRUCTURED_CABLING','CLOCK_PAGING','LONG_LEAD_COMPONENT')
and not exists(select 1 from public.bf_master_ppm_templates p where p.asset_type_id=t.id and p.status='active');

insert into public.bf_master_ppm_steps(template_id,seq,title_ar,title_en,instructions_ar,instructions_en,task_type,response_type,safety_notes)
select p.id,s.seq,s.ar,s.en,s.iar,s.ien,s.task,s.resp,s.safety
from public.bf_master_ppm_templates p
join public.bf_master_asset_types t on t.id=p.asset_type_id
cross join lateral (values
 (1,'فحص الحالة والطاقة','Inspect condition and power','افحص تثبيت الجهاز والطاقة والبطاريات/UPS والمؤشرات.','Inspect mounting, power, UPS/battery supply and indicators.','inspection','pass_fail',null),
 (2,'فحص الاتصالات والربط','Check communications and links','تحقق من حالة الشبكة أو RF أو SIP أو الروابط ذات الصلة وسجل الإنذارات.','Verify network, RF, SIP or applicable links and record alarms.','test','text',null),
 (3,'فحص النسخ الاحتياطي والإعدادات','Check backup and configuration','تحقق من النسخ الاحتياطي للإعدادات والكونفيج والبرمجيات المصرح بها.','Verify approved configuration/software backup and recovery readiness.','inspection','pass_fail',null),
 (4,'اختبار الخدمة','Functional service test','نفذ اختبار خدمة معتمد بدون التأثير على التشغيل وسجل النتيجة.','Perform an approved functional service test without disrupting operations and record result.','test','text',null),
 (5,'فحص قطع الغيار وLong Lead','Review spares and long-lead risk','راجع قطع الغيار الحرجة ومدة التوريد وخطة البديل عند الحاجة.','Review critical spares, lead time and contingency/replacement plan.','inspection','text',null)
) s(seq,ar,en,iar,ien,task,resp,safety)
where t.system_code in('TELEPHONY','UC_AV','RADIO','WIRELESS','DAS','PAGA','STRUCTURED_CABLING','CLOCK_PAGING','LONG_LEAD_COMPONENT')
and not exists(select 1 from public.bf_master_ppm_steps z where z.template_id=p.id)
on conflict(template_id,seq) do nothing;

drop view if exists public.bf_master_asset_catalog_report;

create view public.bf_master_asset_catalog_report
with (security_invoker=true) as
select
 t.id,t.system_code,t.group_ar,t.group_en,t.code,t.icon_text,t.name_ar,t.name_en,
 t.default_criticality,t.expected_life_years,t.procurement_class,t.default_lead_time_days,
 t.critical_spare,t.stock_strategy,
 coalesce(string_agg(distinct m.name,' | ' order by m.name),'Generic / OEM') as manufacturers,
 count(distinct p.id) as maintenance_templates
from public.bf_master_asset_types t
left join public.bf_master_asset_options o on o.asset_type_id=t.id and o.status='active'
left join public.bf_master_manufacturers m on m.id=o.manufacturer_id and m.status='active'
left join public.bf_master_ppm_templates p on p.asset_type_id=t.id and p.status='active'
where t.status='active'
group by t.id;

grant select on public.bf_master_asset_catalog_report to authenticated;
notify pgrst,'reload schema';
commit;
