begin;
insert into public.bf_master_asset_types(
 system_code,code,name_ar,name_en,default_criticality,expected_life_years,icon_text,
 procurement_class,default_lead_time_days,critical_spare
)
values
('AV','AV-VIDEO-WALL','جدار فيديو','Video Wall','high',8,'🖥️','long_lead',90,true),
('AV','AV-VIDEO-WALL-CTRL','كنترولر جدار فيديو','Video Wall Controller','critical',8,'🎛️','long_lead',90,true),
('AV','AV-LED-WALL','شاشة LED Wall','LED Video Wall','high',8,'🧱','long_lead',120,true),
('AV','AV-MATRIX','مصفوفة فيديو/صوت','AV Matrix Switcher','high',10,'🔀','standard',45,true),
('AV','AV-ENCODER','مرسل AV Encoder','AV Encoder','high',8,'📡','standard',45,true),
('AV','AV-DECODER','مستقبل AV Decoder','AV Decoder','high',8,'📡','standard',45,true),
('AV','AV-SWITCHER','سويتشر عروض','Presentation Switcher','medium',8,'🎚️','standard',30,false),
('AV','AV-PTZ-CAMERA','كاميرا مؤتمرات PTZ','PTZ Conference Camera','high',7,'🎥','standard',45,true),
('AV','AV-CEILING-MIC','مايك سقفي','Ceiling Microphone','medium',8,'🎤','standard',30,false),
('AV','AV-WIRELESS-MIC','مايك لاسلكي','Wireless Microphone System','medium',8,'🎤','standard',30,false),
('AV','AV-AMP','مضخم صوت','Audio Power Amplifier','high',10,'🔊','standard',45,true),
('AV','AV-SPEAKER','سماعة احترافية','Professional Loudspeaker','medium',12,'🔊','standard',30,false),
('AV','AV-DSP','معالج صوت DSP','Audio DSP Processor','high',10,'🎚️','standard',45,true),
('AV','AV-CONTROL-PANEL','لوحة تحكم قاعة','Room Control Touch Panel','medium',7,'📱','standard',30,false),
('AV','AV-SIGNAGE-PLAYER','مشغل شاشات رقمية','Digital Signage Player','medium',6,'📺','standard',30,false),
('AV','AV-DIGITAL-SIGNAGE','شاشة Digital Signage','Digital Signage Display','medium',7,'📺','standard',30,false),
('AV','AV-PROJECTOR-LASER','بروجكتور ليزر','Laser Projector','high',8,'📽️','standard',45,true),
('AV','AV-MOTOR-SCREEN','شاشة عرض كهربائية','Motorized Projection Screen','medium',10,'🖼️','standard',45,false),
('IT','IT-DESKTOP','كمبيوتر مكتبي','Desktop Computer','medium',5,'🖥️','standard',30,false),
('IT','IT-WORKSTATION','محطة عمل','Engineering Workstation','high',5,'🖥️','standard',45,true),
('IT','IT-LAPTOP','لابتوب','Laptop Computer','medium',4,'💻','standard',30,false),
('IT','IT-MONITOR','شاشة كمبيوتر','Computer Monitor','low',6,'🖥️','standard',30,false),
('IT','IT-THIN-CLIENT','Thin Client','Thin Client','medium',5,'🖥️','standard',30,false),
('IT','IT-SERVER','خادم','Server','critical',7,'🗄️','long_lead',90,true),
('IT','IT-STORAGE','وحدة تخزين','Storage Array / NAS / SAN','critical',7,'💾','long_lead',90,true),
('IT','IT-KVM','KVM','KVM Switch','medium',8,'🎛️','standard',30,false),
('IT','IT-DOCK','Docking Station','Docking Station','low',5,'🔌','standard',30,false),
('OFFICE','OFFICE-PRINTER-LASER','طابعة ليزر','Laser Printer','medium',6,'🖨️','standard',30,false),
('OFFICE','OFFICE-PRINTER-INK','طابعة حبر','Inkjet Printer','low',5,'🖨️','standard',30,false),
('OFFICE','OFFICE-MFP','طابعة متعددة الوظائف','Multifunction Printer','high',7,'🖨️','standard',45,true),
('OFFICE','OFFICE-COPIER','آلة تصوير مستندات','Photocopier','high',8,'📠','standard',45,true),
('OFFICE','OFFICE-PLOTTER','بلوتر','Large Format Plotter','high',8,'📐','standard',45,true),
('OFFICE','OFFICE-SCANNER','ماسح ضوئي','Document Scanner','medium',6,'📄','standard',30,false),
('OFFICE','OFFICE-SHREDDER','آلة إتلاف مستندات','Document Shredder','medium',6,'🗑️','standard',30,false),
('OFFICE','OFFICE-FAX','فاكس','Fax Machine','low',6,'📠','standard',30,false),
('OFFICE','OFFICE-LAMINATOR','جهاز تغليف','Laminator','low',6,'📑','standard',30,false)
on conflict(code) do update set
 system_code=excluded.system_code,
 name_ar=excluded.name_ar,
 name_en=excluded.name_en,
 default_criticality=excluded.default_criticality,
 expected_life_years=excluded.expected_life_years,
 icon_text=excluded.icon_text,
 procurement_class=excluded.procurement_class,
 default_lead_time_days=excluded.default_lead_time_days,
 critical_spare=excluded.critical_spare,
 status='active';
with x(code,name,short_name) as (values
('SAMSUNG-DISPLAY','Samsung Display','Samsung'),
('LG-DISPLAY','LG Business Solutions','LG'),
('PLANAR','Planar','Planar'),
('BARCO-AV','Barco','Barco'),
('CHRISTIE','Christie Digital','Christie'),
('LEYARD','Leyard','Leyard'),
('UNILUMIN','Unilumin','Unilumin'),
('EXTRON-AV','Extron','Extron'),
('CRESTRON-AV','Crestron','Crestron'),
('KRAMER','Kramer','Kramer'),
('ATLONA','Atlona','Atlona'),
('QSC-AV','Q-SYS / QSC','Q-SYS'),
('BIAMP-AV','Biamp','Biamp'),
('SHURE-AV','Shure','Shure'),
('SENNHEISER-AV','Sennheiser','Sennheiser'),
('BOSE-PRO','Bose Professional','Bose'),
('JBL-PRO','JBL Professional','JBL'),
('YAMAHA-PRO','Yamaha Pro Audio','Yamaha'),
('SONY-PRO','Sony Professional','Sony'),
('PANASONIC-PRO','Panasonic Connect','Panasonic'),
('EPSON','Epson','Epson'),
('HP','HP','HP'),
('DELL','Dell','Dell'),
('LENOVO','Lenovo','Lenovo'),
('APPLE','Apple','Apple'),
('MICROSOFT','Microsoft','Microsoft'),
('HPE','Hewlett Packard Enterprise','Hewlett'),
('DELL-EMC','Dell EMC','Dell'),
('NETAPP','NetApp','NetApp'),
('SYNLOGY','Synology','Synology'),
('QNAP','QNAP','QNAP'),
('CANON','Canon','Canon'),
('RICOH','Ricoh','Ricoh'),
('XEROX','Xerox','Xerox'),
('KONICA','Konica Minolta','Konica'),
('KYOCERA','Kyocera','Kyocera'),
('BROTHER','Brother','Brother'),
('SHARP','Sharp','Sharp'),
('TOSHIBA','Toshiba Tec','Toshiba'),
('LEXMARK','Lexmark','Lexmark')
)
insert into public.bf_master_manufacturers(code,name,short_name,status)
select x.code,x.name,x.short_name,'active'
from x
where not exists (
  select 1
  from public.bf_master_manufacturers m
  where m.code=x.code or m.name=x.name
);
with x(code,name,short_name) as (values
('SAMSUNG-DISPLAY','Samsung Display','Samsung'),
('LG-DISPLAY','LG Business Solutions','LG'),
('PLANAR','Planar','Planar'),
('BARCO-AV','Barco','Barco'),
('CHRISTIE','Christie Digital','Christie'),
('LEYARD','Leyard','Leyard'),
('UNILUMIN','Unilumin','Unilumin'),
('EXTRON-AV','Extron','Extron'),
('CRESTRON-AV','Crestron','Crestron'),
('KRAMER','Kramer','Kramer'),
('ATLONA','Atlona','Atlona'),
('QSC-AV','Q-SYS / QSC','Q-SYS'),
('BIAMP-AV','Biamp','Biamp'),
('SHURE-AV','Shure','Shure'),
('SENNHEISER-AV','Sennheiser','Sennheiser'),
('BOSE-PRO','Bose Professional','Bose'),
('JBL-PRO','JBL Professional','JBL'),
('YAMAHA-PRO','Yamaha Pro Audio','Yamaha'),
('SONY-PRO','Sony Professional','Sony'),
('PANASONIC-PRO','Panasonic Connect','Panasonic'),
('EPSON','Epson','Epson'),
('HP','HP','HP'),
('DELL','Dell','Dell'),
('LENOVO','Lenovo','Lenovo'),
('APPLE','Apple','Apple'),
('MICROSOFT','Microsoft','Microsoft'),
('HPE','Hewlett Packard Enterprise','Hewlett'),
('DELL-EMC','Dell EMC','Dell'),
('NETAPP','NetApp','NetApp'),
('SYNLOGY','Synology','Synology'),
('QNAP','QNAP','QNAP'),
('CANON','Canon','Canon'),
('RICOH','Ricoh','Ricoh'),
('XEROX','Xerox','Xerox'),
('KONICA','Konica Minolta','Konica'),
('KYOCERA','Kyocera','Kyocera'),
('BROTHER','Brother','Brother'),
('SHARP','Sharp','Sharp'),
('TOSHIBA','Toshiba Tec','Toshiba'),
('LEXMARK','Lexmark','Lexmark')
)
update public.bf_master_manufacturers m
set short_name=coalesce(m.short_name,x.short_name),
    status='active'
from x
where m.name=x.name;
with x(asset_code,manufacturer_name,model_family) as (values
('AV-VIDEO-WALL','Samsung Display',null),
('AV-VIDEO-WALL','LG Business Solutions',null),
('AV-VIDEO-WALL','Planar',null),
('AV-VIDEO-WALL','Barco',null),
('AV-VIDEO-WALL','Christie Digital',null),
('AV-VIDEO-WALL','Leyard',null),
('AV-VIDEO-WALL','Unilumin',null),
('AV-VIDEO-WALL-CTRL','Barco',null),
('AV-VIDEO-WALL-CTRL','Planar',null),
('AV-VIDEO-WALL-CTRL','Christie Digital',null),
('AV-VIDEO-WALL-CTRL','Extron',null),
('AV-VIDEO-WALL-CTRL','Crestron',null),
('AV-LED-WALL','Samsung Display',null),
('AV-LED-WALL','LG Business Solutions',null),
('AV-LED-WALL','Planar',null),
('AV-LED-WALL','Barco',null),
('AV-LED-WALL','Christie Digital',null),
('AV-LED-WALL','Leyard',null),
('AV-LED-WALL','Unilumin',null),
('AV-LED-WALL','Extron',null),
('AV-LED-WALL','Crestron',null),
('AV-LED-WALL','Kramer',null),
('AV-MATRIX','Samsung Display',null),
('AV-MATRIX','LG Business Solutions',null),
('AV-MATRIX','Planar',null),
('AV-MATRIX','Barco',null),
('AV-MATRIX','Christie Digital',null),
('AV-MATRIX','Leyard',null),
('AV-MATRIX','Unilumin',null),
('AV-MATRIX','Extron',null),
('AV-MATRIX','Crestron',null),
('AV-MATRIX','Kramer',null),
('AV-ENCODER','Samsung Display',null),
('AV-ENCODER','LG Business Solutions',null),
('AV-ENCODER','Planar',null),
('AV-ENCODER','Barco',null),
('AV-ENCODER','Christie Digital',null),
('AV-ENCODER','Leyard',null),
('AV-ENCODER','Unilumin',null),
('AV-ENCODER','Extron',null),
('AV-ENCODER','Crestron',null),
('AV-ENCODER','Kramer',null),
('AV-DECODER','Samsung Display',null),
('AV-DECODER','LG Business Solutions',null),
('AV-DECODER','Planar',null),
('AV-DECODER','Barco',null),
('AV-DECODER','Christie Digital',null),
('AV-DECODER','Leyard',null),
('AV-DECODER','Unilumin',null),
('AV-DECODER','Extron',null),
('AV-DECODER','Crestron',null),
('AV-DECODER','Kramer',null),
('AV-SWITCHER','Samsung Display',null),
('AV-SWITCHER','LG Business Solutions',null),
('AV-SWITCHER','Planar',null),
('AV-SWITCHER','Barco',null),
('AV-SWITCHER','Christie Digital',null),
('AV-SWITCHER','Leyard',null),
('AV-SWITCHER','Unilumin',null),
('AV-SWITCHER','Extron',null),
('AV-SWITCHER','Crestron',null),
('AV-SWITCHER','Kramer',null),
('AV-PTZ-CAMERA','Sony Professional',null),
('AV-PTZ-CAMERA','Panasonic Connect',null),
('AV-PTZ-CAMERA','CISCO-UC',null),
('AV-PTZ-CAMERA','POLY',null),
('AV-CEILING-MIC','Samsung Display',null),
('AV-CEILING-MIC','LG Business Solutions',null),
('AV-CEILING-MIC','Planar',null),
('AV-CEILING-MIC','Barco',null),
('AV-CEILING-MIC','Christie Digital',null),
('AV-CEILING-MIC','Leyard',null),
('AV-CEILING-MIC','Unilumin',null),
('AV-CEILING-MIC','Extron',null),
('AV-CEILING-MIC','Crestron',null),
('AV-CEILING-MIC','Kramer',null),
('AV-WIRELESS-MIC','Samsung Display',null),
('AV-WIRELESS-MIC','LG Business Solutions',null),
('AV-WIRELESS-MIC','Planar',null),
('AV-WIRELESS-MIC','Barco',null),
('AV-WIRELESS-MIC','Christie Digital',null),
('AV-WIRELESS-MIC','Leyard',null),
('AV-WIRELESS-MIC','Unilumin',null),
('AV-WIRELESS-MIC','Extron',null),
('AV-WIRELESS-MIC','Crestron',null),
('AV-WIRELESS-MIC','Kramer',null),
('AV-AMP','Samsung Display',null),
('AV-AMP','LG Business Solutions',null),
('AV-AMP','Planar',null),
('AV-AMP','Barco',null),
('AV-AMP','Christie Digital',null),
('AV-AMP','Leyard',null),
('AV-AMP','Unilumin',null),
('AV-AMP','Extron',null),
('AV-AMP','Crestron',null),
('AV-AMP','Kramer',null),
('AV-SPEAKER','Samsung Display',null),
('AV-SPEAKER','LG Business Solutions',null),
('AV-SPEAKER','Planar',null),
('AV-SPEAKER','Barco',null),
('AV-SPEAKER','Christie Digital',null),
('AV-SPEAKER','Leyard',null),
('AV-SPEAKER','Unilumin',null),
('AV-SPEAKER','Extron',null),
('AV-SPEAKER','Crestron',null),
('AV-SPEAKER','Kramer',null),
('AV-DSP','Q-SYS / QSC',null),
('AV-DSP','Biamp',null),
('AV-DSP','Yamaha Pro Audio',null),
('AV-DSP','Bose Professional',null),
('AV-CONTROL-PANEL','Samsung Display',null),
('AV-CONTROL-PANEL','LG Business Solutions',null),
('AV-CONTROL-PANEL','Planar',null),
('AV-CONTROL-PANEL','Barco',null),
('AV-CONTROL-PANEL','Christie Digital',null),
('AV-CONTROL-PANEL','Leyard',null),
('AV-CONTROL-PANEL','Unilumin',null),
('AV-CONTROL-PANEL','Extron',null),
('AV-CONTROL-PANEL','Crestron',null),
('AV-CONTROL-PANEL','Kramer',null),
('AV-SIGNAGE-PLAYER','Samsung Display',null),
('AV-SIGNAGE-PLAYER','LG Business Solutions',null),
('AV-SIGNAGE-PLAYER','Planar',null),
('AV-SIGNAGE-PLAYER','Barco',null),
('AV-SIGNAGE-PLAYER','Christie Digital',null),
('AV-SIGNAGE-PLAYER','Leyard',null),
('AV-SIGNAGE-PLAYER','Unilumin',null),
('AV-SIGNAGE-PLAYER','Extron',null),
('AV-SIGNAGE-PLAYER','Crestron',null),
('AV-SIGNAGE-PLAYER','Kramer',null),
('AV-DIGITAL-SIGNAGE','Samsung Display',null),
('AV-DIGITAL-SIGNAGE','LG Business Solutions',null),
('AV-DIGITAL-SIGNAGE','Planar',null),
('AV-DIGITAL-SIGNAGE','Barco',null),
('AV-DIGITAL-SIGNAGE','Christie Digital',null),
('AV-DIGITAL-SIGNAGE','Leyard',null),
('AV-DIGITAL-SIGNAGE','Unilumin',null),
('AV-DIGITAL-SIGNAGE','Extron',null),
('AV-DIGITAL-SIGNAGE','Crestron',null),
('AV-DIGITAL-SIGNAGE','Kramer',null),
('AV-PROJECTOR-LASER','Epson',null),
('AV-PROJECTOR-LASER','Sony Professional',null),
('AV-PROJECTOR-LASER','Panasonic Connect',null),
('AV-PROJECTOR-LASER','Christie Digital',null),
('AV-PROJECTOR-LASER','Barco',null),
('AV-MOTOR-SCREEN','Samsung Display',null),
('AV-MOTOR-SCREEN','LG Business Solutions',null),
('AV-MOTOR-SCREEN','Planar',null),
('AV-MOTOR-SCREEN','Barco',null),
('AV-MOTOR-SCREEN','Christie Digital',null),
('AV-MOTOR-SCREEN','Leyard',null),
('AV-MOTOR-SCREEN','Unilumin',null),
('AV-MOTOR-SCREEN','Extron',null),
('AV-MOTOR-SCREEN','Crestron',null),
('AV-MOTOR-SCREEN','Kramer',null),
('IT-DESKTOP','HP',null),
('IT-DESKTOP','Dell',null),
('IT-DESKTOP','Lenovo',null),
('IT-DESKTOP','Apple',null),
('IT-DESKTOP','Microsoft',null),
('IT-DESKTOP','Hewlett Packard Enterprise',null),
('IT-DESKTOP','Dell EMC',null),
('IT-DESKTOP','NetApp',null),
('IT-DESKTOP','Synology',null),
('IT-DESKTOP','QNAP',null),
('IT-WORKSTATION','HP',null),
('IT-WORKSTATION','Dell',null),
('IT-WORKSTATION','Lenovo',null),
('IT-WORKSTATION','Apple',null),
('IT-WORKSTATION','Microsoft',null),
('IT-WORKSTATION','Hewlett Packard Enterprise',null),
('IT-WORKSTATION','Dell EMC',null),
('IT-WORKSTATION','NetApp',null),
('IT-WORKSTATION','Synology',null),
('IT-WORKSTATION','QNAP',null),
('IT-LAPTOP','HP',null),
('IT-LAPTOP','Dell',null),
('IT-LAPTOP','Lenovo',null),
('IT-LAPTOP','Apple',null),
('IT-LAPTOP','Microsoft',null),
('IT-LAPTOP','Hewlett Packard Enterprise',null),
('IT-LAPTOP','Dell EMC',null),
('IT-LAPTOP','NetApp',null),
('IT-LAPTOP','Synology',null),
('IT-LAPTOP','QNAP',null),
('IT-MONITOR','HP',null),
('IT-MONITOR','Dell',null),
('IT-MONITOR','Lenovo',null),
('IT-MONITOR','Apple',null),
('IT-MONITOR','Microsoft',null),
('IT-MONITOR','Hewlett Packard Enterprise',null),
('IT-MONITOR','Dell EMC',null),
('IT-MONITOR','NetApp',null),
('IT-MONITOR','Synology',null),
('IT-MONITOR','QNAP',null),
('IT-THIN-CLIENT','HP',null),
('IT-THIN-CLIENT','Dell',null),
('IT-THIN-CLIENT','Lenovo',null),
('IT-THIN-CLIENT','Apple',null),
('IT-THIN-CLIENT','Microsoft',null),
('IT-THIN-CLIENT','Hewlett Packard Enterprise',null),
('IT-THIN-CLIENT','Dell EMC',null),
('IT-THIN-CLIENT','NetApp',null),
('IT-THIN-CLIENT','Synology',null),
('IT-THIN-CLIENT','QNAP',null),
('IT-SERVER','Hewlett Packard Enterprise',null),
('IT-SERVER','Dell EMC',null),
('IT-SERVER','Lenovo',null),
('IT-STORAGE','Dell EMC',null),
('IT-STORAGE','NetApp',null),
('IT-STORAGE','Synology',null),
('IT-STORAGE','QNAP',null),
('IT-STORAGE','Hewlett Packard Enterprise',null),
('IT-KVM','HP',null),
('IT-KVM','Dell',null),
('IT-KVM','Lenovo',null),
('IT-KVM','Apple',null),
('IT-KVM','Microsoft',null),
('IT-KVM','Hewlett Packard Enterprise',null),
('IT-KVM','Dell EMC',null),
('IT-KVM','NetApp',null),
('IT-KVM','Synology',null),
('IT-KVM','QNAP',null),
('IT-DOCK','HP',null),
('IT-DOCK','Dell',null),
('IT-DOCK','Lenovo',null),
('IT-DOCK','Apple',null),
('IT-DOCK','Microsoft',null),
('IT-DOCK','Hewlett Packard Enterprise',null),
('IT-DOCK','Dell EMC',null),
('IT-DOCK','NetApp',null),
('IT-DOCK','Synology',null),
('IT-DOCK','QNAP',null),
('OFFICE-PRINTER-LASER','HP',null),
('OFFICE-PRINTER-LASER','Canon',null),
('OFFICE-PRINTER-LASER','Ricoh',null),
('OFFICE-PRINTER-LASER','Xerox',null),
('OFFICE-PRINTER-LASER','Konica Minolta',null),
('OFFICE-PRINTER-LASER','Kyocera',null),
('OFFICE-PRINTER-LASER','Brother',null),
('OFFICE-PRINTER-LASER','Sharp',null),
('OFFICE-PRINTER-LASER','Toshiba Tec',null),
('OFFICE-PRINTER-LASER','Lexmark',null),
('OFFICE-PRINTER-INK','HP',null),
('OFFICE-PRINTER-INK','Canon',null),
('OFFICE-PRINTER-INK','Ricoh',null),
('OFFICE-PRINTER-INK','Xerox',null),
('OFFICE-PRINTER-INK','Konica Minolta',null),
('OFFICE-PRINTER-INK','Kyocera',null),
('OFFICE-PRINTER-INK','Brother',null),
('OFFICE-PRINTER-INK','Sharp',null),
('OFFICE-PRINTER-INK','Toshiba Tec',null),
('OFFICE-PRINTER-INK','Lexmark',null),
('OFFICE-MFP','HP',null),
('OFFICE-MFP','Canon',null),
('OFFICE-MFP','Ricoh',null),
('OFFICE-MFP','Xerox',null),
('OFFICE-MFP','Konica Minolta',null),
('OFFICE-MFP','Kyocera',null),
('OFFICE-MFP','Sharp',null),
('OFFICE-MFP','Toshiba Tec',null),
('OFFICE-COPIER','Canon',null),
('OFFICE-COPIER','Ricoh',null),
('OFFICE-COPIER','Xerox',null),
('OFFICE-COPIER','Konica Minolta',null),
('OFFICE-COPIER','Kyocera',null),
('OFFICE-COPIER','Sharp',null),
('OFFICE-COPIER','Toshiba Tec',null),
('OFFICE-PLOTTER','HP',null),
('OFFICE-PLOTTER','Canon',null),
('OFFICE-PLOTTER','Epson',null),
('OFFICE-SCANNER','HP',null),
('OFFICE-SCANNER','Canon',null),
('OFFICE-SCANNER','Ricoh',null),
('OFFICE-SCANNER','Xerox',null),
('OFFICE-SCANNER','Konica Minolta',null),
('OFFICE-SCANNER','Kyocera',null),
('OFFICE-SCANNER','Brother',null),
('OFFICE-SCANNER','Sharp',null),
('OFFICE-SCANNER','Toshiba Tec',null),
('OFFICE-SCANNER','Lexmark',null),
('OFFICE-SHREDDER','HP',null),
('OFFICE-SHREDDER','Canon',null),
('OFFICE-SHREDDER','Ricoh',null),
('OFFICE-SHREDDER','Xerox',null),
('OFFICE-SHREDDER','Konica Minolta',null),
('OFFICE-SHREDDER','Kyocera',null),
('OFFICE-SHREDDER','Brother',null),
('OFFICE-SHREDDER','Sharp',null),
('OFFICE-SHREDDER','Toshiba Tec',null),
('OFFICE-SHREDDER','Lexmark',null),
('OFFICE-FAX','HP',null),
('OFFICE-FAX','Canon',null),
('OFFICE-FAX','Ricoh',null),
('OFFICE-FAX','Xerox',null),
('OFFICE-FAX','Konica Minolta',null),
('OFFICE-FAX','Kyocera',null),
('OFFICE-FAX','Brother',null),
('OFFICE-FAX','Sharp',null),
('OFFICE-FAX','Toshiba Tec',null),
('OFFICE-FAX','Lexmark',null),
('OFFICE-LAMINATOR','HP',null),
('OFFICE-LAMINATOR','Canon',null),
('OFFICE-LAMINATOR','Ricoh',null),
('OFFICE-LAMINATOR','Xerox',null),
('OFFICE-LAMINATOR','Konica Minolta',null),
('OFFICE-LAMINATOR','Kyocera',null),
('OFFICE-LAMINATOR','Brother',null),
('OFFICE-LAMINATOR','Sharp',null),
('OFFICE-LAMINATOR','Toshiba Tec',null),
('OFFICE-LAMINATOR','Lexmark',null),
('AV-VIDEO-WALL','Samsung Display','Commercial Video Wall Displays'),
('AV-VIDEO-WALL','LG Business Solutions','Video Wall Signage'),
('AV-VIDEO-WALL-CTRL','Barco','Video Wall Processing'),
('AV-DSP','Q-SYS / QSC','Q-SYS Core / DSP'),
('AV-DSP','Biamp','Tesira DSP'),
('AV-PTZ-CAMERA','Sony Professional','PTZ Professional Cameras'),
('AV-PROJECTOR-LASER','Epson','Professional Laser Projectors'),
('IT-DESKTOP','HP','ProDesk / EliteDesk'),
('IT-LAPTOP','Dell','Latitude / Precision'),
('IT-WORKSTATION','Lenovo','ThinkStation'),
('IT-SERVER','Hewlett Packard Enterprise','ProLiant'),
('IT-SERVER','Dell EMC','PowerEdge'),
('OFFICE-MFP','Canon','imageRUNNER ADVANCE / DX'),
('OFFICE-MFP','Ricoh','IM / MFP Series'),
('OFFICE-MFP','Xerox','AltaLink / VersaLink'),
('OFFICE-COPIER','Konica Minolta','bizhub'),
('OFFICE-PLOTTER','HP','DesignJet')
)
insert into public.bf_master_asset_options(asset_type_id,manufacturer_id,model_family)
select t.id,m.id,x.model_family
from x
join public.bf_master_asset_types t on t.code=x.asset_code
join public.bf_master_manufacturers m on m.name=x.manufacturer_name
where not exists(
 select 1 from public.bf_master_asset_options o
 where o.asset_type_id=t.id and o.manufacturer_id=m.id
 and coalesce(o.model_family,'')=coalesce(x.model_family,'')
);
update public.bf_master_asset_types
set group_ar=case system_code when 'AV' then 'الأوديو والفيديو والشاشات' when 'IT' then 'أجهزة تقنية المعلومات' when 'OFFICE' then 'الطباعة والنسخ والأجهزة المكتبية' else group_ar end,
    group_en=case system_code when 'AV' then 'Audio Video & Display Systems' when 'IT' then 'IT Endpoints & Compute' when 'OFFICE' then 'Printing, Copying & Office Equipment' else group_en end
where system_code in('AV','IT','OFFICE');
insert into public.bf_master_ppm_templates(asset_type_id,title_ar,title_en,frequency,estimated_minutes,reference,status)
select t.id,
       'الصيانة الدورية - '||t.name_ar,
       'Periodic Maintenance - '||t.name_en,
       case
         when t.system_code='AV' then 'monthly'
         when t.system_code='IT' then 'quarterly'
         else 'monthly'
       end,
       case when t.default_criticality='critical' then 60 when t.default_criticality='high' then 45 else 30 end,
       'Baseline AV/IT/office equipment preventive maintenance; follow OEM documentation and approved support procedures.',
       'active'
from public.bf_master_asset_types t
where t.status='active'
and t.system_code in('AV','IT','OFFICE')
and not exists(select 1 from public.bf_master_ppm_templates p where p.asset_type_id=t.id and p.status='active');
insert into public.bf_master_ppm_steps(template_id,seq,title_ar,title_en,instructions_ar,instructions_en,task_type,response_type,safety_notes)
select p.id,s.seq,s.ar,s.en,s.iar,s.ien,s.task,s.resp,s.safety
from public.bf_master_ppm_templates p
join public.bf_master_asset_types t on t.id=p.asset_type_id
cross join lateral (values
 (1,'فحص الحالة الخارجية والتوصيلات','Inspect physical condition and connections','افحص الهيكل والكابلات والطاقة والمنافذ والتثبيت ونظافة فتحات التهوية.','Inspect chassis, cables, power, ports, mounting and ventilation cleanliness.','inspection','pass_fail',null),
 (2,'تنظيف وقائي','Preventive cleaning','نظف الأسطح وفتحات التهوية والمراوح والأجزاء المسموح تنظيفها حسب تعليمات المصنع.','Clean surfaces, vents, fans and permitted areas according to OEM instructions.','cleaning','pass_fail',null),
 (3,'اختبار الوظائف','Functional test','اختبر الوظائف الأساسية مثل الصورة والصوت والطباعة والمسح والاتصال بحسب نوع الجهاز.','Test core functions such as video, audio, printing, scanning or connectivity as applicable.','test','text',null),
 (4,'فحص البرامج والفيرموير','Software and firmware review','تحقق من الإصدارات المعتمدة والتحديثات والنسخ الاحتياطي للإعدادات عند الحاجة.','Verify approved software/firmware versions, updates and configuration backup where applicable.','inspection','text',null),
 (5,'فحص القطع الاستهلاكية','Check consumables and wear parts','افحص التونر والحبر والرولات والفلاتر والمراوح والبطاريات والمصابيح أو الليزر حسب الجهاز.','Inspect toner, ink, rollers, filters, fans, batteries, lamps or laser modules as applicable.','inspection','text',null),
 (6,'توثيق العطل والقطعة المطلوبة','Record faults and required parts','سجل أي عطل أو قطعة غيار أو Long Lead Item مطلوبة واربطها بأمر عمل أو طلب شراء.','Record defects, spare parts or long-lead items and link to a work order or procurement request.','other','text',null)
) s(seq,ar,en,iar,ien,task,resp,safety)
where t.system_code in('AV','IT','OFFICE')
and not exists(select 1 from public.bf_master_ppm_steps z where z.template_id=p.id)
on conflict(template_id,seq) do nothing;
notify pgrst,'reload schema';
commit;
