begin;

alter table public.bf_master_asset_types add column if not exists icon_text text not null default '🔧';
alter table public.bf_master_asset_types add column if not exists group_ar text;
alter table public.bf_master_asset_types add column if not exists group_en text;
alter table public.bf_master_manufacturers add column if not exists short_name text;

alter table public.bf_asset_categories add column if not exists icon_text text;
alter table public.bf_asset_categories add column if not exists master_asset_type_id uuid references public.bf_master_asset_types(id) on delete set null;
alter table public.bf_asset_categories add column if not exists preferred_manufacturer_id uuid references public.bf_master_manufacturers(id) on delete set null;


insert into public.bf_master_asset_types(system_code,code,name_ar,name_en,default_criticality,expected_life_years,icon_text)
values
('HVAC','HVAC-WINDOW','مكيف شباك','Window AC','medium',10,'❄️'),
('HVAC','HVAC-SPLIT','مكيف سبليت','Split AC','medium',12,'❄️'),
('HVAC','HVAC-CASSETTE','مكيف كاسيت','Cassette AC','medium',12,'❄️'),
('HVAC','HVAC-DUCTED-SPLIT','مكيف مخفي دكت','Ducted Split AC','high',15,'❄️'),
('HVAC','HVAC-PACKAGE','مكيف باكيج','Package AC Unit','high',15,'❄️'),
('HVAC','HVAC-ROOFTOP','وحدة روف توب','Rooftop Unit','high',15,'❄️'),
('HVAC','HVAC-AHU','وحدة مناولة هواء AHU','Air Handling Unit','high',18,'🌬️'),
('HVAC','HVAC-FAHU','وحدة هواء نقي FAHU','Fresh Air Handling Unit','high',18,'🌬️'),
('HVAC','HVAC-FCU','وحدة ملف ومروحة FCU','Fan Coil Unit','medium',15,'🌬️'),
('HVAC','HVAC-VAV','صندوق VAV','VAV Box','medium',15,'🌬️'),
('HVAC','HVAC-VRF','نظام VRF/VRV','VRF / VRV System','high',15,'❄️'),
('HVAC','HVAC-CHILLER-AIR','شيلر تبريد هوائي','Air-Cooled Chiller','critical',20,'🧊'),
('HVAC','HVAC-CHILLER-WATER','شيلر تبريد مائي','Water-Cooled Chiller','critical',25,'🧊'),
('HVAC','HVAC-COOLING-TOWER','برج تبريد','Cooling Tower','critical',20,'🌫️'),
('HVAC','HVAC-PUMP-CHW','مضخة مياه مبردة','Chilled Water Pump','high',15,'💧'),
('HVAC','HVAC-PUMP-CW','مضخة مياه مكثف','Condenser Water Pump','high',15,'💧'),
('HVAC','HVAC-HEX','مبادل حراري','Heat Exchanger','high',20,'♨️'),
('HVAC','HVAC-EXHAUST-FAN','مروحة شفط','Exhaust Fan','medium',12,'🌀'),
('HVAC','HVAC-FRESH-AIR-FAN','مروحة هواء نقي','Fresh Air Fan','medium',12,'🌀'),
('HVAC','HVAC-STAIR-PRESS','مروحة ضغط السلالم','Staircase Pressurization Fan','critical',15,'🌀'),
('HVAC','HVAC-SMOKE-EXTRACT','مروحة سحب دخان','Smoke Extract Fan','critical',15,'🌀'),
('HVAC','HVAC-JET-FAN','مروحة نفاثة للمواقف','Car Park Jet Fan','high',15,'🌀'),
('HVAC','HVAC-DAMPER','دامبر هواء','Air Damper','medium',15,'▤'),
('HVAC','HVAC-FIRE-DAMPER','دامبر حريق/دخان','Fire / Smoke Damper','critical',20,'🔥'),
('HVAC','HVAC-HUMIDIFIER','مرطب هواء','Humidifier','medium',10,'💨'),
('HVAC','HVAC-DEHUMIDIFIER','مزيل رطوبة','Dehumidifier','medium',10,'💨'),
('BMS','BMS-SERVER','خادم BMS','BMS Server','critical',8,'🖥️'),
('BMS','BMS-WORKSTATION','محطة تشغيل BMS','BMS Workstation','high',7,'🖥️'),
('BMS','BMS-CONTROLLER','كنترولر BMS','BMS Controller','high',12,'🎛️'),
('BMS','BMS-SENSOR','حساس BMS','BMS Sensor','medium',10,'🌡️'),
('BMS','BMS-ACTUATOR','مشغل صمام/دامبر','Valve / Damper Actuator','medium',10,'⚙️'),
('BMS','BMS-GATEWAY','بوابة BACnet/Modbus','BACnet / Modbus Gateway','high',10,'🔗'),
('BMS','BMS-ENERGY-METER','عداد طاقة مرتبط BMS','BMS Energy Meter','high',12,'⚡'),
('BMS','BMS-VFD','مغير سرعة VFD','Variable Frequency Drive','high',12,'🔄'),
('FIRE_ALARM','FIRE-ALARM-PANEL','لوحة إنذار حريق','Fire Alarm Control Panel','critical',15,'🚨'),
('FIRE_ALARM','FIRE-REPEATER','لوحة تكرار إنذار','Fire Alarm Repeater Panel','high',15,'🚨'),
('FIRE_ALARM','FIRE-SMOKE','كاشف دخان','Smoke Detector','high',10,'💨'),
('FIRE_ALARM','FIRE-HEAT','كاشف حرارة','Heat Detector','high',10,'🌡️'),
('FIRE_ALARM','FIRE-BEAM','كاشف شعاعي','Beam Detector','high',10,'📡'),
('FIRE_ALARM','FIRE-ASD','نظام كشف دخان بالشفط','Aspirating Smoke Detection','critical',12,'🧪'),
('FIRE_ALARM','FIRE-MCP','نقطة نداء يدوية','Manual Call Point','high',15,'🛑'),
('FIRE_ALARM','FIRE-SOUNDER','جرس/ساوندر حريق','Fire Sounder / Bell','high',15,'🔔'),
('FIRE_ALARM','FIRE-STROBE','فلاش إنذار حريق','Fire Alarm Strobe','high',15,'💡'),
('FIRE_ALARM','FIRE-IO-MODULE','موديول إنذار حريق','Fire Alarm I/O Module','high',12,'🔌'),
('FIRE_ALARM','FIRE-VOICE-EVAC','نظام إخلاء صوتي','Voice Evacuation System','critical',15,'📢'),
('FIRE_SUPPRESSION','FIRE-FM200','نظام إطفاء FM-200','FM-200 Suppression System','critical',20,'🧯'),
('FIRE_SUPPRESSION','FIRE-NOVEC','نظام Novec 1230 قائم','Existing Novec 1230 System','critical',20,'🧯'),
('FIRE_SUPPRESSION','FIRE-INERT-GAS','نظام غاز خامل','Inert Gas Suppression System','critical',25,'🧯'),
('FIRE_SUPPRESSION','FIRE-CO2','نظام إطفاء CO2','CO2 Suppression System','critical',25,'🧯'),
('FIRE_SUPPRESSION','FIRE-KITCHEN-HOOD','نظام إطفاء هود المطابخ','Kitchen Hood Suppression','critical',15,'🍳'),
('FIRE_SUPPRESSION','FIRE-PUMP-ELECTRIC','مضخة حريق كهربائية','Electric Fire Pump','critical',20,'🚒'),
('FIRE_SUPPRESSION','FIRE-PUMP-DIESEL','مضخة حريق ديزل','Diesel Fire Pump','critical',20,'🚒'),
('FIRE_SUPPRESSION','FIRE-JOCKEY','مضخة جوكي','Jockey Pump','critical',15,'🚒'),
('FIRE_SUPPRESSION','FIRE-SPRINKLER','شبكة رش آلي','Fire Sprinkler System','critical',25,'💦'),
('FIRE_SUPPRESSION','FIRE-HYDRANT','شبكة هيدرنت','Fire Hydrant System','critical',30,'🚒'),
('FIRE_SUPPRESSION','FIRE-HOSE-REEL','بكرة خرطوم حريق','Fire Hose Reel','high',20,'🧯'),
('FIRE_SUPPRESSION','FIRE-EXTINGUISHER','طفاية حريق','Portable Fire Extinguisher','high',12,'🧯'),
('FIRE_SUPPRESSION','FIRE-DELUGE','نظام Deluge','Deluge System','critical',25,'💦'),
('FIRE_SUPPRESSION','FIRE-PREACTION','نظام Pre-action','Pre-action Sprinkler System','critical',25,'💦'),
('ELECTRICAL','ELEC-RMU','وحدة RMU','Ring Main Unit','critical',25,'⚡'),
('ELECTRICAL','ELEC-MV-SWGR','سويتشجير جهد متوسط','MV Switchgear','critical',30,'⚡'),
('ELECTRICAL','ELEC-TRANSFORMER','محول كهربائي','Transformer','critical',30,'🔋'),
('ELECTRICAL','ELEC-MDB','لوحة MDB','Main Distribution Board','critical',25,'⚡'),
('ELECTRICAL','ELEC-SMDB','لوحة SMDB','Sub Main Distribution Board','high',25,'⚡'),
('ELECTRICAL','ELEC-DB','لوحة DB','Distribution Board','high',20,'⚡'),
('ELECTRICAL','ELEC-MCC','لوحة MCC','Motor Control Center','critical',25,'⚙️'),
('ELECTRICAL','ELEC-ATS','مفتاح ATS','Automatic Transfer Switch','critical',20,'🔀'),
('ELECTRICAL','ELEC-GENERATOR','مولد ديزل','Diesel Generator','critical',20,'🔌'),
('ELECTRICAL','ELEC-UPS','UPS','UPS','critical',12,'🔋'),
('ELECTRICAL','ELEC-BATTERY','بنك بطاريات','Battery Bank','high',6,'🔋'),
('ELECTRICAL','ELEC-CAPBANK','بنك مكثفات','Capacitor Bank','high',15,'⚡'),
('ELECTRICAL','ELEC-APFC','لوحة تصحيح معامل القدرة','APFC Panel','high',15,'⚡'),
('ELECTRICAL','ELEC-PQ-METER','محلل جودة الطاقة','Power Quality Meter','high',12,'📈'),
('ELECTRICAL','ELEC-ENERGY-METER','عداد طاقة','Energy Meter','medium',15,'📟'),
('ELECTRICAL','ELEC-LIGHTING-PANEL','لوحة إنارة','Lighting Control Panel','medium',20,'💡'),
('ELECTRICAL','ELEC-EM-LIGHT','إنارة طوارئ','Emergency Light','high',10,'💡'),
('ELECTRICAL','ELEC-EXIT-SIGN','لوحة مخرج طوارئ','Exit Sign','high',10,'🚪'),
('ELECTRICAL','ELEC-LIGHTNING','نظام مانع صواعق','Lightning Protection System','critical',30,'🌩️'),
('ELECTRICAL','ELEC-EARTHING','نظام التأريض','Earthing System','critical',30,'⏚'),
('ELECTRICAL','ELEC-BUSBAR','بسبار ترنك','Busbar Trunking','critical',25,'⚡'),
('ENERGY','SOLAR-PV','ألواح طاقة شمسية','Solar PV Array','high',25,'☀️'),
('ENERGY','SOLAR-INVERTER','انفرتر شمسي','Solar Inverter','high',15,'🔆'),
('ENERGY','SOLAR-BATTERY','بطارية تخزين طاقة','Energy Storage Battery','high',12,'🔋'),
('ENERGY','EV-CHARGER','شاحن مركبات كهربائية','EV Charger','high',12,'🚗'),
('PLUMBING','PLUMB-BOOSTER','مجموعة مضخات تقوية','Booster Pump Set','high',15,'💧'),
('PLUMBING','PLUMB-TRANSFER','مضخة نقل مياه','Water Transfer Pump','high',15,'💧'),
('PLUMBING','PLUMB-SUMP','مضخة تجميع','Sump Pump','high',10,'💧'),
('PLUMBING','PLUMB-SEWAGE','مضخة صرف','Sewage Pump','high',12,'💧'),
('PLUMBING','PLUMB-LIFT-STATION','محطة رفع صرف','Sewage Lift Station','critical',20,'💧'),
('PLUMBING','PLUMB-COLD-TANK','خزان مياه باردة','Cold Water Tank','high',25,'🚰'),
('PLUMBING','PLUMB-HOT-TANK','خزان مياه ساخنة','Hot Water Storage Tank','high',20,'♨️'),
('PLUMBING','PLUMB-WATER-HEATER','سخان مياه','Water Heater','medium',12,'♨️'),
('PLUMBING','PLUMB-CALORIFIER','كالوريفاير','Calorifier','high',18,'♨️'),
('PLUMBING','PLUMB-PRV','صمام تخفيض ضغط','Pressure Reducing Valve','high',15,'🔧'),
('PLUMBING','PLUMB-GREASE-TRAP','مصيدة دهون','Grease Trap','medium',15,'🧼'),
('PLUMBING','PLUMB-OIL-SEPARATOR','فاصل زيوت','Oil Separator','medium',15,'🛢️'),
('WATER','RO-SYSTEM','نظام RO','Reverse Osmosis System','high',15,'💧'),
('WATER','WATER-SOFTENER','منعم مياه','Water Softener','medium',15,'💧'),
('WATER','UF-SYSTEM','نظام ترشيح فائق UF','Ultrafiltration System','high',15,'💧'),
('WATER','UV-STERILIZER','معقم UV','UV Water Sterilizer','high',10,'☀️'),
('WATER','DOSING-SYSTEM','نظام حقن كيماويات','Chemical Dosing System','high',10,'🧪'),
('WATER','CHLORINATION','نظام كلورة','Chlorination System','high',12,'🧪'),
('WATER','STP','محطة معالجة صرف','Sewage Treatment Plant','critical',25,'♻️'),
('WATER','GREYWATER','محطة مياه رمادية','Greywater Treatment System','high',20,'♻️'),
('IRRIGATION','IRR-PUMP','مضخة ري','Irrigation Pump','medium',15,'🌿'),
('IRRIGATION','IRR-CONTROLLER','كنترولر ري','Irrigation Controller','medium',10,'🌿'),
('IRRIGATION','IRR-VALVE','صمام ري','Irrigation Solenoid Valve','low',10,'🌿'),
('IRRIGATION','FOUNTAIN-PUMP','مضخة نافورة','Fountain Pump','medium',12,'⛲'),
('VERTICAL','LIFT-PASSENGER','مصعد ركاب','Passenger Elevator','critical',25,'🛗'),
('VERTICAL','LIFT-SERVICE','مصعد خدمة','Service Elevator','critical',25,'🛗'),
('VERTICAL','LIFT-FREIGHT','مصعد بضائع','Freight Elevator','critical',25,'🛗'),
('VERTICAL','ESCALATOR','سلم متحرك','Escalator','critical',25,'↗️'),
('VERTICAL','TRAVELATOR','ممر متحرك','Moving Walkway','critical',25,'➡️'),
('VERTICAL','PLATFORM-LIFT','منصة رفع ذوي الإعاقة','Accessibility Platform Lift','high',20,'♿'),
('SECURITY','SEC-CCTV-FIXED','كاميرا ثابتة','Fixed CCTV Camera','medium',8,'📷'),
('SECURITY','SEC-CCTV-DOME','كاميرا Dome','Dome CCTV Camera','medium',8,'📷'),
('SECURITY','SEC-CCTV-PTZ','كاميرا PTZ','PTZ Camera','high',8,'📹'),
('SECURITY','SEC-THERMAL','كاميرا حرارية','Thermal Camera','high',8,'🌡️'),
('SECURITY','SEC-NVR','مسجل NVR','Network Video Recorder','high',7,'💾'),
('SECURITY','SEC-VMS','خادم VMS','Video Management Server','critical',7,'🖥️'),
('SECURITY','SEC-ACS','لوحة تحكم دخول','Access Control Panel','high',10,'🔐'),
('SECURITY','SEC-READER','قارئ دخول','Access Card Reader','medium',8,'💳'),
('SECURITY','SEC-BIOMETRIC','قارئ بصمة/وجه','Biometric Reader','medium',7,'👤'),
('SECURITY','SEC-TURNSTILE','بوابة أفراد Turnstile','Turnstile','high',12,'🚷'),
('SECURITY','SEC-BOLLARD','بولارد أمني','Security Bollard','high',15,'🚧'),
('SECURITY','SEC-UVSS','نظام فحص أسفل المركبات','Under Vehicle Surveillance System','high',10,'🚗'),
('SECURITY','SEC-XRAY','جهاز فحص حقائب X-Ray','Baggage X-Ray Scanner','high',10,'🧳'),
('SECURITY','SEC-METAL-DETECTOR','بوابة كشف معادن','Walk-through Metal Detector','high',10,'🚪'),
('ELV','PA-AMPLIFIER','مضخم نظام النداء','PA Amplifier','high',10,'📢'),
('ELV','PA-SPEAKER','سماعة نداء','PA Speaker','medium',12,'🔊'),
('ELV','INTERCOM','نظام إنتركوم','Intercom System','medium',10,'☎️'),
('ELV','MASTER-CLOCK','نظام ساعة مركزية','Master Clock System','medium',12,'🕒'),
('ELV','SMATV','نظام تلفزيون مركزي','SMATV / IPTV Headend','medium',10,'📺'),
('ICT','ICT-CORE-SWITCH','سويتش كور','Core Network Switch','critical',8,'🌐'),
('ICT','ICT-ACCESS-SWITCH','سويتش أكسس','Access Network Switch','high',8,'🌐'),
('ICT','ICT-ROUTER','راوتر','Router','critical',8,'🌐'),
('ICT','ICT-FIREWALL','جدار ناري','Network Firewall','critical',7,'🛡️'),
('ICT','ICT-WLC','كنترولر واي فاي','Wireless LAN Controller','high',7,'📶'),
('ICT','ICT-AP','نقطة وصول Wi-Fi','Wireless Access Point','medium',7,'📶'),
('ICT','ICT-RACK','راك اتصالات','ICT Rack','medium',20,'🗄️'),
('ICT','ICT-FIBER-PANEL','باتش بانل فايبر','Fiber Patch Panel','medium',20,'🔗'),
('ICT','ICT-COPPER-PANEL','باتش بانل نحاس','Copper Patch Panel','medium',20,'🔗'),
('ICT','ICT-OLT','جهاز OLT','Optical Line Terminal','high',10,'🌐'),
('ICT','ICT-GPON','شبكة GPON','GPON System','high',15,'🌐'),
('DATACENTER','DC-CRAC','CRAC','CRAC Precision Cooling','critical',15,'❄️'),
('DATACENTER','DC-CRAH','CRAH','CRAH Precision Cooling','critical',15,'❄️'),
('DATACENTER','DC-INROW','تكييف InRow','InRow Cooling','critical',12,'❄️'),
('DATACENTER','DC-PDU','PDU','Power Distribution Unit','critical',15,'⚡'),
('DATACENTER','DC-RPP','RPP','Remote Power Panel','critical',15,'⚡'),
('DATACENTER','DC-UPS','UPS داتا سنتر','Data Center UPS','critical',12,'🔋'),
('DATACENTER','DC-RACK','راك داتا سنتر','Data Center Rack','high',20,'🗄️'),
('DATACENTER','DC-CONTAINMENT','احتواء ممر حار/بارد','Hot / Cold Aisle Containment','high',20,'🏢'),
('DATACENTER','DC-LEAK-DETECT','كشف تسرب مياه','Water Leak Detection System','critical',10,'💧'),
('DATACENTER','DC-ENV-MON','مراقبة بيئية','Environmental Monitoring System','critical',10,'🌡️'),
('PARKING','PARK-BARRIER','بوابة مواقف','Parking Barrier Gate','medium',12,'🚧'),
('PARKING','PARK-LPR','كاميرا قراءة لوحات','LPR / ANPR Camera','high',8,'🚗'),
('PARKING','PARK-GUIDANCE','نظام توجيه مواقف','Parking Guidance System','medium',10,'🅿️'),
('PARKING','PARK-PAY','جهاز دفع مواقف','Parking Payment Station','medium',10,'💳'),
('GENERAL','AUTO-DOOR','باب أوتوماتيكي','Automatic Door','medium',12,'🚪'),
('GENERAL','SLIDING-GATE','بوابة منزلقة','Sliding Gate','medium',15,'🚪'),
('GENERAL','ROLLING-SHUTTER','باب رول','Rolling Shutter','medium',15,'🚪'),
('GENERAL','SECTIONAL-DOOR','باب سكشن','Sectional Door','medium',15,'🚪'),
('GENERAL','DOCK-LEVELLER','منصة تحميل','Dock Leveller','high',15,'📦'),
('GENERAL','FACADE-BMU','وحدة صيانة واجهات BMU','Building Maintenance Unit','critical',20,'🏗️'),
('GENERAL','ROOF-WATERPROOF','نظام عزل سطح','Roof Waterproofing System','high',20,'🏢'),
('GENERAL','EXPANSION-JOINT','فاصل تمدد','Expansion Joint','medium',20,'↔️'),
('KITCHEN','KITCHEN-HOOD','هود مطبخ','Kitchen Exhaust Hood','high',15,'🍳'),
('KITCHEN','KITCHEN-DISHWASHER','غسالة صحون تجارية','Commercial Dishwasher','medium',10,'🍽️'),
('KITCHEN','KITCHEN-OVEN','فرن تجاري','Commercial Oven','medium',12,'🔥'),
('KITCHEN','KITCHEN-COOKER','بوتاجاز/رينج تجاري','Commercial Range','medium',12,'🔥'),
('KITCHEN','KITCHEN-COLDROOM','غرفة تبريد','Cold Room','high',15,'🧊'),
('KITCHEN','KITCHEN-FREEZER','فريزر تجاري','Commercial Freezer','high',12,'🧊'),
('LAUNDRY','LAUNDRY-WASHER','غسالة صناعية','Industrial Washer','medium',12,'🧺'),
('LAUNDRY','LAUNDRY-DRYER','مجفف صناعي','Industrial Dryer','medium',12,'🧺'),
('LAUNDRY','LAUNDRY-IRONER','مكواة رول صناعية','Flatwork Ironer','medium',15,'🧺'),
('GAS','LPG-TANK','خزان LPG','LPG Tank','critical',25,'⛽'),
('GAS','LPG-DETECTOR','كاشف غاز','Gas Detector','critical',8,'⚠️'),
('GAS','FUEL-TANK','خزان ديزل','Diesel Fuel Tank','critical',25,'⛽'),
('GAS','FUEL-TRANSFER-PUMP','مضخة نقل ديزل','Fuel Transfer Pump','high',15,'⛽'),
('POOL','POOL-PUMP','مضخة مسبح','Swimming Pool Pump','medium',12,'🏊'),
('POOL','POOL-FILTER','فلتر مسبح','Swimming Pool Filter','medium',12,'🏊'),
('POOL','POOL-DOSING','نظام معالجة كيميائية للمسبح','Pool Chemical Dosing System','high',10,'🧪'),
('HEALTHCARE','MED-GAS-MANIFOLD','مانيفولد غازات طبية','Medical Gas Manifold','critical',15,'🏥'),
('HEALTHCARE','MED-GAS-ALARM','لوحة إنذار غازات طبية','Medical Gas Alarm Panel','critical',12,'🚨'),
('HEALTHCARE','NURSE-CALL','نظام نداء ممرضات','Nurse Call System','critical',10,'🔔'),
('PUBLIC','ABLUTION-PUMP','مضخة مرافق وضوء','Ablution Water Pump','medium',12,'🚰'),
('PUBLIC','PRAYER-AUDIO','نظام صوت المساجد','Mosque Audio System','high',10,'🔊')
on conflict(code) do update set
 system_code=excluded.system_code,
 name_ar=excluded.name_ar,
 name_en=excluded.name_en,
 default_criticality=excluded.default_criticality,
 expected_life_years=excluded.expected_life_years,
 icon_text=excluded.icon_text,
 status='active';


insert into public.bf_master_manufacturers(code,name,short_name)
values
('ZAMIL','Zamil Air Conditioners','Zamil'),
('CARRIER','Carrier','Carrier'),
('TRANE','Trane','Trane'),
('YORK','YORK / Johnson Controls','YORK'),
('DAIKIN','Daikin','Daikin'),
('MITSUBISHI','Mitsubishi Electric','Mitsubishi'),
('LG','LG','LG'),
('SAMSUNG','Samsung','Samsung'),
('GREE','Gree','Gree'),
('MIDEA','Midea','Midea'),
('SKM','SKM Air Conditioning','SKM'),
('PETRA','Petra Engineering','Petra'),
('DUNHAM','Dunham-Bush','Dunham-Bush'),
('JCI','Johnson Controls','Johnson'),
('HONEYWELL','Honeywell','Honeywell'),
('SIEMENS','Siemens','Siemens'),
('SCHNEIDER','Schneider Electric','Schneider'),
('DELTA','Delta Controls','Delta'),
('TRIDIUM','Tridium','Tridium'),
('DISTECH','Distech Controls','Distech'),
('ALC','Automated Logic','Automated'),
('NOTIFIER','NOTIFIER by Honeywell','NOTIFIER'),
('SIMPLEX','Simplex / Johnson Controls','Simplex'),
('EDWARDS','Edwards / EST','Edwards'),
('HOCHIKI','Hochiki','Hochiki'),
('APOLLO','Apollo Fire Detectors','Apollo'),
('GENT','Gent by Honeywell','Gent'),
('GST','GST','GST'),
('BOSCH','Bosch','Bosch'),
('KIDDE','Kidde','Kidde'),
('ANSUL','ANSUL','ANSUL'),
('VIKING','Viking','Viking'),
('TYCO','Tyco Fire Protection','Tyco'),
('RELIABLE','Reliable','Reliable'),
('VICTAULIC','Victaulic','Victaulic'),
('NAFFCO','NAFFCO','NAFFCO'),
('SFFECO','SFFECO','SFFECO'),
('PATTERSON','Patterson Pump','Patterson'),
('ABB','ABB','ABB'),
('EATON','Eaton','Eaton'),
('LEGRAND','Legrand','Legrand'),
('ALFANAR','alfanar','alfanar'),
('SOCOMEC','Socomec','Socomec'),
('LS','LS Electric','LS'),
('LUCY','Lucy Electric','Lucy'),
('CUMMINS','Cummins','Cummins'),
('CATERPILLAR','Caterpillar','Caterpillar'),
('PERKINS','Perkins','Perkins'),
('FGWILSON','FG Wilson','FG'),
('MTU','MTU / Rolls-Royce Power Systems','MTU'),
('KOHLER','Kohler','Kohler'),
('VOLVOPENTA','Volvo Penta','Volvo'),
('VERTIV','Vertiv','Vertiv'),
('APC','APC by Schneider Electric','APC'),
('HUAWEI','Huawei','Huawei'),
('RIELLO','Riello UPS','Riello'),
('BORRI','Borri','Borri'),
('STULZ','STULZ','STULZ'),
('RITTAL','Rittal','Rittal'),
('GRUNDFOS','Grundfos','Grundfos'),
('KSB','KSB','KSB'),
('WILO','Wilo','Wilo'),
('XYLEM','Xylem','Xylem'),
('LOWARA','Lowara','Lowara'),
('FLYGT','Flygt','Flygt'),
('ARMSTRONG','Armstrong Fluid Technology','Armstrong'),
('EBARA','Ebara','Ebara'),
('PENTAIR','Pentair','Pentair'),
('KONE','KONE','KONE'),
('OTIS','Otis','Otis'),
('SCHINDLER','Schindler','Schindler'),
('TKE','TK Elevator','TK'),
('FUJITEC','Fujitec','Fujitec'),
('HITACHI','Hitachi','Hitachi'),
('HYUNDAI','Hyundai Elevator','Hyundai'),
('AXIS','Axis Communications','Axis'),
('HIKVISION','Hikvision','Hikvision'),
('DAHUA','Dahua','Dahua'),
('HANWHA','Hanwha Vision','Hanwha'),
('AVIGILON','Avigilon','Avigilon'),
('PELCO','Pelco','Pelco'),
('MILESTONE','Milestone Systems','Milestone'),
('GENETEC','Genetec','Genetec'),
('HID','HID Global','HID'),
('LENEL','LenelS2','LenelS2'),
('GALLAGHER','Gallagher Security','Gallagher'),
('SUPREMA','Suprema','Suprema'),
('ZKTECO','ZKTeco','ZKTeco'),
('CISCO','Cisco','Cisco'),
('ARUBA','HPE Aruba Networking','HPE'),
('JUNIPER','Juniper Networks','Juniper'),
('FORTINET','Fortinet','Fortinet'),
('RUCKUS','Ruckus Networks','Ruckus'),
('COMMSCOPE','CommScope','CommScope'),
('PANDUIT','Panduit','Panduit'),
('DORMAKABA','dormakaba','dormakaba'),
('ASSA','ASSA ABLOY','ASSA'),
('GEZE','GEZE','GEZE'),
('FAAC','FAAC','FAAC'),
('CAME','CAME','CAME'),
('MEIKO','MEIKO','MEIKO'),
('WINTERHALTER','Winterhalter','Winterhalter'),
('RATIONAL','RATIONAL','RATIONAL'),
('HOBART','Hobart','Hobart'),
('ELECTROLUXPRO','Electrolux Professional','Electrolux'),
('VEOLIA','Veolia Water Technologies','Veolia'),
('SUEZ','SUEZ Water Technologies','SUEZ'),
('CULLIGAN','Culligan','Culligan'),
('DANFOSS','Danfoss','Danfoss')
on conflict(code) do update set name=excluded.name,short_name=excluded.short_name,status='active';


with x(asset_code,manufacturer_code,model_family) as (values
('HVAC-WINDOW','ZAMIL',null),
('HVAC-WINDOW','CARRIER',null),
('HVAC-WINDOW','TRANE',null),
('HVAC-WINDOW','YORK',null),
('HVAC-WINDOW','DAIKIN',null),
('HVAC-WINDOW','MITSUBISHI',null),
('HVAC-WINDOW','LG',null),
('HVAC-WINDOW','SAMSUNG',null),
('HVAC-SPLIT','ZAMIL',null),
('HVAC-SPLIT','CARRIER',null),
('HVAC-SPLIT','TRANE',null),
('HVAC-SPLIT','YORK',null),
('HVAC-SPLIT','DAIKIN',null),
('HVAC-SPLIT','MITSUBISHI',null),
('HVAC-SPLIT','LG',null),
('HVAC-SPLIT','SAMSUNG',null),
('HVAC-CASSETTE','ZAMIL',null),
('HVAC-CASSETTE','CARRIER',null),
('HVAC-CASSETTE','TRANE',null),
('HVAC-CASSETTE','YORK',null),
('HVAC-CASSETTE','DAIKIN',null),
('HVAC-CASSETTE','MITSUBISHI',null),
('HVAC-CASSETTE','LG',null),
('HVAC-CASSETTE','SAMSUNG',null),
('HVAC-DUCTED-SPLIT','ZAMIL',null),
('HVAC-DUCTED-SPLIT','CARRIER',null),
('HVAC-DUCTED-SPLIT','TRANE',null),
('HVAC-DUCTED-SPLIT','YORK',null),
('HVAC-DUCTED-SPLIT','DAIKIN',null),
('HVAC-DUCTED-SPLIT','MITSUBISHI',null),
('HVAC-DUCTED-SPLIT','LG',null),
('HVAC-DUCTED-SPLIT','SAMSUNG',null),
('HVAC-PACKAGE','ZAMIL',null),
('HVAC-PACKAGE','CARRIER',null),
('HVAC-PACKAGE','TRANE',null),
('HVAC-PACKAGE','YORK',null),
('HVAC-PACKAGE','DAIKIN',null),
('HVAC-PACKAGE','MITSUBISHI',null),
('HVAC-PACKAGE','LG',null),
('HVAC-PACKAGE','SAMSUNG',null),
('HVAC-ROOFTOP','ZAMIL',null),
('HVAC-ROOFTOP','CARRIER',null),
('HVAC-ROOFTOP','TRANE',null),
('HVAC-ROOFTOP','YORK',null),
('HVAC-ROOFTOP','DAIKIN',null),
('HVAC-ROOFTOP','MITSUBISHI',null),
('HVAC-ROOFTOP','LG',null),
('HVAC-ROOFTOP','SAMSUNG',null),
('HVAC-AHU','ZAMIL',null),
('HVAC-AHU','CARRIER',null),
('HVAC-AHU','TRANE',null),
('HVAC-AHU','YORK',null),
('HVAC-AHU','DAIKIN',null),
('HVAC-AHU','MITSUBISHI',null),
('HVAC-AHU','LG',null),
('HVAC-AHU','SAMSUNG',null),
('HVAC-FAHU','ZAMIL',null),
('HVAC-FAHU','CARRIER',null),
('HVAC-FAHU','TRANE',null),
('HVAC-FAHU','YORK',null),
('HVAC-FAHU','DAIKIN',null),
('HVAC-FAHU','MITSUBISHI',null),
('HVAC-FAHU','LG',null),
('HVAC-FAHU','SAMSUNG',null),
('HVAC-FCU','ZAMIL',null),
('HVAC-FCU','CARRIER',null),
('HVAC-FCU','TRANE',null),
('HVAC-FCU','YORK',null),
('HVAC-FCU','DAIKIN',null),
('HVAC-FCU','MITSUBISHI',null),
('HVAC-FCU','LG',null),
('HVAC-FCU','SAMSUNG',null),
('HVAC-VAV','ZAMIL',null),
('HVAC-VAV','CARRIER',null),
('HVAC-VAV','TRANE',null),
('HVAC-VAV','YORK',null),
('HVAC-VAV','DAIKIN',null),
('HVAC-VAV','MITSUBISHI',null),
('HVAC-VAV','LG',null),
('HVAC-VAV','SAMSUNG',null),
('HVAC-VRF','ZAMIL',null),
('HVAC-VRF','CARRIER',null),
('HVAC-VRF','TRANE',null),
('HVAC-VRF','YORK',null),
('HVAC-VRF','DAIKIN',null),
('HVAC-VRF','MITSUBISHI',null),
('HVAC-VRF','LG',null),
('HVAC-VRF','SAMSUNG',null),
('HVAC-CHILLER-AIR','ZAMIL',null),
('HVAC-CHILLER-AIR','CARRIER',null),
('HVAC-CHILLER-AIR','TRANE',null),
('HVAC-CHILLER-AIR','YORK',null),
('HVAC-CHILLER-AIR','DAIKIN',null),
('HVAC-CHILLER-AIR','MITSUBISHI',null),
('HVAC-CHILLER-AIR','LG',null),
('HVAC-CHILLER-AIR','SAMSUNG',null),
('HVAC-CHILLER-WATER','ZAMIL',null),
('HVAC-CHILLER-WATER','CARRIER',null),
('HVAC-CHILLER-WATER','TRANE',null),
('HVAC-CHILLER-WATER','YORK',null),
('HVAC-CHILLER-WATER','DAIKIN',null),
('HVAC-CHILLER-WATER','MITSUBISHI',null),
('HVAC-CHILLER-WATER','LG',null),
('HVAC-CHILLER-WATER','SAMSUNG',null),
('HVAC-COOLING-TOWER','ZAMIL',null),
('HVAC-COOLING-TOWER','CARRIER',null),
('HVAC-COOLING-TOWER','TRANE',null),
('HVAC-COOLING-TOWER','YORK',null),
('HVAC-COOLING-TOWER','DAIKIN',null),
('HVAC-COOLING-TOWER','MITSUBISHI',null),
('HVAC-COOLING-TOWER','LG',null),
('HVAC-COOLING-TOWER','SAMSUNG',null),
('HVAC-PUMP-CHW','ZAMIL',null),
('HVAC-PUMP-CHW','CARRIER',null),
('HVAC-PUMP-CHW','TRANE',null),
('HVAC-PUMP-CHW','YORK',null),
('HVAC-PUMP-CHW','DAIKIN',null),
('HVAC-PUMP-CHW','MITSUBISHI',null),
('HVAC-PUMP-CHW','LG',null),
('HVAC-PUMP-CHW','SAMSUNG',null),
('HVAC-PUMP-CW','ZAMIL',null),
('HVAC-PUMP-CW','CARRIER',null),
('HVAC-PUMP-CW','TRANE',null),
('HVAC-PUMP-CW','YORK',null),
('HVAC-PUMP-CW','DAIKIN',null),
('HVAC-PUMP-CW','MITSUBISHI',null),
('HVAC-PUMP-CW','LG',null),
('HVAC-PUMP-CW','SAMSUNG',null),
('HVAC-HEX','ZAMIL',null),
('HVAC-HEX','CARRIER',null),
('HVAC-HEX','TRANE',null),
('HVAC-HEX','YORK',null),
('HVAC-HEX','DAIKIN',null),
('HVAC-HEX','MITSUBISHI',null),
('HVAC-HEX','LG',null),
('HVAC-HEX','SAMSUNG',null),
('HVAC-EXHAUST-FAN','ZAMIL',null),
('HVAC-EXHAUST-FAN','CARRIER',null),
('HVAC-EXHAUST-FAN','TRANE',null),
('HVAC-EXHAUST-FAN','YORK',null),
('HVAC-EXHAUST-FAN','DAIKIN',null),
('HVAC-EXHAUST-FAN','MITSUBISHI',null),
('HVAC-EXHAUST-FAN','LG',null),
('HVAC-EXHAUST-FAN','SAMSUNG',null),
('HVAC-FRESH-AIR-FAN','ZAMIL',null),
('HVAC-FRESH-AIR-FAN','CARRIER',null),
('HVAC-FRESH-AIR-FAN','TRANE',null),
('HVAC-FRESH-AIR-FAN','YORK',null),
('HVAC-FRESH-AIR-FAN','DAIKIN',null),
('HVAC-FRESH-AIR-FAN','MITSUBISHI',null),
('HVAC-FRESH-AIR-FAN','LG',null),
('HVAC-FRESH-AIR-FAN','SAMSUNG',null),
('HVAC-STAIR-PRESS','ZAMIL',null),
('HVAC-STAIR-PRESS','CARRIER',null),
('HVAC-STAIR-PRESS','TRANE',null),
('HVAC-STAIR-PRESS','YORK',null),
('HVAC-STAIR-PRESS','DAIKIN',null),
('HVAC-STAIR-PRESS','MITSUBISHI',null),
('HVAC-STAIR-PRESS','LG',null),
('HVAC-STAIR-PRESS','SAMSUNG',null),
('HVAC-SMOKE-EXTRACT','ZAMIL',null),
('HVAC-SMOKE-EXTRACT','CARRIER',null),
('HVAC-SMOKE-EXTRACT','TRANE',null),
('HVAC-SMOKE-EXTRACT','YORK',null),
('HVAC-SMOKE-EXTRACT','DAIKIN',null),
('HVAC-SMOKE-EXTRACT','MITSUBISHI',null),
('HVAC-SMOKE-EXTRACT','LG',null),
('HVAC-SMOKE-EXTRACT','SAMSUNG',null),
('HVAC-JET-FAN','ZAMIL',null),
('HVAC-JET-FAN','CARRIER',null),
('HVAC-JET-FAN','TRANE',null),
('HVAC-JET-FAN','YORK',null),
('HVAC-JET-FAN','DAIKIN',null),
('HVAC-JET-FAN','MITSUBISHI',null),
('HVAC-JET-FAN','LG',null),
('HVAC-JET-FAN','SAMSUNG',null),
('HVAC-DAMPER','ZAMIL',null),
('HVAC-DAMPER','CARRIER',null),
('HVAC-DAMPER','TRANE',null),
('HVAC-DAMPER','YORK',null),
('HVAC-DAMPER','DAIKIN',null),
('HVAC-DAMPER','MITSUBISHI',null),
('HVAC-DAMPER','LG',null),
('HVAC-DAMPER','SAMSUNG',null),
('HVAC-FIRE-DAMPER','ZAMIL',null),
('HVAC-FIRE-DAMPER','CARRIER',null),
('HVAC-FIRE-DAMPER','TRANE',null),
('HVAC-FIRE-DAMPER','YORK',null),
('HVAC-FIRE-DAMPER','DAIKIN',null),
('HVAC-FIRE-DAMPER','MITSUBISHI',null),
('HVAC-FIRE-DAMPER','LG',null),
('HVAC-FIRE-DAMPER','SAMSUNG',null),
('HVAC-HUMIDIFIER','ZAMIL',null),
('HVAC-HUMIDIFIER','CARRIER',null),
('HVAC-HUMIDIFIER','TRANE',null),
('HVAC-HUMIDIFIER','YORK',null),
('HVAC-HUMIDIFIER','DAIKIN',null),
('HVAC-HUMIDIFIER','MITSUBISHI',null),
('HVAC-HUMIDIFIER','LG',null),
('HVAC-HUMIDIFIER','SAMSUNG',null),
('HVAC-DEHUMIDIFIER','ZAMIL',null),
('HVAC-DEHUMIDIFIER','CARRIER',null),
('HVAC-DEHUMIDIFIER','TRANE',null),
('HVAC-DEHUMIDIFIER','YORK',null),
('HVAC-DEHUMIDIFIER','DAIKIN',null),
('HVAC-DEHUMIDIFIER','MITSUBISHI',null),
('HVAC-DEHUMIDIFIER','LG',null),
('HVAC-DEHUMIDIFIER','SAMSUNG',null),
('BMS-SERVER','JCI',null),
('BMS-SERVER','HONEYWELL',null),
('BMS-SERVER','SIEMENS',null),
('BMS-SERVER','SCHNEIDER',null),
('BMS-SERVER','DELTA',null),
('BMS-SERVER','TRIDIUM',null),
('BMS-SERVER','DISTECH',null),
('BMS-SERVER','ALC',null),
('BMS-WORKSTATION','JCI',null),
('BMS-WORKSTATION','HONEYWELL',null),
('BMS-WORKSTATION','SIEMENS',null),
('BMS-WORKSTATION','SCHNEIDER',null),
('BMS-WORKSTATION','DELTA',null),
('BMS-WORKSTATION','TRIDIUM',null),
('BMS-WORKSTATION','DISTECH',null),
('BMS-WORKSTATION','ALC',null),
('BMS-CONTROLLER','JCI',null),
('BMS-CONTROLLER','HONEYWELL',null),
('BMS-CONTROLLER','SIEMENS',null),
('BMS-CONTROLLER','SCHNEIDER',null),
('BMS-CONTROLLER','DELTA',null),
('BMS-CONTROLLER','TRIDIUM',null),
('BMS-CONTROLLER','DISTECH',null),
('BMS-CONTROLLER','ALC',null),
('BMS-SENSOR','JCI',null),
('BMS-SENSOR','HONEYWELL',null),
('BMS-SENSOR','SIEMENS',null),
('BMS-SENSOR','SCHNEIDER',null),
('BMS-SENSOR','DELTA',null),
('BMS-SENSOR','TRIDIUM',null),
('BMS-SENSOR','DISTECH',null),
('BMS-SENSOR','ALC',null),
('BMS-ACTUATOR','JCI',null),
('BMS-ACTUATOR','HONEYWELL',null),
('BMS-ACTUATOR','SIEMENS',null),
('BMS-ACTUATOR','SCHNEIDER',null),
('BMS-ACTUATOR','DELTA',null),
('BMS-ACTUATOR','TRIDIUM',null),
('BMS-ACTUATOR','DISTECH',null),
('BMS-ACTUATOR','ALC',null),
('BMS-GATEWAY','JCI',null),
('BMS-GATEWAY','HONEYWELL',null),
('BMS-GATEWAY','SIEMENS',null),
('BMS-GATEWAY','SCHNEIDER',null),
('BMS-GATEWAY','DELTA',null),
('BMS-GATEWAY','TRIDIUM',null),
('BMS-GATEWAY','DISTECH',null),
('BMS-GATEWAY','ALC',null),
('BMS-ENERGY-METER','JCI',null),
('BMS-ENERGY-METER','HONEYWELL',null),
('BMS-ENERGY-METER','SIEMENS',null),
('BMS-ENERGY-METER','SCHNEIDER',null),
('BMS-ENERGY-METER','DELTA',null),
('BMS-ENERGY-METER','TRIDIUM',null),
('BMS-ENERGY-METER','DISTECH',null),
('BMS-ENERGY-METER','ALC',null),
('BMS-VFD','ABB',null),
('BMS-VFD','SCHNEIDER',null),
('BMS-VFD','SIEMENS',null),
('BMS-VFD','EATON',null),
('FIRE-ALARM-PANEL','NOTIFIER',null),
('FIRE-ALARM-PANEL','SIMPLEX',null),
('FIRE-ALARM-PANEL','SIEMENS',null),
('FIRE-ALARM-PANEL','EDWARDS',null),
('FIRE-ALARM-PANEL','HOCHIKI',null),
('FIRE-ALARM-PANEL','APOLLO',null),
('FIRE-ALARM-PANEL','GENT',null),
('FIRE-ALARM-PANEL','GST',null),
('FIRE-REPEATER','NOTIFIER',null),
('FIRE-REPEATER','SIMPLEX',null),
('FIRE-REPEATER','SIEMENS',null),
('FIRE-REPEATER','EDWARDS',null),
('FIRE-REPEATER','HOCHIKI',null),
('FIRE-REPEATER','APOLLO',null),
('FIRE-REPEATER','GENT',null),
('FIRE-REPEATER','GST',null),
('FIRE-SMOKE','NOTIFIER',null),
('FIRE-SMOKE','SIMPLEX',null),
('FIRE-SMOKE','SIEMENS',null),
('FIRE-SMOKE','EDWARDS',null),
('FIRE-SMOKE','HOCHIKI',null),
('FIRE-SMOKE','APOLLO',null),
('FIRE-SMOKE','GENT',null),
('FIRE-SMOKE','GST',null),
('FIRE-HEAT','NOTIFIER',null),
('FIRE-HEAT','SIMPLEX',null),
('FIRE-HEAT','SIEMENS',null),
('FIRE-HEAT','EDWARDS',null),
('FIRE-HEAT','HOCHIKI',null),
('FIRE-HEAT','APOLLO',null),
('FIRE-HEAT','GENT',null),
('FIRE-HEAT','GST',null),
('FIRE-BEAM','NOTIFIER',null),
('FIRE-BEAM','SIMPLEX',null),
('FIRE-BEAM','SIEMENS',null),
('FIRE-BEAM','EDWARDS',null),
('FIRE-BEAM','HOCHIKI',null),
('FIRE-BEAM','APOLLO',null),
('FIRE-BEAM','GENT',null),
('FIRE-BEAM','GST',null),
('FIRE-ASD','NOTIFIER',null),
('FIRE-ASD','SIMPLEX',null),
('FIRE-ASD','SIEMENS',null),
('FIRE-ASD','EDWARDS',null),
('FIRE-ASD','HOCHIKI',null),
('FIRE-ASD','APOLLO',null),
('FIRE-ASD','GENT',null),
('FIRE-ASD','GST',null),
('FIRE-MCP','NOTIFIER',null),
('FIRE-MCP','SIMPLEX',null),
('FIRE-MCP','SIEMENS',null),
('FIRE-MCP','EDWARDS',null),
('FIRE-MCP','HOCHIKI',null),
('FIRE-MCP','APOLLO',null),
('FIRE-MCP','GENT',null),
('FIRE-MCP','GST',null),
('FIRE-SOUNDER','NOTIFIER',null),
('FIRE-SOUNDER','SIMPLEX',null),
('FIRE-SOUNDER','SIEMENS',null),
('FIRE-SOUNDER','EDWARDS',null),
('FIRE-SOUNDER','HOCHIKI',null),
('FIRE-SOUNDER','APOLLO',null),
('FIRE-SOUNDER','GENT',null),
('FIRE-SOUNDER','GST',null),
('FIRE-STROBE','NOTIFIER',null),
('FIRE-STROBE','SIMPLEX',null),
('FIRE-STROBE','SIEMENS',null),
('FIRE-STROBE','EDWARDS',null),
('FIRE-STROBE','HOCHIKI',null),
('FIRE-STROBE','APOLLO',null),
('FIRE-STROBE','GENT',null),
('FIRE-STROBE','GST',null),
('FIRE-IO-MODULE','NOTIFIER',null),
('FIRE-IO-MODULE','SIMPLEX',null),
('FIRE-IO-MODULE','SIEMENS',null),
('FIRE-IO-MODULE','EDWARDS',null),
('FIRE-IO-MODULE','HOCHIKI',null),
('FIRE-IO-MODULE','APOLLO',null),
('FIRE-IO-MODULE','GENT',null),
('FIRE-IO-MODULE','GST',null),
('FIRE-VOICE-EVAC','NOTIFIER',null),
('FIRE-VOICE-EVAC','SIMPLEX',null),
('FIRE-VOICE-EVAC','SIEMENS',null),
('FIRE-VOICE-EVAC','EDWARDS',null),
('FIRE-VOICE-EVAC','HOCHIKI',null),
('FIRE-VOICE-EVAC','APOLLO',null),
('FIRE-VOICE-EVAC','GENT',null),
('FIRE-VOICE-EVAC','GST',null),
('FIRE-FM200','KIDDE',null),
('FIRE-FM200','ANSUL',null),
('FIRE-FM200','VIKING',null),
('FIRE-FM200','TYCO',null),
('FIRE-FM200','RELIABLE',null),
('FIRE-FM200','VICTAULIC',null),
('FIRE-FM200','NAFFCO',null),
('FIRE-FM200','SFFECO',null),
('FIRE-NOVEC','KIDDE',null),
('FIRE-NOVEC','ANSUL',null),
('FIRE-NOVEC','VIKING',null),
('FIRE-NOVEC','TYCO',null),
('FIRE-NOVEC','RELIABLE',null),
('FIRE-NOVEC','VICTAULIC',null),
('FIRE-NOVEC','NAFFCO',null),
('FIRE-NOVEC','SFFECO',null),
('FIRE-INERT-GAS','KIDDE',null),
('FIRE-INERT-GAS','ANSUL',null),
('FIRE-INERT-GAS','VIKING',null),
('FIRE-INERT-GAS','TYCO',null),
('FIRE-INERT-GAS','RELIABLE',null),
('FIRE-INERT-GAS','VICTAULIC',null),
('FIRE-INERT-GAS','NAFFCO',null),
('FIRE-INERT-GAS','SFFECO',null),
('FIRE-CO2','KIDDE',null),
('FIRE-CO2','ANSUL',null),
('FIRE-CO2','VIKING',null),
('FIRE-CO2','TYCO',null),
('FIRE-CO2','RELIABLE',null),
('FIRE-CO2','VICTAULIC',null),
('FIRE-CO2','NAFFCO',null),
('FIRE-CO2','SFFECO',null),
('FIRE-KITCHEN-HOOD','KIDDE',null),
('FIRE-KITCHEN-HOOD','ANSUL',null),
('FIRE-KITCHEN-HOOD','VIKING',null),
('FIRE-KITCHEN-HOOD','TYCO',null),
('FIRE-KITCHEN-HOOD','RELIABLE',null),
('FIRE-KITCHEN-HOOD','VICTAULIC',null),
('FIRE-KITCHEN-HOOD','NAFFCO',null),
('FIRE-KITCHEN-HOOD','SFFECO',null),
('FIRE-PUMP-ELECTRIC','PATTERSON',null),
('FIRE-PUMP-ELECTRIC','GRUNDFOS',null),
('FIRE-PUMP-ELECTRIC','KSB',null),
('FIRE-PUMP-ELECTRIC','WILO',null),
('FIRE-PUMP-ELECTRIC','NAFFCO',null),
('FIRE-PUMP-ELECTRIC','SFFECO',null),
('FIRE-PUMP-DIESEL','PATTERSON',null),
('FIRE-PUMP-DIESEL','NAFFCO',null),
('FIRE-PUMP-DIESEL','SFFECO',null),
('FIRE-PUMP-DIESEL','CUMMINS',null),
('FIRE-PUMP-DIESEL','PERKINS',null),
('FIRE-JOCKEY','GRUNDFOS',null),
('FIRE-JOCKEY','KSB',null),
('FIRE-JOCKEY','WILO',null),
('FIRE-JOCKEY','PATTERSON',null),
('FIRE-SPRINKLER','KIDDE',null),
('FIRE-SPRINKLER','ANSUL',null),
('FIRE-SPRINKLER','VIKING',null),
('FIRE-SPRINKLER','TYCO',null),
('FIRE-SPRINKLER','RELIABLE',null),
('FIRE-SPRINKLER','VICTAULIC',null),
('FIRE-SPRINKLER','NAFFCO',null),
('FIRE-SPRINKLER','SFFECO',null),
('FIRE-HYDRANT','KIDDE',null),
('FIRE-HYDRANT','ANSUL',null),
('FIRE-HYDRANT','VIKING',null),
('FIRE-HYDRANT','TYCO',null),
('FIRE-HYDRANT','RELIABLE',null),
('FIRE-HYDRANT','VICTAULIC',null),
('FIRE-HYDRANT','NAFFCO',null),
('FIRE-HYDRANT','SFFECO',null),
('FIRE-HOSE-REEL','KIDDE',null),
('FIRE-HOSE-REEL','ANSUL',null),
('FIRE-HOSE-REEL','VIKING',null),
('FIRE-HOSE-REEL','TYCO',null),
('FIRE-HOSE-REEL','RELIABLE',null),
('FIRE-HOSE-REEL','VICTAULIC',null),
('FIRE-HOSE-REEL','NAFFCO',null),
('FIRE-HOSE-REEL','SFFECO',null),
('FIRE-EXTINGUISHER','KIDDE',null),
('FIRE-EXTINGUISHER','ANSUL',null),
('FIRE-EXTINGUISHER','VIKING',null),
('FIRE-EXTINGUISHER','TYCO',null),
('FIRE-EXTINGUISHER','RELIABLE',null),
('FIRE-EXTINGUISHER','VICTAULIC',null),
('FIRE-EXTINGUISHER','NAFFCO',null),
('FIRE-EXTINGUISHER','SFFECO',null),
('FIRE-DELUGE','KIDDE',null),
('FIRE-DELUGE','ANSUL',null),
('FIRE-DELUGE','VIKING',null),
('FIRE-DELUGE','TYCO',null),
('FIRE-DELUGE','RELIABLE',null),
('FIRE-DELUGE','VICTAULIC',null),
('FIRE-DELUGE','NAFFCO',null),
('FIRE-DELUGE','SFFECO',null),
('FIRE-PREACTION','KIDDE',null),
('FIRE-PREACTION','ANSUL',null),
('FIRE-PREACTION','VIKING',null),
('FIRE-PREACTION','TYCO',null),
('FIRE-PREACTION','RELIABLE',null),
('FIRE-PREACTION','VICTAULIC',null),
('FIRE-PREACTION','NAFFCO',null),
('FIRE-PREACTION','SFFECO',null),
('ELEC-RMU','SCHNEIDER',null),
('ELEC-RMU','ABB',null),
('ELEC-RMU','SIEMENS',null),
('ELEC-RMU','EATON',null),
('ELEC-RMU','LEGRAND',null),
('ELEC-RMU','ALFANAR',null),
('ELEC-RMU','SOCOMEC',null),
('ELEC-RMU','LS',null),
('ELEC-MV-SWGR','SCHNEIDER',null),
('ELEC-MV-SWGR','ABB',null),
('ELEC-MV-SWGR','SIEMENS',null),
('ELEC-MV-SWGR','EATON',null),
('ELEC-MV-SWGR','LEGRAND',null),
('ELEC-MV-SWGR','ALFANAR',null),
('ELEC-MV-SWGR','SOCOMEC',null),
('ELEC-MV-SWGR','LS',null),
('ELEC-TRANSFORMER','SCHNEIDER',null),
('ELEC-TRANSFORMER','ABB',null),
('ELEC-TRANSFORMER','SIEMENS',null),
('ELEC-TRANSFORMER','EATON',null),
('ELEC-TRANSFORMER','LEGRAND',null),
('ELEC-TRANSFORMER','ALFANAR',null),
('ELEC-TRANSFORMER','SOCOMEC',null),
('ELEC-TRANSFORMER','LS',null),
('ELEC-MDB','SCHNEIDER',null),
('ELEC-MDB','ABB',null),
('ELEC-MDB','SIEMENS',null),
('ELEC-MDB','EATON',null),
('ELEC-MDB','LEGRAND',null),
('ELEC-MDB','ALFANAR',null),
('ELEC-MDB','SOCOMEC',null),
('ELEC-MDB','LS',null),
('ELEC-SMDB','SCHNEIDER',null),
('ELEC-SMDB','ABB',null),
('ELEC-SMDB','SIEMENS',null),
('ELEC-SMDB','EATON',null),
('ELEC-SMDB','LEGRAND',null),
('ELEC-SMDB','ALFANAR',null),
('ELEC-SMDB','SOCOMEC',null),
('ELEC-SMDB','LS',null),
('ELEC-DB','SCHNEIDER',null),
('ELEC-DB','ABB',null),
('ELEC-DB','SIEMENS',null),
('ELEC-DB','EATON',null),
('ELEC-DB','LEGRAND',null),
('ELEC-DB','ALFANAR',null),
('ELEC-DB','SOCOMEC',null),
('ELEC-DB','LS',null),
('ELEC-MCC','SCHNEIDER',null),
('ELEC-MCC','ABB',null),
('ELEC-MCC','SIEMENS',null),
('ELEC-MCC','EATON',null),
('ELEC-MCC','LEGRAND',null),
('ELEC-MCC','ALFANAR',null),
('ELEC-MCC','SOCOMEC',null),
('ELEC-MCC','LS',null),
('ELEC-ATS','SCHNEIDER',null),
('ELEC-ATS','ABB',null),
('ELEC-ATS','SIEMENS',null),
('ELEC-ATS','EATON',null),
('ELEC-ATS','LEGRAND',null),
('ELEC-ATS','ALFANAR',null),
('ELEC-ATS','SOCOMEC',null),
('ELEC-ATS','LS',null),
('ELEC-GENERATOR','CUMMINS',null),
('ELEC-GENERATOR','CATERPILLAR',null),
('ELEC-GENERATOR','PERKINS',null),
('ELEC-GENERATOR','FGWILSON',null),
('ELEC-GENERATOR','MTU',null),
('ELEC-GENERATOR','KOHLER',null),
('ELEC-GENERATOR','VOLVOPENTA',null),
('ELEC-UPS','VERTIV',null),
('ELEC-UPS','APC',null),
('ELEC-UPS','EATON',null),
('ELEC-UPS','HUAWEI',null),
('ELEC-UPS','RIELLO',null),
('ELEC-UPS','SOCOMEC',null),
('ELEC-UPS','BORRI',null),
('ELEC-BATTERY','SCHNEIDER',null),
('ELEC-BATTERY','ABB',null),
('ELEC-BATTERY','SIEMENS',null),
('ELEC-BATTERY','EATON',null),
('ELEC-BATTERY','LEGRAND',null),
('ELEC-BATTERY','ALFANAR',null),
('ELEC-BATTERY','SOCOMEC',null),
('ELEC-BATTERY','LS',null),
('ELEC-CAPBANK','SCHNEIDER',null),
('ELEC-CAPBANK','ABB',null),
('ELEC-CAPBANK','SIEMENS',null),
('ELEC-CAPBANK','EATON',null),
('ELEC-CAPBANK','LEGRAND',null),
('ELEC-CAPBANK','ALFANAR',null),
('ELEC-CAPBANK','SOCOMEC',null),
('ELEC-CAPBANK','LS',null),
('ELEC-APFC','SCHNEIDER',null),
('ELEC-APFC','ABB',null),
('ELEC-APFC','SIEMENS',null),
('ELEC-APFC','EATON',null),
('ELEC-APFC','LEGRAND',null),
('ELEC-APFC','ALFANAR',null),
('ELEC-APFC','SOCOMEC',null),
('ELEC-APFC','LS',null),
('ELEC-PQ-METER','SCHNEIDER',null),
('ELEC-PQ-METER','ABB',null),
('ELEC-PQ-METER','SIEMENS',null),
('ELEC-PQ-METER','EATON',null),
('ELEC-PQ-METER','LEGRAND',null),
('ELEC-PQ-METER','ALFANAR',null),
('ELEC-PQ-METER','SOCOMEC',null),
('ELEC-PQ-METER','LS',null),
('ELEC-ENERGY-METER','SCHNEIDER',null),
('ELEC-ENERGY-METER','ABB',null),
('ELEC-ENERGY-METER','SIEMENS',null),
('ELEC-ENERGY-METER','EATON',null),
('ELEC-ENERGY-METER','LEGRAND',null),
('ELEC-ENERGY-METER','ALFANAR',null),
('ELEC-ENERGY-METER','SOCOMEC',null),
('ELEC-ENERGY-METER','LS',null),
('ELEC-LIGHTING-PANEL','SCHNEIDER',null),
('ELEC-LIGHTING-PANEL','ABB',null),
('ELEC-LIGHTING-PANEL','SIEMENS',null),
('ELEC-LIGHTING-PANEL','EATON',null),
('ELEC-LIGHTING-PANEL','LEGRAND',null),
('ELEC-LIGHTING-PANEL','ALFANAR',null),
('ELEC-LIGHTING-PANEL','SOCOMEC',null),
('ELEC-LIGHTING-PANEL','LS',null),
('ELEC-EM-LIGHT','SCHNEIDER',null),
('ELEC-EM-LIGHT','ABB',null),
('ELEC-EM-LIGHT','SIEMENS',null),
('ELEC-EM-LIGHT','EATON',null),
('ELEC-EM-LIGHT','LEGRAND',null),
('ELEC-EM-LIGHT','ALFANAR',null),
('ELEC-EM-LIGHT','SOCOMEC',null),
('ELEC-EM-LIGHT','LS',null),
('ELEC-EXIT-SIGN','SCHNEIDER',null),
('ELEC-EXIT-SIGN','ABB',null),
('ELEC-EXIT-SIGN','SIEMENS',null),
('ELEC-EXIT-SIGN','EATON',null),
('ELEC-EXIT-SIGN','LEGRAND',null),
('ELEC-EXIT-SIGN','ALFANAR',null),
('ELEC-EXIT-SIGN','SOCOMEC',null),
('ELEC-EXIT-SIGN','LS',null),
('ELEC-LIGHTNING','SCHNEIDER',null),
('ELEC-LIGHTNING','ABB',null),
('ELEC-LIGHTNING','SIEMENS',null),
('ELEC-LIGHTNING','EATON',null),
('ELEC-LIGHTNING','LEGRAND',null),
('ELEC-LIGHTNING','ALFANAR',null),
('ELEC-LIGHTNING','SOCOMEC',null),
('ELEC-LIGHTNING','LS',null),
('ELEC-EARTHING','SCHNEIDER',null),
('ELEC-EARTHING','ABB',null),
('ELEC-EARTHING','SIEMENS',null),
('ELEC-EARTHING','EATON',null),
('ELEC-EARTHING','LEGRAND',null),
('ELEC-EARTHING','ALFANAR',null),
('ELEC-EARTHING','SOCOMEC',null),
('ELEC-EARTHING','LS',null),
('ELEC-BUSBAR','SCHNEIDER',null),
('ELEC-BUSBAR','ABB',null),
('ELEC-BUSBAR','SIEMENS',null),
('ELEC-BUSBAR','EATON',null),
('ELEC-BUSBAR','LEGRAND',null),
('ELEC-BUSBAR','ALFANAR',null),
('ELEC-BUSBAR','SOCOMEC',null),
('ELEC-BUSBAR','LS',null),
('SOLAR-PV','SCHNEIDER',null),
('SOLAR-PV','ABB',null),
('SOLAR-PV','SIEMENS',null),
('SOLAR-PV','HUAWEI',null),
('SOLAR-PV','EATON',null),
('SOLAR-INVERTER','SCHNEIDER',null),
('SOLAR-INVERTER','ABB',null),
('SOLAR-INVERTER','SIEMENS',null),
('SOLAR-INVERTER','HUAWEI',null),
('SOLAR-INVERTER','EATON',null),
('SOLAR-BATTERY','SCHNEIDER',null),
('SOLAR-BATTERY','ABB',null),
('SOLAR-BATTERY','SIEMENS',null),
('SOLAR-BATTERY','HUAWEI',null),
('SOLAR-BATTERY','EATON',null),
('EV-CHARGER','SCHNEIDER',null),
('EV-CHARGER','ABB',null),
('EV-CHARGER','SIEMENS',null),
('EV-CHARGER','HUAWEI',null),
('EV-CHARGER','EATON',null),
('PLUMB-BOOSTER','GRUNDFOS',null),
('PLUMB-BOOSTER','KSB',null),
('PLUMB-BOOSTER','WILO',null),
('PLUMB-BOOSTER','XYLEM',null),
('PLUMB-BOOSTER','LOWARA',null),
('PLUMB-BOOSTER','FLYGT',null),
('PLUMB-BOOSTER','ARMSTRONG',null),
('PLUMB-BOOSTER','EBARA',null),
('PLUMB-TRANSFER','GRUNDFOS',null),
('PLUMB-TRANSFER','KSB',null),
('PLUMB-TRANSFER','WILO',null),
('PLUMB-TRANSFER','XYLEM',null),
('PLUMB-TRANSFER','LOWARA',null),
('PLUMB-TRANSFER','FLYGT',null),
('PLUMB-TRANSFER','ARMSTRONG',null),
('PLUMB-TRANSFER','EBARA',null),
('PLUMB-SUMP','GRUNDFOS',null),
('PLUMB-SUMP','KSB',null),
('PLUMB-SUMP','WILO',null),
('PLUMB-SUMP','XYLEM',null),
('PLUMB-SUMP','LOWARA',null),
('PLUMB-SUMP','FLYGT',null),
('PLUMB-SUMP','ARMSTRONG',null),
('PLUMB-SUMP','EBARA',null),
('PLUMB-SEWAGE','GRUNDFOS',null),
('PLUMB-SEWAGE','KSB',null),
('PLUMB-SEWAGE','WILO',null),
('PLUMB-SEWAGE','XYLEM',null),
('PLUMB-SEWAGE','LOWARA',null),
('PLUMB-SEWAGE','FLYGT',null),
('PLUMB-SEWAGE','ARMSTRONG',null),
('PLUMB-SEWAGE','EBARA',null),
('PLUMB-LIFT-STATION','GRUNDFOS',null),
('PLUMB-LIFT-STATION','KSB',null),
('PLUMB-LIFT-STATION','WILO',null),
('PLUMB-LIFT-STATION','XYLEM',null),
('PLUMB-LIFT-STATION','LOWARA',null),
('PLUMB-LIFT-STATION','FLYGT',null),
('PLUMB-LIFT-STATION','ARMSTRONG',null),
('PLUMB-LIFT-STATION','EBARA',null),
('PLUMB-COLD-TANK','GRUNDFOS',null),
('PLUMB-COLD-TANK','KSB',null),
('PLUMB-COLD-TANK','WILO',null),
('PLUMB-COLD-TANK','XYLEM',null),
('PLUMB-COLD-TANK','LOWARA',null),
('PLUMB-COLD-TANK','FLYGT',null),
('PLUMB-COLD-TANK','ARMSTRONG',null),
('PLUMB-COLD-TANK','EBARA',null),
('PLUMB-HOT-TANK','GRUNDFOS',null),
('PLUMB-HOT-TANK','KSB',null),
('PLUMB-HOT-TANK','WILO',null),
('PLUMB-HOT-TANK','XYLEM',null),
('PLUMB-HOT-TANK','LOWARA',null),
('PLUMB-HOT-TANK','FLYGT',null),
('PLUMB-HOT-TANK','ARMSTRONG',null),
('PLUMB-HOT-TANK','EBARA',null),
('PLUMB-WATER-HEATER','GRUNDFOS',null),
('PLUMB-WATER-HEATER','KSB',null),
('PLUMB-WATER-HEATER','WILO',null),
('PLUMB-WATER-HEATER','XYLEM',null),
('PLUMB-WATER-HEATER','LOWARA',null),
('PLUMB-WATER-HEATER','FLYGT',null),
('PLUMB-WATER-HEATER','ARMSTRONG',null),
('PLUMB-WATER-HEATER','EBARA',null),
('PLUMB-CALORIFIER','GRUNDFOS',null),
('PLUMB-CALORIFIER','KSB',null),
('PLUMB-CALORIFIER','WILO',null),
('PLUMB-CALORIFIER','XYLEM',null),
('PLUMB-CALORIFIER','LOWARA',null),
('PLUMB-CALORIFIER','FLYGT',null),
('PLUMB-CALORIFIER','ARMSTRONG',null),
('PLUMB-CALORIFIER','EBARA',null),
('PLUMB-PRV','GRUNDFOS',null),
('PLUMB-PRV','KSB',null),
('PLUMB-PRV','WILO',null),
('PLUMB-PRV','XYLEM',null),
('PLUMB-PRV','LOWARA',null),
('PLUMB-PRV','FLYGT',null),
('PLUMB-PRV','ARMSTRONG',null),
('PLUMB-PRV','EBARA',null),
('PLUMB-GREASE-TRAP','GRUNDFOS',null),
('PLUMB-GREASE-TRAP','KSB',null),
('PLUMB-GREASE-TRAP','WILO',null),
('PLUMB-GREASE-TRAP','XYLEM',null),
('PLUMB-GREASE-TRAP','LOWARA',null),
('PLUMB-GREASE-TRAP','FLYGT',null),
('PLUMB-GREASE-TRAP','ARMSTRONG',null),
('PLUMB-GREASE-TRAP','EBARA',null),
('PLUMB-OIL-SEPARATOR','GRUNDFOS',null),
('PLUMB-OIL-SEPARATOR','KSB',null),
('PLUMB-OIL-SEPARATOR','WILO',null),
('PLUMB-OIL-SEPARATOR','XYLEM',null),
('PLUMB-OIL-SEPARATOR','LOWARA',null),
('PLUMB-OIL-SEPARATOR','FLYGT',null),
('PLUMB-OIL-SEPARATOR','ARMSTRONG',null),
('PLUMB-OIL-SEPARATOR','EBARA',null),
('RO-SYSTEM','VEOLIA',null),
('RO-SYSTEM','SUEZ',null),
('RO-SYSTEM','PENTAIR',null),
('RO-SYSTEM','CULLIGAN',null),
('RO-SYSTEM','GRUNDFOS',null),
('WATER-SOFTENER','VEOLIA',null),
('WATER-SOFTENER','SUEZ',null),
('WATER-SOFTENER','PENTAIR',null),
('WATER-SOFTENER','CULLIGAN',null),
('WATER-SOFTENER','GRUNDFOS',null),
('UF-SYSTEM','VEOLIA',null),
('UF-SYSTEM','SUEZ',null),
('UF-SYSTEM','PENTAIR',null),
('UF-SYSTEM','CULLIGAN',null),
('UF-SYSTEM','GRUNDFOS',null),
('UV-STERILIZER','VEOLIA',null),
('UV-STERILIZER','SUEZ',null),
('UV-STERILIZER','PENTAIR',null),
('UV-STERILIZER','CULLIGAN',null),
('UV-STERILIZER','GRUNDFOS',null),
('DOSING-SYSTEM','VEOLIA',null),
('DOSING-SYSTEM','SUEZ',null),
('DOSING-SYSTEM','PENTAIR',null),
('DOSING-SYSTEM','CULLIGAN',null),
('DOSING-SYSTEM','GRUNDFOS',null),
('CHLORINATION','VEOLIA',null),
('CHLORINATION','SUEZ',null),
('CHLORINATION','PENTAIR',null),
('CHLORINATION','CULLIGAN',null),
('CHLORINATION','GRUNDFOS',null),
('STP','VEOLIA',null),
('STP','SUEZ',null),
('STP','PENTAIR',null),
('STP','CULLIGAN',null),
('STP','GRUNDFOS',null),
('GREYWATER','VEOLIA',null),
('GREYWATER','SUEZ',null),
('GREYWATER','PENTAIR',null),
('GREYWATER','CULLIGAN',null),
('GREYWATER','GRUNDFOS',null),
('IRR-PUMP','GRUNDFOS',null),
('IRR-PUMP','WILO',null),
('IRR-PUMP','PENTAIR',null),
('IRR-CONTROLLER','GRUNDFOS',null),
('IRR-CONTROLLER','WILO',null),
('IRR-CONTROLLER','PENTAIR',null),
('IRR-VALVE','GRUNDFOS',null),
('IRR-VALVE','WILO',null),
('IRR-VALVE','PENTAIR',null),
('FOUNTAIN-PUMP','GRUNDFOS',null),
('FOUNTAIN-PUMP','WILO',null),
('FOUNTAIN-PUMP','PENTAIR',null),
('LIFT-PASSENGER','KONE',null),
('LIFT-PASSENGER','OTIS',null),
('LIFT-PASSENGER','SCHINDLER',null),
('LIFT-PASSENGER','TKE',null),
('LIFT-PASSENGER','MITSUBISHI',null),
('LIFT-PASSENGER','FUJITEC',null),
('LIFT-PASSENGER','HITACHI',null),
('LIFT-PASSENGER','HYUNDAI',null),
('LIFT-SERVICE','KONE',null),
('LIFT-SERVICE','OTIS',null),
('LIFT-SERVICE','SCHINDLER',null),
('LIFT-SERVICE','TKE',null),
('LIFT-SERVICE','MITSUBISHI',null),
('LIFT-SERVICE','FUJITEC',null),
('LIFT-SERVICE','HITACHI',null),
('LIFT-SERVICE','HYUNDAI',null),
('LIFT-FREIGHT','KONE',null),
('LIFT-FREIGHT','OTIS',null),
('LIFT-FREIGHT','SCHINDLER',null),
('LIFT-FREIGHT','TKE',null),
('LIFT-FREIGHT','MITSUBISHI',null),
('LIFT-FREIGHT','FUJITEC',null),
('LIFT-FREIGHT','HITACHI',null),
('LIFT-FREIGHT','HYUNDAI',null),
('ESCALATOR','KONE',null),
('ESCALATOR','OTIS',null),
('ESCALATOR','SCHINDLER',null),
('ESCALATOR','TKE',null),
('ESCALATOR','MITSUBISHI',null),
('ESCALATOR','FUJITEC',null),
('ESCALATOR','HITACHI',null),
('ESCALATOR','HYUNDAI',null),
('TRAVELATOR','KONE',null),
('TRAVELATOR','OTIS',null),
('TRAVELATOR','SCHINDLER',null),
('TRAVELATOR','TKE',null),
('TRAVELATOR','MITSUBISHI',null),
('TRAVELATOR','FUJITEC',null),
('TRAVELATOR','HITACHI',null),
('TRAVELATOR','HYUNDAI',null),
('PLATFORM-LIFT','KONE',null),
('PLATFORM-LIFT','OTIS',null),
('PLATFORM-LIFT','SCHINDLER',null),
('PLATFORM-LIFT','TKE',null),
('PLATFORM-LIFT','MITSUBISHI',null),
('PLATFORM-LIFT','FUJITEC',null),
('PLATFORM-LIFT','HITACHI',null),
('PLATFORM-LIFT','HYUNDAI',null),
('SEC-CCTV-FIXED','AXIS',null),
('SEC-CCTV-FIXED','HIKVISION',null),
('SEC-CCTV-FIXED','DAHUA',null),
('SEC-CCTV-FIXED','HANWHA',null),
('SEC-CCTV-FIXED','AVIGILON',null),
('SEC-CCTV-FIXED','PELCO',null),
('SEC-CCTV-FIXED','BOSCH',null),
('SEC-CCTV-FIXED','MILESTONE',null),
('SEC-CCTV-DOME','AXIS',null),
('SEC-CCTV-DOME','HIKVISION',null),
('SEC-CCTV-DOME','DAHUA',null),
('SEC-CCTV-DOME','HANWHA',null),
('SEC-CCTV-DOME','AVIGILON',null),
('SEC-CCTV-DOME','PELCO',null),
('SEC-CCTV-DOME','BOSCH',null),
('SEC-CCTV-DOME','MILESTONE',null),
('SEC-CCTV-PTZ','AXIS',null),
('SEC-CCTV-PTZ','HIKVISION',null),
('SEC-CCTV-PTZ','DAHUA',null),
('SEC-CCTV-PTZ','HANWHA',null),
('SEC-CCTV-PTZ','AVIGILON',null),
('SEC-CCTV-PTZ','PELCO',null),
('SEC-CCTV-PTZ','BOSCH',null),
('SEC-CCTV-PTZ','MILESTONE',null),
('SEC-THERMAL','AXIS',null),
('SEC-THERMAL','HIKVISION',null),
('SEC-THERMAL','DAHUA',null),
('SEC-THERMAL','HANWHA',null),
('SEC-THERMAL','AVIGILON',null),
('SEC-THERMAL','PELCO',null),
('SEC-THERMAL','BOSCH',null),
('SEC-THERMAL','MILESTONE',null),
('SEC-NVR','AXIS',null),
('SEC-NVR','HIKVISION',null),
('SEC-NVR','DAHUA',null),
('SEC-NVR','HANWHA',null),
('SEC-NVR','AVIGILON',null),
('SEC-NVR','PELCO',null),
('SEC-NVR','BOSCH',null),
('SEC-NVR','MILESTONE',null),
('SEC-VMS','MILESTONE',null),
('SEC-VMS','GENETEC',null),
('SEC-VMS','AVIGILON',null),
('SEC-VMS','HIKVISION',null),
('SEC-VMS','DAHUA',null),
('SEC-ACS','HID',null),
('SEC-ACS','LENEL',null),
('SEC-ACS','HONEYWELL',null),
('SEC-ACS','GALLAGHER',null),
('SEC-ACS','SUPREMA',null),
('SEC-READER','HID',null),
('SEC-READER','SUPREMA',null),
('SEC-READER','ZKTECO',null),
('SEC-READER','GALLAGHER',null),
('SEC-BIOMETRIC','SUPREMA',null),
('SEC-BIOMETRIC','ZKTECO',null),
('SEC-BIOMETRIC','HID',null),
('SEC-TURNSTILE','AXIS',null),
('SEC-TURNSTILE','HIKVISION',null),
('SEC-TURNSTILE','DAHUA',null),
('SEC-TURNSTILE','HANWHA',null),
('SEC-TURNSTILE','AVIGILON',null),
('SEC-TURNSTILE','PELCO',null),
('SEC-TURNSTILE','BOSCH',null),
('SEC-TURNSTILE','MILESTONE',null),
('SEC-BOLLARD','AXIS',null),
('SEC-BOLLARD','HIKVISION',null),
('SEC-BOLLARD','DAHUA',null),
('SEC-BOLLARD','HANWHA',null),
('SEC-BOLLARD','AVIGILON',null),
('SEC-BOLLARD','PELCO',null),
('SEC-BOLLARD','BOSCH',null),
('SEC-BOLLARD','MILESTONE',null),
('SEC-UVSS','AXIS',null),
('SEC-UVSS','HIKVISION',null),
('SEC-UVSS','DAHUA',null),
('SEC-UVSS','HANWHA',null),
('SEC-UVSS','AVIGILON',null),
('SEC-UVSS','PELCO',null),
('SEC-UVSS','BOSCH',null),
('SEC-UVSS','MILESTONE',null),
('SEC-XRAY','AXIS',null),
('SEC-XRAY','HIKVISION',null),
('SEC-XRAY','DAHUA',null),
('SEC-XRAY','HANWHA',null),
('SEC-XRAY','AVIGILON',null),
('SEC-XRAY','PELCO',null),
('SEC-XRAY','BOSCH',null),
('SEC-XRAY','MILESTONE',null),
('SEC-METAL-DETECTOR','AXIS',null),
('SEC-METAL-DETECTOR','HIKVISION',null),
('SEC-METAL-DETECTOR','DAHUA',null),
('SEC-METAL-DETECTOR','HANWHA',null),
('SEC-METAL-DETECTOR','AVIGILON',null),
('SEC-METAL-DETECTOR','PELCO',null),
('SEC-METAL-DETECTOR','BOSCH',null),
('SEC-METAL-DETECTOR','MILESTONE',null),
('PA-AMPLIFIER','HONEYWELL',null),
('PA-AMPLIFIER','BOSCH',null),
('PA-AMPLIFIER','SIEMENS',null),
('PA-AMPLIFIER','JCI',null),
('PA-SPEAKER','HONEYWELL',null),
('PA-SPEAKER','BOSCH',null),
('PA-SPEAKER','SIEMENS',null),
('PA-SPEAKER','JCI',null),
('INTERCOM','HONEYWELL',null),
('INTERCOM','BOSCH',null),
('INTERCOM','SIEMENS',null),
('INTERCOM','JCI',null),
('MASTER-CLOCK','HONEYWELL',null),
('MASTER-CLOCK','BOSCH',null),
('MASTER-CLOCK','SIEMENS',null),
('MASTER-CLOCK','JCI',null),
('SMATV','HONEYWELL',null),
('SMATV','BOSCH',null),
('SMATV','SIEMENS',null),
('SMATV','JCI',null),
('ICT-CORE-SWITCH','CISCO',null),
('ICT-CORE-SWITCH','ARUBA',null),
('ICT-CORE-SWITCH','JUNIPER',null),
('ICT-CORE-SWITCH','HUAWEI',null),
('ICT-CORE-SWITCH','FORTINET',null),
('ICT-CORE-SWITCH','RUCKUS',null),
('ICT-CORE-SWITCH','COMMSCOPE',null),
('ICT-CORE-SWITCH','PANDUIT',null),
('ICT-ACCESS-SWITCH','CISCO',null),
('ICT-ACCESS-SWITCH','ARUBA',null),
('ICT-ACCESS-SWITCH','JUNIPER',null),
('ICT-ACCESS-SWITCH','HUAWEI',null),
('ICT-ACCESS-SWITCH','FORTINET',null),
('ICT-ACCESS-SWITCH','RUCKUS',null),
('ICT-ACCESS-SWITCH','COMMSCOPE',null),
('ICT-ACCESS-SWITCH','PANDUIT',null),
('ICT-ROUTER','CISCO',null),
('ICT-ROUTER','ARUBA',null),
('ICT-ROUTER','JUNIPER',null),
('ICT-ROUTER','HUAWEI',null),
('ICT-ROUTER','FORTINET',null),
('ICT-ROUTER','RUCKUS',null),
('ICT-ROUTER','COMMSCOPE',null),
('ICT-ROUTER','PANDUIT',null),
('ICT-FIREWALL','CISCO',null),
('ICT-FIREWALL','ARUBA',null),
('ICT-FIREWALL','JUNIPER',null),
('ICT-FIREWALL','HUAWEI',null),
('ICT-FIREWALL','FORTINET',null),
('ICT-FIREWALL','RUCKUS',null),
('ICT-FIREWALL','COMMSCOPE',null),
('ICT-FIREWALL','PANDUIT',null),
('ICT-WLC','CISCO',null),
('ICT-WLC','ARUBA',null),
('ICT-WLC','JUNIPER',null),
('ICT-WLC','HUAWEI',null),
('ICT-WLC','FORTINET',null),
('ICT-WLC','RUCKUS',null),
('ICT-WLC','COMMSCOPE',null),
('ICT-WLC','PANDUIT',null),
('ICT-AP','CISCO',null),
('ICT-AP','ARUBA',null),
('ICT-AP','JUNIPER',null),
('ICT-AP','HUAWEI',null),
('ICT-AP','FORTINET',null),
('ICT-AP','RUCKUS',null),
('ICT-AP','COMMSCOPE',null),
('ICT-AP','PANDUIT',null),
('ICT-RACK','CISCO',null),
('ICT-RACK','ARUBA',null),
('ICT-RACK','JUNIPER',null),
('ICT-RACK','HUAWEI',null),
('ICT-RACK','FORTINET',null),
('ICT-RACK','RUCKUS',null),
('ICT-RACK','COMMSCOPE',null),
('ICT-RACK','PANDUIT',null),
('ICT-FIBER-PANEL','CISCO',null),
('ICT-FIBER-PANEL','ARUBA',null),
('ICT-FIBER-PANEL','JUNIPER',null),
('ICT-FIBER-PANEL','HUAWEI',null),
('ICT-FIBER-PANEL','FORTINET',null),
('ICT-FIBER-PANEL','RUCKUS',null),
('ICT-FIBER-PANEL','COMMSCOPE',null),
('ICT-FIBER-PANEL','PANDUIT',null),
('ICT-COPPER-PANEL','CISCO',null),
('ICT-COPPER-PANEL','ARUBA',null),
('ICT-COPPER-PANEL','JUNIPER',null),
('ICT-COPPER-PANEL','HUAWEI',null),
('ICT-COPPER-PANEL','FORTINET',null),
('ICT-COPPER-PANEL','RUCKUS',null),
('ICT-COPPER-PANEL','COMMSCOPE',null),
('ICT-COPPER-PANEL','PANDUIT',null),
('ICT-OLT','CISCO',null),
('ICT-OLT','ARUBA',null),
('ICT-OLT','JUNIPER',null),
('ICT-OLT','HUAWEI',null),
('ICT-OLT','FORTINET',null),
('ICT-OLT','RUCKUS',null),
('ICT-OLT','COMMSCOPE',null),
('ICT-OLT','PANDUIT',null),
('ICT-GPON','CISCO',null),
('ICT-GPON','ARUBA',null),
('ICT-GPON','JUNIPER',null),
('ICT-GPON','HUAWEI',null),
('ICT-GPON','FORTINET',null),
('ICT-GPON','RUCKUS',null),
('ICT-GPON','COMMSCOPE',null),
('ICT-GPON','PANDUIT',null),
('DC-CRAC','VERTIV',null),
('DC-CRAC','APC',null),
('DC-CRAC','SCHNEIDER',null),
('DC-CRAC','HUAWEI',null),
('DC-CRAC','EATON',null),
('DC-CRAC','STULZ',null),
('DC-CRAC','RITTAL',null),
('DC-CRAH','VERTIV',null),
('DC-CRAH','APC',null),
('DC-CRAH','SCHNEIDER',null),
('DC-CRAH','HUAWEI',null),
('DC-CRAH','EATON',null),
('DC-CRAH','STULZ',null),
('DC-CRAH','RITTAL',null),
('DC-INROW','VERTIV',null),
('DC-INROW','APC',null),
('DC-INROW','SCHNEIDER',null),
('DC-INROW','HUAWEI',null),
('DC-INROW','EATON',null),
('DC-INROW','STULZ',null),
('DC-INROW','RITTAL',null),
('DC-PDU','VERTIV',null),
('DC-PDU','APC',null),
('DC-PDU','SCHNEIDER',null),
('DC-PDU','HUAWEI',null),
('DC-PDU','EATON',null),
('DC-PDU','STULZ',null),
('DC-PDU','RITTAL',null),
('DC-RPP','VERTIV',null),
('DC-RPP','APC',null),
('DC-RPP','SCHNEIDER',null),
('DC-RPP','HUAWEI',null),
('DC-RPP','EATON',null),
('DC-RPP','STULZ',null),
('DC-RPP','RITTAL',null),
('DC-UPS','VERTIV',null),
('DC-UPS','APC',null),
('DC-UPS','EATON',null),
('DC-UPS','HUAWEI',null),
('DC-UPS','RIELLO',null),
('DC-UPS','SOCOMEC',null),
('DC-UPS','BORRI',null),
('DC-RACK','VERTIV',null),
('DC-RACK','APC',null),
('DC-RACK','SCHNEIDER',null),
('DC-RACK','HUAWEI',null),
('DC-RACK','EATON',null),
('DC-RACK','STULZ',null),
('DC-RACK','RITTAL',null),
('DC-CONTAINMENT','VERTIV',null),
('DC-CONTAINMENT','APC',null),
('DC-CONTAINMENT','SCHNEIDER',null),
('DC-CONTAINMENT','HUAWEI',null),
('DC-CONTAINMENT','EATON',null),
('DC-CONTAINMENT','STULZ',null),
('DC-CONTAINMENT','RITTAL',null),
('DC-LEAK-DETECT','VERTIV',null),
('DC-LEAK-DETECT','APC',null),
('DC-LEAK-DETECT','SCHNEIDER',null),
('DC-LEAK-DETECT','HUAWEI',null),
('DC-LEAK-DETECT','EATON',null),
('DC-LEAK-DETECT','STULZ',null),
('DC-LEAK-DETECT','RITTAL',null),
('DC-ENV-MON','VERTIV',null),
('DC-ENV-MON','APC',null),
('DC-ENV-MON','SCHNEIDER',null),
('DC-ENV-MON','HUAWEI',null),
('DC-ENV-MON','EATON',null),
('DC-ENV-MON','STULZ',null),
('DC-ENV-MON','RITTAL',null),
('PARK-BARRIER','FAAC',null),
('PARK-BARRIER','CAME',null),
('PARK-BARRIER','HIKVISION',null),
('PARK-BARRIER','DAHUA',null),
('PARK-BARRIER','GENETEC',null),
('PARK-LPR','FAAC',null),
('PARK-LPR','CAME',null),
('PARK-LPR','HIKVISION',null),
('PARK-LPR','DAHUA',null),
('PARK-LPR','GENETEC',null),
('PARK-GUIDANCE','FAAC',null),
('PARK-GUIDANCE','CAME',null),
('PARK-GUIDANCE','HIKVISION',null),
('PARK-GUIDANCE','DAHUA',null),
('PARK-GUIDANCE','GENETEC',null),
('PARK-PAY','FAAC',null),
('PARK-PAY','CAME',null),
('PARK-PAY','HIKVISION',null),
('PARK-PAY','DAHUA',null),
('PARK-PAY','GENETEC',null),
('AUTO-DOOR','DORMAKABA',null),
('AUTO-DOOR','ASSA',null),
('AUTO-DOOR','GEZE',null),
('AUTO-DOOR','FAAC',null),
('AUTO-DOOR','CAME',null),
('SLIDING-GATE','DORMAKABA',null),
('SLIDING-GATE','ASSA',null),
('SLIDING-GATE','GEZE',null),
('SLIDING-GATE','FAAC',null),
('SLIDING-GATE','CAME',null),
('ROLLING-SHUTTER','DORMAKABA',null),
('ROLLING-SHUTTER','ASSA',null),
('ROLLING-SHUTTER','GEZE',null),
('ROLLING-SHUTTER','FAAC',null),
('ROLLING-SHUTTER','CAME',null),
('SECTIONAL-DOOR','DORMAKABA',null),
('SECTIONAL-DOOR','ASSA',null),
('SECTIONAL-DOOR','GEZE',null),
('SECTIONAL-DOOR','FAAC',null),
('SECTIONAL-DOOR','CAME',null),
('DOCK-LEVELLER','DORMAKABA',null),
('DOCK-LEVELLER','ASSA',null),
('DOCK-LEVELLER','GEZE',null),
('DOCK-LEVELLER','FAAC',null),
('DOCK-LEVELLER','CAME',null),
('FACADE-BMU','DORMAKABA',null),
('FACADE-BMU','ASSA',null),
('FACADE-BMU','GEZE',null),
('FACADE-BMU','FAAC',null),
('FACADE-BMU','CAME',null),
('ROOF-WATERPROOF','DORMAKABA',null),
('ROOF-WATERPROOF','ASSA',null),
('ROOF-WATERPROOF','GEZE',null),
('ROOF-WATERPROOF','FAAC',null),
('ROOF-WATERPROOF','CAME',null),
('EXPANSION-JOINT','DORMAKABA',null),
('EXPANSION-JOINT','ASSA',null),
('EXPANSION-JOINT','GEZE',null),
('EXPANSION-JOINT','FAAC',null),
('EXPANSION-JOINT','CAME',null),
('KITCHEN-HOOD','RATIONAL',null),
('KITCHEN-HOOD','HOBART',null),
('KITCHEN-HOOD','MEIKO',null),
('KITCHEN-HOOD','WINTERHALTER',null),
('KITCHEN-HOOD','ELECTROLUXPRO',null),
('KITCHEN-DISHWASHER','RATIONAL',null),
('KITCHEN-DISHWASHER','HOBART',null),
('KITCHEN-DISHWASHER','MEIKO',null),
('KITCHEN-DISHWASHER','WINTERHALTER',null),
('KITCHEN-DISHWASHER','ELECTROLUXPRO',null),
('KITCHEN-OVEN','RATIONAL',null),
('KITCHEN-OVEN','HOBART',null),
('KITCHEN-OVEN','MEIKO',null),
('KITCHEN-OVEN','WINTERHALTER',null),
('KITCHEN-OVEN','ELECTROLUXPRO',null),
('KITCHEN-COOKER','RATIONAL',null),
('KITCHEN-COOKER','HOBART',null),
('KITCHEN-COOKER','MEIKO',null),
('KITCHEN-COOKER','WINTERHALTER',null),
('KITCHEN-COOKER','ELECTROLUXPRO',null),
('KITCHEN-COLDROOM','CARRIER',null),
('KITCHEN-COLDROOM','DAIKIN',null),
('KITCHEN-COLDROOM','DUNHAM',null),
('KITCHEN-FREEZER','CARRIER',null),
('KITCHEN-FREEZER','DAIKIN',null),
('KITCHEN-FREEZER','ELECTROLUXPRO',null),
('LAUNDRY-WASHER','ELECTROLUXPRO',null),
('LAUNDRY-DRYER','ELECTROLUXPRO',null),
('LAUNDRY-IRONER','ELECTROLUXPRO',null),
('LPG-TANK','HONEYWELL',null),
('LPG-TANK','SIEMENS',null),
('LPG-TANK','SCHNEIDER',null),
('LPG-DETECTOR','HONEYWELL',null),
('LPG-DETECTOR','SIEMENS',null),
('LPG-DETECTOR','SCHNEIDER',null),
('FUEL-TANK','HONEYWELL',null),
('FUEL-TANK','SIEMENS',null),
('FUEL-TANK','SCHNEIDER',null),
('FUEL-TRANSFER-PUMP','HONEYWELL',null),
('FUEL-TRANSFER-PUMP','SIEMENS',null),
('FUEL-TRANSFER-PUMP','SCHNEIDER',null),
('POOL-PUMP','PENTAIR',null),
('POOL-PUMP','GRUNDFOS',null),
('POOL-FILTER','PENTAIR',null),
('POOL-FILTER','GRUNDFOS',null),
('POOL-DOSING','PENTAIR',null),
('POOL-DOSING','GRUNDFOS',null),
('MED-GAS-MANIFOLD','HONEYWELL',null),
('MED-GAS-MANIFOLD','SIEMENS',null),
('MED-GAS-MANIFOLD','SCHNEIDER',null),
('MED-GAS-ALARM','HONEYWELL',null),
('MED-GAS-ALARM','SIEMENS',null),
('MED-GAS-ALARM','SCHNEIDER',null),
('NURSE-CALL','HONEYWELL',null),
('NURSE-CALL','SIEMENS',null),
('NURSE-CALL','SCHNEIDER',null),
('ABLUTION-PUMP','GRUNDFOS',null),
('ABLUTION-PUMP','BOSCH',null),
('ABLUTION-PUMP','HONEYWELL',null),
('PRAYER-AUDIO','GRUNDFOS',null),
('PRAYER-AUDIO','BOSCH',null),
('PRAYER-AUDIO','HONEYWELL',null),
('HVAC-SPLIT','ZAMIL','Classic / Cooline / Commercial Split'),
('HVAC-PACKAGE','ZAMIL','Package / Rooftop Units'),
('HVAC-CHILLER-AIR','CARRIER','AquaForce / Air-Cooled Chillers'),
('HVAC-CHILLER-WATER','CARRIER','AquaEdge / Water-Cooled Chillers'),
('HVAC-CHILLER-AIR','TRANE','Sintesis / Air-Cooled'),
('HVAC-CHILLER-WATER','TRANE','CenTraVac / Water-Cooled'),
('HVAC-CHILLER-AIR','YORK','YVAA / Air-Cooled'),
('HVAC-CHILLER-WATER','YORK','YK / YZ Water-Cooled'),
('BMS-SERVER','JCI','Metasys'),
('BMS-CONTROLLER','JCI','Metasys Controllers'),
('BMS-SERVER','HONEYWELL','Honeywell Building Management / Niagara-based'),
('BMS-CONTROLLER','HONEYWELL','Optimizer / Building Controllers'),
('FIRE-ALARM-PANEL','NOTIFIER','ONYX / INSPIRE / FireWarden'),
('FIRE-ALARM-PANEL','SIMPLEX','4100ES / ES Series'),
('FIRE-ALARM-PANEL','SIEMENS','Cerberus PRO'),
('FIRE-FM200','KIDDE','FM-200 Clean Agent'),
('FIRE-FM200','ANSUL','Clean Agent Systems'),
('FIRE-NOVEC','KIDDE','Existing Novec 1230 Installed Base'),
('ELEC-GENERATOR','CUMMINS','Power Generation Sets'),
('ELEC-GENERATOR','CATERPILLAR','Cat Generator Sets'),
('ELEC-UPS','VERTIV','Liebert UPS'),
('ELEC-UPS','APC','Galaxy / Smart-UPS'),
('DC-CRAC','VERTIV','Liebert Precision Cooling'),
('DC-CRAC','STULZ','CyberAir'),
('ICT-CORE-SWITCH','CISCO','Catalyst / Nexus'),
('ICT-ACCESS-SWITCH','ARUBA','CX Switching'),
('SEC-CCTV-FIXED','AXIS','Network Cameras'),
('SEC-VMS','GENETEC','Security Center')
)
insert into public.bf_master_asset_options(asset_type_id,manufacturer_id,model_family)
select t.id,m.id,x.model_family
from x
join public.bf_master_asset_types t on t.code=x.asset_code
join public.bf_master_manufacturers m on m.code=x.manufacturer_code
where not exists(
 select 1 from public.bf_master_asset_options o
 where o.asset_type_id=t.id and o.manufacturer_id=m.id
 and coalesce(o.model_family,'')=coalesce(x.model_family,'')
);


update public.bf_master_asset_types
set group_ar=case system_code when 'HVAC' then 'التكييف والتهوية' when 'BMS' then 'إدارة المباني والتحكم' when 'FIRE_ALARM' then 'إنذار الحريق' when 'FIRE_SUPPRESSION' then 'مكافحة وإطفاء الحريق' when 'ELECTRICAL' then 'الأنظمة الكهربائية' when 'ENERGY' then 'الطاقة والاستدامة' when 'PLUMBING' then 'السباكة والمياه' when 'WATER' then 'معالجة المياه' when 'IRRIGATION' then 'الري والمناظر الطبيعية' when 'VERTICAL' then 'النقل الرأسي' when 'SECURITY' then 'الأمن والمراقبة' when 'ELV' then 'الأنظمة منخفضة التيار' when 'ICT' then 'الشبكات والاتصالات' when 'DATACENTER' then 'مراكز البيانات' when 'PARKING' then 'المواقف وإدارة المركبات' when 'GENERAL' then 'الأبواب والعناصر المعمارية' when 'KITCHEN' then 'معدات المطابخ' when 'LAUNDRY' then 'معدات المغاسل' when 'GAS' then 'الغاز والوقود' when 'POOL' then 'المسابح والنوافير' when 'HEALTHCARE' then 'أنظمة المرافق الصحية' when 'PUBLIC' then 'مرافق عامة خاصة' else coalesce(group_ar,system_code) end,
    group_en=case system_code when 'HVAC' then 'HVAC & Ventilation' when 'BMS' then 'BMS & Controls' when 'FIRE_ALARM' then 'Fire Alarm' when 'FIRE_SUPPRESSION' then 'Fire Fighting & Suppression' when 'ELECTRICAL' then 'Electrical' when 'ENERGY' then 'Energy & Sustainability' when 'PLUMBING' then 'Plumbing' when 'WATER' then 'Water Treatment' when 'IRRIGATION' then 'Irrigation & Landscape' when 'VERTICAL' then 'Vertical Transportation' when 'SECURITY' then 'Security & CCTV' when 'ELV' then 'ELV / AV' when 'ICT' then 'ICT & Networks' when 'DATACENTER' then 'Data Center' when 'PARKING' then 'Parking' when 'GENERAL' then 'Doors & Architectural' when 'KITCHEN' then 'Commercial Kitchen' when 'LAUNDRY' then 'Laundry' when 'GAS' then 'Gas & Fuel' when 'POOL' then 'Pools & Fountains' when 'HEALTHCARE' then 'Healthcare Facility Systems' when 'PUBLIC' then 'Public Facility Systems' else coalesce(group_en,system_code) end;


insert into public.bf_master_ppm_templates(asset_type_id,title_ar,title_en,frequency,estimated_minutes,reference,status)
select t.id,
       'الصيانة الدورية - '||t.name_ar,
       'Periodic Maintenance - '||t.name_en,
       case
         when t.system_code in('FIRE_ALARM','FIRE_SUPPRESSION','ELECTRICAL','DATACENTER','VERTICAL','HEALTHCARE') then 'monthly'
         when t.system_code in('HVAC','BMS','PLUMBING','WATER','GAS','KITCHEN','LAUNDRY') then 'monthly'
         else 'quarterly'
       end,
       case when t.default_criticality='critical' then 90 when t.default_criticality='high' then 60 else 45 end,
       'Master Asset Library - baseline; follow OEM manual and approved site method statement.',
       'active'
from public.bf_master_asset_types t
where t.status='active'
and not exists(select 1 from public.bf_master_ppm_templates p where p.asset_type_id=t.id and p.status='active');


insert into public.bf_master_ppm_steps(template_id,seq,title_ar,title_en,instructions_ar,instructions_en,task_type,response_type,safety_notes)
select p.id,s.seq,s.ar,s.en,s.iar,s.ien,s.task,s.resp,s.safety
from public.bf_master_ppm_templates p
join public.bf_master_asset_types t on t.id=p.asset_type_id
cross join lateral (values
 (1,'فحص بصري وحالة الأصل','Visual inspection and asset condition','افحص الحالة العامة والتسريب والتآكل والتثبيت وأي تلف ظاهر.','Inspect overall condition, leaks, corrosion, mounting and visible damage.','inspection','pass_fail',case when t.default_criticality='critical' then 'Follow approved PTW/LOTO and OEM safety instructions.' else null end),
 (2,'تنظيف وفحص منطقة التشغيل','Clean and inspect operating area','نظف المناطق المسموح بها وتأكد من عدم وجود عوائق أو أتربة مؤثرة.','Clean permitted areas and verify no obstruction or harmful dust buildup.','cleaning','pass_fail',null),
 (3,'فحص الحماية والتوصيلات','Check protections and connections','افحص وسائل الحماية والتوصيلات والحساسات أو الصمامات حسب نوع الأصل.','Check protections, connections, sensors or valves as applicable.','inspection','pass_fail',null),
 (4,'اختبار التشغيل والقراءات','Operational test and readings','شغل الأصل وفق الإجراء المعتمد وسجل القراءات الأساسية والإنذارات.','Operate per approved procedure and record key readings and alarms.','test','text',null),
 (5,'توثيق العيوب والإجراءات','Record defects and actions','سجل أي عيب أو قطعة مطلوبة أو توصية واربطها بأمر عمل عند الحاجة.','Record defects, required spares and recommendations; raise a work order when required.','other','text',null)
) s(seq,ar,en,iar,ien,task,resp,safety)
where not exists(select 1 from public.bf_master_ppm_steps z where z.template_id=p.id)
on conflict(template_id,seq) do nothing;


create or replace view public.bf_master_asset_catalog_report
with (security_invoker=true) as
select
 t.id,t.system_code,t.group_ar,t.group_en,t.code,t.icon_text,t.name_ar,t.name_en,
 t.default_criticality,t.expected_life_years,
 coalesce(string_agg(distinct m.name,' | ' order by m.name),'Generic / OEM') as manufacturers,
 count(distinct p.id) as maintenance_templates
from public.bf_master_asset_types t
left join public.bf_master_asset_options o on o.asset_type_id=t.id and o.status='active'
left join public.bf_master_manufacturers m on m.id=o.manufacturer_id and m.status='active'
left join public.bf_master_ppm_templates p on p.asset_type_id=t.id and p.status='active'
where t.status='active'
group by t.id;
grant select on public.bf_master_asset_catalog_report to authenticated;


create or replace function public.bf_master_adopt_templates(p_org uuid,p_asset_type uuid,p_manufacturer uuid default null)
returns jsonb language plpgsql security definer set search_path=''
as $$
declare t public.bf_master_asset_types; m public.bf_master_manufacturers; cat uuid; p record; proc uuid; n integer:=0;
begin
 if auth.uid() is null then raise exception 'Authentication required' using errcode='42501'; end if;
 if not public.bf_can(p_org,'assets.manage') then raise exception 'Permission denied' using errcode='42501'; end if;
 select * into t from public.bf_master_asset_types where id=p_asset_type and status='active';
 if not found then raise exception 'Asset type not found'; end if;
 if p_manufacturer is not null then
   select * into m from public.bf_master_manufacturers where id=p_manufacturer and status='active';
   if not found then raise exception 'Manufacturer not found'; end if;
 end if;

 select id into cat from public.bf_asset_categories where organization_id=p_org and code=t.code;
 if cat is null then
   insert into public.bf_asset_categories(organization_id,code,name_ar,name_en,description,icon_text,master_asset_type_id,preferred_manufacturer_id)
   values(p_org,t.code,t.name_ar,t.name_en,coalesce(t.description_en,t.name_en),t.icon_text,t.id,p_manufacturer)
   returning id into cat;
 else
   update public.bf_asset_categories
   set icon_text=t.icon_text,
       master_asset_type_id=t.id,
       preferred_manufacturer_id=coalesce(p_manufacturer,preferred_manufacturer_id)
   where id=cat;
 end if;

 for p in
   select * from public.bf_master_ppm_templates x
   where x.asset_type_id=t.id and x.status='active'
     and (x.manufacturer_id is null or x.manufacturer_id=p_manufacturer)
   order by x.frequency
 loop
  if not exists(
    select 1 from public.bf_ppm_procedures z
    where z.organization_id=p_org and z.category_id=cat and z.name_en=p.title_en and z.status<>'archived'
  ) then
   insert into public.bf_ppm_procedures(
     organization_id,code,name_ar,name_en,category_id,manufacturer,frequency,status,reference,estimated_minutes,created_by
   )
   values(
     p_org,'LIB-'||left(replace(t.code,'-',''),12)||'-'||left(replace(p.id::text,'-',''),8),
     p.title_ar,p.title_en,cat,case when p_manufacturer is null then null else m.name end,
     p.frequency,'approved',p.reference,p.estimated_minutes,auth.uid()
   ) returning id into proc;

   insert into public.bf_ppm_steps(
     procedure_id,seq,title_ar,title_en,instructions_ar,instructions_en,task_type,response_type,unit,safety_notes,tools,materials
   )
   select proc,s.seq,s.title_ar,s.title_en,s.instructions_ar,s.instructions_en,s.task_type,s.response_type,s.unit,s.safety_notes,s.tools,s.materials
   from public.bf_master_ppm_steps s where s.template_id=p.id order by s.seq;
   n:=n+1;
  end if;
 end loop;

 return jsonb_build_object('category_id',cat,'procedures_created',n,'asset_type',t.name_en,'manufacturer',m.name,'icon',t.icon_text);
end $$;

revoke all on function public.bf_master_adopt_templates(uuid,uuid,uuid) from public,anon;
grant execute on function public.bf_master_adopt_templates(uuid,uuid,uuid) to authenticated;

notify pgrst,'reload schema';
commit;
