-- Basmat Facilities CMMS V12.7.1
-- Direct, idempotent seed for Supabase SQL Editor.
-- Does not use Super Admin RPCs.
-- Does not change PPM, Dashboard, AppShell, users, permissions, or existing procedures.

begin;

create temporary table _v1271_brands(code text primary key,name text,short_name text) on commit drop;
insert into _v1271_brands(code,name,short_name) values
('SIEMENS','Siemens','Siemens'),
('SCHNEIDER','Schneider Electric','Schneider'),
('ABB','ABB','ABB'),
('EATON','Eaton','Eaton'),
('LEGRAND','Legrand','Legrand'),
('ALFANAR','alfanar','alfanar'),
('SOCOMEC','Socomec','Socomec'),
('LS','LS Electric','LS'),
('HONEYWELL','Honeywell','Honeywell'),
('JCI','Johnson Controls','JCI'),
('CARRIER','Carrier','Carrier'),
('TRANE','Trane','Trane'),
('YORK','York','York'),
('DAIKIN','Daikin','Daikin'),
('MITSUBISHI_E','Mitsubishi Electric','Mitsubishi'),
('LG','LG','LG'),
('SAMSUNG','Samsung','Samsung'),
('ZAMIL','Zamil','Zamil'),
('GREE','Gree','Gree'),
('MIDEA','Midea','Midea'),
('DANFOSS','Danfoss','Danfoss'),
('BELIMO','Belimo','Belimo'),
('DELTA_CONTROLS','Delta Controls','Delta Controls'),
('DISTECH','Distech Controls','Distech'),
('ALC','Automated Logic','ALC'),
('SAUTER','SAUTER','SAUTER'),
('TREND','Trend Controls','Trend'),
('TRIDIUM','Tridium','Tridium'),
('CISCO','Cisco','Cisco'),
('HPE','HPE','HPE'),
('ARUBA','Aruba','Aruba'),
('JUNIPER','Juniper Networks','Juniper'),
('HUAWEI','Huawei','Huawei'),
('FORTINET','Fortinet','Fortinet'),
('PALOALTO','Palo Alto Networks','Palo Alto'),
('DELL','Dell Technologies','Dell'),
('LENOVO','Lenovo','Lenovo'),
('IBM','IBM','IBM'),
('EXTREME','Extreme Networks','Extreme'),
('RUCKUS','Ruckus Networks','Ruckus'),
('UBIQUITI','Ubiquiti','Ubiquiti'),
('AVAYA','Avaya','Avaya'),
('MITEL','Mitel','Mitel'),
('NEC','NEC','NEC'),
('YEALINK','Yealink','Yealink'),
('POLY','Poly','Poly'),
('CRESTRON','Crestron','Crestron'),
('EXTRON','Extron','Extron'),
('BIAMP','Biamp','Biamp'),
('BOSE','Bose Professional','Bose'),
('JBL','JBL Professional','JBL'),
('SHURE','Shure','Shure'),
('SENNHEISER','Sennheiser','Sennheiser'),
('BARCO','Barco','Barco'),
('LOGITECH','Logitech','Logitech'),
('COMMSCOPE','CommScope','CommScope'),
('CORNING','Corning','Corning'),
('PANDUIT','Panduit','Panduit'),
('R_M','R&M','R&M'),
('NEXANS','Nexans','Nexans'),
('BELDEN','Belden','Belden'),
('SIEMON','Siemon','Siemon'),
('PRYSMIAN','Prysmian','Prysmian'),
('VERTIV','Vertiv','Vertiv'),
('RITTAL','Rittal','Rittal'),
('STULZ','STULZ','STULZ'),
('DELTA','Delta Electronics','Delta'),
('APC','APC by Schneider Electric','APC'),
('CUMMINS','Cummins','Cummins'),
('CATERPILLAR','Caterpillar','CAT'),
('PERKINS','Perkins','Perkins'),
('MTU','MTU','MTU'),
('FGWILSON','FG Wilson','FG Wilson'),
('KOHLER','Kohler','Kohler'),
('GRUNDFOS','Grundfos','Grundfos'),
('WILO','Wilo','Wilo'),
('KSB','KSB','KSB'),
('XYLEM','Xylem','Xylem'),
('LOWARA','Lowara','Lowara'),
('EBARA','Ebara','Ebara'),
('SULZER','Sulzer','Sulzer'),
('ARMSTRONG','Armstrong Fluid Technology','Armstrong'),
('NOTIFIER','Notifier by Honeywell','Notifier'),
('SIMPLEX','Simplex','Simplex'),
('TYCO','Tyco','Tyco'),
('EDWARDS','Edwards','Edwards'),
('BOSCH','Bosch','Bosch'),
('KIDDE','Kidde','Kidde'),
('HOCHIKI','Hochiki','Hochiki'),
('APOLLO','Apollo Fire Detectors','Apollo'),
('SFFECO','SFFECO','SFFECO'),
('NAFFCO','NAFFCO','NAFFCO'),
('ANSUL','ANSUL','ANSUL'),
('FIKE','Fike','Fike'),
('MINIMAX','Minimax','Minimax'),
('AXIS','Axis Communications','Axis'),
('HIKVISION','Hikvision','Hikvision'),
('DAHUA','Dahua Technology','Dahua'),
('HANWHA','Hanwha Vision','Hanwha'),
('GENETEC','Genetec','Genetec'),
('MILESTONE','Milestone Systems','Milestone'),
('HID','HID Global','HID'),
('SUPREMA','Suprema','Suprema'),
('DORMAKABA','dormakaba','dormakaba'),
('ASSA_ABLOY','ASSA ABLOY','ASSA ABLOY'),
('SALTO','SALTO','SALTO'),
('LENEL','LenelS2','LenelS2'),
('KONE','KONE','KONE'),
('OTIS','Otis','Otis'),
('SCHINDLER','Schindler','Schindler'),
('TKE','TK Elevator','TKE'),
('HYUNDAI_ELEV','Hyundai Elevator','Hyundai'),
('FUJITEC','Fujitec','Fujitec'),
('FAAC','FAAC','FAAC'),
('CAME','CAME','CAME'),
('NICE','Nice','Nice'),
('MAGNETIC','Magnetic Autocontrol','Magnetic'),
('HORMANN','Hörmann','Hörmann'),
('RATIONAL','RATIONAL','RATIONAL'),
('ELECTROLUX_PRO','Electrolux Professional','Electrolux'),
('HOBART','Hobart','Hobart'),
('MIELE','Miele','Miele'),
('PRIMUS','Primus','Primus'),
('IPSO','IPSO','IPSO'),
('SPEEDQUEEN','Speed Queen','Speed Queen'),
('CANON','Canon','Canon'),
('HP','HP','HP'),
('EPSON','Epson','Epson'),
('RICOH','Ricoh','Ricoh'),
('XEROX','Xerox','Xerox'),
('KYOCERA','Kyocera','Kyocera'),
('LEXMARK','Lexmark','Lexmark'),
('MOTOROLA','Motorola Solutions','Motorola'),
('HYTERA','Hytera','Hytera'),
('KENWOOD','Kenwood','Kenwood'),
('ICOM','Icom','Icom'),
('SEPURA','Sepura','Sepura'),
('DAMM','DAMM Cellular Systems','DAMM'),
('ERICSSON','Ericsson','Ericsson'),
('NOKIA','Nokia','Nokia'),
('COMBA','Comba Telecom','Comba'),
('SOLID','SOLiD','SOLiD'),
('JMA','JMA Wireless','JMA'),
('NEXTIVITY','Nextivity','Nextivity'),
('TOA','TOA','TOA'),
('ZENITEL','Zenitel','Zenitel'),
('INDUSTRONIC','INDUSTRONIC','INDUSTRONIC'),
('SAPLING','Sapling','Sapling'),
('BODET','Bodet','Bodet'),
('GORGY','Gorgy Time','Gorgy'),
('MASTER_CLOCK','Masterclock','Masterclock'),
('PHILIPS','Philips','Philips'),
('SONY','Sony','Sony'),
('PANASONIC','Panasonic','Panasonic'),
('PLANAR','Planar','Planar'),
('GE','GE','GE'),
('EMERSON','Emerson','Emerson'),
('ROCKWELL','Rockwell Automation','Rockwell'),
('OMRON','Omron','Omron'),
('PHOENIX','Phoenix Contact','Phoenix Contact'),
('WAGO','WAGO','WAGO'),
('SICK','SICK','SICK'),
('ENDRESS','Endress+Hauser','E+H'),
('VEGA','VEGA','VEGA'),
('YOKOGAWA','Yokogawa','Yokogawa'),
('KROHNE','KROHNE','KROHNE'),
('PENTAIR','Pentair','Pentair'),
('HAYWARD','Hayward','Hayward'),
('ASTRALPOOL','AstralPool','AstralPool'),
('RAINBIRD','Rain Bird','Rain Bird'),
('HUNTER','Hunter Industries','Hunter'),
('TORO','Toro','Toro');

-- Update existing manufacturer by code OR name, preserving IDs.
update public.bf_master_manufacturers m
set code=b.code,
    name=b.name,
    short_name=b.short_name,
    status='active'
from _v1271_brands b
where m.code=b.code or m.name=b.name;

-- Insert only truly new manufacturers.
insert into public.bf_master_manufacturers
(id,code,name,website,status,created_at,short_name)
select gen_random_uuid(),b.code,b.name,null,'active',now(),b.short_name
from _v1271_brands b
where not exists (
  select 1 from public.bf_master_manufacturers m
  where m.code=b.code or m.name=b.name
);

create temporary table _v1271_assets(
 code text primary key,
 system_code text,
 name_ar text,
 name_en text,
 icon_text text,
 default_criticality text,
 procurement_class text
) on commit drop;

insert into _v1271_assets(code,system_code,name_ar,name_en,icon_text,default_criticality,procurement_class) values
('CORE_SWITCH','ICT','سويتش أساسي','Core Network Switch','🌐','critical','long_lead'),
('DISTRIBUTION_SWITCH','ICT','سويتش توزيع','Distribution Switch','🌐','high','standard'),
('ACCESS_SWITCH','ICT','سويتش وصول','Access Switch','🌐','high','standard'),
('ROUTER','ICT','راوتر','Router','🌐','critical','standard'),
('FIREWALL','ICT','جدار حماية','Network Firewall','🛡️','critical','standard'),
('WLC','ICT','متحكم واي فاي','Wireless LAN Controller','📡','high','standard'),
('ACCESS_POINT','ICT','نقطة وصول لاسلكية','Wireless Access Point','📶','medium','standard'),
('LOAD_BALANCER','ICT','موازن أحمال','Load Balancer','⚖️','critical','long_lead'),
('SERVER','ICT','خادم','Server','🖥️','critical','standard'),
('STORAGE_ARRAY','ICT','مصفوفة تخزين','Storage Array','💾','critical','long_lead'),
('IP_PBX','TELEPHONY','سنترال IP','IP PBX / Call Manager','☎️','critical','long_lead'),
('IP_PHONE','TELEPHONY','هاتف IP','IP Phone','☎️','medium','standard'),
('VOICE_GATEWAY','TELEPHONY','بوابة صوت','Voice Gateway','☎️','high','standard'),
('SBC','TELEPHONY','متحكم حدود الجلسات','Session Border Controller','🛡️','critical','standard'),
('CONTACT_CENTER','TELEPHONY','منصة مركز اتصال','Contact Center Platform','🎧','critical','long_lead'),
('BMS_SERVER','BMS','خادم إدارة المبنى','BMS Server','🖥️','high','standard'),
('BMS_WORKSTATION','BMS','محطة تشغيل BMS','BMS Workstation','🖥️','medium','standard'),
('BMS_CONTROLLER','BMS','متحكم BMS','BMS Controller','🎛️','high','standard'),
('DDC','BMS','متحكم DDC','DDC Controller','🎛️','high','standard'),
('IO_MODULE','BMS','وحدة إدخال وإخراج','I/O Module','🔌','medium','standard'),
('FIELD_SENSOR','BMS','حساس ميداني','Field Sensor','🌡️','medium','standard'),
('ACTUATOR','BMS','مشغل صمام/دامبر','Actuator','⚙️','medium','standard'),
('CHILLER','HVAC','مبرد مركزي','Chiller','❄️','high','long_lead'),
('AHU','HVAC','وحدة مناولة هواء','Air Handling Unit','🌬️','high','standard'),
('FCU','HVAC','وحدة ملف ومروحة','Fan Coil Unit','🌬️','medium','standard'),
('VRF_ODU','HVAC','وحدة VRF خارجية','VRF Outdoor Unit','❄️','high','long_lead'),
('VRF_IDU','HVAC','وحدة VRF داخلية','VRF Indoor Unit','🌬️','medium','standard'),
('PACKAGE_AC','HVAC','وحدة تكييف باكيج','Package AC Unit','❄️','high','standard'),
('SPLIT_AC','HVAC','مكيف سبليت','Split AC Unit','❄️','medium','standard'),
('CRAC','HVAC','تكييف دقيق لمراكز البيانات','CRAC Unit','🧊','critical','long_lead'),
('COOLING_TOWER','HVAC','برج تبريد','Cooling Tower','💧','high','long_lead'),
('CHW_PUMP','HVAC','مضخة مياه مبردة','Chilled Water Pump','💧','high','standard'),
('VAV','HVAC','صندوق VAV','VAV Box','🌬️','medium','standard'),
('MV_SWITCHGEAR','ELECTRICAL','لوحة جهد متوسط','MV Switchgear','⚡','critical','long_lead'),
('LV_SWITCHGEAR','ELECTRICAL','لوحة جهد منخفض','LV Switchgear','⚡','critical','long_lead'),
('MDB','ELECTRICAL','لوحة توزيع رئيسية','Main Distribution Board','⚡','critical','long_lead'),
('SMDB','ELECTRICAL','لوحة توزيع فرعية','Sub Main Distribution Board','⚡','high','standard'),
('MCC','ELECTRICAL','مركز تحكم محركات','Motor Control Center','⚡','high','long_lead'),
('ATS','ELECTRICAL','مفتاح تحويل آلي','Automatic Transfer Switch','🔁','critical','long_lead'),
('TRANSFORMER','ELECTRICAL','محول كهربائي','Transformer','⚡','critical','long_lead'),
('UPS','ELECTRICAL','وحدة طاقة غير منقطعة','UPS','🔋','critical','long_lead'),
('BATTERY_BANK','ELECTRICAL','بنك بطاريات','Battery Bank','🔋','high','standard'),
('GENERATOR','ELECTRICAL','مولد كهربائي','Generator','🛢️','critical','long_lead'),
('VFD','ELECTRICAL','مغير سرعة','Variable Frequency Drive','🎚️','high','standard'),
('FACP','FIRE_ALARM','لوحة إنذار حريق','Fire Alarm Control Panel','🔥','critical','long_lead'),
('SMOKE_DETECTOR','FIRE_ALARM','كاشف دخان','Smoke Detector','🚨','high','standard'),
('HEAT_DETECTOR','FIRE_ALARM','كاشف حرارة','Heat Detector','🌡️','high','standard'),
('BEAM_DETECTOR','FIRE_ALARM','كاشف شعاع','Beam Detector','🔦','high','standard'),
('VESDA','FIRE_ALARM','نظام كشف دخان مبكر','Aspirating Smoke Detection','💨','critical','long_lead'),
('MCP','FIRE_ALARM','نقطة نداء يدوية','Manual Call Point','🟥','high','standard'),
('SOUNDER','FIRE_ALARM','جرس/صافرة إنذار','Alarm Sounder','🔊','high','standard'),
('FIRE_PUMP','FIRE_SUPPRESSION','مضخة حريق','Fire Pump','🚒','critical','long_lead'),
('JOCKEY_PUMP','FIRE_SUPPRESSION','مضخة جوكي','Jockey Pump','🚒','high','standard'),
('SPRINKLER_VALVE','FIRE_SUPPRESSION','صمام رشاشات','Sprinkler Valve Assembly','🚿','high','standard'),
('FIRE_HOSE_REEL','FIRE_SUPPRESSION','بكرة خرطوم حريق','Fire Hose Reel','🧯','high','standard'),
('FIRE_EXTINGUISHER','FIRE_SUPPRESSION','طفاية حريق','Fire Extinguisher','🧯','high','standard'),
('FM200_PANEL','FIRE_SUPPRESSION','لوحة إطفاء غازي','Clean Agent Releasing Panel','🔥','critical','long_lead'),
('FM200_CYLINDER','FIRE_SUPPRESSION','اسطوانة إطفاء غازي','Clean Agent Cylinder','🧯','critical','long_lead'),
('CCTV_CAMERA','SECURITY','كاميرا مراقبة','CCTV Camera','📷','high','standard'),
('NVR','SECURITY','مسجل شبكي','Network Video Recorder','🎥','high','standard'),
('VMS_SERVER','SECURITY','خادم إدارة فيديو','VMS Server','🖥️','high','standard'),
('ACCESS_CONTROLLER','SECURITY','متحكم دخول','Access Control Panel','🚪','high','standard'),
('CARD_READER','SECURITY','قارئ بطاقات','Card Reader','💳','medium','standard'),
('BIOMETRIC_READER','SECURITY','قارئ بصمة/وجه','Biometric Reader','🖐️','medium','standard'),
('TURNSTILE','SECURITY','بوابة أفراد','Turnstile','🚧','high','long_lead'),
('DC_RACK','DATACENTER','راك مركز بيانات','Data Center Rack','🗄️','high','long_lead'),
('RACK_PDU','DATACENTER','وحدة توزيع طاقة راك','Rack PDU','🔌','high','standard'),
('PRECISION_COOLING','DATACENTER','تبريد دقيق','Precision Cooling Unit','🧊','critical','long_lead'),
('DCIM','DATACENTER','نظام DCIM','DCIM Platform','🖥️','high','long_lead'),
('STATIC_TRANSFER_SWITCH','DATACENTER','مفتاح تحويل ثابت','Static Transfer Switch','⚡','critical','long_lead'),
('BUSWAY','DATACENTER','مسار طاقة Busway','Data Center Busway','⚡','critical','long_lead'),
('COPPER_PATCH_PANEL','STRUCTURED_CABLING','باتش بانل نحاسي','Copper Patch Panel','🔌','medium','standard'),
('FIBER_PATCH_PANEL','STRUCTURED_CABLING','باتش بانل فايبر','Fiber Patch Panel','🔦','high','standard'),
('ODF','STRUCTURED_CABLING','موزع ألياف','Optical Distribution Frame','🔦','high','standard'),
('NETWORK_RACK','STRUCTURED_CABLING','راك شبكات','Network Rack','🗄️','high','long_lead'),
('FIBER_CABLE','STRUCTURED_CABLING','كابل ألياف','Fiber Optic Cable','🧵','high','long_lead'),
('COPPER_CABLE','STRUCTURED_CABLING','كابل نحاسي','Copper Data Cable','🧵','medium','standard'),
('DAS_HEADEND','DAS','وحدة DAS رئيسية','DAS Headend','📶','critical','long_lead'),
('DAS_REMOTE','DAS','وحدة DAS طرفية','DAS Remote Unit','📶','critical','long_lead'),
('BDA','DAS','مضخم ثنائي الاتجاه','Bi-Directional Amplifier','📶','high','standard'),
('RF_REPEATER','DAS','مكرر RF','RF Repeater','📶','high','standard'),
('DAS_ANTENNA','DAS','هوائي داخلي','Indoor DAS Antenna','📡','medium','standard'),
('DMR_REPEATER','RADIO','مكرر DMR','DMR Repeater','📻','high','standard'),
('TETRA_REPEATER','RADIO','مكرر TETRA','TETRA Repeater','📻','critical','long_lead'),
('BASE_STATION','RADIO','محطة لاسلكية','Radio Base Station','📡','high','long_lead'),
('HANDHELD_RADIO','RADIO','جهاز لاسلكي محمول','Handheld Radio','📻','medium','standard'),
('DISPATCH_CONSOLE','RADIO','كونسول تحكم لاسلكي','Radio Dispatch Console','🎧','high','standard'),
('VIDEO_CODEC','UC_AV','وحدة مؤتمر مرئي','Video Conferencing Codec','🎥','high','standard'),
('ROOM_PANEL','UC_AV','لوحة تحكم غرفة','Room Control Panel','🎛️','medium','standard'),
('DSP','UC_AV','معالج صوت رقمي','Audio DSP','🎚️','high','standard'),
('AMPLIFIER','UC_AV','مضخم صوت','Audio Amplifier','🔊','medium','standard'),
('MICROPHONE','UC_AV','ميكروفون','Microphone','🎤','medium','standard'),
('AV_MATRIX','UC_AV','مصفوفة AV','AV Matrix Switcher','🎛️','high','standard'),
('PROJECTOR','UC_AV','بروجكتر','Projector','📽️','medium','standard'),
('LED_DISPLAY','UC_AV','شاشة LED','LED Display','🖥️','high','long_lead'),
('PAGA_CONTROLLER','PAGA','متحكم PAGA','PAGA Controller','📢','critical','long_lead'),
('PA_AMPLIFIER','PAGA','مضخم نداء عام','PA Amplifier','🔊','high','standard'),
('PA_SPEAKER','PAGA','سماعة نداء عام','PA Speaker','🔊','medium','standard'),
('PAGING_MIC','PAGA','ميكروفون نداء','Paging Microphone','🎤','medium','standard'),
('ELEVATOR','VERTICAL','مصعد','Elevator','🛗','critical','long_lead'),
('ESCALATOR','VERTICAL','سلم متحرك','Escalator','↗️','critical','long_lead'),
('MOVING_WALK','VERTICAL','ممر متحرك','Moving Walk','➡️','critical','long_lead'),
('DOMESTIC_PUMP','PLUMBING','مضخة مياه استخدام','Domestic Water Pump','💧','high','standard'),
('BOOSTER_SET','PLUMBING','مجموعة تقوية ضغط','Booster Pump Set','💧','high','long_lead'),
('SUMP_PUMP','PLUMBING','مضخة تجميع','Sump Pump','💧','medium','standard'),
('SEWAGE_PUMP','PLUMBING','مضخة صرف صحي','Sewage Pump','💧','high','standard'),
('WATER_HEATER','PLUMBING','سخان مياه','Water Heater','♨️','medium','standard'),
('RO_SYSTEM','WATER','نظام تناضح عكسي','RO System','💧','high','long_lead'),
('UV_SYSTEM','WATER','وحدة تعقيم UV','UV Disinfection Unit','💡','high','standard'),
('SOFTENER','WATER','منقي مياه','Water Softener','💧','medium','standard'),
('FILTER_SKID','WATER','وحدة ترشيح','Water Filtration Skid','💧','high','standard'),
('PARKING_BARRIER','PARKING','حاجز مواقف','Parking Barrier','🚧','high','standard'),
('PARKING_CONTROLLER','PARKING','متحكم مواقف','Parking Controller','🎛️','high','standard'),
('LPR_CAMERA','PARKING','كاميرا قراءة لوحات','LPR Camera','📷','high','standard'),
('PARKING_SENSOR','PARKING','حساس موقف','Parking Bay Sensor','🅿️','medium','standard'),
('AUTO_DOOR','GENERAL','باب أوتوماتيكي','Automatic Door','🚪','high','standard'),
('REVOLVING_DOOR','GENERAL','باب دوار','Revolving Door','🚪','high','long_lead'),
('ROLLER_SHUTTER','GENERAL','باب رول','Roller Shutter','🚪','high','standard'),
('GATE_OPERATOR','GENERAL','محرك بوابة','Gate Operator','🚧','high','standard'),
('COMBI_OVEN','KITCHEN','فرن كومبي','Combi Oven','🍳','high','long_lead'),
('DISHWASHER','KITCHEN','غسالة صحون تجارية','Commercial Dishwasher','🍽️','high','standard'),
('KITCHEN_HOOD','KITCHEN','شفاط مطبخ','Kitchen Hood','🌬️','high','standard'),
('WALKIN_FREEZER','KITCHEN','فريزر غرفة','Walk-in Freezer','🧊','high','long_lead'),
('WASHER_EXTRACTOR','LAUNDRY','غسالة صناعية','Washer Extractor','🧺','high','long_lead'),
('TUMBLE_DRYER','LAUNDRY','مجفف صناعي','Tumble Dryer','🧺','high','long_lead'),
('IRONER','LAUNDRY','مكواة رول','Flatwork Ironer','🧺','high','long_lead'),
('LASER_PRINTER','OFFICE','طابعة ليزر','Laser Printer','🖨️','low','standard'),
('MFP','OFFICE','طابعة متعددة الوظائف','Multifunction Printer','🖨️','medium','standard'),
('PLOTTER','OFFICE','بلوتر','Large Format Plotter','🖨️','medium','standard'),
('SOLAR_INVERTER','ENERGY','عاكس شمسي','Solar Inverter','☀️','high','long_lead'),
('PV_PANEL','ENERGY','لوح شمسي','PV Panel','☀️','medium','long_lead'),
('EV_CHARGER','ENERGY','شاحن مركبات كهربائية','EV Charger','🔌','high','standard'),
('IRR_PUMP','IRRIGATION','مضخة ري','Irrigation Pump','💧','medium','standard'),
('IRR_CONTROLLER','IRRIGATION','متحكم ري','Irrigation Controller','🎛️','medium','standard'),
('SOLENOID_VALVE','IRRIGATION','صمام ري كهربائي','Irrigation Solenoid Valve','🔧','low','standard'),
('POOL_PUMP','POOL','مضخة مسبح','Pool Pump','🏊','medium','standard'),
('POOL_FILTER','POOL','فلتر مسبح','Pool Filter','🏊','medium','standard'),
('POOL_DOSING','POOL','نظام جرعات مسبح','Pool Chemical Dosing','🧪','high','standard'),
('GAS_DETECTOR','GAS','كاشف غاز','Gas Detector','⚠️','critical','standard'),
('GAS_PANEL','GAS','لوحة كشف غاز','Gas Detection Panel','⚠️','critical','standard'),
('LPG_TANK','GAS','خزان غاز','LPG Tank','🛢️','critical','long_lead'),
('MED_GAS_PANEL','HEALTHCARE','لوحة غازات طبية','Medical Gas Alarm Panel','🏥','critical','standard'),
('MED_GAS_MANIFOLD','HEALTHCARE','مجمع غازات طبية','Medical Gas Manifold','🏥','critical','long_lead'),
('NURSE_CALL','HEALTHCARE','نظام نداء تمريض','Nurse Call System','🏥','critical','long_lead'),
('MASTER_CLOCK','CLOCK_PAGING','ساعة رئيسية','Master Clock','🕒','high','standard'),
('SLAVE_CLOCK','CLOCK_PAGING','ساعة فرعية','Slave Clock','🕒','medium','standard'),
('CLOCK_SERVER','CLOCK_PAGING','خادم توقيت','Time Server','🕒','high','standard');

insert into public.bf_master_asset_types(
 id,system_code,code,name_ar,name_en,description_ar,description_en,
 default_criticality,expected_life_years,status,created_at,icon_text,
 group_ar,group_en,procurement_class,default_lead_time_days,critical_spare,stock_strategy
)
select
 gen_random_uuid(),a.system_code,a.code,a.name_ar,a.name_en,null,null,
 a.default_criticality,null,'active',now(),a.icon_text,
 null,null,a.procurement_class,null,(a.default_criticality='critical'),
 case when a.procurement_class='long_lead' then 'critical_spares_review' else null end
from _v1271_assets a
on conflict (code) do update set
 system_code=excluded.system_code,
 name_ar=excluded.name_ar,
 name_en=excluded.name_en,
 icon_text=excluded.icon_text,
 default_criticality=excluded.default_criticality,
 procurement_class=excluded.procurement_class,
 critical_spare=excluded.critical_spare,
 stock_strategy=coalesce(public.bf_master_asset_types.stock_strategy,excluded.stock_strategy),
 status='active';

create temporary table _v1271_map(system_code text,brand_code text) on commit drop;
insert into _v1271_map(system_code,brand_code) values
('ICT','CISCO'),
('ICT','HPE'),
('ICT','ARUBA'),
('ICT','JUNIPER'),
('ICT','HUAWEI'),
('ICT','FORTINET'),
('ICT','PALOALTO'),
('ICT','DELL'),
('ICT','LENOVO'),
('ICT','IBM'),
('ICT','EXTREME'),
('ICT','RUCKUS'),
('ICT','UBIQUITI'),
('TELEPHONY','AVAYA'),
('TELEPHONY','CISCO'),
('TELEPHONY','MITEL'),
('TELEPHONY','NEC'),
('TELEPHONY','YEALINK'),
('TELEPHONY','POLY'),
('TELEPHONY','HUAWEI'),
('BMS','JCI'),
('BMS','HONEYWELL'),
('BMS','SIEMENS'),
('BMS','SCHNEIDER'),
('BMS','DELTA_CONTROLS'),
('BMS','DISTECH'),
('BMS','ALC'),
('BMS','SAUTER'),
('BMS','TREND'),
('BMS','TRIDIUM'),
('BMS','BELIMO'),
('HVAC','CARRIER'),
('HVAC','TRANE'),
('HVAC','YORK'),
('HVAC','DAIKIN'),
('HVAC','MITSUBISHI_E'),
('HVAC','LG'),
('HVAC','SAMSUNG'),
('HVAC','ZAMIL'),
('HVAC','GREE'),
('HVAC','MIDEA'),
('HVAC','DANFOSS'),
('HVAC','BELIMO'),
('HVAC','JCI'),
('HVAC','HONEYWELL'),
('HVAC','SIEMENS'),
('HVAC','SCHNEIDER'),
('ELECTRICAL','SIEMENS'),
('ELECTRICAL','SCHNEIDER'),
('ELECTRICAL','ABB'),
('ELECTRICAL','EATON'),
('ELECTRICAL','LEGRAND'),
('ELECTRICAL','ALFANAR'),
('ELECTRICAL','SOCOMEC'),
('ELECTRICAL','LS'),
('ELECTRICAL','HUAWEI'),
('ELECTRICAL','VERTIV'),
('ELECTRICAL','DELTA'),
('ELECTRICAL','APC'),
('ELECTRICAL','CUMMINS'),
('ELECTRICAL','CATERPILLAR'),
('ELECTRICAL','KOHLER'),
('FIRE_ALARM','HONEYWELL'),
('FIRE_ALARM','NOTIFIER'),
('FIRE_ALARM','SIMPLEX'),
('FIRE_ALARM','JCI'),
('FIRE_ALARM','SIEMENS'),
('FIRE_ALARM','EDWARDS'),
('FIRE_ALARM','BOSCH'),
('FIRE_ALARM','KIDDE'),
('FIRE_ALARM','HOCHIKI'),
('FIRE_ALARM','APOLLO'),
('FIRE_SUPPRESSION','SFFECO'),
('FIRE_SUPPRESSION','NAFFCO'),
('FIRE_SUPPRESSION','ANSUL'),
('FIRE_SUPPRESSION','TYCO'),
('FIRE_SUPPRESSION','KIDDE'),
('FIRE_SUPPRESSION','FIKE'),
('FIRE_SUPPRESSION','MINIMAX'),
('FIRE_SUPPRESSION','GRUNDFOS'),
('FIRE_SUPPRESSION','KSB'),
('SECURITY','AXIS'),
('SECURITY','BOSCH'),
('SECURITY','HONEYWELL'),
('SECURITY','JCI'),
('SECURITY','HIKVISION'),
('SECURITY','DAHUA'),
('SECURITY','HANWHA'),
('SECURITY','GENETEC'),
('SECURITY','MILESTONE'),
('SECURITY','HID'),
('SECURITY','SUPREMA'),
('SECURITY','DORMAKABA'),
('SECURITY','ASSA_ABLOY'),
('SECURITY','SALTO'),
('SECURITY','LENEL'),
('DATACENTER','VERTIV'),
('DATACENTER','SCHNEIDER'),
('DATACENTER','RITTAL'),
('DATACENTER','HUAWEI'),
('DATACENTER','EATON'),
('DATACENTER','LEGRAND'),
('DATACENTER','STULZ'),
('DATACENTER','DELTA'),
('DATACENTER','APC'),
('DATACENTER','COMMSCOPE'),
('STRUCTURED_CABLING','COMMSCOPE'),
('STRUCTURED_CABLING','CORNING'),
('STRUCTURED_CABLING','PANDUIT'),
('STRUCTURED_CABLING','R_M'),
('STRUCTURED_CABLING','LEGRAND'),
('STRUCTURED_CABLING','NEXANS'),
('STRUCTURED_CABLING','BELDEN'),
('STRUCTURED_CABLING','SIEMON'),
('STRUCTURED_CABLING','PRYSMIAN'),
('DAS','COMMSCOPE'),
('DAS','COMBA'),
('DAS','SOLID'),
('DAS','JMA'),
('DAS','NEXTIVITY'),
('DAS','ERICSSON'),
('DAS','NOKIA'),
('DAS','HUAWEI'),
('RADIO','MOTOROLA'),
('RADIO','HYTERA'),
('RADIO','KENWOOD'),
('RADIO','ICOM'),
('RADIO','SEPURA'),
('RADIO','DAMM'),
('UC_AV','CISCO'),
('UC_AV','AVAYA'),
('UC_AV','YEALINK'),
('UC_AV','POLY'),
('UC_AV','CRESTRON'),
('UC_AV','EXTRON'),
('UC_AV','BIAMP'),
('UC_AV','BOSE'),
('UC_AV','JBL'),
('UC_AV','SHURE'),
('UC_AV','SENNHEISER'),
('UC_AV','BARCO'),
('UC_AV','LOGITECH'),
('UC_AV','SONY'),
('UC_AV','PANASONIC'),
('PAGA','TOA'),
('PAGA','ZENITEL'),
('PAGA','INDUSTRONIC'),
('PAGA','BOSCH'),
('PAGA','HONEYWELL'),
('VERTICAL','KONE'),
('VERTICAL','OTIS'),
('VERTICAL','SCHINDLER'),
('VERTICAL','TKE'),
('VERTICAL','MITSUBISHI_E'),
('VERTICAL','HYUNDAI_ELEV'),
('VERTICAL','FUJITEC'),
('PLUMBING','GRUNDFOS'),
('PLUMBING','WILO'),
('PLUMBING','KSB'),
('PLUMBING','XYLEM'),
('PLUMBING','LOWARA'),
('PLUMBING','EBARA'),
('PLUMBING','SULZER'),
('PLUMBING','ARMSTRONG'),
('WATER','GRUNDFOS'),
('WATER','XYLEM'),
('WATER','PENTAIR'),
('WATER','ENDRESS'),
('WATER','VEGA'),
('WATER','KROHNE'),
('PARKING','FAAC'),
('PARKING','CAME'),
('PARKING','NICE'),
('PARKING','MAGNETIC'),
('PARKING','HORMANN'),
('PARKING','HIKVISION'),
('PARKING','DAHUA'),
('GENERAL','DORMAKABA'),
('GENERAL','ASSA_ABLOY'),
('GENERAL','FAAC'),
('GENERAL','CAME'),
('GENERAL','NICE'),
('GENERAL','HORMANN'),
('KITCHEN','RATIONAL'),
('KITCHEN','ELECTROLUX_PRO'),
('KITCHEN','HOBART'),
('KITCHEN','MIELE'),
('LAUNDRY','ELECTROLUX_PRO'),
('LAUNDRY','MIELE'),
('LAUNDRY','PRIMUS'),
('LAUNDRY','IPSO'),
('LAUNDRY','SPEEDQUEEN'),
('OFFICE','CANON'),
('OFFICE','HP'),
('OFFICE','EPSON'),
('OFFICE','RICOH'),
('OFFICE','XEROX'),
('OFFICE','KYOCERA'),
('OFFICE','LEXMARK'),
('ENERGY','SCHNEIDER'),
('ENERGY','SIEMENS'),
('ENERGY','ABB'),
('ENERGY','HUAWEI'),
('ENERGY','DELTA'),
('ENERGY','EATON'),
('IRRIGATION','RAINBIRD'),
('IRRIGATION','HUNTER'),
('IRRIGATION','TORO'),
('IRRIGATION','GRUNDFOS'),
('POOL','PENTAIR'),
('POOL','HAYWARD'),
('POOL','ASTRALPOOL'),
('POOL','GRUNDFOS'),
('GAS','HONEYWELL'),
('GAS','BOSCH'),
('GAS','SIEMENS'),
('GAS','ENDRESS'),
('GAS','VEGA'),
('HEALTHCARE','HONEYWELL'),
('HEALTHCARE','JCI'),
('HEALTHCARE','SIEMENS'),
('HEALTHCARE','SCHNEIDER'),
('HEALTHCARE','BOSCH'),
('CLOCK_PAGING','SAPLING'),
('CLOCK_PAGING','BODET'),
('CLOCK_PAGING','GORGY'),
('CLOCK_PAGING','MASTER_CLOCK');

-- Add generic brand-family associations only where that asset/brand pair has no row yet.
insert into public.bf_master_asset_options(
 id,asset_type_id,manufacturer_id,model_family,notes,status
)
select
 gen_random_uuid(),
 a.id,
 m.id,
 'Common / Generic',
 'V12.7.1 Saudi facilities catalog seed; refine to exact installed model/family when registering the asset.',
 'active'
from _v1271_map x
join public.bf_master_asset_types a on a.system_code=x.system_code and a.status='active'
join public.bf_master_manufacturers m on m.code=x.brand_code and m.status='active'
where not exists (
 select 1
 from public.bf_master_asset_options o
 where o.asset_type_id=a.id
   and o.manufacturer_id=m.id
);

commit;

-- Verification
select 'manufacturers' item,count(*) total from public.bf_master_manufacturers
union all
select 'asset_types',count(*) from public.bf_master_asset_types
union all
select 'brand_options',count(*) from public.bf_master_asset_options
order by item;
