-- Basmat Facilities CMMS
-- Mobile Field QR / automatic-code lookup hotfix
-- Fixes the real mismatch:
-- Asset QR encodes .../assets/<uuid>, while bf31_asset_lookup previously accepted
-- only the raw asset_tag or raw UUID.

begin;

create or replace function public.bf31_asset_lookup(p_code text)
returns jsonb
language plpgsql stable security definer set search_path=''
as $$
declare
 result jsonb;
 raw_code text:=btrim(coalesce(p_code,''));
 lookup_uuid uuid;
 extracted text;
begin
 if auth.uid() is null then
  raise exception 'Authentication required' using errcode='42501';
 end if;

 if length(raw_code) not between 1 and 500 then
  raise exception 'Asset reference is required';
 end if;

 -- Accept the server-generated asset tag directly.
 -- Accept a raw asset UUID.
 -- Accept the QR payload currently generated by AssetDetails:
 -- https://<host>/assets/<uuid>
 if raw_code ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' then
   lookup_uuid:=raw_code::uuid;
 else
   extracted:=substring(
     raw_code from '(?i)/assets/([0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})'
   );
   if extracted is not null then lookup_uuid:=extracted::uuid; end if;
 end if;

 with candidate as (
   select a.*,c.name client_name,s.name site_name
   from public.bf_assets a
   join public.bf_clients c on c.id=a.client_id
   join public.bf_sites s on s.id=a.site_id
   where a.status='active'
     and (
       lower(a.asset_tag)=lower(raw_code)
       or (lookup_uuid is not null and a.id=lookup_uuid)
     )
     and (
       public.bf4_staff(a.organization_id,'mobile-field.view')
       or public.bf4_client(a.organization_id,a.client_id)
     )
   limit 1
 ),
 work_orders as (
   select w.id,w.work_order_number,w.title,w.priority,w.status,w.sla_status,w.completion_due_at
   from public.bf_work_orders w
   join candidate a on a.id=w.asset_id
   where w.status not in('closed','cancelled')
     and public.bf9_view(w.id)
   order by w.created_at desc
   limit 20
 )
 select jsonb_build_object(
   'asset',(select to_jsonb(x) from candidate x),
   'work_orders',coalesce((select jsonb_agg(to_jsonb(x)) from work_orders x),'[]'::jsonb)
 ) into result;

 if result->'asset' is null then
  raise exception 'Asset not found or access denied';
 end if;

 return result;
end $$;

revoke all on function public.bf31_asset_lookup(text) from public,anon;
grant execute on function public.bf31_asset_lookup(text) to authenticated;

commit;
